Repository PowerShell/PowerShell, pull requests merged in 2018-10, with the labels that each got.

#7630 Add %F option to Get-Date -UFormat
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetDateCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Date.Tests.ps1
Labels: Documentation Needed

#7902 Replace 'hang' term
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-Process.Tests.ps1
  test/powershell/engine/Api/BasicEngine.Tests.ps1
Labels: Compliance

#7775 Add EscapeHandling parameter in ConvertTo-Json cmdlet
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertToJsonCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertTo-Json.Tests.ps1
Labels: Documentation Needed

#7935 Remove unused commented out code
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteError.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimAssociatedInstanceCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/CommonUtils.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/CimJobException.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetComputerInfoCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-hex/Format-Hex.cs
  src/Microsoft.WSMan.Management/CredSSP.cs
  src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs
Labels: Hacktoberfest

#7899 No longer skips double quote delimiter in Import-Csv
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CSVCommands.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Import-Csv.Tests.ps1
Labels: Hacktoberfest

#7901 Add support for Byte Literals
  src/System.Management.Automation/engine/parser/CharTraits.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
  test/powershell/Language/Parser/Parser.Tests.ps1
Labels: Breaking-Change, Committee-Reviewed, Documentation Needed

#7754 Revert "Only display properties with values for MeasureInfo (#7104)"
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_List.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/object.tests.ps1
Labels: Review - Abandoned

#7877 Add new Offset and Count parameters to Format-Hex and refactor the cmdlet
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-hex/Format-Hex.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/UtilityCommon.cs
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/FormatHex.Tests.ps1
Labels: Committee-Reviewed

#7702 Add -Name, -NoUserOverrides and -ListAvailable parameters to Get-Culture cmdlet
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetCultureCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Culture.Tests.ps1
Labels: Committee-Reviewed

#8077 Combine notes about `ITuple` changes in Change Log
  CHANGELOG.md
Labels: Area-Documentation

#8068 Replace StringComparision.CurrentCulture with StringComparision.Ordinal
  src/Microsoft.PowerShell.Commands.Diagnostics/ImportCounterCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Eventlog.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetComputerInfoCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfacePrompt.cs
  src/Microsoft.WSMan.Management/InvokeWSManAction.cs
  src/Microsoft.WSMan.Management/PingWSMan.cs
  src/Microsoft.WSMan.Management/WSManConnections.cs
  src/Microsoft.WSMan.Management/WSManInstance.cs
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/engine/CommandInfo.cs
  src/System.Management.Automation/engine/DataStoreAdapter.cs
  src/System.Management.Automation/engine/GetCommandCommand.cs
  src/System.Management.Automation/engine/SessionStateLocationAPIs.cs
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  src/System.Management.Automation/help/CommandHelpProvider.cs
  src/System.Management.Automation/help/DscResourceHelpProvider.cs
  src/System.Management.Automation/help/PSClassHelpProvider.cs
  src/System.Management.Automation/namespaces/FileSystemContentStream.cs
  src/System.Management.Automation/namespaces/LocationGlobber.cs
  src/System.Management.Automation/namespaces/NavigationProviderBase.cs
Labels: Issue-Code Cleanup

#8067 Added 'Learn Windows PowerShell in a Month of Lunches' as recommended reading
  docs/learning-powershell/README.md
Labels: Area-Documentation

#8079 Move processing of `-WorkingDirectory` before processing of profiles for pwsh.exe
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
Labels: Breaking-Change, Committee-Reviewed

#7910 Remove clone args
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
Labels: Issue-Code Cleanup

#8115 Honor `-OutputFormat` if specified in noninteractive, redirected, encoded command used with pwsh
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
Labels: Breaking-Change, Committee-Reviewed

#8054 Make PSVersionInfo.PSVersion and PSVersionInfo.PSEdition public
  src/System.Management.Automation/engine/PSVersionInfo.cs
Labels: Committee-Reviewed, New-Public-API
