Repository PowerShell/PowerShell, pull requests merged in 2018-02, with the labels that each got.

#6122 Updating Raspbian installation instructions to create pwsh symlink
  docs/installation/linux.md
Labels: Area-Documentation

#5732 Fix range operator
  src/System.Management.Automation/engine/lang/parserutils.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  test/powershell/Language/Operators/RangeOperator.Tests.ps1
Labels: Breaking-Change, Documentation Needed

#6109 Make UTF-8 Default Encoding for application/json
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/BasicHtmlWebResponseObject.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: Breaking-Change, Committee-Reviewed, Documentation Needed

#5816 Add common aliases for all write-* commands default message parameter
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WriteConsoleCmdlet.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/write.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Write-Host.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Write-Stream.Tests.ps1
Labels: Committee-Reviewed, Documentation Needed

#6018 Add -SkipHeaderValidation Support to ContentType on Web Cmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/WebCmdletStrings.resx
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: Documentation Needed

#6182 Throw terminating error in New-TemporaryFile and make it not rely on the presence of the 'TEMP' environment variable
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/NewTemporaryFileCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/NewTemporaryFile.Tests.ps1
Labels: Breaking-Change

#5568 Don't add trailing spaces to last column when using Format-Table
  src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Out-File.Tests.ps1
Labels: Committee-Reviewed

#6113 Add Password parameter to Get-PfxCertificate cmdlet
  src/Microsoft.PowerShell.Security/security/CertificateCommands.cs
  test/powershell/Modules/Microsoft.PowerShell.Security/CmsMessage.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Security/certificateCommon.psm1
Labels: Committee-Reviewed, Documentation Needed

#5817 Add Path alias to -FilePath parameters and others for several commands
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/tee-object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/SetTracerCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/TraceExpressionCommand.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/RegisterJobDefinition.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/SetJobDefinition.cs
  src/Microsoft.WSMan.Management/InvokeWSManAction.cs
  src/Microsoft.WSMan.Management/WSManInstance.cs
  src/System.Management.Automation/help/SaveHelpCommand.cs
  src/System.Management.Automation/help/UpdateHelpCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Tee-Object.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Trace-Command.Tests.ps1
Labels: Committee-Reviewed, Documentation Needed
