Repository PowerShell/PowerShell, pull requests merged in 2018-09, with the labels that each got.

#7701 Fix Windows MSI uninstallation issue whereby shortcut does not get removed when more than one version is installed
  assets/Product.wxs
Labels: Area-Build

#7721 Support calling method with ByRef-like type parameters
  src/System.Management.Automation/engine/CoreAdapter.cs
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/engine/parser/PSType.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  test/powershell/Language/Interop/DotNet/DotNetInterop.Tests.ps1
Labels: Documentation Needed

#7697 Do not add PATHEXT environment variable on Unix
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/SpecialVariables.cs
Labels: Breaking-Change, Committee-Reviewed

#7636 Allow numeric Ids and name of registered code pages in '-Encoding' parameters
  src/System.Management.Automation/utils/EncodingUtils.cs
  test/powershell/engine/Basic/Encoding.Tests.ps1
Labels: Documentation Needed

#7231 Type inference for Select-Object, Group-Object, PSObject and Hashtable
  src/System.Management.Automation/engine/CommandInfo.cs
  src/System.Management.Automation/engine/MshMemberInfo.cs
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: Area-Engine, Committee-Reviewed

#7813 Add C#-style type accelerators and suffixes for ushort, uint, ulong, and short literals
  src/System.Management.Automation/engine/parser/CharTraits.cs
  src/System.Management.Automation/engine/parser/TypeResolver.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
  test/powershell/Language/Parser/Parser.Tests.ps1
  test/powershell/Language/Parser/TypeAccelerator.Tests.ps1
Labels: Breaking-Change, Documentation Needed
