Repository PowerShell/PowerShell, pull requests merged in 2018-11, with the labels that each got.

#7125 Refactor module version/GUID comparison logic
  src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs
  test/powershell/Modules/Microsoft.PowerShell.Core/ModuleConstraint.Tests.ps1
Labels: Area-Cmdlets-Core, Breaking-Change, Issue-Code Cleanup

#8168 Adding yml for Linux builds
  tools/releaseBuild/azureDevOps/LinuxBuild.yml
Labels: Area-Build

#8073 Load assembly from module base path before trying to load from GAC
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  test/powershell/Modules/Microsoft.PowerShell.Core/Import-Module.Tests.ps1
Labels: Breaking-Change

#8186 Fix static "secret" in test code
  test/powershell/Modules/Microsoft.PowerShell.Utility/clixml.tests.ps1
Labels: Area-Test, Compliance

#8244 Remove tilde from Linux preview packages
  tools/packaging/packaging.psm1
Labels: Breaking-Change

#7660 Join-String cmdlet for creating text from pipeline input
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/join-string.cs
  src/Modules/Unix/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/Modules/Windows/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/engine/MshObject.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Join-String.Tests.ps1
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
Labels: CL-General, Documentation Needed

#8232 Support `Get-PSHostProcessInfo` and `Enter-PSHostProcess` on non-Windows
  src/System.Management.Automation/System.Management.Automation.csproj
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/hostifaces/LocalConnection.cs
  src/System.Management.Automation/engine/remoting/commands/EnterPSHostProcessCommand.cs
  src/System.Management.Automation/engine/remoting/common/RemoteSessionNamedPipe.cs
  src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs
  src/System.Management.Automation/engine/remoting/server/OutOfProcServerMediator.cs
  test/powershell/Host/Logging.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Core/Enter-PSHostProcess.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Core/Get-PSHostProcessInfo.Tests.ps1
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
Labels: Documentation Needed

#8283 Merge changelogs from 6.1.1 and 6.0.5 into master
  .spelling
  .vsts-ci/spelling.yml
  CHANGELOG.md
Labels: CL-Docs

#8203 Change default issue template to use different categories
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Bug_Report.md
  .github/ISSUE_TEMPLATE/Documentation_Issue.md
  .github/ISSUE_TEMPLATE/Feature_Request.md
  .github/ISSUE_TEMPLATE/Support_Question.md
  .github/ISSUE_TEMPLATE/Windows_PowerShell.md
Labels: CL-Docs

#8190 Cleanup assemblyinfo
  src/Microsoft.Management.Infrastructure.CimCmdlets/AssemblyInfo.cs
  src/Microsoft.PowerShell.ConsoleHost/AssemblyInfo.cs
  src/System.Management.Automation/AssemblyInfo.cs
Labels: CL-CodeCleanup

#8287 Enable `Open Here` context menu on Windows to work with root of a drive
  assets/Product.wxs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
Labels: CL-BuildPackaging

#8238 Token calculation fix for Get-Help executed on ScriptBlock.
  src/System.Management.Automation/help/HelpCommentsParser.cs
  test/powershell/Language/Scripting/ScriptHelp.Tests.ps1
Labels: CL-General

#8080 Test-Path: Return $false when given an empty or $null -Path/-LiteralPath value
  src/Microsoft.PowerShell.Commands.Management/commands/management/PingPathCommand.cs
  src/Microsoft.PowerShell.Commands.Management/resources/TestPathResources.resx
  test/powershell/Language/Scripting/ErrorPosition.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Test-Path.Tests.ps1
Labels: Breaking-Change, CL-General, Committee-Reviewed

#8284 Add fix for Start-Job initialization script in system lockdown
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
  test/powershell/Modules/Microsoft.PowerShell.Security/ConstrainedLanguageValidation.Tests.ps1
Labels: Area-Remoting, CL-Engine, OS-Windows

#8273 Publish test package to AppVeyor daily build
  build.psm1
  tools/appveyor.psm1
Labels: CL-Test

#8340 Build alpine tar.gz package in release builds
  build.psm1
  tools/packaging/packaging.psm1
  tools/releaseBuild/Images/GenericLinuxFiles/PowerShellPackage.ps1
  tools/releaseBuild/Images/microsoft_powershell_alpine3/Dockerfile
  tools/releaseBuild/Images/microsoft_powershell_alpine3/build-and-run-pwsh.sh
  tools/releaseBuild/build.json
Labels: CL-BuildPackaging

#8279 Add SkipCA and SkipCN check requirement to WinRM/OMI HTTPS connection
  src/System.Management.Automation/System.Management.Automation.csproj
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/remoting/commands/NewPSSessionOptionCommand.cs
  src/System.Management.Automation/engine/remoting/common/remotingexceptions.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManNativeAPI.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManTransportManager.cs
  src/System.Management.Automation/resources/RemotingErrorIdStrings.resx
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
  test/powershell/engine/Remoting/PSSession.Tests.ps1
Labels: Area-Remoting, Breaking-Change, CL-Engine, Documentation Needed, Review - Committee

#8249 Fix race condition to access powershell.config.json
  src/System.Management.Automation/engine/PSConfiguration.cs
Labels: Area-Engine, CL-Engine

#8291 Remove `Persist` parameter from `New-PSDrive` on non-Windows platform
  src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
Labels: CL-General

#8335 Cleanup updatablehelpsystem and enable XSD validation on MAML help content
  assets/files.wxs
  src/System.Management.Automation/help/UpdatableHelpSystem.cs
  src/powershell-unix/powershell-unix.csproj
  src/powershell-win-core/powershell-win-core.csproj
Labels: CL-CodeCleanup

#8337 Cleanup '#if !CORECLR' code
  src/Microsoft.PowerShell.Commands.Diagnostics/NewWinEventCommand.cs
  src/Microsoft.WSMan.Management/CredSSP.cs
  src/Microsoft.WSMan.Management/WsManHelper.cs
  src/System.Management.Automation/System.Management.Automation.csproj
  src/System.Management.Automation/engine/CodeMethods.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/Types_Ps1Xml.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/hostifaces/InternalHost.cs
  src/System.Management.Automation/engine/remoting/fanin/BaseTransportManager.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-CodeCleanup

#8305 Fix for PSDrive creation with a UNC path with a trailing backslash or forward slash when combined with -Persist
  src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/New-PSDrive.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/PSDrive.Tests.ps1
Labels: CL-General

#8303 Conditionally mark getter/setter implementations virtual in generated classes
  src/System.Management.Automation/engine/parser/PSType.cs
  test/powershell/Language/Classes/scripting.Classes.inheritance.tests.ps1
Labels: CL-General

#8346 Remove workaround for fixed invalid json array deserializing bug
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertFrom-Json.Tests.ps1
Labels: CL-CodeCleanup

#8195 Debug parameter now sets debugpreference to continue
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
  test/powershell/Language/Scripting/ActionPreference.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Write-Debug.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Write-Stream.Tests.ps1
Labels: Breaking-Change, CL-BreakingChange, CL-Engine, Committee-Reviewed

#8353 Fix `Get-Help` for advanced functions with MAML help content
  src/System.Management.Automation/help/CommandHelpProvider.cs
  test/powershell/engine/Help/HelpSystem.Tests.ps1
  test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1
  test/powershell/engine/Help/assets/Microsoft.PowerShell.Archive_eb74e8da-9ae2-482a-a648-e96550fb8733_HelpInfo.xml
  test/powershell/engine/Help/assets/Microsoft.PowerShell.Archive_eb74e8da-9ae2-482a-a648-e96550fb8733_en-US_HelpContent.cab
  test/powershell/engine/Help/assets/Microsoft.PowerShell.Archive_eb74e8da-9ae2-482a-a648-e96550fb8733_en-US_HelpContent.zip
  test/powershell/engine/Help/assets/PSReadline_5714753b-2afd-4492-a5fd-01d9e2cff8b5_HelpInfo.xml
  test/powershell/engine/Help/assets/PSReadline_5714753b-2afd-4492-a5fd-01d9e2cff8b5_en-US_helpcontent.cab
  test/powershell/engine/Help/assets/PSReadline_5714753b-2afd-4492-a5fd-01d9e2cff8b5_en-US_helpcontent.zip
Labels: CL-General

#8363 Fix Export-ModuleMember bug for scriptblocks having no context
  src/System.Management.Automation/engine/Modules/ExportModuleMemberCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Security/ConstrainedLanguageModules.Tests.ps1
Labels: Area-Cmdlets-Core, CL-Engine, Issue-Bug, OS-Windows
