Repository PowerShell/PowerShell, pull requests merged in 2018-04, with the labels that each got.

#6442 Simplify the paths the MSI uses
  assets/Product.wxs
  test/packaging/windows/msi.tests.ps1
  tools/appveyor.psm1
  tools/packaging/packaging.psm1
Labels: Breaking-Change

#6352 Add functionality to update help in user scope
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/help/CabinetNativeApi.cs
  src/System.Management.Automation/help/CommandHelpProvider.cs
  src/System.Management.Automation/help/HelpFileHelpProvider.cs
  src/System.Management.Automation/help/HelpUtils.cs
  src/System.Management.Automation/help/UpdatableHelpCommandBase.cs
  src/System.Management.Automation/help/UpdateHelpCommand.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
  test/powershell/engine/Help/HelpSystem.Tests.ps1
  test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1
  test/powershell/engine/Help/assets/Microsoft.PowerShell.Core_00000000-0000-0000-0000-000000000000_HelpInfo.xml
  test/powershell/engine/Help/assets/Microsoft.PowerShell.Core_00000000-0000-0000-0000-000000000000_en-US_HelpContent.cab
  test/powershell/engine/Help/assets/Microsoft.PowerShell.Core_00000000-0000-0000-0000-000000000000_en-US_HelpContent.zip
Labels: Breaking-Change, Committee-Reviewed

#6523 Clean up workflow logic in the module loading component
  src/System.Management.Automation/engine/ExecutionContext.cs
  src/System.Management.Automation/engine/GetCommandCommand.cs
  src/System.Management.Automation/engine/Modules/AnalysisCache.cs
  src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Modules/PSModuleInfo.cs
  src/System.Management.Automation/help/CommandHelpProvider.cs
  src/System.Management.Automation/resources/AutomationExceptions.resx
  src/System.Management.Automation/resources/Modules.resx
  src/System.Management.Automation/utils/PsUtils.cs
  test/powershell/Modules/Microsoft.PowerShell.Core/Import-Module.Tests.ps1
  test/powershell/engine/Module/TestModuleManifest.Tests.ps1
Labels: Area-Engine

#5328 Add ported Test-Connection cmdlet
  src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs
  src/Microsoft.PowerShell.Commands.Management/resources/ComputerResources.resx
  src/Microsoft.PowerShell.Commands.Management/resources/TestConnectionResources.resx
  src/Modules/Unix/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.psd1
  src/Modules/Windows-Core/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.psd1
  test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
Labels: Area-Cmdlets-Management, Issue-Enhancement

#6542 Some fixes in Get-Date -UFormat
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetDateCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Date.Tests.ps1
Labels: Breaking-Change

#6601 Remove support for file to opt-out of telemetry, only support env var
  .gitignore
  .travis.yml
  DELETE_ME_TO_DISABLE_CONSOLEHOST_TELEMETRY
  README.md
  appveyor.yml
  assets/files.wxs
  build.psm1
  src/Microsoft.PowerShell.ConsoleHost/host/msh/Telemetry.cs
  src/powershell-unix/powershell-unix.csproj
  src/powershell-win-core/powershell-win-core.csproj
  tools/appveyor.psm1
  tools/releaseBuild/Images/microsoft_powershell_alpine3/build-and-run-pwsh.sh
  tools/travis.ps1
Labels: Breaking-Change

#6133 Port Windows PowerShell AppLocker and DeviceGuard UMCI application white listing support
  src/System.Management.Automation/CoreCLR/CorePsStub.cs
  src/System.Management.Automation/System.Management.Automation.csproj
  src/System.Management.Automation/security/SecurityManager.cs
  src/System.Management.Automation/security/SecuritySupport.cs
  src/System.Management.Automation/security/wldpNativeMethods.cs
  test/powershell/Modules/Microsoft.PowerShell.Security/AmsiInterface.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Security/ConstrainedLanguageRestriction.Tests.ps1
Labels: Area-Security, OS-Windows, Porting

#6141 Enhance and refactor Add-Type cmdlet
  assets/files.wxs
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/AddTypeStrings.resx
  src/System.Management.Automation/utils/ExtensionMethods.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Add-Type.Tests.ps1
Labels: Breaking-Change, Committee-Reviewed, Documentation Needed

#6708 Cleanup uses of `CommandTypes.Workflow` and `WorkflowInfo`
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/HelpV3_format_ps1xml.cs
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/Help_format_ps1xml.cs
  src/System.Management.Automation/engine/CmdletInfo.cs
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/engine/CommandInfo.cs
  src/System.Management.Automation/engine/CommandSearcher.cs
  src/System.Management.Automation/engine/CommonCommandParameters.cs
  src/System.Management.Automation/engine/FunctionInfo.cs
  src/System.Management.Automation/engine/GetCommandCommand.cs
  src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs
  src/System.Management.Automation/engine/Modules/ModuleUtils.cs
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  src/System.Management.Automation/engine/ParameterSetInfo.cs
  src/System.Management.Automation/engine/SessionStateFunctionAPIs.cs
  src/System.Management.Automation/engine/SessionStateScope.cs
  src/System.Management.Automation/engine/WorkflowInfo.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
  src/System.Management.Automation/help/DefaultCommandHelpObjectBuilder.cs
  src/System.Management.Automation/help/HelpCommentsParser.cs
  src/System.Management.Automation/resources/HelpDisplayStrings.resx
  src/System.Management.Automation/resources/Modules.resx
  src/System.Management.Automation/security/SecurityManager.cs
Labels: Breaking-Change
