Repository PowerShell/PowerShell, pull requests merged in 2018-07, with the labels that each got.

#7126 Refactor module specification logic
  src/System.Management.Automation/engine/Modules/ModuleSpecification.cs
Labels: Area-Cmdlets-Core, Issue-Code Cleanup

#7169 Add ThreadJob module package and tests
  assets/files.wxs
  src/Modules/PSGalleryModules.csproj
  test/powershell/Modules/Microsoft.PowerShell.Security/ConstrainedLanguageRestriction.Tests.ps1
  test/powershell/Modules/ThreadJob/ThreadJob.Tests.ps1
Labels: Area-Engine

#7241 Update PowerShell Direct to try pwsh then fallback to powershell
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
  src/System.Management.Automation/resources/RemotingErrorIdStrings.resx
Labels: Breaking-Change, Committee-Reviewed

#7240 Fix for issue 5752: pwsh cannot start in a directory with a name that includes a wildcard
  src/System.Management.Automation/engine/InitialSessionState.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
Labels: Breaking-Change

#7242 Add support to experimental features
  src/PowerShell.Core.Instrumentation/PowerShell.Core.Instrumentation.man
  src/System.Management.Automation/CoreCLR/EventResource.cs
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  src/System.Management.Automation/engine/Attributes.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CommandProcessor.cs
  src/System.Management.Automation/engine/CommandProcessorBase.cs
  src/System.Management.Automation/engine/CompiledCommandParameter.cs
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/ExperimentalFeature/GetExperimentalFeatureCommand.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/Modules/AnalysisCache.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs
  src/System.Management.Automation/engine/Modules/PSModuleInfo.cs
  src/System.Management.Automation/engine/PSConfiguration.cs
  src/System.Management.Automation/engine/PseudoParameters.cs
  src/System.Management.Automation/engine/ScriptCommandProcessor.cs
  src/System.Management.Automation/engine/SessionState.cs
  src/System.Management.Automation/engine/SpecialVariables.cs
  src/System.Management.Automation/engine/TypeMetadata.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/parser/TypeResolver.cs
  src/System.Management.Automation/engine/parser/ast.cs
  src/System.Management.Automation/engine/remoting/common/PSETWTracer.cs
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  src/System.Management.Automation/resources/DiscoveryExceptions.resx
  src/System.Management.Automation/resources/EventResource.resx
  src/System.Management.Automation/resources/Logging.resx
  src/System.Management.Automation/resources/Metadata.resx
  src/System.Management.Automation/resources/Modules.resx
  src/System.Management.Automation/resources/RunspaceInit.resx
  src/System.Management.Automation/utils/PsUtils.cs
  test/powershell/Language/Parser/TypeAccelerator.Tests.ps1
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
  test/powershell/engine/ExperimentalFeature/ExperimentalFeature.Basic.Tests.ps1
  test/powershell/engine/ExperimentalFeature/Get-ExperimentalFeature.Tests.ps1
  test/powershell/engine/ExperimentalFeature/assets/ExpTest/ExpTest.cs
  test/powershell/engine/ExperimentalFeature/assets/ExpTest/ExpTest.psd1
  test/powershell/engine/ExperimentalFeature/assets/ExpTest/ExpTest.psm1
  test/powershell/engine/Help/HelpSystem.Tests.ps1
  tools/ResxGen/ResxGen.ps1
Labels: Documentation Needed

#7284 Remove the 'VisualBasic' support from Add-Type
  assets/files.wxs
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Add-Type.Tests.ps1
Labels: Breaking-Change

#6926 Added Markdown rendering cmdlets
  PowerShell.sln
  ThirdPartyNotices.txt
  assets/files.wxs
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertFromMarkdownCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MarkdownOptionCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ShowMarkdownCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/ConvertMarkdownStrings.resx
  src/Microsoft.PowerShell.MarkdownRender/CodeInlineRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/EmphasisInlineRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/FencedCodeBlockRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/HeaderBlockRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/LeafInlineRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/LineBreakRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/LinkInlineRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/ListBlockRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/ListItemBlockRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/MarkdownConverter.cs
  src/Microsoft.PowerShell.MarkdownRender/Microsoft.PowerShell.MarkdownRender.csproj
  src/Microsoft.PowerShell.MarkdownRender/ParagraphBlockRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/QuoteBlockRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/VT100EscapeSequences.cs
  src/Microsoft.PowerShell.MarkdownRender/VT100ObjectRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/VT100Renderer.cs
  src/Modules/Unix/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/Modules/Windows/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/System.Management.Automation/engine/TypesV3_Ps1Xml.cs
  src/System.Management.Automation/engine/Utils.cs
  src/powershell-native/nativemsh/pwrshcommon/pwrshcommon.cpp
  test/powershell/Modules/Microsoft.PowerShell.Utility/MarkdownCmdlets.Tests.ps1
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
Labels: Committee-Reviewed

#7202 Update `Enable-PSRemoting` so configuration name for Preview releases
  src/System.Management.Automation/engine/PSVersionInfo.cs
  src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
  test/powershell/Host/PSVersionTable.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Core/PSSessionConfiguration.Tests.ps1
Labels: Breaking-Change

#7311 Add maintainers best practice document and update maintainer list
  docs/maintainers/Images/merge-commit-confirm.png
  docs/maintainers/Images/merge-commit.png
  docs/maintainers/Images/squash-confirm.png
  docs/maintainers/Images/squash-merge.png
  docs/maintainers/README.md
  docs/maintainers/best-practice.md
Labels: Area-Documentation

#7305 Fix error position for switch-statement condition and for-statement initializer
  src/System.Management.Automation/engine/parser/Compiler.cs
  test/powershell/Language/Scripting/Debugging/Debugging.Tests.ps1
  test/powershell/Language/Scripting/ErrorPosition.Tests.ps1
Labels: Area-Debugging, Area-Engine

#7350 Update PowerShell to reference psrp.1.4.5-0
  src/powershell-unix/powershell-unix.csproj
  test/powershell/engine/Remoting/RemoteSession.Basic.Tests.ps1
Labels: Area-Build

#7344 Update 'Utils.IsComObject' to use 'Marshal.IsComObject' since CAS is no longer supported in .NET Core
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
Labels: Issue-Code Cleanup

#7360 Fix runspace tests so that they will run more reliably
  test/powershell/Modules/ThreadJob/ThreadJob.Tests.ps1
Labels: Area-Test

#7346 Format Management csproj with updated codeformatter
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/SessionBasedWrapper.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimConverter.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ClearPropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ContentCommandBase.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ConvertPathCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/CopyPropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetChildrenCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetComputerInfoCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetPropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/MovePropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/NewPropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ParsePathCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/PingPathCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/RemovePropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/RenamePropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ResolvePathCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/SetPropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/TimeZoneCommands.cs
Labels: Issue-Code Cleanup
