Repository PowerShell/PowerShell, pull requests merged in 2019-07, with the labels that each got.

#10022 Keep Untracked files on Start-PSBuild -Clean
  build.psm1
Labels: CL-Tools

#10024 Reduce allocations in GetAssemblies()
  src/System.Management.Automation/engine/parser/PSType.cs
  src/System.Management.Automation/utils/ClrFacade.cs
Labels: Area-Performance

#9975 Use AddRange in GetModules()
  src/System.Management.Automation/engine/Utils.cs
Labels: CL-CodeCleanup

#10020 Add fast path for wildcard patterns that contains no wildcard characters
  src/System.Management.Automation/engine/regex.cs
  src/System.Management.Automation/singleshell/config/MshSnapinInfo.cs
Labels: CL-Performance

#10034 Set request headers when request body is empty in Web Cmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: CL-General

#10007 Use AddOrUpdate() to register runspace
  src/System.Management.Automation/engine/runtime/Operations/ClassOps.cs
Labels: CL-CodeCleanup

#10038 Reduce allocations in NavigationCmdletProvider.NormalizePath()
  src/System.Management.Automation/namespaces/NavigationProviderBase.cs
Labels: CL-Performance

#10049 Indent fix in markdown-link.tests.ps1
  test/common/markdown/markdown-link.tests.ps1
Labels: CL-Tools

#10028 Use a static cache for `PSVersionInfo.PSVersion` to avoid casting `SemanticVersion` to `Version` very time accessing that property
  src/System.Management.Automation/engine/PSVersionInfo.cs
Labels: CL-Performance

#9638 Cleanup workflow code
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/System.Management.Automation/engine/CommandInfo.cs
  src/System.Management.Automation/engine/EventManager.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs
  src/System.Management.Automation/engine/Modules/PSModuleInfo.cs
  src/System.Management.Automation/engine/SessionStateStrings.cs
  src/System.Management.Automation/engine/WorkflowInfo.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs
  src/System.Management.Automation/engine/remoting/commands/ReceiveJob.cs
  src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
  src/System.Management.Automation/help/HelpCommands.cs
  src/System.Management.Automation/resources/DebuggerStrings.resx
  src/System.Management.Automation/resources/Modules.resx
  src/System.Management.Automation/resources/RemotingErrorIdStrings.resx
  test/powershell/Modules/Microsoft.PowerShell.Core/Import-Module.Tests.ps1
  test/powershell/engine/Module/TestModuleManifest.Tests.ps1
Labels: CL-CodeCleanup

#10066 Add to /etc/shells on macOS
  tools/packaging/packaging.psm1
  tools/packaging/packaging.strings.psd1
Labels: CL-BuildPackaging

#9895 Fix auto-downloading of files in OneDrive when doing `dir`
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: Committee-Reviewed

#10047 Make `Foreach-Object` 2x faster by reducing unnecessary allocations and boxing
  Settings.StyleCop
  src/System.Management.Automation/engine/CommandInfo.cs
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/hostifaces/ConnectionBase.cs
  src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs
  src/System.Management.Automation/engine/lang/scriptblock.cs
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
  stylecop.json
Labels: CL-Performance

#10071 Update 'Start-PSBuild -Clean' logic of 'git clean' to ignore locked files from VS2017 to VS2019
  build.psm1
Labels: CL-Tools

#10057 Create JumpList in STA thread as some COM APIs are strictly STA only to avoid sporadic CLR crashes
  src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/TaskbarJumpList.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
Labels: CL-General

#10053 Reduce allocations where new WildcardPattern is used
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/GetEventCommand.cs
  src/System.Management.Automation/engine/regex.cs
Labels: CL-Performance

#10054 Speed up WildcardPattern.IsMatch if an pattern ends with asterisk
  src/System.Management.Automation/engine/regex.cs
Labels: CL-Performance

#8626 Add -SecurityDescriptorSddl parameter to Set-Service
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
  src/Microsoft.PowerShell.Commands.Management/resources/ServiceResources.resx
  src/System.Management.Automation/utils/PInvokeDllNames.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1
Labels: CL-General

#10125 Revert "Bump System.IO.Packaging from 4.6.0-preview6.19303.8 to 4.6.0-preview.19113.10"
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
Labels: CL-BuildPackaging

#10126 Revert "Bump System.Data.SqlClient from 4.7.0-preview6.19303.8 to 4.7.0-preview.19113.10"
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
Labels: CL-BuildPackaging

#10127 Revert "Bump System.Threading.AccessControl from 4.6.0-preview6.19303.8 to 4.6.0-preview.19113.10"
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
Labels: CL-BuildPackaging

#10124 Revert "Bump System.Text.Encodings.Web from 4.6.0-preview6.19303.8 to 4.6.0-preview.19113.10"
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
Labels: CL-BuildPackaging

#10129 Revert "Bump System.Management from 4.6.0-preview6.19303.8 to 4.6.0-preview.19113.10"
  src/System.Management.Automation/System.Management.Automation.csproj
Labels: CL-BuildPackaging

#10130 Revert "Bump System.Security.Cryptography.Pkcs from 4.6.0-preview6.19303.8 to 4.6.0-preview.19113.10"
  src/System.Management.Automation/System.Management.Automation.csproj
Labels: CL-BuildPackaging

#10131 Revert "Bump System.Text.Encoding.CodePages from 4.6.0-preview6.19303.8 to 4.6.0-preview.19113.10"
  src/System.Management.Automation/System.Management.Automation.csproj
Labels: CL-BuildPackaging

#10132 Revert "Bump System.Security.AccessControl from 4.6.0-preview6.19303.8 to 4.6.0-preview.19113.10 in /tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility"
  tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
Labels: CL-BuildPackaging

#10128 Revert "Bump System.Configuration.ConfigurationManager from 4.6.0-preview6.19303.8 to 4.6.0-preview.19113.10"
  src/System.Management.Automation/System.Management.Automation.csproj
Labels: CL-BuildPackaging

#10133 Revert "Bump System.Security.Principal.Windows from 4.6.0-preview6.19303.8 to 4.6.0-preview.19113.10 in /tools/packaging/projects/reference/System.Management.Automation"
  tools/packaging/projects/reference/System.Management.Automation/System.Management.Automation.csproj
Labels: CL-BuildPackaging

#10083 Cleanup workflow - remove PSProxyJob
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
  src/System.Management.Automation/engine/remoting/client/PSProxyJob.cs
  src/System.Management.Automation/resources/PowerShellStrings.resx
  src/System.Management.Automation/resources/RemotingErrorIdStrings.resx
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-BreakingChange

#9735 Cleanup CompiledScriptBlock.cs
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
Labels: CL-CodeCleanup, CL-Engine

#9940 Add alias for Service 'StartType'
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
Labels: CL-General, Documentation Needed

#10146 Mark Set-Service tests with password as `Pending`
  test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1
Labels: CL-Test

#10134 Split the fxdependent package on Windows into two packages
  build.psm1
  src/Microsoft.PowerShell.GlobalTool.Shim/Microsoft.PowerShell.GlobalTool.Shim.csproj
  src/powershell-win-core/powershell-win-core.csproj
  tools/packaging/packaging.psm1
  tools/releaseBuild/Images/microsoft_powershell_windowsservercore/PowerShellPackage.ps1
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/nuget.yml
  tools/releaseBuild/azureDevOps/templates/windows-build.yml
  tools/releaseBuild/azureDevOps/templates/windows-package-signing.yml
  tools/releaseBuild/build.json
Labels: CL-BuildPackaging

#10098 Remove 'kill' alias for Stop-Process cmdlet on Unix
  src/System.Management.Automation/engine/InitialSessionState.cs
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
Labels: CL-BreakingChange, Committee-Reviewed

#10113 Identify renaming a parameter set as non-breaking in the breaking change contract document
  docs/dev-process/breaking-change-contract.md
Labels: CL-NotInBuild

#10145 Update DotNet Support links
  README.md
Labels: CL-Docs

#10163 Remove markdownlint tests due to security issues
  test/common/markdown/gulpfile.js
  test/common/markdown/markdown.tests.ps1
  test/common/markdown/package.json
  test/common/markdown/yarn.lock
Labels: CL-Test, Compliance

#10164 Skip JumpList on NanoServer and IoT
  .vsts-ci/templates/nanoserver.yml
  .vsts-ci/windows.yml
  src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/TaskbarJumpList.cs
  test/nanoserver/nanoserver.tests.ps1
Labels: CL-Engine

#9976 Fix hungarian prefix 'my'
  Settings.StyleCop
  stylecop.json
Labels: CL-Tools

#10041 Reduce allocations in Escape() and Unescape()
  src/System.Management.Automation/engine/regex.cs
Labels: CL-Performance

#9901 Add -Raw switch to Select-String for convenience
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Select-String.Tests.ps1
Labels: CL-General

#10052 Reduce allocations in PSTraceSource.WriteLine()
  src/System.Management.Automation/engine/CmdletParameterBinderController.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManTransportManager.cs
  src/System.Management.Automation/namespaces/LocationGlobber.cs
  src/System.Management.Automation/utils/StructuredTraceSource.cs
Labels: CL-Performance

#10200 Use nameof() in LocationGlobber and PathInfo
  src/System.Management.Automation/namespaces/LocationGlobber.cs
  src/System.Management.Automation/namespaces/PathInfo.cs
Labels: CL-CodeCleanup

#10061 Enable -sta and -mta switches for pwsh
  src/Microsoft.PowerShell.Commands.Management/commands/management/WMIHelper.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/New-Object.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/resources/CommandLineParameterParserStrings.resx
  src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/hostifaces/Connection.cs
  src/System.Management.Automation/engine/hostifaces/ConnectionBase.cs
  src/System.Management.Automation/engine/hostifaces/LocalConnection.cs
  src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
  src/System.Management.Automation/engine/hostifaces/RunspacePool.cs
  src/System.Management.Automation/engine/hostifaces/RunspacePoolInternal.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspace.cs
  src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/EncodeAndDecode.cs
  src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
  src/System.Management.Automation/engine/remoting/server/ServerPowerShellDriver.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
  src/System.Management.Automation/engine/remoting/server/ServerSteppablePipelineDriver.cs
  src/System.Management.Automation/engine/remoting/server/serverremotesession.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
Labels: Committee-Reviewed

#10205 Use 'Platform.IsWindowsDesktop' instead of checking both NanoServer and IoT
  src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/TaskbarJumpList.cs
Labels: CL-Engine

#10186 Special case the posix locale in WildcardPattern
  src/System.Management.Automation/engine/regex.cs
  test/powershell/Language/Parser/LanguageAndParser.TestFollowup.Tests.ps1
Labels: CL-Engine

#10204 Quote arguments in .vscode/tasks.json incase of spaces in expanded paths
  .vscode/tasks.json
Labels: CL-Tools

#10260 Revert the temporary change in `windows.yml`.
  .vsts-ci/windows.yml
Labels: CL-BuildPackaging
