Repository PowerShell/PowerShell, pull requests merged in 2019-02, with the labels that each got.

#8806 Move Final artifacts from universal build to `finalResults` folder
  .vscode/extensions.json
  .vsts-ci/linux.yml
  .vsts-ci/mac.yml
  .vsts-ci/windows.yml
  tools/releaseBuild/README.md
  tools/releaseBuild/azureDevOps/diagram.png
  tools/releaseBuild/azureDevOps/diagram.puml
  tools/releaseBuild/azureDevOps/diagram.svg
  tools/releaseBuild/azureDevOps/templates/compliance.yml
  tools/releaseBuild/azureDevOps/templates/insert-nuget-config-azfeed.yml
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/upload-final-results.yml
  tools/releaseBuild/azureDevOps/templates/upload.yml
  tools/releaseBuild/azureDevOps/templates/windows-build.yml
  tools/releaseBuild/azureDevOps/templates/windows-component-governance.yml
Labels: CL-BuildPackaging

#8808 Fix passing credential to the `SyncGalleryToAzArtifacts.psm1` script
  tools/releaseBuild/azureDevOps/AzArtifactFeed/PSGalleryToAzArtifacts.yml
  tools/releaseBuild/azureDevOps/AzArtifactFeed/SyncGalleryToAzArtifacts.psm1
Labels: CL-BuildPackaging

#8811 Add instrumentation for Start-PSPackage
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging

#8681 Parse numeric strings as numbers again during conversions
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  test/powershell/Language/Parser/Conversions.Tests.ps1
Labels: CL-General

#8821 Fix broken python method
  demos/python/class1.py
Labels: CL-Docs

#8831 Reduce string allocations when formatting file system objects.
  src/System.Management.Automation/engine/DataStoreAdapterProvider.cs
Labels: CL-CodeCleanup

#7281 Allow .exe files to be used as binary modules
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CommandInfo.cs
  src/System.Management.Automation/engine/Modules/AnalysisCache.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs
  src/System.Management.Automation/engine/Modules/ModuleUtils.cs
  src/System.Management.Automation/engine/Modules/TestModuleManifestCommand.cs
  src/System.Management.Automation/engine/SessionStateStrings.cs
  src/System.Management.Automation/engine/Utils.cs
  test/powershell/Modules/Microsoft.PowerShell.Core/Import-Module.Tests.ps1
  test/powershell/engine/Module/TestModuleManifest.Tests.ps1
Labels: CL-Engine

#8746 Don't use Win32 native APIs on non-Windows for crypto of secure string over remoting
  src/System.Management.Automation/engine/remoting/client/clientremotesession.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/resources/SecuritySupportStrings.resx
  src/System.Management.Automation/utils/CryptoUtils.cs
Labels: CL-Engine

#8837 Fix length check in `PSSnapinQualifiedName.GetInstance()`
  src/System.Management.Automation/engine/MshSnapinQualifiedName.cs
Labels: CL-CodeCleanup

#8846 Make license a link in the MSI
  assets/Product.wxs
  assets/files.wxs
  assets/ps_black_32x32.ico
Labels: CL-BuildPackaging

#8854 Remove yet another appveyor reference
  test/common/markdown/markdown.tests.ps1
Labels: CL-Tools

#8844 Update Coding Guidlines
  docs/dev-process/coding-guidelines.md
Labels: CL-Docs

#8843 Fix lgtm issues
  src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/convert-HTML.cs
  src/System.Management.Automation/FormatAndOutput/common/BaseOutputtingCommand.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataQuery.cs
  src/System.Management.Automation/cimSupport/cmdletization/ScriptWriter.cs
  src/System.Management.Automation/engine/CoreAdapter.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs
  src/System.Management.Automation/help/DefaultCommandHelpObjectBuilder.cs
  src/System.Management.Automation/help/HelpSystem.cs
  src/System.Management.Automation/help/UpdatableHelpCommandBase.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-CodeCleanup

#8905 Fix broken link
  docs/git/README.md
Labels: CL-Docs

#8918 Update CHANGELOG for release 6.1.3
  CHANGELOG.md
Labels: CL-Docs

#8888 Minor updates in build.psm1
  build.psm1
Labels: CL-Tools

#8894 Fix style issues in Csv cmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CSVCommands.cs
Labels: CL-CodeCleanup

#8199 Add configurable maximum depth in ConvertFrom-Json with `-Depth`
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertFromJsonCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertFrom-Json.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/JsonObject.Tests.ps1
Labels: CL-General, Committee-Reviewed

#8920 Use the OperationCancellationException to replace the StoppingException in 'ConvertToJson'
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs
  src/System.Management.Automation/engine/serialization.cs
Labels: CL-CodeCleanup

#8939 update the "dir -recurse" example
  docs/learning-powershell/README.md
Labels: CL-Docs

#8937 Use verbatim string literals for paths
  test/xUnit/csharp/test_PSConfiguration.cs
Labels: CL-Test

#8943 Fix typo in Test-Json tests: aganist ➜ against
  test/powershell/Modules/Microsoft.PowerShell.Utility/Test-Json.Tests.ps1
Labels: CL-CodeCleanup

#8889 [feature] Add -CustomPipeName to `pwsh` and `Enter-PSHostProcess`
  .gitignore
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/resources/CommandLineParameterParserStrings.resx
  src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx
  src/System.Management.Automation/engine/remoting/commands/EnterPSHostProcessCommand.cs
  src/System.Management.Automation/engine/remoting/common/RemoteSessionNamedPipe.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
  src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs
  src/System.Management.Automation/resources/RemotingErrorIdStrings.resx
  test/powershell/Modules/Microsoft.PowerShell.Core/Enter-PSHostProcess.Tests.ps1
  test/xUnit/csharp/test_NamedPipe.cs
Labels: CL-General

#8945 Make xUnit test run sequentially to rule out race conditions around 'powershell.config.json'
  .vsts-ci/windows.yml
  build.psm1
  test/xUnit/xUnit.tests.csproj
  test/xUnit/xunit.runner.json
  tools/ci.psm1
Labels: CL-Test

#8979 Make test file result names unique
  tools/ci.psm1
Labels: CL-BuildPackaging

#8895 Change label in doc issue template
  .github/ISSUE_TEMPLATE/Documentation_Issue.md
Labels: CL-Docs

#8996 Update release template
  .github/ISSUE_TEMPLATE/Release_Process.md
Labels: CL-Docs

#8847 Cleanup dllimport
  src/Microsoft.PowerShell.Commands.Diagnostics/CommonUtils.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/TimeZoneCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/SetDateCommand.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs
  src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Native.cs
  src/Microsoft.WSMan.Management/Interop.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/namespaces/FileSystemContentStream.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/namespaces/Win32Native.cs
  src/System.Management.Automation/security/SecureStringHelper.cs
  src/System.Management.Automation/security/nativeMethods.cs
  src/System.Management.Automation/utils/PlatformInvokes.cs
Labels: CL-CodeCleanup

#8966 Add test for -WhatIf for New-FileCatalog
  test/powershell/Modules/Microsoft.PowerShell.Security/FileCatalog.Tests.ps1
Labels: CL-Test, Hackathon

#8990 Remove ArchLinux Dockerfile
  docker/community/archlinux/Dockerfile
Labels: CL-CodeCleanup

#9001 Use List.AddRange()
  src/System.Management.Automation/engine/lang/parserutils.cs
Labels: CL-CodeCleanup

#9013 Fix MSI Upgrade failure for preview builds
  assets/Product.wxs
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging

#8993 Code coverage artifacts
  tools/ci.psm1
Labels: CL-Tools
