Repository PowerShell/PowerShell, pull requests merged in 2019-03, with the labels that each got.

#8959 Suggest "-id pid" for "Get-Process pid"
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Management/resources/ProcessResources.resx
Labels: CL-General, Hackathon

#8969 Refactor Shuffle in Get-Random to save a full iteration of the objects.
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Random.Tests.ps1
Labels: CL-General

#9019 Remove unused cached types from CachedReflectionInfo
  src/System.Management.Automation/engine/parser/Compiler.cs
Labels: CL-CodeCleanup

#8997 Update UML to represent SDK and Global tool builds
  tools/releaseBuild/azureDevOps/diagram.puml
  tools/releaseBuild/azureDevOps/diagram.svg
Labels: CL-BuildPackaging

#9032 Fix duplicate recommendation of Azure DevOps extension for VS Code
  .vscode/extensions.json
Labels: CL-Untagged

#9034 Align name schemes for test files
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Hex.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/New-Guid.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/New-TemporaryFile.Tests.ps1
Labels: CL-Test

#9036 Style fixes for ConvertTo-Xml tests
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertTo-Xml.Tests.ps1
Labels: CL-Test

#8954 Added RequireSudoOnUnix tags to PowerShellGet tests and unmark as pending
  test/powershell/Modules/PowerShellGet/PowerShellGet.Tests.ps1
Labels: CL-Test

#8851 Documentation Cleanup
  docs/DOCSMIGRATION.md
  docs/building/internals.md
  docs/cmdlet-example/visual-studio-simple-example.md
  docs/community/governance.md
  docs/debugging/README.md
  docs/dev-process/breaking-change-contract.md
  docs/dev-process/coding-guidelines.md
  docs/dev-process/resx-files.md
  docs/git/README.md
  docs/git/basics.md
  docs/learning-powershell/README.md
  docs/learning-powershell/create-powershell-scripts.md
  docs/learning-powershell/debugging-from-commandline.md
  docs/learning-powershell/powershell-beginners-guide.md
  docs/learning-powershell/working-with-powershell-objects.md
  docs/maintainers/README.md
  docs/maintainers/best-practice.md
  docs/maintainers/issue-management.md
  docs/testing-guidelines/CodeCoverageAnalysis.md
Labels: CL-Docs

#8859 Enable cross-platform Send-MailMessage tests for CI
  test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1
Labels: CL-Test

#9037 Style fixes for Select-Xml tests
  test/powershell/Modules/Microsoft.PowerShell.Utility/Select-XML.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Select-Xml.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/xml.tests.ps1
Labels: CL-Test

#9021 Cleanup & update ErrorRecord class code style
  src/System.Management.Automation/engine/ErrorPackage.cs
Labels: CL-CodeCleanup

#9063 Publish test package on release builds
  tools/releaseBuild/azureDevOps/diagram.puml
  tools/releaseBuild/azureDevOps/diagram.svg
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/testartifacts.yml
Labels: CL-BuildPackaging

#8056 Add 5 'InvokeAsync' overloads and 'StopAsync' to the 'PowerShell' type
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/DotNetTypes_format_ps1xml.cs
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
  test/powershell/engine/Api/TaskBasedAsyncPowerShellAPI.Tests.ps1
Labels: CL-Engine, Committee-Reviewed

#8951 Add UseQuotes parameter
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CSVCommands.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertTo-Csv.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Export-Csv.Tests.ps1
Labels: CL-General

#9051 Update release process issue template
  .github/ISSUE_TEMPLATE/Release_Process.md
Labels: CL-Untagged

#9079 Update the task-based async APIs added to PowerShell to return a Task object directly
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
  test/powershell/engine/Api/TaskBasedAsyncPowerShellAPI.Tests.ps1
Labels: CL-Engine

#9074 Rename private methods in MshCommandRuntime.cs
  src/System.Management.Automation/engine/MshCommandRuntime.cs
Labels: CL-CodeCleanup

#9071 Make install scripts more consistent over different operating systems
  .vsts-ci/install-ps.yml
  .vsts-ci/templates/install-ps-phase.yml
  tools/Xml/Xml.psm1
  tools/install-powershell-readme.md
  tools/install-powershell.sh
  tools/installpsh-amazonlinux.sh
  tools/installpsh-debian.sh
  tools/installpsh-osx.sh
  tools/installpsh-redhat.sh
  tools/installpsh-suse.sh
  tools/windows/Reset-PWSHSystemPath.ps1
Labels: CL-Tools

#9010 Update Docker README
  docker/README.md
Labels: CL-Docs

#9095 Fix artifact Download issue in release build
  tools/releaseBuild/azureDevOps/templates/nuget.yml
Labels: CL-BuildPackaging

#8779 Reduce race condition probability for config file access
  src/System.Management.Automation/engine/PSConfiguration.cs
Labels: CL-Engine

#9029 Update CachedReflectionInfo class with parameter types
  src/System.Management.Automation/engine/parser/Compiler.cs
Labels: CL-Engine

#8687 Allow `Test-ModuleManifest` to work when filename is not specified #8388
  src/System.Management.Automation/engine/Modules/TestModuleManifestCommand.cs
  test/powershell/engine/Module/TestModuleManifest.Tests.ps1
Labels: CL-General

#9107 Using supported syntax for restoring warnings
  src/Microsoft.PowerShell.Security/security/AclCommands.cs
  src/System.Management.Automation/engine/COM/ComUtil.cs
  src/System.Management.Automation/security/Authenticode.cs
  src/System.Management.Automation/security/nativeMethods.cs
Labels: CL-CodeCleanup

#9007 Fix Enter-PSHostProcess tests flakiness
  docs/learning-powershell/create-powershell-scripts.md
  docs/learning-powershell/powershell-beginners-guide.md
  test/powershell/Host/ConsoleHost.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Core/Enter-PSHostProcess.Tests.ps1
  test/tools/Modules/HelpersRemoting/HelpersRemoting.psd1
  test/tools/Modules/HelpersRemoting/HelpersRemoting.psm1
Labels: CL-Test

#8788 Fixing issue with help progress
  src/System.Management.Automation/help/HelpCommands.cs
  test/powershell/engine/Help/HelpSystem.Tests.ps1
Labels: CL-General

#8891 tab completion test doesn't handle multiple matches
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-Test

#8991 Fixed Dockerfile syntax highlighting
  tools/releaseBuild/Images/microsoft_powershell_windowsservercore/Dockerfile
  tools/releaseBuild/build.json
Labels: CL-BuildPackaging

#9045 Correct punctuations in README.md
  README.md
Labels: CL-Docs

#9090 Update link to Contributing guide to new PowerShell-Doc repo
  .github/CONTRIBUTING.md
Labels: CL-Docs

#8789 Removing Hardlink from Mode property in default file system format
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs
  src/System.Management.Automation/engine/Types_Ps1Xml.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/Test.Common.props
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-FormatData.Tests.ps1
  test/powershell/engine/Api/TypeInference.Tests.ps1
  test/xUnit/csharp/test_FileSystemProvider.cs
Labels: Committee-Reviewed, Documentation Needed

#9109 Add support empty NoteProperty in Group-Object
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ObjectCommandComparer.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Group-Object.Tests.ps1
Labels: CL-General

#9069 Fix -NoEnumerate behaviour in Write-Output
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Write-Object.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Write-Output.Tests.ps1
Labels: Breaking-Change, CL-BreakingChange, Committee-Reviewed

#9104 Make New-ModuleManifest consistent with Update-ModuleManifest
  src/System.Management.Automation/engine/Modules/NewModuleManifestCommand.cs
  src/System.Management.Automation/resources/Modules.resx
  test/powershell/engine/Module/NewModuleManifest.Tests.ps1
Labels: CL-General

#9066 Remove 'out' in ReadConsole pinvoke
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs
Labels: CL-CodeCleanup

#9133 Clean up Get-Random cmdlet
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Random.Tests.ps1
Labels: CL-CodeCleanup

#9130 Disable Homebrew analytics in macOS VSTS builds
  .vsts-ci/mac.yml
  tools/releaseBuild/azureDevOps/templates/mac.yml
Labels: CL-BuildPackaging

#8961 Made -Subject parameter of sendMail command no longer mandatory.
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Send-MailMessage.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1
Labels: CL-General

#9108 Adding CmdletsToExport and AliasesToExport to test module manifests.
  test/tools/Modules/HelpersCommon/HelpersCommon.psd1
  test/tools/Modules/HelpersHostCS/HelpersHostCS.psd1
  test/tools/Modules/HelpersLanguage/HelpersLanguage.psd1
  test/tools/Modules/HelpersRemoting/HelpersRemoting.psd1
  test/tools/Modules/HelpersSecurity/HelpersSecurity.psd1
  test/tools/Modules/HttpListener/HttpListener.psd1
  test/tools/Modules/PSSysLog/PSSysLog.psd1
  test/tools/Modules/WebListener/WebListener.psd1
Labels: CL-Tools

#9116 Fix for FormatTable remote deserialization regression
  src/System.Management.Automation/FormatAndOutput/common/FormattingObjectsDeserializer.cs
Labels: CL-Engine

#9143 Make `Start-Job` throw terminating exception when `-RunAs32` is specified in 64-bit pwsh
  src/System.Management.Automation/engine/hostifaces/PowerShellProcessInstance.cs
  src/System.Management.Automation/engine/remoting/commands/StartJob.cs
  src/System.Management.Automation/resources/RemotingErrorIdStrings.resx
  test/powershell/Modules/Microsoft.PowerShell.Core/Job.Tests.ps1
  test/xUnit/csharp/test_PowerShellAPI.cs
Labels: CL-General, Documentation Needed

#8100 Improve type inference of array literals and foreach statement variables
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: CL-Engine

#9160 Fix `Restart-Computer` to work on localhost when WinRM is not present
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/System.Management.Automation/engine/Modules/RemoteDiscoveryHelper.cs
Labels: CL-General

#9124 Translate Skipped the test results into something Azure DevOps does NOT understand
  build.psm1
Labels: CL-BuildPackaging

#9163 Publish global tool packages to pwshtool blob and bug fixes
  tools/packaging/packaging.psm1
  tools/releaseBuild/azureDevOps/templates/nuget.yml
Labels: CL-BuildPackaging

#9176 Add tsaVersion property as TsaV1 for compliance build phase
  tools/releaseBuild/azureDevOps/templates/compliance.yml
Labels: CL-BuildPackaging

#9177 Add xsd for cdxml
  src/System.Management.Automation/cimSupport/cmdletization/xml/cmdlets-over-objects.xsd
Labels: CL-Engine

#9171 Use IL assemblies for NuGet packages to reduce size
  tools/packaging/packaging.psd1
  tools/packaging/packaging.psm1
  tools/releaseBuild/azureDevOps/templates/nuget.yml
Labels: CL-BuildPackaging

#9179 Performance improvements for release build
  tools/releaseBuild/azureDevOps/diagram.puml
  tools/releaseBuild/azureDevOps/diagram.svg
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/compliance.yml
  tools/releaseBuild/azureDevOps/templates/windows-package-signing.yml
  tools/releaseBuild/build.json
  tools/releaseBuild/macOS/PowerShellPackageVsts.ps1
  tools/releaseBuild/vstsbuild.ps1
Labels: CL-BuildPackaging

#9180 Add tests for command globbing
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
  test/powershell/engine/Basic/CommandDiscovery.Tests.ps1
Labels: CL-Test

#9165 Refactor ReadConsole P/Invoke in ConsoleHost
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
Labels: CL-CodeCleanup

#9195 Minor cleanups in Process.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
Labels: CL-CodeCleanup

#9190 Cleanup style issues in CoreAdapter and MshObject
  src/System.Management.Automation/engine/CoreAdapter.cs
  src/System.Management.Automation/engine/MshObject.cs
  test/xUnit/csharp/test_PSObject.cs
Labels: CL-CodeCleanup

#9199 Enable securestring cmdlets for non-Windows
  src/System.Management.Automation/security/SecureStringHelper.cs
  test/powershell/Modules/Microsoft.PowerShell.Security/SecureString.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/clixml.tests.ps1
Labels: CL-General

#9209 Make linux CI parallel
  .vsts-ci/linux.yml
  .vsts-ci/mac.yml
Labels: CL-BuildPackaging

#9182 Minor FileSystemProvider cleanup
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-CodeCleanup

#9205 Typo in new parameter set
  src/System.Management.Automation/engine/remoting/commands/EnterPSHostProcessCommand.cs
Labels: CL-CodeCleanup

#9203 Add psremoting enable/disable cmdlet warning messages
  src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs
  src/System.Management.Automation/resources/RemotingErrorIdStrings.resx
Labels: OS-Windows

#9214 Remove non-existent paths from csproj files
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
Labels: CL-CodeCleanup

#9220 Cleanup HostUtilities.cs - remove unused CredUIPromptForCredential()
  src/System.Management.Automation/engine/hostifaces/HostUtilities.cs
Labels: CL-CodeCleanup

#9111 Implement Get-Random -Count without specifying an InputObject list
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Random.Tests.ps1
Labels: CL-General

#9134 Fix coding style for NewModuleManifestCommand
  src/System.Management.Automation/engine/Modules/NewModuleManifestCommand.cs
Labels: CL-CodeCleanup

#9197 Refactor LookupAccountSid P/Invoke in Process.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/System.Management.Automation/namespaces/Win32Native.cs
Labels: CL-CodeCleanup

#9212 Remove code from `CI.psm1` to optionally run Feature tests
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/testing-guidelines/testing-guidelines.md
  tools/ci.psm1
Labels: CL-BuildPackaging

#9101 Fix Get-Module -FullyQualifiedName option to work with paths
  src/System.Management.Automation/engine/Modules/GetModuleCommand.cs
  src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs
  test/powershell/Modules/Microsoft.PowerShell.Core/Get-Module.Tests.ps1
Labels: Breaking-Change, Committee-Reviewed

#9249 Add secret scanning to CI
  .vsts-ci/misc-analysis.yml
  .vsts-ci/templates/credscan.yml
Labels: CL-BuildPackaging
