Repository PowerShell/PowerShell, pull requests merged in 2019-04, with the labels that each got.

#9253 Check to be sure that the test result file has actual results before uploading
  build.psm1
Labels: Area-Build, CL-BuildPackaging

#8587 Add support for PathSeparator property in Providers
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
  src/System.Management.Automation/engine/DataStoreAdapterProvider.cs
  src/System.Management.Automation/namespaces/AliasProvider.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/namespaces/ProviderBase.cs
  src/System.Management.Automation/namespaces/RegistryProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-PSProvider.Tests.ps1
  test/powershell/Modules/Microsoft.WSMan.Management/ConfigProvider.Tests.ps1
Labels: CL-General, Committee-Reviewed

#9202 Make command searcher not use wildcard search for execution
  build.psm1
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/engine/CommandSearcher.cs
  test/powershell/engine/Basic/CommandDiscovery.Tests.ps1
Labels: Breaking-Change, CL-Engine, Committee-Reviewed

#8500 Style: Update StyleCop rules
  Settings.StyleCop
  stylecop.json
Labels: CL-CodeCleanup

#9288 Publish windows daily build to MyGet
  build.psm1
  tools/ci.psm1
Labels: CL-BuildPackaging

#7993 Add Binary Parsing Support & Refactor TryGetNumberValue & ScanNumberHelper
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/parser/CharTraits.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
  test/powershell/Language/Parser/Parser.Tests.ps1
Labels: Breaking-Change, CL-Engine, Committee-Reviewed, Documentation Needed

#9297 Remove duplicate Policheck task and pin to specific version
  tools/releaseBuild/azureDevOps/templates/compliance.yml
Labels: CL-BuildPackaging

#9132 Add QuoteFields parameter to ConvertTo-Csv and Export-Csv
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CSVCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/CsvCommandStrings.resx
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertTo-Csv.Tests.ps1
Labels: CL-General

#9281 Fix stylecop hungarian
  Settings.StyleCop
  stylecop.json
Labels: CL-CodeCleanup

#9304 Fix skipping of tests in RemoteSession.Basic.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Security/ExecutionPolicy.Tests.ps1
  test/powershell/engine/Remoting/RemoteSession.Basic.Tests.ps1
  tools/ci.psm1
Labels: CL-Test

#9305 Preserve user shortcuts pinned to Taskbar during MSI upgrade
  assets/Product.wxs
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging

#9324 Update repo for Ubuntu 14.04 EOL
  README.md
  build.psm1
  docker/tests/Templates/fxdependent-ubuntu14.04/Dockerfile
  docker/tests/Templates/ubuntu14.04/Dockerfile
  docker/tests/containerTestCommon.psm1
  docs/building/linux.md
  tools/packaging/packaging.psm1
  tools/releaseBuild/Images/microsoft_powershell_ubuntu14.04/Dockerfile
  tools/releaseBuild/build.json
Labels: CL-CodeCleanup

#9033 Fix help paging issues on macOS/Linux and with custom pager that takes arguments
  src/System.Management.Automation/engine/InitialSessionState.cs
Labels: CL-General

#9247 Added more tests for import-alias by file, regarding parsing 'difficult' aliases strings
  test/powershell/Modules/Microsoft.PowerShell.Utility/Import-Alias.Tests.ps1
Labels: CL-Test

#9302 Reduce time for stack overflow test
  test/powershell/Host/ConsoleHost.Tests.ps1
Labels: CL-Test

#9351 Add AccessToken variable to jobs that perform signing
  tools/releaseBuild/azureDevOps/templates/mac-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/nuget.yml
Labels: CL-BuildPackaging

#9344 Create macOS test package for release build
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/testartifacts.yml
Labels: CL-BuildPackaging

#9329 Style: Match file name casings of C# source files for Utility commands
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Compare-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertTo-Html.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-object/Format-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-printer/Out-Printer.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-string/Out-String.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Group-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Join-String.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/New-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/NewEventCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Select-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Sort-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Tee-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Update-List.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Write.cs
Labels: CL-CodeCleanup

#8923 New `New-PSBreakpoint` cmdlet & new `-Breakpoint` parameter for `Debug-Runspace`
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/DebugRunspaceCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/New-PSBreakpoint.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/PSBreakpointCreationBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Set-PSBreakpoint.cs
  src/Modules/Unix/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/Modules/Windows/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/debugger/Breakpoint.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspace.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Enable-RunspaceDebug.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/New-PSBreakpoint.Tests.ps1
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
  test/tools/TestMetadata.json
  test/xUnit/csharp/test_Runspace.cs
Labels: CL-General

#9368 Create dependabot config.yml
  .dependabot/config.yml
  .vsts-ci/linux.yml
  .vsts-ci/mac.yml
  .vsts-ci/windows-daily.yml
  .vsts-ci/windows.yml
Labels: CL-Tools

#9374 Add ability to cross compile
  PowerShell.Common.props
  build.psm1
  test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1
Labels: CL-BuildPackaging

#9373 Create codecoverage and test packages for non-windows
  .vsts-ci/linux.yml
  .vsts-ci/mac.yml
  .vsts-ci/templates/windows-packaging.yml
  build.psm1
  tools/ci.psm1
Labels: CL-BuildPackaging

#9376 Run CodeFormatter for Utility module
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddMember.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Compare-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertFrom-SddlString.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertFromMarkdownCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetDateCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetVerbCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MarkdownOptionCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/UtilityCommon.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertToJsonCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebProxy.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebResponseObjectFactory.CoreClr.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/PSUserAgent.cs
Labels: CL-CodeCleanup

#9377 Run CodeFormatter for Microsoft.PowerShell.Commands.Management
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/CimJobException.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimChildJobBase.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
Labels: CL-CodeCleanup

#9378 Run CodeFormatter for Diagnostics module
  src/Microsoft.PowerShell.Commands.Diagnostics/GetEventCommand.cs
Labels: CL-CodeCleanup

#9383 Add wildcard back to end of tab completion command lookup
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: Area-Engine

#9338 fix assert firing in line 695 in debug builds
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
Labels: CL-General

#9392 Use Environment.NewLine instead of Crlf
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
Labels: CL-CodeCleanup

#9394 Run CodeFormatter for Eventing
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/UnsafeNativeMethods.cs
Labels: CL-CodeCleanup

#9398 Run CodeFormatter for MarkdownRender
  src/Microsoft.PowerShell.MarkdownRender/CodeInlineRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/EmphasisInlineRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/ListItemBlockRenderer.cs
Labels: CL-CodeCleanup

#9399 Run CodeFormatter for Security module
  src/Microsoft.PowerShell.Security/security/AclCommands.cs
  src/Microsoft.PowerShell.Security/security/CertificateCommands.cs
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
Labels: CL-CodeCleanup

#9401 Run CodeFormatter for WSMan.Runtime
  src/Microsoft.WSMan.Runtime/WSManSessionOption.cs
Labels: CL-CodeCleanup

#9400 Run CodeFormatter for WSMan.Management
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/Microsoft.WSMan.Management/CredSSP.cs
  src/Microsoft.WSMan.Management/CurrentConfigurations.cs
  src/Microsoft.WSMan.Management/Interop.cs
  src/Microsoft.WSMan.Management/InvokeWSManAction.cs
  src/Microsoft.WSMan.Management/NewWSManSession.cs
  src/Microsoft.WSMan.Management/PingWSMan.cs
  src/Microsoft.WSMan.Management/Set-QuickConfig.cs
  src/Microsoft.WSMan.Management/WSManConnections.cs
  src/Microsoft.WSMan.Management/WSManInstance.cs
  src/Microsoft.WSMan.Management/WsManHelper.cs
Labels: CL-CodeCleanup

#9393 Run CodeFormatter for ConsoleHost
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostRawUserInterface.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfaceProgress.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ManagedEntrance.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/Serialization.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/StartTranscriptCmdlet.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/Telemetry.cs
Labels: CL-CodeCleanup

#9276 Adding tests for `Remove-Module`
  test/powershell/Modules/Microsoft.PowerShell.Core/Remove-Module.Tests.ps1
Labels: CL-Test

#9385 Move warning message to EndProcessing for ExperimentalFeature cmdlets so it only shows up once
  src/System.Management.Automation/engine/ExperimentalFeature/EnableDisableExperimentalFeatureCommand.cs
  test/powershell/engine/ExperimentalFeature/EnableDisable-ExperimentalFeature.Tests.ps1
Labels: CL-General

#9250 Return correct casing of filesystem path during normalization
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Set-Location.Tests.ps1
Labels: CL-General

#9457 Update 'Publish-TestResults' to make AzDO fail the task when any tests failed
  build.psm1
  test/powershell/Modules/Microsoft.PowerShell.Management/Set-Location.Tests.ps1
Labels: CL-BuildPackaging

#9471 Enable building on Kali Linux
  build.psm1
Labels: Area-Build

#9476 Build test packages for windows, linux-x64, linux-arm, linux-arm64 and macOS
  build.psm1
  tools/releaseBuild/azureDevOps/diagram.puml
  tools/releaseBuild/azureDevOps/diagram.svg
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/testartifacts.yml
Labels: CL-BuildPackaging

#9479 Allow passing just a dash as an arg to a file via pwsh
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
Labels: CL-Engine

#9455 Cleanup Export-Command from assemblyinfo
  src/System.Management.Automation/AssemblyInfo.cs
Labels: CL-CodeCleanup
