Repository PowerShell/PowerShell, pull requests merged in 2019-05, with the labels that each got.

#9438 Fix Get-Runspace runspace object format Type column
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
Labels: CL-General

#9458 Ensure Wait-UntilTrue returns $true in Pester tests
  test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Core/Enter-PSHostProcess.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Core/Get-PSHostProcessInfo.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertTo-Json.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Invoke-Item.Tests.ps1
  test/powershell/engine/Api/BasicEngine.Tests.ps1
  test/powershell/engine/Api/TaskBasedAsyncPowerShellAPI.Tests.ps1
  test/tools/Modules/HelpersCommon/HelpersCommon.psm1
Labels: CL-Test

#9503 Update width of datetime formatting to accommodate change in Japan datetime era
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/Diagnostics_Format_ps1xml.cs
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/DotNetTypes_format_ps1xml.cs
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/Event_Format_ps1xml.cs
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs
Labels: CL-General

#9510 Update to Pester 4.8.0
  build.psm1
Labels: CL-Test

#9213 Add unit and feature tests for Send-MailMessage
  test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1
Labels: CL-Test

#9520 Add download link to raspbian64 to README.md
  README.md
Labels: CL-Docs

#9508 Update use of `Windows PowerShell` to just `PowerShell` in our logging
  src/Microsoft.PowerShell.Commands.Diagnostics/resources/GetEventResources.txt
  src/Microsoft.WSMan.Management/resources/WsManResources.txt
  src/Modules/Windows/Microsoft.PowerShell.Diagnostics/GetEvent.types.ps1xml
  src/Modules/Windows/Microsoft.WSMan.Management/WSMan.format.ps1xml
  src/Modules/Windows/PSDiagnostics/PSDiagnostics.psm1
  src/PowerShell.Core.Instrumentation/PowerShell.Core.Instrumentation.man
  src/System.Management.Automation/engine/remoting/client/remoterunspace.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/RemoteHost.cs
  src/System.Management.Automation/resources/EventResource.resx
  src/System.Management.Automation/resources/RunspacePoolStrings.resx
  test/powershell/engine/Module/ModulePath.Tests.ps1
Labels: CL-CodeCleanup

#9404 Fix null reference when module is null in hosting scenarios
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertFromMarkdownCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MarkdownOptionCommands.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/MarkdownCmdlets.Tests.ps1
Labels: CL-General

#9536 Add Support for Null Usernames in Web Cmdlet Basic Auth
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: CL-General

#9529 Change MatchType for EnumerationOptions to be Win32
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1
Labels: CL-General

#9509 Enable recursion into OneDrive
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-General

#9531 Cleanup unused pinvokes on unix
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
  src/System.Management.Automation/engine/InformationRecord.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  test/xUnit/csharp/test_CorePsPlatform.cs
Labels: CL-CodeCleanup

#9528 Add support for `-l` to pwsh so that it is compatible with POSIX shell expectations
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx
  test/powershell/Host/ConsoleHost.Tests.ps1
Labels: CL-General

#9059 Add support for ValidateRangeKind to ParameterMetadata.GetProxyAttributeData
  src/System.Management.Automation/engine/Attributes.cs
  src/System.Management.Automation/engine/TypeMetadata.cs
  test/powershell/engine/Basic/ProxyCommand.tests.ps1
Labels: CL-Engine

#9534 Remove `IsSymLink()` P/Invoke on Unix
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-CodeCleanup

#9551 Improve error message in FileSystemProvider
  src/System.Management.Automation/resources/FileSystemProviderStrings.resx
Labels: CL-General

#9530 Use IPGlobalProperties on all platforms
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
  src/System.Management.Automation/utils/PsUtils.cs
Labels: CL-CodeCleanup

#9555 use PkgMgmt 1.3.2 and PSGet 2.1.3 which has fix for NetCore30
  src/Modules/PSGalleryModules.csproj
Labels: CL-General

#8938 Support line continuance with pipe at the start of a line
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
  test/powershell/Language/Parser/LineContinuance.Tests.ps1
  test/powershell/Language/Parser/Parsing.Tests.ps1
Labels: CL-Engine

#9589 fix use of unicode ellipsis in xml
  src/System.Management.Automation/resources/ErrorPackage.resx
Labels: CL-General

#9577 Updating committee membership
  docs/community/governance.md
Labels: CL-Docs

#9607 Convert windows CI to stages
  .vsts-ci/linux.yml
  .vsts-ci/mac.yml
  .vsts-ci/templates/verify-xunit.yml
  .vsts-ci/windows-daily.yml
  .vsts-ci/windows.yml
Labels: CL-Test

#9606 Switch from BMP to PNG for graphical MSI installer assets
  assets/Product.wxs
  assets/WixUIBannerBmp.bmp
  assets/WixUIBannerBmp.png
  assets/WixUIDialogBmp.bmp
  assets/WixUIDialogBmp.png
  assets/WixUIInfoIco.bmp
  assets/WixUIInfoIco.png
Labels: CL-BuildPackaging

#9619 Add checkbox to PR checklist for experimental feature use
  .github/PULL_REQUEST_TEMPLATE.md
Labels: CL-Docs

#9623 Make sure we always return an object in command searcher
  src/System.Management.Automation/engine/CommandSearcher.cs
  test/powershell/engine/Basic/CommandDiscovery.Tests.ps1
Labels: CL-Engine

#9618 Remove Workflow from PSSessionType
  src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs
  src/System.Management.Automation/engine/remoting/commands/NewPSSessionConfigurationOptionCommand.cs
  src/System.Management.Automation/engine/remoting/common/PSSessionConfigurationTypeOption.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
  src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
  src/System.Management.Automation/utils/tracing/TracingGen.cs
Labels: CL-CodeCleanup

#9625 Attributes.cs - Style / Formatting Fixes
  src/System.Management.Automation/engine/Attributes.cs
Labels: CL-CodeCleanup

#9646 Fix the CI build
  tools/ci.psm1
  tools/metadata.json
Labels: CL-Test

#9658 Update vNext release branches in dependabot config
  .dependabot/config.yml
Labels: CL-NotInBuild

#9645 Disable the debugger when in system lock-down mode
  src/System.Management.Automation/engine/debugger/debugger.cs
  test/powershell/Modules/Microsoft.PowerShell.Security/ConstrainedLanguageDebugger.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Security/ConstrainedLanguageRestriction.Tests.ps1
Labels: Area-Engine, Breaking-Change, CL-BreakingChange, Committee-Reviewed, Compliance, Issue-Bug

#9708 Integrate building NuGet package in the coordinated build (#8947)
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/nuget.yml
Labels: CL-BuildPackaging

#9715 Enable building of msix package (#9289)
  .gitignore
  assets/AppxManifest.xml
  assets/Square150x150Logo.png
  assets/Square44x44Logo.png
  assets/Square44x44Logo.targetsize-48.png
  assets/Square44x44Logo.targetsize-48_altform-unplated.png
  assets/StoreLogo.png
  tools/packaging/packaging.psm1
  tools/releaseBuild/Images/microsoft_powershell_windowsservercore/Dockerfile
  tools/releaseBuild/Images/microsoft_powershell_windowsservercore/PowerShellPackage.ps1
  tools/releaseBuild/azureDevOps/templates/upload.yml
  tools/releaseBuild/azureDevOps/templates/windows-package-signing.yml
  tools/releaseBuild/build.json
Labels: CL-BuildPackaging

#9748 Pin version of netDumbster to 2.0.0.4
  test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1
Labels: CL-BuildPackaging

#9747 Update the target framework for reference assemblies to netcoreapp3.0
  tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  tools/packaging/projects/reference/System.Management.Automation/System.Management.Automation.csproj
Labels: CL-BuildPackaging

#9760 Change log for release 6.2.1
  .spelling
  CHANGELOG.md
Labels: CL-Docs

#9759 Change log 6.1.4
  CHANGELOG.md
Labels: CL-Docs

#9772 Increase timeout of NuGet job to workaround build timeout
  tools/releaseBuild/azureDevOps/templates/nuget.yml
Labels: CL-BuildPackaging

#9732 Code Cleanup: Tidy up scriptblock.cs
  src/System.Management.Automation/engine/lang/scriptblock.cs
Labels: CL-CodeCleanup

#9785 Disable stale bot
  .github/stale.yml
Labels: CL-NotInBuild
