Repository PowerShell/PowerShell, pull requests merged in 2019-10, with the labels that each got.

#10644 Remove [ValidateNotNullOrEmpty] from -InputObject on Get-Random to allow empty string
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Random.Tests.ps1
Labels: AutoMerge, CL-General

#10653 Add back newline for grouping with `Format-Table` and `-Property`
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/Certificate_format_ps1xml.cs
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/Registry_format_ps1xml.cs
  src/System.Management.Automation/FormatAndOutput/common/BaseOutputtingCommand.cs
  src/System.Management.Automation/resources/FileSystemProviderStrings.resx
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Custom.Tests.ps1
Labels: CL-General

#10681 Direct Clear-Host output to terminal
  src/System.Management.Automation/engine/InitialSessionState.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
Labels: CL-General

#10662 Read special reparse points without accessing it
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-Item.Tests.ps1
Labels: CL-General

#10666 Replace Ambiguous language for tests from switch to argument for acc…
  test/powershell/Modules/Microsoft.PowerShell.Management/Remove-Item.Tests.ps1
Labels: CL-Test

#10478 Test-Connection - Remove informational output, consolidate Ping usage
  src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs
  src/Microsoft.PowerShell.Commands.Management/resources/TestConnectionResources.resx
Labels: CL-General

#10638 Update `Support_Question.md` to link to Stack Overflow as anothe…
  .github/ISSUE_TEMPLATE/Support_Question.md
Labels: CL-Docs

#10483 Adding New-Service to -SecurityDescriptorSDDL parameter like Set-Service
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1
Labels: CL-General

#10507 Add `Get-ChildItem` test
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1
Labels: CL-Test

#10678 Update help format to use proper case
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/HelpV3_format_ps1xml.cs
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/Help_format_ps1xml.cs
Labels: CL-CodeCleanup

#10680 Replace 'api-ms-win-core-file-l1-2-2.dll' with 'Kernell32.dll'
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-General

#10672 Set current working directory of each ForEach-Object -Parallel running script to the same location as the calling script.
  src/System.Management.Automation/engine/InternalCommands.cs
  src/System.Management.Automation/engine/hostifaces/PSTask.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Foreach-Object-Parallel.Tests.ps1
Labels: CL-General

#10320 Remove deprecated workflow logic from the remoting setup scripts
  src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs
Labels: CL-CodeCleanup

#10702 Fix broken DSC overview link
  demos/DSC/readme.md
Labels: CL-Docs

#10641 Add ConciseView for $ErrorView
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  src/System.Management.Automation/engine/CommandBase.cs
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/parser/Position.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
  test/powershell/Language/Parser/RedirectionOperator.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Implicit.Remoting.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Write-Error.Tests.ps1
  test/powershell/engine/Formatting/ErrorView.Tests.ps1
Labels: CL-General

#10698 Some code cleanup work
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleShell.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ManagedEntrance.cs
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/Modules/AnalysisCache.cs
  src/System.Management.Automation/engine/PSConfiguration.cs
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/hostifaces/HostUtilities.cs
  test/powershell/engine/Basic/Telemetry.Tests.ps1
  test/xUnit/csharp/test_PSConfiguration.cs
Labels: CL-CodeCleanup

#10138 $PSCulture follows CurrentThread.CurrentCulture
  src/System.Management.Automation/engine/CultureVariable.cs
  src/System.Management.Automation/engine/SessionState.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Culture.Tests.ps1
Labels: CL-BreakingChange, Committee-Reviewed

#10706 Add the missing token text for `TokenKind.QuestionMark`
  src/System.Management.Automation/engine/parser/token.cs
Labels: CL-General

#10616 Replace CR and new line with a 0x23CE character
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
  test/powershell/Host/Logging.Tests.ps1
Labels: CL-Engine

#10659 Renamed wrongly named file
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/InvokeExpressionCommand.cs
Labels: CL-CodeCleanup

#10674 Add support for \\wsl$\ubuntu path
  src/System.Management.Automation/engine/Utils.cs
Labels: CL-General

#8963 Adds emphasis to Select-String default formatter
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Select-String.Tests.ps1
Labels: CL-General, Committee-Reviewed, Hacktoberfest

#10736 Add `MacPorts` support to the build system
  .spelling
  build.psm1
  docs/building/macos.md
Labels: CL-BuildPackaging

#10746 For `ConciseView`, show line context information if line is greater than 1 even if there is no scriptname
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
Labels: CL-General

#10721 Adding positional parameter for ScriptBlock when using Invoke-Command with SSH
  src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Core/RemotingCmdlets.Tests.ps1
Labels: CL-General

#10703 Add comment describing why -ia is not the alias for -InformationAction common parameter
  src/System.Management.Automation/engine/CommonCommandParameters.cs
Labels: Breaking-Change, CL-General, Committee-Reviewed

#10738 Check `pwsh.exe` and `pwsh` in daily version on Windows
  tools/install-powershell.ps1
Labels: CL-Tools

#10740 Add back `Get-HotFix` cmdlet
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Management/commands/management/Hotfix.cs
  src/Modules/Windows/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.psd1
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-HotFix.Tests.ps1
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
Labels: CL-General

#10768 Add test for the even handler leaking fix
  test/xUnit/csharp/test_Runspace.cs
Labels: CL-Test

#10767 Sync capitalization in CI YAML
  .vsts-ci/misc-analysis.yml
  .vsts-ci/templates/ci-build.yml
  .vsts-ci/templates/credscan.yml
  .vsts-ci/templates/install-ps-phase.yml
  .vsts-ci/templates/nanoserver.yml
  .vsts-ci/templates/nix-test.yml
  .vsts-ci/templates/windows-test.yml
Labels: CL-Test

#10665 Add -Delimiter to ConvertFrom-StringData
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertFrom-StringData.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertFrom-StringData.Tests.ps1
Labels: CL-General

#10773 `install-powershell.sh`: Switch from `/etc/lsb-release` to `/etc/os-release` for Debian
  tools/install-powershell.sh
Labels: AutoMerge, CL-Tools

#10778 Replace links from MSDN to docs.microsoft.com
  docs/learning-powershell/powershell-beginners-guide.md
Labels: CL-Docs

#10765 Remove unused `SourceLength` remoting property causing formatting issues
  src/System.Management.Automation/FormatAndOutput/common/FormatViewManager.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/EncodeAndDecode.cs
Labels: CL-General

#10646 Enable tab completion for variable assignment that is enum
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General

#10639 Reword access denied error message in Get-WinEvent
  src/Microsoft.PowerShell.Commands.Diagnostics/resources/GetEventResources.resx
Labels: CL-General

#10749 Fix for `Get-Content -ReadCount 0` behavior when `-TotalCount` is set
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetContentCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-Content.Tests.ps1
Labels: CL-General

#8674 Format-Hex: Improve mixed-collection piped input and piped streams of input
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-hex/Format-Hex.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/UtilityCommon.cs
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Hex.Tests.ps1
Labels: CL-General, Documentation Needed

#9899 Cleanup COM interfaces in jump list code - fix PreserveSig attributes
  src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/ComInterfaces.cs
Labels: CL-CodeCleanup

#10727 Implement `Get-Error` cmdlet as Experimental Feature
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Get-Error.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/Modules/Unix/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/Modules/Windows/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Error.Tests.ps1
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
Labels: CL-Experimental

#10569 Minor performance improvements for runspace initialization
  src/System.Management.Automation/singleshell/config/MshSnapinInfo.cs
Labels: CL-Performance

#10775 Update build docs
  docs/building/windows-core.md
  docs/testing-guidelines/testing-guidelines.md
Labels: CL-Docs

#10781 LanguagePrimitives.IsNullLike() - use more effective evaluation order
  src/System.Management.Automation/engine/LanguagePrimitives.cs
Labels: CL-General

#10790 Stabilize the event handler leaking test and make `Start-PSBuild -SMAOnly` literally just rebuild `S.M.A.dll`
  build.psm1
  test/xUnit/csharp/test_SecuritySupport.cs
Labels: CL-Test

#10636 Implement Null Coalescing and Null Coalescing assignment operators
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/parser/token.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
  test/powershell/Language/Operators/NullConditional.Tests.ps1
  test/powershell/Language/Parser/Parsing.Tests.ps1
Labels: Breaking-Change, Committee-Reviewed

#10827 Skip the flaky test `TestAppDomainProcessExitEvenHandlerNotLeaking` for now
  test/xUnit/csharp/test_Runspace.cs
Labels: CL-Test

#10826 Bump Microsoft.PowerShell.Native to 7.0.0-preview.3
  src/System.Management.Automation/System.Management.Automation.csproj
Labels: CL-BuildPackaging

#10800 Disable strict mode in `Get-Error` formatting script
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
Labels: CL-General

#10836 Fix pure expressions setting $? in pipeline chains
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/parser/token.cs
  test/powershell/Language/Operators/PipelineChainOperator.Tests.ps1
Labels: CL-Engine

#10834 Update ThirdPartyNotices.txt
  ThirdPartyNotices.txt
Labels: CL-BuildPackaging

#10824 Set the output encoding to [Console]::OutputEncoding for native commands
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1
Labels: CL-General

#10837 Select the files for compliance tests which are owned by PowerShell
  tools/packaging/packaging.psm1
  tools/releaseBuild/azureDevOps/templates/compliance.yml
Labels: CL-BuildPackaging

#10368 Cleanup style issues in Compiler.cs
  src/System.Management.Automation/engine/SessionStateFunctionAPIs.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
Labels: CL-CodeCleanup

#10840 Fix command runtime so StopUpstreamCommandsException doesn't get populated in `-ErrorVariable`
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Select-Object.Tests.ps1
Labels: CL-General

#10810 Fix stringdata test to correctly validate keys of hashtables
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertFrom-StringData.Tests.ps1
Labels: CL-Test

#10648 Add limit check in Get-WinEvent
  src/Microsoft.PowerShell.Commands.Diagnostics/GetEventCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/resources/GetEventResources.resx
  test/powershell/Modules/Microsoft.PowerShell.Diagnostics/Get-WinEvent.Tests.ps1
Labels: CL-General

#10854 Updating links in README.md and metadata.json for Preview.5
  README.md
  tools/metadata.json
Labels: CL-BuildPackaging

#10878 Update AppX Manifest and Packaging module to conform to MS Store requirements
  assets/AppxManifest.xml
  tools/packaging/packaging.psm1
  tools/releaseBuild/Images/microsoft_powershell_windowsservercore/PowerShellPackage.ps1
Labels: CL-BuildPackaging

#10909 Add back `Clear-RecycleBin` for Windows
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Management/commands/management/ClearRecycleBinCommand.cs
  src/Modules/Windows/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.psd1
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
Labels: CL-General

#10910 During Tab Completion, skip file if can't read file attributes
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
Labels: CL-General

#10925 Updated FWLink Id for Clear-RecycleBin
  src/Microsoft.PowerShell.Commands.Management/commands/management/ClearRecycleBinCommand.cs
  test/powershell/engine/Help/assets/HelpURI/V3Cmdlets.csv
Labels: CL-General

#10890 Fix to Select-String emphasis and Import-DscResource in CHANGELOG.md
  CHANGELOG.md
Labels: CL-Docs

#10928 Update tests to accurately describe test actions.
  test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Set-Location.Tests.ps1
Labels: CL-Test

#10922 Add back `Update-List` command
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Update-List.cs
  src/Modules/Unix/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/Modules/Windows/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Update-List.Tests.ps1
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
  test/powershell/engine/Help/assets/HelpURI/V2Cmdlets.csv
Labels: CL-General

#10937 Fix use of accent colors for hosts that don't support them
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
Labels: CL-General

#10938 Handle case where Host may not return Rows or Cols of screen
  src/System.Management.Automation/FormatAndOutput/out-console/ConsoleLineOutput.cs
Labels: CL-General

#10914 Add basic examples for `install-powershell.ps1`
  tools/install-powershell-readme.md
Labels: CL-Tools

#10849 Change TabExpansion2 to not require `-CursorColumn` and treat as `$InputScript.Length`
  src/System.Management.Automation/engine/InitialSessionState.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: AutoMerge, CL-General

#10808 Reinstate debugging API lost in #10338
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/hostifaces/PSTask.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspace.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
Labels: CL-CodeCleanup

#10930 Fix GetCorrectCasedPath() to first check if any system file entries is returned before calling First()
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-General

#10850 Fix tab completion for parameters so that it shows common parameters as available
  src/System.Management.Automation/engine/MergedCommandParameterMetadata.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Member.Tests.ps1
Labels: CL-General

#10903 Disable update notification check for daily builds
  src/Microsoft.PowerShell.ConsoleHost/host/msh/UpdatesNotification.cs
Labels: CL-CodeCleanup
