Repository PowerShell/PowerShell, pull requests merged in 2019-08, with the labels that each got.

#10230 Cleanup: ThreadAbortException is now in .Net Core 3.0
  src/Microsoft.PowerShell.ScheduledJob/ScheduledJobDefinition.cs
  src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs
  src/System.Management.Automation/engine/hostifaces/Pipeline.cs
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
  src/System.Management.Automation/engine/interpreter/ControlFlowInstructions.cs
  src/System.Management.Automation/engine/interpreter/InterpretedFrame.cs
  src/System.Management.Automation/engine/interpreter/Interpreter.cs
  src/System.Management.Automation/engine/remoting/client/JobManager.cs
Labels: CL-CodeCleanup

#10297 Update dead links from powershell.com
  .spelling
  docs/learning-powershell/README.md
  docs/learning-powershell/powershell-beginners-guide.md
Labels: CL-Docs

#10244 Remove extra check that the system dll exists
  .github/CODEOWNERS
  src/System.Management.Automation/security/wldpNativeMethods.cs
Labels: CL-Performance

#10227 Update .Net Core runtime from 3.0-preview6 to preview7
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  assets/files.wxs
  global.json
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  src/powershell-win-core/powershell-win-core.csproj
  test/tools/WebListener/WebListener.csproj
  tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  tools/packaging/projects/reference/System.Management.Automation/System.Management.Automation.csproj
Labels: CL-BuildPackaging

#10269 Fix debugger disable performance regression
  src/System.Management.Automation/engine/debugger/debugger.cs
  test/powershell/Modules/Microsoft.PowerShell.Security/ConstrainedLanguageDebugger.Tests.ps1
Labels: CL-Engine

#10294 Don't collect process starttime as it's not being used on consolehost startup
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
Labels: CL-CodeCleanup

#10310 Cleanup Docker release testing
  docker/InstallTarballPackage.sh
  docker/tests/README.md
  docker/tests/Templates/centos7/Dockerfile
  docker/tests/Templates/fxdependent-dotnetsdk-latest/Dockerfile
  docker/tests/Templates/fxdependent-fedora28/Dockerfile
  docker/tests/Templates/fxdependent-ubuntu16.04/Dockerfile
  docker/tests/Templates/fxdependent-ubuntu18.04/Dockerfile
  docker/tests/containerTestCommon.psm1
Labels: CL-Test

#10304 Update language on our policy applying to security issues
  .github/SECURITY.md
Labels: CL-Docs

#10090 Add tests for WildcardPattern.Escape() and Unescape()
  test/xUnit/csharp/test_WildcardPattern.cs
Labels: CL-Test

#10305 Update 'Microsoft.PowerShell.CoreCLR.Eventing' to resolve conflict with 'System.Diagnostics.EventLog'
  assets/files.wxs
  build.psm1
  src/Microsoft.PowerShell.Commands.Diagnostics/Microsoft.PowerShell.Commands.Diagnostics.csproj
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventBookmark.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventKeyword.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventLevel.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventLogConfiguration.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventLogException.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventLogInformation.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventLogLink.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventLogPropertySelector.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventLogQuery.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventLogReader.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventLogRecord.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventLogSession.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventLogStatus.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventMetadata.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventOpcode.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventProperty.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventPropertyContext.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventRecord.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/EventTask.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/NativeWrapper.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/ProviderMetadata.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/ProviderMetadataCachedInformation.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/Winmeta.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1
Labels: CL-CodeCleanup

#10316 Expose PreRelease label in PSModuleInfo formatter
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
Labels: CL-General

#10027 Reduce allocations in MakePath() method
  src/System.Management.Automation/namespaces/NavigationProviderBase.cs
Labels: CL-Performance

#10323 Add dispose of _runspaceDebugCompleteEvent event object.
  src/System.Management.Automation/engine/debugger/debugger.cs
Labels: CL-Engine

#10329 Make module name matching for `get-module -FullyQualifiedName` ignore case
  src/System.Management.Automation/engine/Modules/GetModuleCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Core/Get-Module.Tests.ps1
Labels: CL-General

#9943 Fix `#requires -version` for pwsh 7 to include 6.1 and 6.2 in `PSCompatibleVersions`
  src/System.Management.Automation/engine/PSVersionInfo.cs
  test/powershell/Host/PSVersionTable.Tests.ps1
  test/powershell/Language/Scripting/Requires.Tests.ps1
Labels: CL-Engine, Committee-Reviewed

#10350 Make Get-DscResource work with class based resources
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
Labels: CL-Engine

#10050 pwsh -Login support
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx
  src/powershell/Program.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
Labels: CL-BreakingChange, CL-General

#10319 Deprecate internal HelpCategory.Workflow enumeration
  src/System.Management.Automation/help/AliasHelpInfo.cs
  src/System.Management.Automation/help/CommandHelpProvider.cs
  src/System.Management.Automation/help/HelpCommands.cs
  src/System.Management.Automation/help/HelpRequest.cs
  src/System.Management.Automation/help/HelpSystem.cs
  src/System.Management.Automation/help/ScriptCommandHelpProvider.cs
Labels: CL-CodeCleanup

#10352 Fix style issues in InternalCommands.cs
  src/System.Management.Automation/engine/InternalCommands.cs
Labels: CL-CodeCleanup

#10321 Deprecate workflow debugging code
  src/System.Management.Automation/engine/debugger/debugger.cs
  test/powershell/SDK/PSDebugging.Tests.ps1
Labels: CL-CodeCleanup

#10366 Update `Microsoft.Management.Infrastructure` version to `2.0.0-preview.2`
  src/System.Management.Automation/System.Management.Automation.csproj
Labels: CL-BuildPackaging

#10328 Mark -parallel as reserved for foreach and switch, and -throttlelimit as reserved for foreach
  src/System.Management.Automation/engine/parser/SemanticChecks.cs
  src/System.Management.Automation/resources/ParserStrings.resx
  test/powershell/Language/Scripting/ForeachParallel.Tests.ps1
  test/powershell/Language/Scripting/SwitchParallel.Tests.ps1
Labels: CL-CodeCleanup

#10339 Fix minor breakpoint rehydration bug
  src/System.Management.Automation/engine/debugger/Breakpoint.cs
  src/System.Management.Automation/engine/serialization.cs
  test/powershell/Language/Scripting/PSSerializer.Tests.ps1
Labels: CL-General

#10336 Additional Telemetry - Implementation of RFC0036
  build.psm1
  src/Microsoft.PowerShell.ConsoleHost/Microsoft.PowerShell.ConsoleHost.csproj
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/Telemetry.cs
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
  src/System.Management.Automation/System.Management.Automation.csproj
  src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/GetCommandCommand.cs
  src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
  src/System.Management.Automation/engine/pipeline.cs
  src/System.Management.Automation/engine/remoting/client/RemoteRunspacePoolInternal.cs
  src/System.Management.Automation/utils/Telemetry.cs
  test/common/markdown/markdown-link.tests.ps1
  test/powershell/Host/Startup.Tests.ps1
  test/powershell/engine/Basic/Telemetry.Tests.ps1
Labels: CL-Engine

#10208 Formatting: handle XTPUSHSGR/XTPOPSGR sequences
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
Labels: CL-General

#9828 .CPL should be added to PATHEXT
  src/System.Management.Automation/engine/AutomationEngine.cs
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
Labels: CL-Engine, Committee-Reviewed

#10354 Add missing experimental feature check for ForEach-Object -Parallel tests
  test/powershell/Modules/Microsoft.PowerShell.Utility/Foreach-Object-Parallel.Tests.ps1
Labels: CL-Test

#10397 Add some regular contributors to allow access to retry CI
  .poshchan/settings.json
Labels: CL-NotInBuild

#9609 Block type update in Add-Type cmdlet
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Add-Type.Tests.ps1
Labels: CL-General

#10356 Increase built-with-PowerShell module versions to 7.0.0.0
  src/Modules/Shared/Microsoft.PowerShell.Host/Microsoft.PowerShell.Host.psd1
  src/Modules/Unix/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.psd1
  src/Modules/Unix/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.psd1
  src/Modules/Unix/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/Modules/Windows/CimCmdlets/CimCmdlets.psd1
  src/Modules/Windows/Microsoft.PowerShell.Diagnostics/Microsoft.PowerShell.Diagnostics.psd1
  src/Modules/Windows/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.psd1
  src/Modules/Windows/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.psd1
  src/Modules/Windows/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/Modules/Windows/Microsoft.WSMan.Management/Microsoft.WSMan.Management.psd1
  src/Modules/Windows/PSDiagnostics/PSDiagnostics.psd1
  test/powershell/Modules/Microsoft.PowerShell.Core/Get-Module.Tests.ps1
Labels: CL-General

#10425 Rename default ParameterSetName back to `Delimiter` for `ConvertTo-Csv` & `ConvertFrom-Csv`
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
Labels: CL-CodeCleanup

#10385 Skip auto-loading PSReadLine on Windows if the NVDA screen reader is active
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx
  test/powershell/Host/ScreenReader.Tests.ps1
Labels: CL-General

#8205 Break action preference
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs
  src/System.Management.Automation/engine/CommandBase.cs
  src/System.Management.Automation/engine/ExecutionContext.cs
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/hostifaces/InternalHostUserInterface.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/parser/Position.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  src/System.Management.Automation/utils/RuntimeException.cs
  test/powershell/Language/Scripting/ActionPreference.Tests.ps1
  test/powershell/Language/Scripting/Debugging/Debugging.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Wait-Debugger.Tests.ps1
  test/powershell/engine/Api/TaskBasedAsyncPowerShellAPI.Tests.ps1
  test/tools/Modules/HelpersDebugger/HelpersDebugger.psm1
Labels: CL-Engine, Committee-Reviewed

#10428 Alpine validation changes
  build.psm1
  test/powershell/Host/Startup.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Date.Tests.ps1
  test/powershell/Modules/PSDesiredStateConfiguration/MOF-Compilation.Tests.ps1
  test/powershell/engine/Remoting/PSSession.Tests.ps1
  test/powershell/engine/Remoting/RemoteSession.Basic.Tests.ps1
  test/tools/Modules/HelpersCommon/HelpersCommon.psd1
  test/tools/Modules/HelpersCommon/HelpersCommon.psm1
Labels: CL-Test

#10416 Cleanup AutomationEngine and remove extra SetSessionStateDrive method call
  src/System.Management.Automation/engine/AutomationEngine.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
Labels: CL-CodeCleanup

#10405 Minor fix for recursion into OneDrive - Change FindFirstFileEx() to use SafeFindHandle type
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-General

#10465 Fix a typo in README.md
  README.md
Labels: CL-Docs

#10454 Make `ForEach-Object` faster for its commonly used scenarios
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  test/powershell/Modules/Microsoft.PowerShell.Core/ForEach-Object.Tests.ps1
Labels: CL-Performance

#10461 Fix global tool issues around exit code, command line parameters and path with spaces
  src/Microsoft.PowerShell.GlobalTool.Shim/GlobalToolShim.cs
Labels: CL-General
