Repository PowerShell/PowerShell, pull requests merged in 2020-05, with the labels that each got.

#12526 Update @PoshChan config to include SSH
  .poshchan/settings.json
Labels: CL-Tools

#12581 Update the build to sign any unsigned files as 3rd party Dlls
  tools/packaging/packaging.psd1
  tools/packaging/packaging.psm1
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
  tools/releaseBuild/generatePackgeSigning.ps1
Labels: CL-BuildPackaging, Compliance

#12610 Remove unused code
  test/docker/networktest/New-DockerTestBuild.ps1
Labels: CL-CodeCleanup

#12301 Add CmdletInfo to Command Clone()
  src/System.Management.Automation/engine/hostifaces/Command.cs
  test/powershell/engine/Api/PSCommand.Tests.ps1
Labels: CL-General

#12630 Fixing incorrect index in format string in ParameterBinderBase
  src/System.Management.Automation/engine/ParameterBinderBase.cs
Labels: CL-General

#12636 Make CIM tab completion test case insensitive
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-Test

#11634 Fix String Parameter Binding for Biginteger numeric literals
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs
  test/powershell/Language/Parser/ParameterBinding.Tests.ps1
Labels: CL-BreakingChange, CL-Engine, Committee-Reviewed

#12576 Replace Unicode nbsp with space in source
  test/powershell/Language/Scripting/Debugging/DebuggerScriptTests.Tests.ps1
  test/tools/Modules/PSSysLog/PSSysLog.psm1
  test/tools/OpenCover/OpenCover.psm1
Labels: CL-CodeCleanup

#12651 Prevent NRE in Unix computer cmdlets with test hooks active
  src/Microsoft.PowerShell.Commands.Management/commands/management/ComputerUnix.cs
Labels: CL-General

#12656 Remove markdown unused definitions
  README.md
  docs/community/governance.md
  docs/learning-powershell/README.md
Labels: CL-Docs

#12669 Merge 7.0.1 change log
  CHANGELOG/7.0.md
Labels: CL-Docs

#12653 Update docs.microsoft.com links
  .github/ISSUE_TEMPLATE/Bug_Report.md
  .github/SUPPORT.md
  ADOPTERS.md
  CHANGELOG/6.0.md
  README.md
  demos/DSC/readme.md
  docs/FAQ.md
  docs/building/linux.md
  docs/cmdlet-example/command-line-simple-example.md
  docs/learning-powershell/README.md
  docs/learning-powershell/debugging-from-commandline.md
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Get-Error.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/assets/localized.ps1
  test/tools/Modules/HelpersCommon/HelpersCommon.psm1
  test/tools/Modules/HttpListener/HttpListener.psm1
Labels: AutoMerge, CL-Docs

#12683 Remove duplicate tests from Measure-Object.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Measure-Object.Tests.ps1
Labels: CL-Test

#12687 Disable uploading Symbols package
  tools/releaseBuild/azureDevOps/templates/upload.yml
Labels: CL-BuildPackaging

#12667 Ensure null-coalescing LHS is evaluated only once
  src/System.Management.Automation/engine/parser/Compiler.cs
  test/powershell/Language/Operators/NullConditional.Tests.ps1
Labels: CL-Engine

#12666 Formatting: remove duplicate semicolons
  src/Microsoft.PowerShell.Commands.Diagnostics/GetEventCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/UnblockFile.cs
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatViewManager.cs
  src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs
  src/System.Management.Automation/engine/ComInterop/ComInvokeBinder.cs
  src/System.Management.Automation/engine/remoting/commands/DebugJob.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
  src/System.Management.Automation/help/UpdatableHelpInfo.cs
Labels: CL-CodeCleanup

#12628 Update required Visual Studio version in build docs
  docs/building/windows-core.md
Labels: AutoMerge, CL-Docs

#12665 Added missing changelog for v7.1.0-preview.2
  .spelling
  CHANGELOG/preview.md
Labels: CL-Docs

#12659 NRE in CommandSearcher.GetNextCmdlet
  src/System.Management.Automation/engine/CommandSearcher.cs
Labels: AutoMerge, CL-General

#12711 Fix comments in Mshexpression.cs
  src/System.Management.Automation/FormatAndOutput/common/Utilities/Mshexpression.cs
Labels: AutoMerge, CL-CodeCleanup

#12713 Add link to Github compare in changelog
  CHANGELOG/preview.md
Labels: AutoMerge, CL-Docs

#12707 Update README.md removing experimental status of Arm builds
  README.md
Labels: CL-Docs

#12717 Update README and metadata files for next release
  DotnetRuntimeMetadata.json
  README.md
  tools/metadata.json
Labels: CL-Docs

#12729 Update `LICENSE.txt` so that it's recognized as MIT
  LICENSE.txt
Labels: CL-Docs

#12658 IDictionary -> IDictionary<string, FunctionInfo> for FunctionTable
  src/System.Management.Automation/engine/CommandSearcher.cs
  src/System.Management.Automation/engine/GetCommandCommand.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/SessionStateFunctionAPIs.cs
  src/System.Management.Automation/namespaces/FunctionProvider.cs
Labels: AutoMerge, CL-CodeCleanup

#12721 Remove `assets\license.rtf`
  tools/packaging/packaging.psm1
Labels: AutoMerge, CL-BuildPackaging

#12722 Remove phrase 'All rights reserved' from Microsoft copyright statements
  PowerShell.Common.props
  assets/pwsh.1.ronn
  src/System.Management.Automation/cimSupport/cmdletization/xml/cmdlets-over-objects.xsd
  src/System.Management.Automation/engine/Modules/ImportProvider.Tests.ps1
  test/Test.Common.props
  test/powershell/engine/Api/PSCommand.Tests.ps1
  test/tools/Modules/Microsoft.PowerShell.RemotingTools/Microsoft.PowerShell.RemotingTools.psd1
  tools/packaging/packaging.strings.psd1
Labels: AutoMerge, CL-CodeCleanup

#12725 Redundancy: Remove 'partial' modifier from type with a single part
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/HttpKnownHeaderNames.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebResponseHelper.CoreClr.cs
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/System.Management.Automation/engine/cmdlet.cs
  src/System.Management.Automation/engine/interpreter/DynamicSplatInstruction.cs
  src/System.Management.Automation/engine/interpreter/Instruction.cs
  src/System.Management.Automation/engine/interpreter/Utilities.cs
  src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs
  src/System.Management.Automation/utils/ExtensionMethods.cs
Labels: AutoMerge, CL-CodeCleanup

#12730 Restrict loading of `amsi.dll` from system32 folder
  src/System.Management.Automation/security/SecuritySupport.cs
  src/System.Management.Automation/security/wldpNativeMethods.cs
Labels: AutoMerge, CL-Engine

#11701 Make `-OutFile` param in web cmdlets to work like -LiteralPath
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: CL-BreakingChange, CL-General, Committee-Reviewed

#12733 Nullable annotations for CommandSearcher
  src/System.Management.Automation/engine/CommandPathSearch.cs
  src/System.Management.Automation/engine/CommandSearcher.cs
  src/System.Management.Automation/engine/MshSnapinQualifiedName.cs
Labels: AutoMerge, CL-CodeCleanup

#12738 Delete license.rtf
  assets/license.rtf
Labels: AutoMerge, CL-CodeCleanup

#12740 Update to dotnet SDK 5.0.0-preview.5.20268.9
  assets/files.wxs
  global.json
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
  tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  tools/packaging/projects/reference/System.Management.Automation/System.Management.Automation.csproj
Labels: AutoMerge, CL-BuildPackaging

#12723 Maintainability: Rethrow to preserve stack details
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimSessionOptionCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/New-Object.cs
  src/Microsoft.WSMan.Management/WsManHelper.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/remoting/server/serverremotesession.cs
Labels: CL-CodeCleanup

#12617 Change CimCmdlets to use AliasAttribute
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimCmdletModuleInitialize.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimAssociatedInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimClassCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/InvokeCimMethodCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimSessionOptionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RegisterCimIndicationCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RemoveCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RemoveCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/SetCimInstanceCommand.cs
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
Labels: CL-General

#12758 Fixing "Double "period" (..) in message for System.InvalidOperationException"
  src/Microsoft.PowerShell.Commands.Management/resources/ProcessResources.resx
Labels: AutoMerge, CL-CodeCleanup

#12700 Wrap tests in pester blocks
  test/packaging/windows/msi.tests.ps1
  test/powershell/Language/Classes/scripting.Classes.NestedModules.tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertFrom-Csv.Tests.ps1
  test/powershell/engine/Basic/PropertyAccessor.Tests.ps1
  test/powershell/engine/COM/COM.Basic.Tests.ps1
  test/powershell/engine/ETS/CimAdapter.Tests.ps1
Labels: AutoMerge, CL-Test

#12786 Replace link to Slack with link to PowerShell Virtual User Group
  README.md
Labels: AutoMerge, CL-Docs

#12520 Clarify defaultRefAssemblies list capacity in AddType.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs
Labels: AutoMerge, CL-CodeCleanup

#12798 Adding more ETW logs to wsman plugin
  src/System.Management.Automation/engine/remoting/fanin/WSManPlugin.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManTransportManager.cs
Labels: CL-Engine

#11943 Make module formatting not generate error with strict mode
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
Labels: CL-Engine

#12792 Fix MSI upgrade and shortcut issues
  assets/Product.wxs
  assets/files.wxs
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging

#12657 Fix markdown ordered lists
  docs/learning-powershell/debugging-from-commandline.md
  docs/learning-powershell/powershell-beginners-guide.md
Labels: AutoMerge, CL-Docs

#10908 Adds Mask Input Parameter to `Read-Host`
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ReadConsoleCmdlet.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/System.Management.Automation/engine/hostifaces/InternalHostUserInterface.cs
  src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs
  src/System.Management.Automation/engine/remoting/server/ServerRemoteHostUserInterface.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Read-Host.Tests.ps1
  test/tools/Modules/HelpersHostCS/HelpersHostCS.psm1
Labels: CL-General, Committee-Reviewed, Review - Needed

#12163 Remove extra line before formatting group
  src/System.Management.Automation/FormatAndOutput/common/BaseFormattingCommand.cs
  src/System.Management.Automation/FormatAndOutput/common/BaseOutputtingCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Custom.Tests.ps1
Labels: CL-Engine

#11146 Allow use of build module on unknown Linux distros
  build.psm1
Labels: CL-BuildPackaging

#12826 Use `t_` naming convention for ThreadStatic members
  src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs
  src/System.Management.Automation/engine/parser/TypeResolver.cs
  src/System.Management.Automation/utils/tracing/PSSysLogProvider.cs
  src/System.Management.Automation/utils/tracing/SysLogProvider.cs
Labels: AutoMerge, CL-CodeCleanup

#12830 Update the CI builds
  .vsts-ci/linux.yml
  .vsts-ci/mac.yml
  .vsts-ci/windows-daily.yml
Labels: AutoMerge, CL-BuildPackaging

#12288 Add CommandLine property to Process
  src/System.Management.Automation/engine/TypeTable_Types_Ps1Xml.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-Process.Tests.ps1
Labels: CL-General

#12744 Minor typo corrections in Distribution Request Issue Templates
  .github/ISSUE_TEMPLATE/Distribution_Request.md
Labels: AutoMerge, CL-Docs, Review - Needed

#12820 Add missing assessibility modifiers
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimAssociatedInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimClassCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/InvokeCimMethodCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimSessionOptionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RegisterCimIndicationCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RemoveCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RemoveCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/SetCimInstanceCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/PdhHelper.cs
  src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/PropVariant.cs
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/Microsoft.WSMan.Management/CredSSP.cs
  src/Microsoft.WSMan.Management/Interop.cs
  src/Microsoft.WSMan.Management/InvokeWSManAction.cs
  src/Microsoft.WSMan.Management/WSManInstance.cs
  src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/engine/MshMemberInfo.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/ProcessCodeMethods.cs
  src/System.Management.Automation/engine/parser/AstVisitor.cs
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
  src/System.Management.Automation/logging/LogProvider.cs
Labels: AutoMerge, CL-CodeCleanup

#12829 cleanup: Use coalesce expression
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimAssociatedInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimClassCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/InvokeCimMethodCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RemoveCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/SetCimInstanceCommand.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterProviders/FilterRuleTemplateSelector.cs
  src/Microsoft.Management.UI.Internal/commandHelpers/ShowCommandHelper.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs
  src/Microsoft.WSMan.Management/CredSSP.cs
  src/Microsoft.WSMan.Management/WSManConnections.cs
  src/Microsoft.WSMan.Management/WsManHelper.cs
  src/System.Management.Automation/engine/PSConfiguration.cs
  src/System.Management.Automation/engine/SessionStateDriveAPIs.cs
  src/System.Management.Automation/engine/lang/parserutils.cs
  src/System.Management.Automation/help/HelpProvider.cs
Labels: CL-CodeCleanup

#11777 Add readonly modifier to internal static members
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionOperations.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/Utils.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
  src/Microsoft.WSMan.Management/WsManHelper.cs
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
  src/System.Management.Automation/FormatAndOutput/common/BaseOutputtingCommand.cs
  src/System.Management.Automation/FormatAndOutput/common/OutputManager.cs
  src/System.Management.Automation/FormatAndOutput/common/Utilities/MshParameter.cs
  src/System.Management.Automation/FormatAndOutput/common/Utilities/MshParameterAssociation.cs
  src/System.Management.Automation/FormatAndOutput/out-console/ConsoleLineOutput.cs
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/engine/ExecutionContext.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/engine/Modules/AnalysisCache.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs
  src/System.Management.Automation/engine/Modules/PSModuleInfo.cs
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  src/System.Management.Automation/engine/MshObject.cs
  src/System.Management.Automation/engine/MshObjectTypeDescriptor.cs
  src/System.Management.Automation/engine/ParameterBinderBase.cs
  src/System.Management.Automation/engine/PseudoParameters.cs
  src/System.Management.Automation/engine/SpecialVariables.cs
  src/System.Management.Automation/engine/TypeTable.cs
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/interpreter/Utilities.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/parser/TypeResolver.cs
  src/System.Management.Automation/engine/parser/ast.cs
  src/System.Management.Automation/engine/remoting/commands/NewPSSessionConfigurationOptionCommand.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
  src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPlugin.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPluginFacade.cs
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
  src/System.Management.Automation/engine/runtime/Operations/NumericOps.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/help/CabinetAPI.cs
  src/System.Management.Automation/help/DefaultCommandHelpObjectBuilder.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/namespaces/ProviderBase.cs
  src/System.Management.Automation/security/SecureStringHelper.cs
  src/System.Management.Automation/security/SecuritySupport.cs
  src/System.Management.Automation/utils/EncodingUtils.cs
  src/System.Management.Automation/utils/PlatformInvokes.cs
Labels: AutoMerge, CL-CodeCleanup
