Repository PowerShell/PowerShell, pull requests merged in 2020-07, with the labels that each got.

#13070 Fix Path for the Preview MSI
  assets/Product.wxs
  test/packaging/windows/msi.tests.ps1
Labels: CL-BuildPackaging

#13085 Fix error message from new symbolic link missing target
  src/System.Management.Automation/engine/SessionStateContainer.cs
  src/System.Management.Automation/resources/SessionStateStrings.resx
  test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1
Labels: CL-General

#13065 Use null check with pattern-matching instead of object.ReferenceEquals
  src/ResGen/Program.cs
  src/System.Management.Automation/engine/Modules/PSModuleInfo.cs
  src/System.Management.Automation/engine/MshMemberInfo.cs
  src/System.Management.Automation/engine/PSVersionInfo.cs
  src/System.Management.Automation/utils/tracing/SysLogProvider.cs
Labels: CL-CodeCleanup

#13100 Add Fluent Design Icon asset for PowerShell 7 usage
  assets/ps_fluent_design_384.svg
Labels: CL-General

#13128 Update `.devcontainer` to use nightly docker SDK images
  DotnetRuntimeMetadata.json
  tools/UpdateDotnetRuntime.ps1
Labels: CL-Tools

#12580 Add support for some .Net intrinsic type converters
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  test/powershell/engine/Api/LanguagePrimitive.Tests.ps1
Labels: CL-Engine, Review - Needed

#13140 Add new chibi version of the avatar
  assets/Chibi_Avatar.png
Labels: CL-BuildPackaging

#13144 Disable R2R for debug build
  PowerShell.Common.props
Labels: CL-BuildPackaging

#13139 Refactor MSI code to make it easier to add a WiX EXE installer
  assets/Product.wxs
  assets/files.wxs
  tools/ci.psm1
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging

#13150 Make other switches mandatory as per issue #12991
  src/Microsoft.PowerShell.Commands.Management/commands/management/ParsePathCommand.cs
Labels: CL-General

#13120 Handle WSL filesystem path when analyze security zone of a file
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/utils/ClrFacade.cs
Labels: CL-General

#13173 Fix Azure File Copy break in AzDevOps
  tools/releaseBuild/azureDevOps/WindowsBuild.yml
  tools/releaseBuild/azureDevOps/templates/compliance.yml
  tools/releaseBuild/azureDevOps/templates/json.yml
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/nuget.yml
  tools/releaseBuild/azureDevOps/templates/upload.yml
  tools/releaseBuild/azureDevOps/templates/windows-package-signing.yml
Labels: CL-BuildPackaging

#13043 Add support for installing ARM64 MSIX package.
  tools/install-powershell.ps1
Labels: CL-BuildPackaging

#13194 Update change logs for `6.2.x` and `7.0.x`
  CHANGELOG/6.2.md
  CHANGELOG/7.0.md
Labels: CL-Docs

#13137 Avoid usage of do statement to create an infinite loop
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ShowCommand/ShowCommand.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfacePromptForChoice.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/PendingProgress.cs
  src/System.Management.Automation/engine/CommandPathSearch.cs
  src/System.Management.Automation/engine/GetCommandCommand.cs
  src/System.Management.Automation/engine/MshCmdlet.cs
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  src/System.Management.Automation/engine/hostifaces/InternalHostUserInterface.cs
  src/System.Management.Automation/engine/hostifaces/PSDataCollection.cs
  src/System.Management.Automation/engine/hostifaces/RunspacePoolInternal.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
  src/System.Management.Automation/engine/remoting/fanin/BaseTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/PriorityCollection.cs
  src/System.Management.Automation/engine/remoting/server/OutOfProcServerMediator.cs
  src/System.Management.Automation/namespaces/FileSystemContentStream.cs
  src/System.Management.Automation/namespaces/RegistryProvider.cs
  src/System.Management.Automation/utils/StringUtil.cs
Labels: CL-CodeCleanup

#13205 Fix conflicting shorthand switch `-in` for pwsh
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
Labels: CL-General

#13123 Remove rcedit dependency, move daily ico dependency to props file
  PowerShell.Common.props
  tools/install-powershell.ps1
Labels: Area-Build, CL-BuildPackaging, Review - Needed

#10492 Add -Runspace parameter to all *-PSBreakpoint cmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Disable-PSBreakpoint.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Enable-PSBreakpoint.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Get-PSBreakpoint.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/PSBreakpointAccessorCommandBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/PSBreakpointCommandBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/PSBreakpointCreationBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/PSBreakpointUpdaterCommandBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Remove-PSBreakpoint.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/RunspaceAttribute.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Set-PSBreakpoint.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/Debugger.resx
  src/Modules/Unix/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/Modules/Windows/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Disable-PSBreakpoint.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Enable-PSBreakpoint.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Remove-PSBreakpoint.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/RunspaceBreakpointManagement.Tests.ps1
  test/tools/TestMetadata.json
Labels: CL-Experimental, Committee-Reviewed

#13090 Enable C# 9.0 features
  PowerShell.Common.props
Labels: CL-BuildPackaging

#13249 Fix SA1026CodeMustNotContainSpaceAfterNewKeywordInImplicitlyTypedArrayAllocation
  src/System.Management.Automation/utils/CryptoUtils.cs
  test/tools/WebListener/DeflateFilter.cs
  test/tools/WebListener/GzipFilter.cs
Labels: CL-CodeCleanup

#13259 Remove `ComEnumerator` as COM objects using IEnumerator is now supported in .NET 5
  src/System.Management.Automation/engine/COM/ComUtil.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
Labels: CL-General

#13270 Fix Test-XUnitTestResults function
  build.psm1
Labels: CL-Tools

#13269 Grammar correction of Readme.md and other docs
  README.md
  docs/building/internals.md
  docs/building/linux.md
  docs/building/windows-core.md
  docs/cmdlet-example/command-line-simple-example.md
Labels: CL-Docs

#13298 Fixing typo in `Out-File.cs` and `Out-Printer.cs`
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-file/Out-File.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-printer/Out-Printer.cs
Labels: CL-CodeCleanup

#13306 Use `file_header_template` in .editorconfig for copyright header and update files
  .editorconfig
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/RunspaceAttribute.cs
  test/xUnit/csharp/test_CryptoUtils.cs
Labels: CL-CodeCleanup

#13230 Update the dependabot config to v2
  .dependabot/config.yml
  .github/dependabot.yml
Labels: Review - Needed

#13321 Add action to label size of PR
  .github/workflows/size-label.yml
Labels: size/S

#13316 Remove unreachable code in CustomShellCommands.cs
  src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs
Labels: Review - Needed

#13262 Fix conflicting shorthand switch `-s` (sta) for pwsh
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
Labels: CL-General, Review - Needed

#13258 Add `DefaultVisit` method to the visitor interface and class
  src/System.Management.Automation/engine/parser/AstVisitor.cs
  src/System.Management.Automation/engine/parser/PreOrderVisitor.cs
  test/xUnit/csharp/test_AstDefaultVisit.cs
Labels: CL-General, Documentation Needed

#13325 Revert "Add action to label size of PR"
  .github/workflows/size-label.yml
Labels: CL-NotInBuild

#13323 Use `is not` syntax and remove unnecessary parentheses
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimAsyncOperation.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/clientSideQuery.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/TraceExpressionCommand.cs
  src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/PropertyKey.cs
  src/Microsoft.PowerShell.ScheduledJob/ScheduledJobDefinition.cs
  src/Microsoft.PowerShell.Security/security/AclCommands.cs
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
  src/System.Management.Automation/FormatAndOutput/out-console/OutConsole.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CompiledCommandParameter.cs
  src/System.Management.Automation/engine/EventManager.cs
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/engine/Modules/NewModuleManifestCommand.cs
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  src/System.Management.Automation/engine/MshMemberInfo.cs
  src/System.Management.Automation/engine/TypeTable.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/hostifaces/ConnectionBase.cs
  src/System.Management.Automation/engine/hostifaces/ConnectionFactory.cs
  src/System.Management.Automation/engine/hostifaces/History.cs
  src/System.Management.Automation/engine/hostifaces/PSDataCollection.cs
  src/System.Management.Automation/engine/hostifaces/RunspacePool.cs
  src/System.Management.Automation/engine/interpreter/CallInstruction.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/parser/SemanticChecks.cs
  src/System.Management.Automation/engine/parser/SymbolResolver.cs
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
  src/System.Management.Automation/engine/pipeline.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
  src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/help/CommandHelpProvider.cs
  src/System.Management.Automation/help/HelpSystem.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: Review - Maintainer
