Repository PowerShell/PowerShell, pull requests merged in 2020-12, with the labels that each got.

#14288 Remove unnecessary usings part 9
  src/Microsoft.WSMan.Runtime/WSManSessionOption.cs
Labels: CL-CodeCleanup

#14078 Enable IDE0075: SimplifyConditionalExpression
  .globalconfig
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Get-Error.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressPane.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/EventProvider.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/NativeWrapper.cs
  src/Microsoft.PowerShell.MarkdownRender/EmphasisInlineRenderer.cs
  src/System.Management.Automation/FormatAndOutput/common/FormattingObjectsDeserializer.cs
  src/System.Management.Automation/engine/CommandParameter.cs
  src/System.Management.Automation/engine/ExecutionContext.cs
  src/System.Management.Automation/engine/ExternalScriptInfo.cs
  src/System.Management.Automation/engine/GetCommandCommand.cs
  src/System.Management.Automation/engine/ScriptCommandProcessor.cs
  src/System.Management.Automation/engine/hostifaces/InternalHostUserInterface.cs
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
  src/System.Management.Automation/engine/parser/ast.cs
  src/System.Management.Automation/engine/remoting/client/ClientMethodExecutor.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
  src/System.Management.Automation/engine/remoting/client/RemoteRunspacePoolInternal.cs
  src/System.Management.Automation/engine/remoting/client/RemotingProtocol2.cs
  src/System.Management.Automation/engine/remoting/client/RunspaceRef.cs
  src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs
  src/System.Management.Automation/engine/remoting/commands/newrunspacecommand.cs
  src/System.Management.Automation/engine/remoting/common/fragmentor.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManTransportManager.cs
  src/System.Management.Automation/engine/remoting/server/ServerRemoteHost.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-CodeCleanup

#14301 Fix IDE0090: Simplify new expression part 5
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/EventProvider.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/EventProviderTraceListener.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/NativeWrapper.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/UnsafeNativeMethods.cs
Labels: CL-CodeCleanup

#14298 Use StringComparison.Ordinal insted of StringComparison.CurrentCulture at startup time
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
Labels: CL-Performance

#14176 Enable nullable: System.Management.Automation.Provider.IPropertyCmdletProvider
  src/System.Management.Automation/namespaces/IPropertiesProvider.cs
Labels: Review - Needed

#14170 Enable nullable: System.Management.Automation.Host.IHostSupportsInteractiveSession
  src/System.Management.Automation/engine/hostifaces/MshHost.cs
Labels: CL-CodeCleanup

#13634 Avoid an exception if file system does not support reparse points
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: BackPort-7.1.x-Consider, CL-General

#14303 Use OrdinalIgnoreCase in CommandLineParser
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
Labels: CL-Performance

#14314 Update dead link in Code Guidelines
  docs/dev-process/coding-guidelines.md
Labels: CL-Docs

#14262 Fix RCS1188: Remove redundant auto-property initialization part 2
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Measure-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/New-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/NewTimeSpanCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/OrderObjectBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Select-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Sort-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Write.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WriteConsoleCmdlet.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WriteProgressCmdlet.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/XmlCommands.cs
Labels: CL-CodeCleanup

#14283 Speedup InitialSessionState..cctor()
  src/System.Management.Automation/security/wldpNativeMethods.cs
Labels: CL-Performance

#14330 Replace GetFiles in UpdatableHelpCommandBase
  src/System.Management.Automation/help/UpdatableHelpCommandBase.cs
Labels: CL-CodeCleanup

#14344 Fix nuget packaging to scrub 'NullableAttribute'
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging

#14324 Move macOS and nuget to esrp signing
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/mac-file-signing.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/nuget.yml
  tools/releaseBuild/azureDevOps/templates/windows-package-signing.yml
Labels: BackPort-7.0.x-Consider, BackPort-7.1.x-Consider

#13941 The -Stream parameter now works with directories
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Add-Content.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Clear-Content.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-Content.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-Item.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Remove-Item.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Set-Content.Tests.ps1
Labels: CL-General

#14148 Refactor multiply operation for better performance in 2 Commands.Utility functions
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Measure-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ObjectCommandComparer.cs
Labels: CL-Performance

#14140 Restrict New-Object in NoLanguage mode under lock down #14139
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/New-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/NewObjectStrings.resx
Labels: CL-General

#14338 Fix IDE0090: Simplify new expression part 6
  src/System.Management.Automation/CoreCLR/CorePsAssemblyLoadContext.cs
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/cimSupport/cmdletization/EnumWriter.cs
  src/System.Management.Automation/cimSupport/cmdletization/MethodInvocationInfo.cs
  src/System.Management.Automation/cimSupport/cmdletization/ScriptWriter.cs
  src/System.Management.Automation/cimSupport/cmdletization/cim/WildcardPatternToCimQueryParser.cs
  src/System.Management.Automation/cimSupport/other/ciminstancetypeadapter.cs
Labels: CL-CodeCleanup

#13897 Enable CA1822: Mark private members as static
  .globalconfig
  src/Microsoft.PowerShell.MarkdownRender/ListBlockRenderer.cs
  src/TypeCatalogGen/TypeCatalogGen.cs
  test/tools/WebListener/Controllers/LinkController.cs
  test/tools/WebListener/Controllers/ResponseController.cs
  test/tools/WebListener/Controllers/ResumeController.cs
  test/xUnit/csharp/test_FileSystemProvider.cs
  test/xUnit/csharp/test_PSConfiguration.cs
Labels: CL-CodeCleanup

#13672 Add `-SkipLimitCheck` switch to `Import-PowerShellDataFile`
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImportPowerShellDataFile.cs
  src/Modules/Unix/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/Modules/Windows/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/System.Management.Automation/engine/parser/SafeValues.cs
  src/System.Management.Automation/engine/parser/ast.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/PowerShellData.tests.ps1
Labels: Waiting on Author

#14182 Enable nullable: System.Management.Automation.IArgumentCompleter
  src/System.Management.Automation/engine/CommandCompletion/ExtensibleCompletion.cs
Labels: Review - Needed

#13919 Mark applicable structs as readonly and use in-modifier
  src/Microsoft.PowerShell.Commands.Diagnostics/NewWinEventCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ContentCommandBase.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetContentCommand.cs
  src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/ComInterfaces.cs
  src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/PropertyKey.cs
  src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/TaskbarJumpList.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/EventDescriptor.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/EventProvider.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/UnsafeNativeMethods.cs
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
  src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs
  src/System.Management.Automation/engine/CommandInfo.cs
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/engine/MshCmdlet.cs
  src/System.Management.Automation/engine/interpreter/BranchLabel.cs
  src/System.Management.Automation/engine/interpreter/InstructionList.cs
  src/System.Management.Automation/engine/interpreter/LightCompiler.cs
  src/System.Management.Automation/engine/interpreter/LocalVariables.cs
  src/System.Management.Automation/engine/interpreter/Utilities.cs
  src/System.Management.Automation/engine/regex.cs
  src/System.Management.Automation/security/nativeMethods.cs
  src/System.Management.Automation/utils/PowerShellETWTracer.cs
  src/System.Management.Automation/utils/tracing/EtwActivity.cs
  src/System.Management.Automation/utils/tracing/EtwEventCorrelator.cs
  src/System.Management.Automation/utils/tracing/PSEtwLogProvider.cs
  src/System.Management.Automation/utils/tracing/TracingGen.cs
Labels: Review - Needed

#13910 Simplify getting Encoding in `TranscriptionOption.FlushContentToDisk`
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs
Labels: CL-CodeCleanup, Review - Needed

#14221 Optimize IEnumerable variant of replace operator
  src/System.Management.Automation/engine/lang/parserutils.cs
  test/powershell/Language/Operators/ReplaceOperator.Tests.ps1
Labels: CL-Performance, Documentation Needed

#14317 Replace GetFiles in TestModuleManifestCommand
  src/System.Management.Automation/engine/Modules/TestModuleManifestCommand.cs
Labels: CL-CodeCleanup

#14090 Use `Microsoft.PowerShell.MarkdownRender` package from `nuget.org`
  PowerShell.sln
  assets/files.wxs
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.MarkdownRender/CodeInlineRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/EmphasisInlineRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/FencedCodeBlockRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/HeaderBlockRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/LeafInlineRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/LineBreakRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/LinkInlineRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/ListBlockRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/ListItemBlockRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/MarkdownConverter.cs
  src/Microsoft.PowerShell.MarkdownRender/Microsoft.PowerShell.MarkdownRender.csproj
  src/Microsoft.PowerShell.MarkdownRender/ParagraphBlockRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/QuoteBlockRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/VT100EscapeSequences.cs
  src/Microsoft.PowerShell.MarkdownRender/VT100ObjectRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/VT100Renderer.cs
  tools/packaging/packaging.psm1
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
  tools/releaseBuild/signing.xml
Labels: CL-CodeCleanup

#14353 Make AppLocker Enforce mode take precedence over UMCI Audit mode
  src/System.Management.Automation/security/wldpNativeMethods.cs
Labels: BackPort-7.0.x-Consider, BackPort-7.1.x-Consider, WG-Security

#14367 Fix issue with unsigned build
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/mac-file-signing.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/nuget.yml
  tools/releaseBuild/azureDevOps/templates/windows-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
  tools/releaseBuild/setReleaseTag.ps1
Labels: BackPort-7.0.x-Consider, BackPort-7.1.x-Consider, CL-BuildPackaging

#14358 Remove redundant local assignment in AclCommands
  src/Microsoft.PowerShell.Security/security/AclCommands.cs
Labels: CL-CodeCleanup

#12766 Ensure -PipelineVariable is set for all output from script cmdlets
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1
Labels: Backport-7.2.x-Consider, CL-BreakingChange, Committee-Reviewed, Review - Needed

#12495 (#12430) Improve detection of mutable value types
  src/System.Management.Automation/engine/hostifaces/History.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
Labels: Backport-7.2.x-Consider, Review - Maintainer, Review - Needed

#14377 Fix syntax error in Windows packaging script
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
Labels: BackPort-7.0.x-Consider, BackPort-7.1.x-Consider

#14168 Enable nullable: System.Management.Automation.Tracing.IEtwEventCorrelator
  src/System.Management.Automation/utils/tracing/EtwEventCorrelator.cs
Labels: CL-CodeCleanup

#14169 Enable nullable: System.Management.Automation.IHasSessionStateEntryVisibility
  src/System.Management.Automation/engine/SessionStatePublic.cs
Labels: CL-CodeCleanup

#14173 Enable nullable: System.Management.Automation.Interpreter.IInstructionProvider
  src/System.Management.Automation/engine/interpreter/Instruction.cs
Labels: CL-CodeCleanup

#14174 Enable nullable: System.Management.Automation.IJobDebugger
  src/System.Management.Automation/engine/remoting/client/Job.cs
Labels: CL-CodeCleanup

#14175 Enable nullable: System.Management.Automation.IOutputProcessingState
  src/System.Management.Automation/engine/remoting/client/Job.cs
Labels: CL-CodeCleanup

#14183 Enable nullable: System.Management.Automation.ICommandRuntime2
  src/System.Management.Automation/engine/ICommandRuntime.cs
Labels: CL-CodeCleanup

#14180 Enable nullable: System.Management.Automation.Language.ISupportsAssignment
  src/System.Management.Automation/engine/parser/ast.cs
Labels: CL-CodeCleanup

#14186 Enable nullable: ...Automation.Remoting.Client.IWSManNativeApiFacade
  src/System.Management.Automation/engine/remoting/fanin/WSManNativeAPI.cs
Labels: CL-CodeCleanup

#14187 Enable nullable: System.Management.Automation.LanguagePrimitives.IConversionData
  src/System.Management.Automation/engine/LanguagePrimitives.cs
Labels: CL-CodeCleanup

#14192 Enable nullable: System.Management.Automation.Language.ICustomAstVisitor2
  src/System.Management.Automation/engine/parser/AstVisitor.cs
Labels: CL-CodeCleanup

#14179 Enable nullable: System.Management.Automation.Language.IScriptExtent
  src/System.Management.Automation/engine/parser/Position.cs
Labels: CL-CodeCleanup

#14167 Enable nullable: System.Management.Automation.Provider.IDynamicPropertyProvider
  src/System.Management.Automation/namespaces/IDynamicPropertyProvider.cs
Labels: CL-CodeCleanup

#14165 Enable nullable: System.Management.Automation.Interpreter.IBoxableInstruction
  src/System.Management.Automation/engine/interpreter/LocalAccess.cs
Labels: CL-CodeCleanup

#14178 Enable nullable: System.Management.Automation.IScriptCommandInfo
  src/System.Management.Automation/engine/CommandInfo.cs
Labels: CL-CodeCleanup

#14184 Enable nullable: System.Management.Automation.Provider.IContentCmdletProvider
  src/System.Management.Automation/namespaces/IContentProvider.cs
Labels: CL-CodeCleanup

#14332 Retrieve PowerShell version in PSVersionInfo using assembly informational version instead of FileVersionInfo
  src/System.Management.Automation/engine/PSVersionInfo.cs
  test/powershell/Host/Startup.Tests.ps1
Labels: CL-Performance

#14354 Upgrade StyleCopAnalyzers to v1.2.0-beta.312
  Analyzers.props
Labels: CL-Tools

#14424 Fix path signed RPMs are uploaded from in release build
  tools/releaseBuild/azureDevOps/templates/linux.yml
Labels: BackPort-7.0.x-Consider, BackPort-7.1.x-Consider

#14431 Update document link because of HTTP 301 redirect
  docs/learning-powershell/powershell-beginners-guide.md
Labels: CL-Docs

#14437 Fix Universal Dashboard to refer to PowerShell Universal to fix CI
  ADOPTERS.md
Labels: CL-Docs

#14398 Refactor complex if statement
  src/System.Management.Automation/engine/GetCommandCommand.cs
Labels: CL-CodeCleanup

#14447 Fix PSStyle blink codes
  src/System.Management.Automation/FormatAndOutput/common/PSStyle.cs
  test/powershell/engine/Formatting/PSStyle.Tests.ps1
Labels: CL-General

#14461 Add support to `$PSStyle` for strikethrough and hyperlinks
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  src/System.Management.Automation/FormatAndOutput/common/PSStyle.cs
  test/powershell/engine/Formatting/PSStyle.Tests.ps1
Labels: CL-General

#14443 Fix IDE0032: UseAutoProperty part 3
  src/Microsoft.PowerShell.Commands.Diagnostics/CounterSample.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/CounterSet.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/GetCounterCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/GetEventCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/NewWinEventCommand.cs
Labels: CL-CodeCleanup

#14368 Use string.Contains(char) overload
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/Microsoft.WSMan.Management/WsManHelper.cs
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/engine/InternalCommands.cs
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs
  src/System.Management.Automation/help/SaveHelpCommand.cs
Labels: CL-CodeCleanup

#14465 Use String.Split(char) instead of String.Split(String)
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
Labels: CL-CodeCleanup

#14442 Add summary element to documentation comment
  src/Microsoft.PowerShell.Commands.Diagnostics/GetCounterCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/GetEventCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/NewWinEventCommand.cs
Labels: CL-CodeCleanup

#14472 Enable SA1213: Event accessors should follow order
  .globalconfig
Labels: CL-CodeCleanup

#14471 Enable SA1216/SA1217: Using static directives
  .globalconfig
Labels: CL-CodeCleanup

#14470 Enable SA1314: Type parameter names should begin with T
  .globalconfig
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Measure-Object.cs
  src/System.Management.Automation/engine/MshMemberInfo.cs
  src/System.Management.Automation/engine/MshObject.cs
  src/System.Management.Automation/engine/hostifaces/PSDataCollection.cs
  src/System.Management.Automation/engine/interpreter/Utilities.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/EncodeAndDecode.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/utils/ObjectReader.cs
Labels: CL-CodeCleanup

#14476 Enable SA1003: Symbols should be spaced correctly
  .globalconfig
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimResultObserver.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/GetCounterCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleTextWriter.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/Serialization.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/FormatTable.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader.cs
  src/System.Management.Automation/engine/EventManager.cs
  src/System.Management.Automation/engine/ExtendedTypeSystemException.cs
  src/System.Management.Automation/engine/Modules/NewModuleManifestCommand.cs
  src/System.Management.Automation/engine/SessionStateDriveAPIs.cs
  src/System.Management.Automation/engine/interpreter/InstructionList.cs
  src/System.Management.Automation/engine/parser/Position.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
  src/System.Management.Automation/engine/remoting/client/RemotingErrorRecord.cs
  src/System.Management.Automation/engine/remoting/client/remotepipeline.cs
  src/System.Management.Automation/engine/remoting/common/RemoteSessionNamedPipe.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
  src/System.Management.Automation/engine/remoting/common/psstreamobject.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManTransportManager.cs
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
  src/System.Management.Automation/help/HelpCategoryInvalidException.cs
  src/System.Management.Automation/help/HelpNotFoundException.cs
  src/System.Management.Automation/namespaces/FileSystemContentStream.cs
  src/System.Management.Automation/namespaces/NavigationProviderBase.cs
  src/System.Management.Automation/namespaces/SessionStateProviderBase.cs
  src/System.Management.Automation/security/Authenticode.cs
  src/System.Management.Automation/security/SecuritySupport.cs
  src/System.Management.Automation/utils/CryptoUtils.cs
  src/System.Management.Automation/utils/HostInterfacesExceptions.cs
  src/System.Management.Automation/utils/MetadataExceptions.cs
  src/System.Management.Automation/utils/StructuredTraceSource.cs
  src/System.Management.Automation/utils/tracing/PSSysLogProvider.cs
  src/System.Management.Automation/utils/tracing/SysLogProvider.cs
  src/powershell/Program.cs
  test/tools/TestExe/TestExe.cs
  test/tools/WebListener/Controllers/ResponseController.cs
  test/tools/WebListener/Controllers/ResponseHeadersController.cs
Labels: CL-CodeCleanup

#14441 Enable SA1205: Partial elements should declare access
  .globalconfig
Labels: CL-CodeCleanup

#14454 Update ini component version in test package.json
  test/common/markdown/package.json
Labels: CL-Test, WG-Security
