Repository PowerShell/PowerShell, pull requests merged in 2020-02, with the labels that each got.

#11563 Set `StrictMode` version `3.0`
  assets/GroupPolicy/InstallPSCorePolicyDefinitions.ps1
  build.psm1
  src/PowerShell.Core.Instrumentation/RegisterManifest.ps1
  src/powershell-native/Install-PowerShellRemoting.ps1
  test/powershell/Host/Logging.Tests.ps1
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
  test/powershell/Language/Classes/Scripting.Classes.BasicParsing.Tests.ps1
  test/powershell/Language/Interop/DotNet/DotNetInterop.Tests.ps1
  test/powershell/engine/Help/HelpSystem.Tests.ps1
  test/tools/Modules/HelpersDebugger/HelpersDebugger.psm1
  test/tools/Modules/PSSysLog/PSSysLog.psm1
  tools/ci.psm1
  tools/install-powershell.ps1
Labels: CL-BuildPackaging

#10634 Ensure that types referenced by PowerShellStandard are present
  test/powershell/engine/Basic/StandardLibraryTypes.Tests.ps1
  test/powershell/engine/Basic/assets/standardtypes.csv
Labels: CL-Test

#11603 Update `PSPath` in `certificate_format_ps1.xml`
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/Certificate_format_ps1xml.cs
Labels: CL-General

#11741 Fix typo in FileSystem provider error message
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-CodeCleanup

#11737 Fix `help` function to check if `less` is available before using
  src/System.Management.Automation/engine/InitialSessionState.cs
Labels: CL-General

#11319 Refactor and implement `Restart-Computer` for `Un*x` and macOS
  src/Microsoft.PowerShell.Commands.Management/commands/management/ComputerUnix.cs
  src/Modules/Unix/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.psd1
  test/powershell/Modules/Microsoft.PowerShell.Management/Restart-Computer.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Stop-Computer.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Unimplemented-Cmdlet.Tests.ps1
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
Labels: CL-General

#11748 Enable pwsh to work on Windows systems where mpr.dll and STA is not available
  src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/TaskbarJumpList.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-General

#11766 Build tar packages only when building on Ubuntu
  tools/packaging/packaging.psm1
Labels: Area-Build, CL-BuildPackaging

#11765 Update to `CredScan v2`
  .vsts-ci/templates/credscan.yml
  test/powershell/Modules/Microsoft.PowerShell.LocalAccounts/Pester.Command.Cmdlets.LocalAccounts.LocalUser.Tests.ps1
  tools/credScan/suppress.json
Labels: CL-Tools

#11726 Add WinCompat deny list support using a setting in powershell.config.json
  build.psm1
  src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs
  src/System.Management.Automation/engine/PSConfiguration.cs
  src/System.Management.Automation/resources/Modules.resx
  test/powershell/Modules/Microsoft.PowerShell.Core/CompatiblePSEditions.Module.Tests.ps1
Labels: Area-Engine, CL-General

#11586 Fix `Invoke-Command` missing error on session termination.
  src/System.Management.Automation/engine/remoting/client/Job.cs
  test/powershell/engine/Job/Jobs.Tests.ps1
Labels: Area-Remoting, Breaking-Change, CL-BreakingChange, Committee-Reviewed, Issue-Bug

#11736 Update changelog generation script
  CHANGELOG/6.2.md
  tools/releaseTools.psm1
Labels: AutoMerge, CL-Tools

#11767 Use Dictionary<T, M>.TryAdd() where possible
  src/Microsoft.PowerShell.Commands.Diagnostics/GetCounterCommand.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfacePromptForChoice.cs
  src/System.Management.Automation/FormatAndOutput/common/Utilities/MshParameterAssociation.cs
  src/System.Management.Automation/engine/ComInterop/ComTypeDesc.cs
  src/System.Management.Automation/engine/hostifaces/InternalHostUserInterface.cs
  src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs
  src/System.Management.Automation/security/CatalogHelper.cs
Labels: CL-CodeCleanup

#11643 Update `CmsCommands` to use Store vs cert provider
  src/Modules/Unix/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.psd1
  src/System.Management.Automation/security/SecuritySupport.cs
  test/powershell/Modules/Microsoft.PowerShell.Security/CmsMessage2.Tests.ps1
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
Labels: CL-General

#11787 Fix `NativeDllHandler` to not throw when file is not found
  src/System.Management.Automation/CoreCLR/CorePsAssemblyLoadContext.cs
Labels: AutoMerge, CL-Engine

#11775 Specifiy csharp_preferred_modifier_order in EditorConfig
  .editorconfig
Labels: CL-Tools

#11365 Add information about how Amazon AWS uses PowerShell.
  ADOPTERS.md
Labels: CL-Docs, Waiting on Author

#11795 Fix how COM objects are enumerated
  src/System.Management.Automation/engine/COM/ComUtil.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  test/powershell/engine/COM/COM.Basic.Tests.ps1
Labels: CL-Engine

#11807 Handle cases where `CustomEvent` was not initially sent
  src/System.Management.Automation/utils/Telemetry.cs
  test/powershell/engine/Basic/Telemetry.Tests.ps1
Labels: CL-Engine

#11809 Auto-sync current directory in WinCompat remote session
  src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  test/powershell/Modules/Microsoft.PowerShell.Core/CompatiblePSEditions.Module.Tests.ps1
Labels: CL-General

#11832 Update the NuGet package generation to include 'cimcmdlet.dll' and most of the built-in modules
  test/hosting/test_HostingBasic.cs
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging

#11602 Add new tests for Get-ChildItem (FileSystemProvider)
  test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/FileSystemProviderExtended.Tests.ps1
Labels: CL-Test

#11784 Fix ConciseView to handle case where there isn't a console to obtain the width
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
Labels: CL-General

#11838 Fix Package Sorting for sync to private Module Feed
  tools/releaseBuild/azureDevOps/AzArtifactFeed/SyncGalleryToAzArtifacts.psm1
Labels: CL-BuildPackaging

#11836 Restore the PowerShellStreamType enum with an ObsoleteAttribute
  src/System.Management.Automation/engine/PowerShellStreamType.cs
Labels: CL-Engine

#11842 Update Get-Platform helper and tests for Debian 10, 11 and CentOS 8
  test/powershell/Host/Startup.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Date.Tests.ps1
  test/powershell/Modules/PSDesiredStateConfiguration/MOF-Compilation.Tests.ps1
  test/powershell/Modules/PSDesiredStateConfiguration/PSDesiredStateConfiguration.Tests.ps1
  test/powershell/engine/Remoting/PSSession.Tests.ps1
  test/powershell/engine/Remoting/RemoteSession.Basic.Tests.ps1
  test/tools/Modules/HelpersCommon/HelpersCommon.psm1
Labels: CL-Test

#11843 Make sure `LTS` packages have symlink for `pwsh` and `pwsh-lts`
  tools/ci.psm1
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging

#11862 Fix error message
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
Labels: CL-General

#11878 Skip directory creation at root test on macOS
  test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
Labels: CL-Test

#11185 Allow cross-platform CAPI-compatible remote key exchange
  src/System.Management.Automation/engine/remoting/server/OutOfProcServerMediator.cs
  src/System.Management.Automation/engine/remoting/server/serverremotesession.cs
  src/System.Management.Automation/resources/SecuritySupportStrings.resx
  src/System.Management.Automation/utils/CryptoUtils.cs
  test/xUnit/csharp/test_CryptoUtils.cs
Labels: Waiting on Author

#11882 Fix daily package build
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
Labels: CL-BuildPackaging

#11892 Make sure to test whether we skip a new-pssession test using consistent logic
  test/powershell/engine/Remoting/RemoteSession.Basic.Tests.ps1
Labels: CL-Test

#11895 Make LTS package always not a preview
  build.psm1
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging

#11897 Add `LTSRelease` value from `metadata.json` to `release.json`
  tools/releaseBuild/azureDevOps/releaseBuild.yml
Labels: CL-BuildPackaging

#11880 Fix ConciseView where error message is wider than window width and doesn't have whitespace
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  test/powershell/engine/Formatting/ErrorView.Tests.ps1
Labels: CL-General

#11896 Generate guid for FormatViewDefinition InstanceId if not provided
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Export-FormatData.Tests.ps1
Labels: CL-General

#11886 Remove old dead code from FullCLR
  src/Microsoft.PowerShell.Security/security/ExecutionPolicyCommands.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPluginFacade.cs
  src/System.Management.Automation/help/UpdatableHelpCommandBase.cs
Labels: CL-CodeCleanup

#11870 Fix NREs in SuspendStoppingPipeline() and RestoreStoppingPipeline()
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Eventing.Tests.ps1
Labels: CL-General

#11888 Update Adopters.md to include info on Azure Pipelines and GitHub Actions
  ADOPTERS.md
Labels: CL-Docs

#11907 Fix SSH remoting error on Windows platform
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
Labels: CL-Engine

#11891 Update the map between console color to VT sequences
  src/System.Management.Automation/utils/VTUtils.cs
Labels: CL-Engine

#11952 Fix ConciseView to not show the line information within the error message
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  test/powershell/engine/Formatting/ErrorView.Tests.ps1
Labels: CL-General

#11956 Ensure the man gzip has the correct name for LTS release
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging

#11963 Bump .NET core framework to `3.1.2`
  .devcontainer/Dockerfile
  assets/files.wxs
  global.json
  test/tools/WebListener/WebListener.csproj
Labels: CL-BuildPackaging

#11920 Remove hop restrictions for interactive sessions
  src/System.Management.Automation/engine/remoting/commands/PushRunspaceCommand.cs
  src/System.Management.Automation/engine/remoting/common/remotingexceptions.cs
  src/System.Management.Automation/engine/remoting/server/ServerRemoteHost.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
  src/System.Management.Automation/resources/RemotingErrorIdStrings.resx
Labels: Area-Remoting, CL-General
