Repository PowerShell/PowerShell, pull requests merged in 2020-01, with the labels that each got.

#11332 Added setting to disable implicit WinPS module loading
  src/System.Management.Automation/engine/Modules/AnalysisCache.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/PSConfiguration.cs
  src/System.Management.Automation/resources/Modules.resx
  test/powershell/Modules/Microsoft.PowerShell.Core/CompatiblePSEditions.Module.Tests.ps1
Labels: CL-Engine

#11438 Include url in the markdown-links test error message
  test/common/markdown/markdown-link.tests.ps1
Labels: CL-Test

#11485 Add script to rebuild component refs
  assets/files.wxs
  tools/packaging/packaging.psm1
Labels: MustHave

#11486 Run pwsh correctly in tests
  test/powershell/Host/ConsoleHost.Tests.ps1
  test/powershell/Host/ScreenReader.Tests.ps1
  test/powershell/Host/Startup.Tests.ps1
  test/powershell/Language/Parser/UsingAssembly.Tests.ps1
  test/powershell/Language/Scripting/NativeExecution/NativeStreams.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Core/CompatiblePSEditions.Module.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Core/Get-Module.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Core/Import-Module.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Command.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Read-Host.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Write-Error.Tests.ps1
  test/powershell/Modules/Microsoft.Powershell.Host/Start-Transcript.Tests.ps1
  test/powershell/engine/Api/BasicEngine.Tests.ps1
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
  test/powershell/engine/Basic/GroupPolicySettings.Tests.ps1
  test/powershell/engine/Basic/TypeResolution.Tests.ps1
  test/powershell/engine/ExperimentalFeature/EnableDisable-ExperimentalFeature.Tests.ps1
  test/powershell/engine/ExperimentalFeature/Get-ExperimentalFeature.Tests.ps1
  test/powershell/engine/Formatting/ErrorView.Tests.ps1
  test/powershell/engine/Job/Jobs.Tests.ps1
  test/powershell/engine/Module/ModulePath.Tests.ps1
  test/powershell/engine/ParameterBinding/ParameterBinding.Tests.ps1
Labels: CL-Test

#11420 Re-balance CI tests
  test/powershell/Modules/Microsoft.PowerShell.Core/Job.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Diagnostics/Get-WinEvent.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
  test/powershell/engine/Api/Serialization.Tests.ps1
  test/powershell/engine/Api/TaskBasedAsyncPowerShellAPI.Tests.ps1
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
  test/powershell/engine/Help/HelpSystem.OnlineHelp.Tests.ps1
  test/powershell/engine/Job/Jobs.Tests.ps1
Labels: CL-Test

#11480 Update ADOPTERS.md
  .spelling
  ADOPTERS.md
Labels: CL-Docs

#11421 Allow a blank/empty ContentType to be passed to Invoke-WebRequest for compatibility with PS6 and earlier
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: CL-General

#11439 Allow error 504 (Gateway Timeout) in markdown-link tests
  test/common/markdown/markdown-link.tests.ps1
Labels: CL-Test

#11444 Add ssh parameter sets for JobName
  src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs
Labels: CL-Engine

#11512 Remove RequireLicenseAcceptance default value
  src/System.Management.Automation/engine/Modules/NewModuleManifestCommand.cs
  test/powershell/engine/Module/NewModuleManifest.Tests.ps1
Labels: Breaking-Change, CL-General

#11483 Build test artifacts for Alpine
  tools/releaseBuild/azureDevOps/templates/testartifacts.yml
Labels: CL-Test

#11424 Ignore headers with null values in web cmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: CL-General

#11514 Adding PowerShell Editor Services and PSScriptAnalyzer to tracked modules
  src/System.Management.Automation/utils/Telemetry.cs
Labels: CL-Engine

#11474 Fix symbolic links on Debian 10 packages
  build.psm1
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging

#11508 DSC test fixes for alpine
  test/powershell/Modules/PSDesiredStateConfiguration/PSDesiredStateConfiguration.Tests.ps1
Labels: CL-Test

#11473 Correct startup error messages
  src/Microsoft.PowerShell.ConsoleHost/resources/CommandLineParameterParserStrings.resx
Labels: CL-General

#11499 Normalize line endings before comparing string in tests
  test/powershell/Language/Scripting/Debugging/DebuggerCommand.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-List.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1
Labels: CL-Test

#11526 Update building of MSIX for RC to use 100 range revision
  tools/packaging/packaging.psm1
Labels: MustHave

#11516 Update the breaking change definition
  docs/maintainers/best-practice.md
Labels: CL-Docs

#11448 Skip null data (fix NRE) in output data received handler
  src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs
Labels: CL-Engine, MustHave

#11540 Update Debian Install Script To Support Debian 10
  tools/installpsh-debian.sh
Labels: CL-BuildPackaging

#11559 Avoid variable names that conflict with automatic variables part2
  test/powershell/engine/Module/TestModuleManifest.Tests.ps1
Labels: CL-Test

#11545 Generate the correct reference assembly for `Microsoft.PowerShell.ConsoleHost` NuGet package
  test/hosting/test_HostingBasic.cs
  tools/packaging/packaging.psm1
  tools/packaging/projects/reference/Microsoft.PowerShell.ConsoleHost/Microsoft.PowerShell.ConsoleHost.csproj
Labels: CL-BuildPackaging

#11435 Fix NRE in ConsiceView
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
Labels: CL-General

#11046 Port GetProcessorArchitecture()
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/utils/PsUtils.cs
  test/powershell/engine/Module/NewModuleManifest.Tests.ps1
Labels: CL-CodeCleanup

#11576 Mark System32-PSModulePath test as pending
  test/powershell/Modules/Microsoft.PowerShell.Core/CompatiblePSEditions.Module.Tests.ps1
Labels: Area-Test, CL-Test

#11541 More test fixes for failing tests
  test/powershell/Modules/Microsoft.PowerShell.Management/Split-Path.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Set-Date.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
  test/powershell/engine/ExperimentalFeature/Get-ExperimentalFeature.Tests.ps1
Labels: Area-Test

#11552 Support expanding ~ in $env:PATH when doing command discovery
  src/System.Management.Automation/engine/CommandDiscovery.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Environment-Variables.Tests.ps1
Labels: CL-Engine, Documentation Needed

#11536 Use ISOWeek for week numbers in Get-Date
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetDateCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Date.Tests.ps1
Labels: CL-BreakingChange, CL-General

#11572 Fixes: Build.psm1
  build.psm1
Labels: CL-BuildPackaging

#11597 Update README.md and metadata.json for next release
  README.md
  tools/metadata.json
Labels: CL-Docs

#11517 Make Test-Connection always use the default synchronization context for sending ping requests
  src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1
Labels: CL-General

#11653 Fix markdown-link test failure
  CHANGELOG/6.0.md
Labels: CL-Docs

#11654 Specify charset in .editorconfig as utf-8 (no BOM)
  .editorconfig
Labels: CL-Tools

#11623 Change name of ClrVersion parameter back
  src/System.Management.Automation/engine/Modules/NewModuleManifestCommand.cs
Labels: CL-CodeCleanup

#11587 Format-Hex - Fix Grouping Behaviour with Boolean values
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-hex/Format-Hex.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Hex.Tests.ps1
Labels: CL-General

#11627 vscode: Enable EditorConfig support in OmniSharp
  .vscode/settings.json
Labels: CL-Tools

#11611 Add -AsUTC to the Get-Date cmdlet
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetDateCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Date.Tests.ps1
Labels: CL-General

#11548 Add custom 'Selected.*' type to PSCustomObject in Select-Object only once
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Select-Object.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Select-Object.Tests.ps1
Labels: CL-General

#11675 Update .editorconfig
  .editorconfig
Labels: CL-Tools

#11664 Update README.md and metadata.json for next release
  README.md
  tools/metadata.json
Labels: CL-BuildPackaging

#11697 Move to version 3 of AzFileCopy
  tools/releaseBuild/azureDevOps/WindowsBuild.yml
  tools/releaseBuild/azureDevOps/templates/json.yml
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/nuget.yml
  tools/releaseBuild/azureDevOps/templates/upload.yml
Labels: AutoMerge, CL-BuildPackaging

#11704 Move to latest Azure DevOps agent images
  .vsts-ci/linux.yml
  .vsts-ci/mac.yml
  .vsts-ci/templates/ci-build.yml
  .vsts-ci/templates/nanoserver.yml
  .vsts-ci/templates/nix-test.yml
  .vsts-ci/templates/verify-xunit.yml
  .vsts-ci/windows-daily.yml
  .vsts-ci/windows.yml
Labels: CL-BuildPackaging, CL-Test

#11652 Add links to diffs on Github in changelog
  CHANGELOG/6.0.md
  CHANGELOG/6.1.md
  CHANGELOG/6.2.md
  CHANGELOG/preview.md
  docs/testing-guidelines/PowerShellCoreTestStatus.md
Labels: CL-Docs

#11707 Bump .devcontainer version to dotnet 3.1.101
  .devcontainer/Dockerfile
Labels: AutoMerge, CL-BuildPackaging

#11648 Revert the PRs that made `DBNull.Value` and `NullString.Value` treated as `$null`
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  test/powershell/Language/Operators/NullConditional.Tests.ps1
  test/powershell/Language/Scripting/NullRepresentatives.Tests.ps1
  test/powershell/engine/Basic/SemanticVersion.Tests.ps1
  test/powershell/engine/ETS/TypeTable.Tests.ps1
Labels: CL-Engine

#11723 Fix Symlink creation in packaging.psm1
  tools/packaging/packaging.psm1
Labels: Area-Build, CL-BuildPackaging

#11518 don't needlessly pass `-l login_name` or `-p port` to ssh (PowerShell…
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
Labels: CL-Engine

#11703 Added info about DeploymentScripts in ADOPTERS.md
  ADOPTERS.md
Labels: CL-Docs

#11670 Fix unnecessary trimming of line resulting in incorrect indexi…
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  test/powershell/engine/Formatting/ErrorView.Tests.ps1
Labels: CL-General

#11622 Restore `SetBreakpoints` API
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Set-PSBreakpoint.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/hostifaces/PSTask.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspace.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
  test/powershell/SDK/Breakpoint.Tests.ps1
Labels: CL-Engine

#11574 Check state and report reason if it's not "opened"
  test/powershell/Modules/Microsoft.PowerShell.Core/Enter-PSHostProcess.Tests.ps1
Labels: CL-Test

#11331 Fix error message during symlink deletion
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: Area-Cmdlets-Management, Area-Providers, Issue-Bug

#11690 Refactor delegate types to lambda expressions
  src/Microsoft.Management.UI.Internal/ManagementList/ManagementList/Innerlist.cs
  src/Microsoft.Management.UI.Internal/commandHelpers/HelpWindowHelper.cs
  src/Microsoft.Management.UI.Internal/commandHelpers/OutGridView.cs
  src/Microsoft.Management.UI.Internal/commandHelpers/ShowCommandHelper.cs
Labels: CL-CodeCleanup

#11725 Add link to .NET CLI version in build documentation
  docs/building/windows-core.md
Labels: CL-Docs

#11640 Replace use of throw GetExceptionForHR with ThrowExceptionForHR
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
  src/System.Management.Automation/engine/parser/FusionAssemblyIdentity.cs
  src/System.Management.Automation/security/SecuritySupport.cs
Labels: CL-CodeCleanup

#11711 Change regex to match relation-types w/o quotes in Link header
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
Labels: CL-General

#11681 Reformat code according to EditorConfig rules
  src/Microsoft.Management.Infrastructure.CimCmdlets/AssemblyInfo.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetAssociatedInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimIndicationWatcher.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimInvokeCimMethod.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimNewCimInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimRemoveCimInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionOperations.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSetCimInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteError.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimClassCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RemoveCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RemoveCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/Utils.cs
  src/Microsoft.Management.UI.Internal/ManagementList/Common/TextBlockService.cs
  src/Microsoft.Management.UI.Internal/ManagementList/ManagementList/ViewGroupToStringConverter.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/Controls/ShowModuleControl.xaml.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/ViewModel/CommandViewModel.cs
  src/Microsoft.Management.UI.Internal/commandHelpers/ShowCommandHelper.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/PdhHelper.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ComputerUnix.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Hotfix.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
  src/System.Management.Automation/engine/CommandSearcher.cs
  src/System.Management.Automation/engine/CoreAdapter.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/TypeTable_TypesV3_Ps1Xml.cs
  src/System.Management.Automation/engine/TypeTable_Types_Ps1Xml.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/hostifaces/ConnectionBase.cs
  src/System.Management.Automation/engine/lang/parserutils.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspace.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspaceinfo.cs
  src/System.Management.Automation/engine/remoting/commands/StartJob.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/RemoteDebuggingCapability.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
  src/System.Management.Automation/utils/Telemetry.cs
  test/xUnit/csharp/test_FileSystemProvider.cs
  test/xUnit/csharp/test_NamedPipe.cs
Labels: CL-CodeCleanup
