Repository PowerShell/PowerShell, pull requests merged in 2020-06, with the labels that each got.

#12797 Fix New-Item to create symlink to relative path target
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1
Labels: CL-General

#12840 Expand numberOfPowershellRefAssemblies list capacity
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs
Labels: AutoMerge, CL-CodeCleanup

#12864 Reorder modifiers according to preferred order
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
Labels: AutoMerge, CL-CodeCleanup

#10622 Bring back Certificate provider parameters
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
  src/System.Management.Automation/security/SecuritySupport.cs
  test/powershell/Modules/Microsoft.PowerShell.Security/CertificateProvider.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Security/certificateCommon.psm1
Labels: CL-General, Documentation Needed

#12686 Update the PowerShell modules to use the new Help URI
  src/Modules/Shared/Microsoft.PowerShell.Host/Microsoft.PowerShell.Host.psd1
  src/Modules/Unix/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.psd1
  src/Modules/Unix/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.psd1
  src/Modules/Unix/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/Modules/Windows/CimCmdlets/CimCmdlets.psd1
  src/Modules/Windows/Microsoft.PowerShell.Diagnostics/Microsoft.PowerShell.Diagnostics.psd1
  src/Modules/Windows/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.psd1
  src/Modules/Windows/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.psd1
  src/Modules/Windows/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/Modules/Windows/Microsoft.WSMan.Management/Microsoft.WSMan.Management.psd1
  src/Modules/Windows/PSDiagnostics/PSDiagnostics.psd1
  src/System.Management.Automation/help/UpdatableHelpCommandBase.cs
Labels: CL-CodeCleanup

#12549 Restore `markdownlint` tests
  .github/ISSUE_TEMPLATE/Bug_Report.md
  .github/ISSUE_TEMPLATE/Distribution_Request.md
  .github/ISSUE_TEMPLATE/Feature_Request.md
  .github/ISSUE_TEMPLATE/Release_Process.md
  .github/ISSUE_TEMPLATE/Security_Issue_Report.md
  .vsts-ci/misc-analysis.yml
  README.md
  test/common/markdown/gulpfile.js
  test/common/markdown/markdown-link.tests.ps1
  test/common/markdown/markdown.tests.ps1
  test/common/markdown/package.json
  test/common/markdown/yarn.lock
  tools/install-powershell.ps1-README.md
  tools/install-powershell.sh-README.md
Labels: CL-Test, Waiting on Author

#11934 Add parameter `SchemaFile` to `Test-Json` cmdlet
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/TestJsonCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/TestJsonCmdletStrings.resx
  test/powershell/Modules/Microsoft.PowerShell.Utility/Test-Json.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/assets/invalid_schema_definitions.json
  test/powershell/Modules/Microsoft.PowerShell.Utility/assets/invalid_schema_reference.json
  test/powershell/Modules/Microsoft.PowerShell.Utility/assets/valid_schema_definitions.json
  test/powershell/Modules/Microsoft.PowerShell.Utility/assets/valid_schema_reference.json
Labels: CL-General

#12878 Make contributors unique in Release notes
  tools/releaseTools.psm1
Labels: CL-BuildPackaging

#12887 Fix broken link in README.md
  README.md
Labels: AutoMerge, CL-Docs

#12889 Fix break in package build by pinning `ffi` version to `1.12`
  build.psm1
Labels: CL-BuildPackaging

#12894 Enable skipped tests
  test/powershell/Modules/Microsoft.PowerShell.Management/Clipboard.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/FileSystemProviderExtended.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-Process.Tests.ps1
Labels: CL-BuildPackaging

#12921 Check if Azure Blob exists before overwriting
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/checkAzureContainer.yml
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/mac.yml
  tools/releaseBuild/azureDevOps/templates/windows-hosted-build.yml
Labels: CL-BuildPackaging

#10487 Flag `default` switch statement condition clause as keyword
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/parser/token.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
  test/powershell/Language/Parser/Parsing.Tests.ps1
Labels: CL-General, Review - Needed, Waiting on Author

#11946 Start-Process: Correct Unspecified WorkingDirectory Resolution
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
Labels: Breaking-Change, CL-BreakingChange, CL-General, Committee-Reviewed

#12927 Add @TylerLeonhardt to PowerShell team list to correct changelog generation
  tools/releaseTools.psm1
Labels: CL-Tools

#12778 Remove use of `Test-Path` in ConciseView
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  test/powershell/engine/Formatting/ErrorView.Tests.ps1
Labels: CL-General

#12855 Disable NonPrivateReadonlyFieldsMustBeginWithUpperCaseLetter
  Settings.StyleCop
Labels: Review - Needed

#12955 Rename CimCmdlet resources
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimCommandBase.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimInvokeCimMethod.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimRegisterCimIndication.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionOperations.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSetCimInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteProgress.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/Utils.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/resources/CimCmdletStrings.resx
Labels: CL-General

#12960 Remove positional assignment of QUALIFIER for SPLIT-PATH
  src/Microsoft.PowerShell.Commands.Management/commands/management/ParsePathCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Split-Path.Tests.ps1
Labels: CL-BreakingChange, CL-General, Review - Committee

#12943 Remove dependency on DNS for `Test-Connection` tests on macOS
  test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1
Labels: CL-Test

#12972 Update `DotnetRutimeMetadata.json` to point to preview 6
  DotnetRuntimeMetadata.json
Labels: CL-BuildPackaging

#12945 Fix conflicting shorthand switch `-w` for pwsh
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
Labels: CL-General

#12940 Add HoloLens to list of PowerShell adopters
  .spelling
  ADOPTERS.md
Labels: CL-Docs

#12989 Use correct isError parameter with Write-Log
  build.psm1
Labels: CL-Tools

#12958 Use HashSet instead of Hashtable with null values
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataQuery.cs
  src/System.Management.Automation/FormatAndOutput/common/Utilities/Mshexpression.cs
  src/System.Management.Automation/help/AliasHelpProvider.cs
  src/System.Management.Automation/help/CommandHelpProvider.cs
Labels: CL-CodeCleanup

#12954 Replace `SortedList` with `Generic.SortedList<TKey,TValue>`
  src/System.Management.Automation/engine/ManagementObjectAdapter.cs
Labels: CL-CodeCleanup

#11097 Fix Issue in Select-Object where Hashtable members (e.g., `Keys`) cannot be used with -Property or -ExpandProperty
  src/System.Management.Automation/FormatAndOutput/common/Utilities/Mshexpression.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Select-Object.Tests.ps1
Labels: CL-General

#13010 Fix tests writing errors to console.
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-FileHash.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-RunspaceDebug.Tests.ps1
Labels: CL-Test

#13019 Remove component ref when regenerating the WIX file
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging

#13033 Add @rjmholt to maintainers list
  .spelling
  docs/maintainers/README.md
Labels: CL-Docs

#13053 Update windows-core.md
  docs/building/windows-core.md
Labels: CL-Docs

#13008 Add update packages.microsoft.com step to distribution request template.
  .github/ISSUE_TEMPLATE/Distribution_Request.md
Labels: CL-Docs

#13056 Fix links for MSI packages for point to `7.1.0-preview.3`
  README.md
Labels: CL-Docs

#13036 Correct stable and preview upgrade codes for `MSI`
  assets/Product.wxs
  test/packaging/windows/msi.tests.ps1
Labels: CL-BuildPackaging

#11393 Add new test for Format-Custom to avoid data loss
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Custom.Tests.ps1
Labels: CL-Test, Review - Needed

#12968 Ensure assemblies listed `FileList` are not loaded
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  test/powershell/Modules/Microsoft.PowerShell.Core/Import-Module.Tests.ps1
Labels: CL-Engine

#12871 Add missing `.editorconfig` settings present in dotnet/runtime
  .editorconfig
Labels: CL-Tools, Review - Needed

#12970 Add right-click menu to Run with PowerShell for ps1 scripts
  assets/Product.wxs
Labels: CL-BuildPackaging
