Repository PowerShell/PowerShell, pull requests merged in 2020-08, with the labels that each got.

#13330 Use authenticode cert for msix signing
  tools/packaging/packaging.psm1
  tools/releaseBuild/generatePackgeSigning.ps1
Labels: BackPort-7.0.x, CL-BuildPackaging

#12629 Improve BigInteger casting behaviours
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  test/powershell/Language/Parser/Conversions.Tests.ps1
Labels: CL-General

#13274 HelpSystem: Improve the wording of inline comments
  src/System.Management.Automation/help/HelpSystem.cs
Labels: CL-Docs, Review - Needed

#13354 Increase the timeout of Windows daily build to 90 minutes
  .vsts-ci/windows-daily.yml
Labels: CL-Tools

#13162 Allow explicitly specified named parameter to supersede the same one from hashtable splatting
  src/System.Management.Automation/engine/CmdletParameterBinderController.cs
  src/System.Management.Automation/engine/CommandParameter.cs
  src/System.Management.Automation/engine/MinishellParameterBinderController.cs
  src/System.Management.Automation/engine/ParameterBinderController.cs
  src/System.Management.Automation/engine/hostifaces/PSCommand.cs
  src/System.Management.Automation/engine/hostifaces/Parameter.cs
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs
  src/System.Management.Automation/engine/scriptparameterbindercontroller.cs
  test/powershell/engine/ParameterBinding/Splatting.Tests.ps1
Labels: CL-BreakingChange, CL-Engine, Committee-Reviewed

#13305 Switch to MIT license for files copied from Roslyn
  src/System.Management.Automation/engine/parser/FusionAssemblyIdentity.cs
  src/System.Management.Automation/engine/parser/GlobalAssemblyCache.cs
Labels: CL-Docs, CL-General

#13331 Remove AssemblyInfo property from list views
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
Labels: CL-CodeCleanup

#13281 Change "operable" to "executable"
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/resources/DiscoveryExceptions.resx
  test/powershell/Modules/Microsoft.PowerShell.Core/CompatiblePSEditions.Module.Tests.ps1
Labels: CL-CodeCleanup

#13336 Bump Visual Studio 2019 required version in build documention
  docs/building/windows-core.md
Labels: CL-BuildPackaging

#13291 SwitchParameter should be property not field
  src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetDateCommand.cs
Labels: CL-CodeCleanup, Review - Needed

#13372 Revert "Add password confirmation in Get-Credential"
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfacePrompt.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfaceSecurity.cs
  src/Microsoft.PowerShell.ConsoleHost/resources/ConsoleHostUserInterfaceSecurityResources.resx
  src/Microsoft.PowerShell.Security/security/CredentialCommands.cs
  src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs
  src/System.Management.Automation/engine/hostifaces/internalHostuserInterfacesecurity.cs
  src/System.Management.Automation/engine/remoting/server/ServerRemoteHostUserInterface.cs
  src/System.Management.Automation/security/CredentialParameter.cs
  test/powershell/Modules/Microsoft.PowerShell.Security/GetCredential.Tests.ps1
  test/tools/Modules/HelpersHostCS/HelpersHostCS.psm1
Labels: CL-NotInBuild

#13355 Update pwsh help for -InputFormat parameter
  src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx
Labels: CL-General

#13287 Use 'is' operator instead of 'as' operator
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ShowCommand/ShowCommandCommandInfo.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/System.Management.Automation/engine/remoting/commands/NewPSSessionConfigurationFile.cs
  src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
Labels: CL-CodeCleanup

#13387 Fix dotnet install errors during release build
  build.psm1
Labels: CL-Tools

#13265 Improve inline documentation for VerbInfo
  src/System.Management.Automation/utils/Verbs.cs
Labels: CL-CodeCleanup, CL-Docs

#13373 Clarified instructions for running Start-PSPester tests in window-core readme
  docs/building/windows-core.md
Labels: CL-Docs

#13285 Fix comparison of value type object to null
  src/Microsoft.PowerShell.Commands.Diagnostics/PdhHelper.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs
  src/System.Management.Automation/engine/remoting/client/RemoteRunspacePoolInternal.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPluginFacade.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManTransportManager.cs
  src/System.Management.Automation/help/CabinetNativeApi.cs
  src/System.Management.Automation/help/UpdatableHelpModuleInfo.cs
  src/System.Management.Automation/help/UpdatableHelpUri.cs
  src/System.Management.Automation/security/Authenticode.cs
Labels: Review - Needed

#13353 Fix Get-Help not properly displaying if parameter supports wildcards
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/HelpV3_format_ps1xml.cs
  src/System.Management.Automation/help/DefaultCommandHelpObjectBuilder.cs
  test/powershell/Language/Scripting/ScriptHelp.Tests.ps1
Labels: CL-General

#11482 Refactor command line parser to do early parsing
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleShell.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ManagedEntrance.cs
  src/powershell/Program.cs
  test/xUnit/csharp/test_CommandLineParser.cs
Labels: CL-Engine

#13084 Add `-UnixTimeSeconds` to `Get-Date` to allow Unix time input
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetDateCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Date.Tests.ps1
Labels: CL-BreakingChange, CL-General

#13420 Add missing dispose for CancellationTokenSource
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimChildJobBase.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs
Labels: CL-General

#13427 Update infrastructure to consume private builds from .NET
  build.psm1
  tools/UpdateDotnetRuntime.ps1
Labels: CL-BuildPackaging

#13394 Create release pipeline as a yaml pipeline
  tools/releaseBuild/azureDevOps/releasePipeline.yml
  tools/releaseBuild/azureDevOps/templates/nuget.yml
  tools/releaseBuild/azureDevOps/templates/release-BuildJson.yml
  tools/releaseBuild/azureDevOps/templates/release-CreateGitHubDraft.yml
  tools/releaseBuild/azureDevOps/templates/release-GlobalToolTest.yml
  tools/releaseBuild/azureDevOps/templates/release-MakeContainerPublic.yml
  tools/releaseBuild/azureDevOps/templates/release-PublishPackageMsftCom.yml
  tools/releaseBuild/azureDevOps/templates/release-ReleaseToNuGet.yml
  tools/releaseBuild/azureDevOps/templates/release-SDKTests.yml
  tools/releaseBuild/azureDevOps/templates/release-SetReleaseTagAndContainerName.yml
  tools/releaseBuild/azureDevOps/templates/release-UpdateDepsJson.yml
  tools/releaseBuild/azureDevOps/templates/release-ValidatePackageNames.yml
Labels: CL-BuildPackaging

#13437 Update README links and metadata.json for 7.1.0-preview.6
  README.md
  tools/metadata.json
Labels: CL-Docs

#13430 Create warnings when UTF7 is specified as an encoding
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-hex/Format-Hex.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-file/Out-File.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Send-MailMessage.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/XmlCommands.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/resources/PathUtilsStrings.resx
  src/System.Management.Automation/utils/EncodingUtils.cs
  test/powershell/engine/Basic/Encoding.Tests.ps1
Labels: CL-General

#13227 Add a precheck for git to build.psm1
  build.psm1
Labels: CL-BuildPackaging

#13441 Remove redundant delegate creation
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-printer/PrinterLineOutput.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ShowCommand/ShowCommand.cs
Labels: CL-CodeCleanup

#13395 Fix `$?` to not be `$false` because native command wrote to stderr
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1
Labels: CL-BreakingChange, CL-Engine, Review - Needed

#13438 Optimize 'GetSystemLockdownPolicy' for non-lockdown scenarios
  src/System.Management.Automation/security/wldpNativeMethods.cs
Labels: CL-Engine

#13186 Initial work of the subsystem plugin model (for minimal powershell)
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/Subsystem/CommandPrediction/CommandPrediction.cs
  src/System.Management.Automation/engine/Subsystem/CommandPrediction/ICommandPredictor.cs
  src/System.Management.Automation/engine/Subsystem/Commands/GetSubsystemCommand.cs
  src/System.Management.Automation/engine/Subsystem/ISubsystem.cs
  src/System.Management.Automation/engine/Subsystem/SubsystemInfo.cs
  src/System.Management.Automation/engine/Subsystem/SubsystemManager.cs
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/resources/SubsystemStrings.resx
  test/powershell/engine/Help/HelpSystem.Tests.ps1
  test/xUnit/csharp/test_Prediction.cs
  test/xUnit/csharp/test_Subsystem.cs
  tools/packaging/packaging.psm1
Labels: CL-Engine

#13440 Change `Add-Type -OutputType` to not support `ConsoleApplication` and `WindowsApplication`
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/AddTypeStrings.resx
  test/powershell/Modules/Microsoft.PowerShell.Utility/Add-Type.Tests.ps1
Labels: CL-General

#13408 Add StringUtil.Format overload to avoid unnecessary allocations
  src/System.Management.Automation/utils/StringUtil.cs
Labels: CL-CodeCleanup, Review - Needed

#13350 Remove if statement to prevent InvalidOperation error
  build.psm1
Labels: CL-Tools, Review - Needed

#13375 #13347: ObRoot: Use field if property does not exist
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
Labels: CL-General, Review - Needed

#13522 Change `PSNativePSPathResolution` to not be Experimental
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/NativeCommandParameterBinder.cs
  test/powershell/Language/Scripting/NativeExecution/NativeCommandArguments.Tests.ps1
Labels: CL-General

#13529 Remove experimental flag from `PSNullConditionalOperators` feature
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
  test/powershell/Language/Operators/NullConditional.Tests.ps1
  test/powershell/Language/Parser/Parsing.Tests.ps1
  test/tools/TestMetadata.json
Labels: MustHave

#13481 Process reparse points to Microsoft Store applications
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-General

#13451 Add null check for args in CommandLineParser
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/resources/CommandLineParameterParserStrings.resx
  test/xUnit/csharp/test_CommandLineParser.cs
Labels: CL-General

#13509 Reformat StringUtil
  src/System.Management.Automation/utils/StringUtil.cs
Labels: CL-CodeCleanup

#13530 Update to .NET 5 preview 8
  DotnetRuntimeMetadata.json
  assets/files.wxs
  global.json
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/FilterRuleExtensions.cs
  src/Microsoft.Management.UI.Internal/Microsoft.PowerShell.GraphicalHost.csproj
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/RemoteSessionCapability.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/utils/EncodingUtils.cs
  src/powershell-win-core/powershell-win-core.csproj
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
  tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  tools/packaging/projects/reference/System.Management.Automation/System.Management.Automation.csproj
Labels: CL-BuildPackaging

#13539 Fix RCS1243: Duplicate word in a comment
  src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ReadConsoleCmdlet.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs
  src/Microsoft.WSMan.Management/InvokeWSManAction.cs
  src/Microsoft.WSMan.Management/WSManInstance.cs
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataManager.cs
  src/System.Management.Automation/engine/AliasInfo.cs
  src/System.Management.Automation/engine/CmdletParameterBinderController.cs
  src/System.Management.Automation/engine/DataStoreAdapter.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/MshMemberInfo.cs
  src/System.Management.Automation/engine/MshObjectTypeDescriptor.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/hostifaces/History.cs
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
  src/System.Management.Automation/engine/remoting/commands/ConnectPSSession.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/EncodeAndDecode.cs
  src/System.Management.Automation/engine/remoting/common/fragmentor.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
  src/System.Management.Automation/help/CommandHelpProvider.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/utils/IObjectWriter.cs
  src/System.Management.Automation/utils/MshTraceSource.cs
  src/System.Management.Automation/utils/ObjectStream.cs
  src/System.Management.Automation/utils/ObjectWriter.cs
  src/System.Management.Automation/utils/StructuredTraceSource.cs
Labels: CL-CodeCleanup
