Repository PowerShell/PowerShell, pull requests merged in 2020-11, with the labels that each got.

#13957 Enforce code style in build
  .globalconfig
  PowerShell.Common.props
  test/Test.Common.props
Labels: CL-CodeCleanup

#13958 Enable IDE0036: OrderModifiers
  .globalconfig
  src/powershell/Program.cs
Labels: CL-General

#13926 Enable CA1830: Prefer strongly-typed Append and Insert method overloads on StringBuilder
  .globalconfig
  src/System.Management.Automation/FormatAndOutput/common/FormatViewManager.cs
  src/System.Management.Automation/engine/ManagementObjectAdapter.cs
  src/System.Management.Automation/engine/ProxyCommand.cs
Labels: CL-CodeCleanup

#13960 Add IDE analyzer rule IDs to comments
  .globalconfig
Labels: CL-CodeCleanup

#13887 Fix IDE0044: MakeFieldReadonly part 4
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CustomSerialization.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/DebugRunspaceCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ExportAliasCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/ExpressionColumnInfo.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/HeaderInfo.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/OriginalColumnInfo.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/OutGridViewCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/OutWindowProxy.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/ScalarTypeColumnInfo.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/common/WriteFormatDataCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-printer/PrinterLineOutput.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-string/Out-String.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetMember.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MarkdownOptionCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Measure-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ObjectCommandComparer.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/OrderObjectBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Select-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Send-MailMessage.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ShowCommand/ShowCommandProxy.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/StartSleepCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/TimeExpressionCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Update-TypeData.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WaitEventCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertFromJsonCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertToJsonCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebProxy.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/StreamHelper.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/XmlCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/MshHostTraceListener.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/TraceExpressionCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/TraceListenerCommandBase.cs
Labels: CL-CodeCleanup

#13891 Fix IDE0044: MakeFieldReadonly part 8
  src/Microsoft.PowerShell.Security/security/CatalogCommands.cs
  src/Microsoft.PowerShell.Security/security/CertificateCommands.cs
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
  src/Microsoft.PowerShell.Security/security/CmsCommands.cs
  src/Microsoft.PowerShell.Security/security/SecureStringCommands.cs
  src/Microsoft.PowerShell.Security/security/SignatureCommands.cs
Labels: CL-CodeCleanup

#13884 Fix IDE0044: MakeFieldReadonly part 1
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimAsyncOperation.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimBaseAction.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimCommandBase.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetCimClass.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimIndicationWatcher.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimInvokeCimMethod.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimPromptUser.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimRegisterCimIndication.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimResultObserver.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionOperations.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSetCimInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteError.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteMessage.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteProgress.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteResultObject.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CmdletOperation.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimAssociatedInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimClassCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/InvokeCimMethodCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimSessionOptionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RegisterCimIndicationCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RemoveCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RemoveCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/SetCimInstanceCommand.cs
Labels: CL-CodeCleanup

#13863 Remove unnecessary using in utils folder
  src/System.Management.Automation/utils/ClrFacade.cs
  src/System.Management.Automation/utils/CommandDiscoveryExceptions.cs
  src/System.Management.Automation/utils/EncodingUtils.cs
  src/System.Management.Automation/utils/ExecutionExceptions.cs
  src/System.Management.Automation/utils/FormatAndTypeDataHelper.cs
  src/System.Management.Automation/utils/FuzzyMatch.cs
  src/System.Management.Automation/utils/IObjectReader.cs
  src/System.Management.Automation/utils/IObjectWriter.cs
  src/System.Management.Automation/utils/MshArgumentException.cs
  src/System.Management.Automation/utils/MshArgumentNullException.cs
  src/System.Management.Automation/utils/MshArgumentOutOfRangeException.cs
  src/System.Management.Automation/utils/MshInvalidOperationException.cs
  src/System.Management.Automation/utils/MshNotImplementedException.cs
  src/System.Management.Automation/utils/MshNotSupportedException.cs
  src/System.Management.Automation/utils/MshObjectDisposedException.cs
  src/System.Management.Automation/utils/ObjectReader.cs
  src/System.Management.Automation/utils/ParameterBinderExceptions.cs
  src/System.Management.Automation/utils/PlatformInvokes.cs
  src/System.Management.Automation/utils/RuntimeException.cs
  src/System.Management.Automation/utils/SessionStateExceptions.cs
Labels: CL-CodeCleanup

#13920 Bump .NET to version `5.0.100-rtm.20526.5`
  .devcontainer/Dockerfile
  assets/files.wxs
  build.psm1
  global.json
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
  tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  tools/packaging/projects/reference/System.Management.Automation/System.Management.Automation.csproj
Labels: BackPort-7.1.x-Consider

#13975 Update PSReadLine version to `2.1.0`
  src/Modules/PSGalleryModules.csproj
Labels: BackPort-7.1.x-Consider

#13976 Bump `Microsoft.PowerShell.Native` version from `v7.1.0-rc.2` to `v7.1.0`
  src/System.Management.Automation/System.Management.Automation.csproj
Labels: BackPort-7.1.x-Consider

#13921 Fix typo in MapSecurityZone
  src/System.Management.Automation/utils/ClrFacade.cs
Labels: BackPort-7.1.x-Consider, CL-Engine

#13969 Fix IDE0044: MakeFieldReadonly part 14
  src/System.Management.Automation/help/AliasHelpInfo.cs
  src/System.Management.Automation/help/AliasHelpProvider.cs
  src/System.Management.Automation/help/CabinetAPI.cs
  src/System.Management.Automation/help/CommandHelpProvider.cs
  src/System.Management.Automation/help/HelpCategoryInvalidException.cs
  src/System.Management.Automation/help/HelpCommands.cs
  src/System.Management.Automation/help/HelpCommentsParser.cs
  src/System.Management.Automation/help/HelpErrorTracer.cs
  src/System.Management.Automation/help/HelpFileHelpInfo.cs
  src/System.Management.Automation/help/HelpFileHelpProvider.cs
  src/System.Management.Automation/help/HelpNotFoundException.cs
  src/System.Management.Automation/help/HelpProvider.cs
  src/System.Management.Automation/help/HelpProviderWithCache.cs
  src/System.Management.Automation/help/HelpSystem.cs
  src/System.Management.Automation/help/MUIFileSearcher.cs
  src/System.Management.Automation/help/MamlClassHelpInfo.cs
  src/System.Management.Automation/help/MamlCommandHelpInfo.cs
  src/System.Management.Automation/help/MamlNode.cs
  src/System.Management.Automation/help/ProviderCommandHelpInfo.cs
  src/System.Management.Automation/help/ProviderHelpInfo.cs
  src/System.Management.Automation/help/RemoteHelpInfo.cs
  src/System.Management.Automation/help/UpdatableHelpCommandBase.cs
  src/System.Management.Automation/help/UpdatableHelpSystem.cs
Labels: CL-CodeCleanup

#13874 Mark PowerShellAssemblyLoadContextInitializer with static modifier
  src/System.Management.Automation/CoreCLR/CorePsAssemblyLoadContext.cs
Labels: CL-CodeCleanup

#13961 Enable CA1825: Avoid zero-length array allocations
  .globalconfig
  docs/dev-process/coding-guidelines.md
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/New-Object.cs
  src/System.Management.Automation/engine/EventManager.cs
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/ParameterBinderBase.cs
  src/System.Management.Automation/engine/PseudoParameters.cs
  src/System.Management.Automation/engine/hostifaces/LocalConnection.cs
  src/System.Management.Automation/engine/remoting/host/RemoteHostMethodInfo.cs
  src/System.Management.Automation/engine/runtime/Operations/ArrayOps.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  src/System.Management.Automation/namespaces/RegistryProvider.cs
  src/System.Management.Automation/utils/GraphicalHostReflectionWrapper.cs
  test/xUnit/csharp/test_CommandLineParser.cs
Labels: CL-CodeCleanup

#13748 Update pwsh -? output to match docs
  src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx
Labels: BackPort-7.1.x-Approved, CL-General

#13503 Run `dotnet-format` to improve formatting of source code
  src/Microsoft.PowerShell.Commands.Diagnostics/PdhHelper.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ManagedEntrance.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/UnsafeNativeMethods.cs
  src/System.Management.Automation/CoreCLR/CorePsAssemblyLoadContext.cs
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
  src/System.Management.Automation/engine/COM/ComDispatch.cs
  src/System.Management.Automation/engine/ComInterop/VariantArray.cs
  src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs
  src/System.Management.Automation/engine/ReflectionParameterBinder.cs
  src/System.Management.Automation/engine/Subsystem/CommandPrediction/CommandPrediction.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManNativeAPI.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPlugin.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/namespaces/RegistryProvider.cs
  src/System.Management.Automation/security/SecureStringHelper.cs
  src/System.Management.Automation/security/SecurityManager.cs
  src/System.Management.Automation/security/SecuritySupport.cs
  src/System.Management.Automation/security/nativeMethods.cs
  src/System.Management.Automation/utils/CryptoUtils.cs
Labels: CL-CodeCleanup, Review - Needed

#13924 Enable CA18XX rules with suggestion severity
  .globalconfig
Labels: CL-CodeCleanup

#13971 Fix IDE0044: MakeFieldReadonly part 16
  src/System.Management.Automation/FormatAndOutput/common/BaseCommand.cs
  src/System.Management.Automation/FormatAndOutput/common/BaseFormattingCommand.cs
  src/System.Management.Automation/FormatAndOutput/common/BaseFormattingCommandParameters.cs
  src/System.Management.Automation/FormatAndOutput/common/BaseOutputtingCommand.cs
  src/System.Management.Automation/FormatAndOutput/common/ColumnWidthManager.cs
  src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/FormatTable.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/XmlLoaderBase.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayResourceManagerCache.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataManager.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataQuery.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatMsgCtxManager.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator_Complex.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatViewManager.cs
  src/System.Management.Automation/FormatAndOutput/common/ILineOutput.cs
  src/System.Management.Automation/FormatAndOutput/common/OutputManager.cs
  src/System.Management.Automation/FormatAndOutput/common/OutputQueue.cs
  src/System.Management.Automation/FormatAndOutput/common/Utilities/MshParameter.cs
  src/System.Management.Automation/FormatAndOutput/common/Utilities/Mshexpression.cs
  src/System.Management.Automation/FormatAndOutput/out-console/ConsoleLineOutput.cs
Labels: CL-CodeCleanup

#13970 Fix IDE0044: MakeFieldReadonly part 15
  src/System.Management.Automation/namespaces/CoreCommandContext.cs
  src/System.Management.Automation/namespaces/FileSystemContentStream.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/namespaces/LocationGlobber.cs
  src/System.Management.Automation/namespaces/PathInfo.cs
  src/System.Management.Automation/namespaces/ProviderDeclarationAttribute.cs
  src/System.Management.Automation/namespaces/RegistryProvider.cs
  src/System.Management.Automation/namespaces/RegistryWrapper.cs
  src/System.Management.Automation/namespaces/SessionStateProviderBase.cs
Labels: CL-CodeCleanup, Review - Needed

#13968 Fix IDE0044: MakeFieldReadonly part 13
  src/System.Management.Automation/utils/CommandDiscoveryExceptions.cs
  src/System.Management.Automation/utils/CryptoUtils.cs
  src/System.Management.Automation/utils/ExecutionExceptions.cs
  src/System.Management.Automation/utils/IObjectWriter.cs
  src/System.Management.Automation/utils/MetadataExceptions.cs
  src/System.Management.Automation/utils/MshArgumentException.cs
  src/System.Management.Automation/utils/MshArgumentNullException.cs
  src/System.Management.Automation/utils/MshArgumentOutOfRangeException.cs
  src/System.Management.Automation/utils/MshInvalidOperationException.cs
  src/System.Management.Automation/utils/MshNotImplementedException.cs
  src/System.Management.Automation/utils/MshNotSupportedException.cs
  src/System.Management.Automation/utils/MshObjectDisposedException.cs
  src/System.Management.Automation/utils/MshTraceSource.cs
  src/System.Management.Automation/utils/ObjectReader.cs
  src/System.Management.Automation/utils/ObjectStream.cs
  src/System.Management.Automation/utils/ObjectWriter.cs
  src/System.Management.Automation/utils/ParameterBinderExceptions.cs
  src/System.Management.Automation/utils/ParserException.cs
  src/System.Management.Automation/utils/PsUtils.cs
  src/System.Management.Automation/utils/ResourceManagerCache.cs
  src/System.Management.Automation/utils/SessionStateExceptions.cs
  src/System.Management.Automation/utils/StructuredTraceSource.cs
  src/System.Management.Automation/utils/Telemetry.cs
  src/System.Management.Automation/utils/Verbs.cs
  src/System.Management.Automation/utils/assert.cs
  src/System.Management.Automation/utils/tracing/EtwActivity.cs
  src/System.Management.Automation/utils/tracing/PSEtwLog.cs
  src/System.Management.Automation/utils/tracing/PSEtwLogProvider.cs
  src/System.Management.Automation/utils/tracing/PSSysLogProvider.cs
  src/System.Management.Automation/utils/tracing/SysLogProvider.cs
Labels: CL-CodeCleanup

#13945 Enable IDE0064: MakeStructFieldsWritable
  .globalconfig
Labels: CL-CodeCleanup

#13928 Enable CA20XX rules with suggestion severity
  .globalconfig
Labels: CL-CodeCleanup

#13870 Enable CA10XX rules with suggestion severity
  .globalconfig
Labels: CL-CodeCleanup

#13867 Enable CA1068: CancellationToken parameters must come last
  .globalconfig
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertToJsonCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs
  src/System.Management.Automation/engine/Modules/GetModuleCommand.cs
  src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs
  src/System.Management.Automation/engine/Modules/RemoteDiscoveryHelper.cs
  test/xUnit/csharp/test_Utils.cs
Labels: CL-CodeCleanup

#13833 Fix RCS1098: Constant values should be on right side of comparisons
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/ExtrinsicMethodInvocationJob.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/MethodInvocationJobBase.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/TimeZoneCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Compare-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetUnique.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator.cs
  src/System.Management.Automation/engine/CommandProcessor.cs
  src/System.Management.Automation/engine/InternalCommands.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Modules/TestModuleManifestCommand.cs
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  src/System.Management.Automation/engine/MshMemberInfo.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/VariablePath.cs
  src/System.Management.Automation/engine/hostifaces/PSDataCollection.cs
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
  src/System.Management.Automation/engine/lang/parserutils.cs
  src/System.Management.Automation/engine/pipeline.cs
  src/System.Management.Automation/engine/regex.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManNativeAPI.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPlugin.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPluginShellSession.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/help/AliasHelpProvider.cs
  src/System.Management.Automation/help/CabinetNativeApi.cs
  src/System.Management.Automation/help/CommandHelpProvider.cs
  src/System.Management.Automation/help/HelpCommands.cs
  src/System.Management.Automation/utils/RuntimeException.cs
Labels: CL-CodeCleanup

#13546 Enable IDE0054: Use compound assignment
  .globalconfig
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/SetClipboardCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddMember.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
  src/Microsoft.PowerShell.Security/security/CmsCommands.cs
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/Microsoft.WSMan.Management/WSManInstance.cs
  src/Microsoft.WSMan.Management/WsManHelper.cs
  src/System.Management.Automation/engine/CmdletParameterBinderController.cs
  src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/MinishellParameterBinderController.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Modules/RemoteDiscoveryHelper.cs
  src/System.Management.Automation/engine/ParameterBinderController.cs
  src/System.Management.Automation/engine/SessionStateVariableAPIs.cs
  src/System.Management.Automation/engine/TypeMetadata.cs
  src/System.Management.Automation/engine/hostifaces/Parameter.cs
  src/System.Management.Automation/engine/interpreter/LightCompiler.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/parser/PSType.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/parser/VariableAnalysis.cs
  src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs
  src/System.Management.Automation/engine/remoting/common/fragmentor.cs
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
  src/System.Management.Automation/engine/runtime/MutableTuple.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/help/HelpProvider.cs
  src/System.Management.Automation/help/UpdatableHelpSystem.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/namespaces/NavigationProviderBase.cs
  src/System.Management.Automation/security/CatalogHelper.cs
  src/System.Management.Automation/utils/ClrFacade.cs
  src/System.Management.Automation/utils/ExtensionMethods.cs
Labels: CL-CodeCleanup

#13538 Fix accessor order
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimCommandBase.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimRegisterCimIndication.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/SetCimInstanceCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetContentCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddMember.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/OutGridViewCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetMember.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetUnique.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Measure-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/OrderObjectBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Select-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/TimeExpressionCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Update-Data.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Update-TypeData.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/TraceExpressionCommand.cs
  src/Microsoft.WSMan.Management/Interop.cs
  src/System.Management.Automation/FormatAndOutput/common/BaseCommand.cs
  src/System.Management.Automation/FormatAndOutput/common/BaseOutputtingCommand.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData.cs
  src/System.Management.Automation/FormatAndOutput/out-console/OutConsole.cs
  src/System.Management.Automation/engine/Attributes.cs
  src/System.Management.Automation/engine/DefaultCommandRuntime.cs
  src/System.Management.Automation/engine/ExecutionContext.cs
  src/System.Management.Automation/engine/InternalCommands.cs
  src/System.Management.Automation/engine/Modules/ExportModuleMemberCommand.cs
  src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Modules/NewModuleCommand.cs
  src/System.Management.Automation/engine/Modules/PSModuleInfo.cs
  src/System.Management.Automation/engine/Modules/RemoveModuleCommand.cs
  src/System.Management.Automation/engine/ParameterBinderBase.cs
  src/System.Management.Automation/engine/hostifaces/History.cs
  src/System.Management.Automation/engine/remoting/client/RemoteRunspacePoolInternal.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspace.cs
  src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs
  src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs
  src/System.Management.Automation/engine/remoting/commands/PushRunspaceCommand.cs
  src/System.Management.Automation/engine/remoting/common/throttlemanager.cs
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/help/HelpCommands.cs
Labels: CL-CodeCleanup, Review - Needed

#13536 Replace magic number with constant in PDH
  src/Microsoft.PowerShell.Commands.Diagnostics/GetCounterCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/PdhHelper.cs
Labels: CL-CodeCleanup

#13338 Use `is not` syntax part 2
  src/Microsoft.Management.UI.Internal/ManagementList/Common/Utilities.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/Controls/ParameterSetControl.xaml.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetContentCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/TraceListenerCommandBase.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader_Views.cs
  src/System.Management.Automation/cimSupport/cmdletization/xml/cmdlets-over-objects.xmlSerializer.autogen.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CommandProcessor.cs
  src/System.Management.Automation/engine/CommandProcessorBase.cs
  src/System.Management.Automation/engine/ExecutionContext.cs
  src/System.Management.Automation/engine/GetCommandCommand.cs
  src/System.Management.Automation/engine/InternalCommands.cs
  src/System.Management.Automation/engine/MinishellParameterBinderController.cs
  src/System.Management.Automation/engine/Modules/PSModuleInfo.cs
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  src/System.Management.Automation/engine/MshObject.cs
  src/System.Management.Automation/engine/Pipe.cs
  src/System.Management.Automation/engine/ScopedItemSearcher.cs
  src/System.Management.Automation/engine/hostifaces/Connection.cs
  src/System.Management.Automation/engine/hostifaces/InternalHost.cs
  src/System.Management.Automation/engine/hostifaces/LocalConnection.cs
  src/System.Management.Automation/engine/hostifaces/pipelinebase.cs
  src/System.Management.Automation/engine/interpreter/CallInstruction.cs
  src/System.Management.Automation/engine/parser/AstVisitor.cs
  src/System.Management.Automation/engine/parser/ConstantValues.cs
  src/System.Management.Automation/engine/parser/DebugViewWriter.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/parser/SemanticChecks.cs
  src/System.Management.Automation/engine/parser/ast.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspace.cs
  src/System.Management.Automation/engine/remoting/commands/ReceiveJob.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/RemoteHostEncoder.cs
  src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  src/System.Management.Automation/help/MamlUtil.cs
  src/System.Management.Automation/utils/PowerShellExecutionHelper.cs
Labels: CL-CodeCleanup

#13454 Fix RCS1033: Remove redundant boolean literal part 1
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/CreateInstanceJob.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/StartSleepCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/XmlCommands.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator.cs
  src/System.Management.Automation/namespaces/RegistryProvider.cs
  src/System.Management.Automation/utils/ObjectStream.cs
  src/System.Management.Automation/utils/PsUtils.cs
Labels: CL-CodeCleanup

#13578 Simplify delegate creation
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionOperations.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/SessionBasedWrapper.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/TerminatingErrorTracker.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimConverter.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Get-PSBreakpoint.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetAliasCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Var.cs
  src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs
  src/System.Management.Automation/engine/ErrorPackage.cs
  src/System.Management.Automation/engine/EventManager.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/InternalCommands.cs
  src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs
  src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs
  src/System.Management.Automation/engine/Modules/NewModuleManifestCommand.cs
  src/System.Management.Automation/engine/Modules/RemoteDiscoveryHelper.cs
  src/System.Management.Automation/engine/Modules/ScriptAnalysis.cs
  src/System.Management.Automation/engine/ParameterSetInfo.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/hostifaces/ConnectionBase.cs
  src/System.Management.Automation/engine/hostifaces/History.cs
  src/System.Management.Automation/engine/hostifaces/LocalConnection.cs
  src/System.Management.Automation/engine/remoting/client/ClientMethodExecutor.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
  src/System.Management.Automation/engine/remoting/client/RemotingProtocol2.cs
  src/System.Management.Automation/engine/remoting/commands/ConnectPSSession.cs
  src/System.Management.Automation/engine/remoting/commands/DisconnectPSSession.cs
  src/System.Management.Automation/engine/remoting/commands/PushRunspaceCommand.cs
  src/System.Management.Automation/engine/remoting/commands/newrunspacecommand.cs
  src/System.Management.Automation/engine/remoting/common/RemoteSessionNamedPipe.cs
  src/System.Management.Automation/engine/remoting/fanin/BaseTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManTransportManager.cs
  src/System.Management.Automation/engine/remoting/server/serverremotesession.cs
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
  src/System.Management.Automation/namespaces/FileSystemContentStream.cs
  src/System.Management.Automation/namespaces/SessionStateProviderBase.cs
Labels: CL-CodeCleanup

#13993 Add validation and dependencies for Ubuntu20.04 distribution to packaging script
  build.psm1
  tools/packaging/packaging.psm1
Labels: BackPort-7.1.x-Approved

#13992 Don't do a shallow checkout
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/checkAzureContainer.yml
  tools/releaseBuild/azureDevOps/templates/compliance.yml
  tools/releaseBuild/azureDevOps/templates/json.yml
  tools/releaseBuild/azureDevOps/templates/mac-file-signing.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/release-GlobalToolTest.yml
  tools/releaseBuild/azureDevOps/templates/release-SDKTests.yml
  tools/releaseBuild/azureDevOps/templates/release-UpdateDepsJson.yml
  tools/releaseBuild/azureDevOps/templates/vpackReleaseJob.yml
  tools/releaseBuild/azureDevOps/templates/windows-package-signing.yml
  tools/releaseBuild/azureDevOps/vpackRelease.yml
Labels: BackPort-7.1.x-Consider

#13937 Fix CA1003: Use generic event handler instances
  .globalconfig
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimResultObserver.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/System.Management.Automation/help/HelpCommands.cs
  src/System.Management.Automation/help/HelpSystem.cs
Labels: CL-CodeCleanup

#13966 Fix IDE0044: MakeFieldReadonly part 11
  src/System.Management.Automation/engine/remoting/client/ClientMethodExecutor.cs
  src/System.Management.Automation/engine/remoting/client/ClientRemotePowerShell.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
  src/System.Management.Automation/engine/remoting/client/Job2.cs
  src/System.Management.Automation/engine/remoting/client/RemoteRunspacePoolInternal.cs
  src/System.Management.Automation/engine/remoting/client/RemotingErrorRecord.cs
  src/System.Management.Automation/engine/remoting/client/RemotingProtocol2.cs
  src/System.Management.Automation/engine/remoting/client/RunspaceRef.cs
  src/System.Management.Automation/engine/remoting/client/clientremotesession.cs
  src/System.Management.Automation/engine/remoting/client/clientremotesessionprotocolstatemachine.cs
  src/System.Management.Automation/engine/remoting/client/remotepipeline.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspace.cs
  src/System.Management.Automation/engine/remoting/client/remotingprotocolimplementation.cs
  src/System.Management.Automation/engine/remoting/commands/ConnectPSSession.cs
  src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs
  src/System.Management.Automation/engine/remoting/commands/DisconnectPSSession.cs
  src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs
  src/System.Management.Automation/engine/remoting/commands/JobRepository.cs
  src/System.Management.Automation/engine/remoting/commands/NewPSSessionConfigurationOptionCommand.cs
  src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs
  src/System.Management.Automation/engine/remoting/commands/ReceivePSSession.cs
  src/System.Management.Automation/engine/remoting/commands/RemoveJob.cs
  src/System.Management.Automation/engine/remoting/commands/getrunspacecommand.cs
  src/System.Management.Automation/engine/remoting/commands/newrunspacecommand.cs
  src/System.Management.Automation/engine/remoting/common/AsyncObject.cs
  src/System.Management.Automation/engine/remoting/common/DispatchTable.cs
  src/System.Management.Automation/engine/remoting/common/Indexer.cs
  src/System.Management.Automation/engine/remoting/common/ObjectRef.cs
  src/System.Management.Automation/engine/remoting/common/RemoteSessionHyperVSocket.cs
  src/System.Management.Automation/engine/remoting/common/RemoteSessionNamedPipe.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/RemoteHost.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/RemoteSessionCapability.cs
  src/System.Management.Automation/engine/remoting/common/fragmentor.cs
  src/System.Management.Automation/engine/remoting/common/throttlemanager.cs
  src/System.Management.Automation/engine/remoting/fanin/BaseTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
  src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/PriorityCollection.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManNativeAPI.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPlugin.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPluginFacade.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPluginShellSession.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPluginTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManTransportManager.cs
  src/System.Management.Automation/engine/remoting/server/ServerMethodExecutor.cs
  src/System.Management.Automation/engine/remoting/server/ServerPowerShellDriver.cs
  src/System.Management.Automation/engine/remoting/server/ServerRemoteHost.cs
  src/System.Management.Automation/engine/remoting/server/ServerRemoteHostRawUserInterface.cs
  src/System.Management.Automation/engine/remoting/server/ServerRemoteHostUserInterface.cs
  src/System.Management.Automation/engine/remoting/server/ServerRemotingProtocol2.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
  src/System.Management.Automation/engine/remoting/server/ServerSteppablePipelineDriver.cs
  src/System.Management.Automation/engine/remoting/server/ServerSteppablePipelineSubscriber.cs
  src/System.Management.Automation/engine/remoting/server/serverremotesession.cs
  src/System.Management.Automation/engine/remoting/server/serverremotesessionstatemachine.cs
  src/System.Management.Automation/engine/remoting/server/serverremotingprotocolimplementation.cs
Labels: CL-CodeCleanup

#14000 Make applicable private Guid fields readonly
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionOperations.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/EventProvider.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/UnsafeNativeMethods.cs
  src/System.Management.Automation/engine/EventManager.cs
  src/System.Management.Automation/engine/hostifaces/PSDataCollection.cs
  src/System.Management.Automation/engine/remoting/client/ClientMethodExecutor.cs
  src/System.Management.Automation/engine/remoting/client/RemotingErrorRecord.cs
  src/System.Management.Automation/engine/remoting/client/RemotingProtocol2.cs
  src/System.Management.Automation/engine/remoting/client/clientremotesessionprotocolstatemachine.cs
  src/System.Management.Automation/engine/remoting/client/remotepipeline.cs
  src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs
  src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs
  src/System.Management.Automation/engine/remoting/server/ServerMethodExecutor.cs
  src/System.Management.Automation/engine/remoting/server/ServerRemoteHost.cs
  src/System.Management.Automation/engine/remoting/server/ServerRemotingProtocol2.cs
  src/System.Management.Automation/help/UpdatableHelpModuleInfo.cs
  src/System.Management.Automation/utils/ObjectStream.cs
Labels: CL-CodeCleanup

#14012 Revert changes to ComInterop
  src/System.Management.Automation/engine/ComInterop/.globalconfig
  src/System.Management.Automation/engine/ComInterop/ComInvokeBinder.cs
  src/System.Management.Automation/engine/ComInterop/ExcepInfo.cs
Labels: CL-CodeCleanup

#13962 Enable IDE0040: AddAccessibilityModifiers
  .globalconfig
  src/System.Management.Automation/engine/PSConfiguration.cs
  src/System.Management.Automation/utils/tracing/SysLogProvider.cs
  test/tools/TestExe/TestExe.cs
  test/tools/TestService/Program.cs
Labels: CL-CodeCleanup

#14014 Remove unnecessary usings part 1
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimAsyncOperation.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimBaseAction.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetAssociatedInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetCimClass.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimInvokeCimMethod.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimRemoveCimInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimResultObserver.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionOperations.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSetCimInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CmdletOperation.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimAssociatedInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/Utils.cs
Labels: CL-CodeCleanup

#14017 Remove unnecessary usings part 2
  src/Microsoft.PowerShell.Commands.Diagnostics/CommonUtils.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/CoreCLR/Stubs.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/CounterSample.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/CounterSet.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/GetCounterCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/GetEventCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/NewWinEventCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/PdhHelper.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/PdhSafeHandle.cs
Labels: CL-CodeCleanup

#14021 Remove unnecessary usings part 3
  src/Microsoft.PowerShell.Commands.Management/commands/management/AddContentCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ClearContentCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ClearPropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ClearRecycleBinCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/CombinePathCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ConvertPathCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/CopyPropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetChildrenCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetPropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/MovePropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/NewPropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/PassThroughContentCommandBase.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/PassThroughPropertyCommandBase.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/PingPathCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/PropertyCommandBase.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/RemovePropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/RenamePropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ResolvePathCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/SetContentCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/SetPropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/WriteContentCommandBase.cs
Labels: CL-CodeCleanup

#13808 Fix nullable usage on displayDescriptionData_Table.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Table.cs
Labels: CL-CodeCleanup, Hacktoberfest-Accepted, Review - Needed

#13805 Fix nullable usage on displayDescriptionData_Wide
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Wide.cs
Labels: CL-CodeCleanup, Hacktoberfest-Accepted, Review - Needed

#13923 Enable CA1827: Do not use Count() or LongCount() when Any() can be used
  .globalconfig
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
Labels: CL-CodeCleanup, Review - Needed

#13925 Enable CA1829: Use Length/Count property instead of Count()
  .globalconfig
  test/tools/WebListener/Program.cs
Labels: CL-CodeCleanup

#14010 Migrate 3rd party signing to ESRP
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
Labels: BackPort-7.0.x-Consider, BackPort-7.1.x-Consider, CL-BuildPackaging

#14038 Remove workarounds for .NET 5 RTM builds
  build.psm1
  nuget.config
  test/hosting/NuGet.Config
  tools/releaseBuild/azureDevOps/templates/nuget.yml
Labels: CL-BuildPackaging

#14070 Fix links to LTS versions for Windows in README.md
  README.md
Labels: CL-Docs

#14066 Remove unnecessary usings part 7
  src/Microsoft.PowerShell.MarkdownRender/CodeInlineRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/EmphasisInlineRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/FencedCodeBlockRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/HeaderBlockRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/LeafInlineRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/LineBreakRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/LinkInlineRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/ListBlockRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/ListItemBlockRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/MarkdownConverter.cs
  src/Microsoft.PowerShell.MarkdownRender/ParagraphBlockRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/QuoteBlockRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/VT100EscapeSequences.cs
  src/Microsoft.PowerShell.MarkdownRender/VT100ObjectRenderer.cs
  src/Microsoft.PowerShell.MarkdownRender/VT100Renderer.cs
Labels: CL-CodeCleanup

#14050 Remove unnecessary usings part 5
  src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/ComInterfaces.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostRawUserInterface.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostTranscript.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfacePromptForChoice.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfaceSecurity.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleTextWriter.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/Executor.cs
Labels: CL-CodeCleanup

#14063 Enable CA1837: Use 'Environment.ProcessId'
  .globalconfig
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/System.Management.Automation/engine/InformationRecord.cs
  src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs
  src/System.Management.Automation/engine/remoting/commands/EnterPSHostProcessCommand.cs
  src/System.Management.Automation/engine/remoting/common/RemoteSessionNamedPipe.cs
  src/System.Management.Automation/utils/PsUtils.cs
Labels: CL-CodeCleanup

#14068 Enable CA2207: Initialize value type static fields inline
  .globalconfig
Labels: CL-CodeCleanup

#14044 Enable IDE0062: MakeLocalFunctionStatic
  .globalconfig
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/System.Management.Automation/engine/DataStoreAdapterProvider.cs
  src/System.Management.Automation/engine/parser/ast.cs
Labels: CL-CodeCleanup

#13994 Fix RCS1049: Simplify boolean comparison
  src/System.Management.Automation/engine/ComInterop/ComEventSinksContainer.cs
  src/System.Management.Automation/engine/ComInterop/IDispatchComObject.cs
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/engine/CommandMetadata.cs
  src/System.Management.Automation/engine/CommandProcessor.cs
  src/System.Management.Automation/engine/CoreAdapter.cs
  src/System.Management.Automation/engine/ErrorPackage.cs
  src/System.Management.Automation/engine/GetCommandCommand.cs
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/SessionStateContainer.cs
  src/System.Management.Automation/engine/TypeTable.cs
  src/System.Management.Automation/engine/hostifaces/ConnectionBase.cs
  src/System.Management.Automation/engine/hostifaces/History.cs
  src/System.Management.Automation/engine/hostifaces/InternalHostUserInterface.cs
  src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs
  src/System.Management.Automation/engine/hostifaces/PSDataCollection.cs
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
  src/System.Management.Automation/engine/hostifaces/pipelinebase.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
  src/System.Management.Automation/engine/remoting/client/JobManager.cs
  src/System.Management.Automation/engine/remoting/client/PowerShellStreams.cs
  src/System.Management.Automation/engine/remoting/client/RemoteRunspacePoolInternal.cs
  src/System.Management.Automation/engine/remoting/client/clientremotesessionprotocolstatemachine.cs
  src/System.Management.Automation/engine/remoting/client/remotepipeline.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspace.cs
  src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs
  src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs
  src/System.Management.Automation/engine/remoting/common/AsyncObject.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/utils/tracing/SysLogProvider.cs
Labels: CL-CodeCleanup

#13324 Reinstate Test-Connection tests
  test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1
Labels: CL-Test, Review - Needed, WG-Quality-Test

#13176 Update hyperlink for DefaultPromptFunctionText
  src/System.Management.Automation/engine/InitialSessionState.cs
  test/powershell/engine/Help/assets/HelpURI/V2Cmdlets.csv
Labels: CL-Engine

#13496 Write better error message if config file is broken
  src/System.Management.Automation/engine/PSConfiguration.cs
  src/System.Management.Automation/resources/PSConfigurationStrings.resx
  test/xUnit/csharp/test_PSConfiguration.cs
Labels: CL-General, Review - Needed

#14094 Fix PriorityAttribute name
  test/xUnit/csharp/test_PSConfiguration.cs
Labels: CL-CodeCleanup

#14023 Remove unnecessary usings part 4
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertFrom-SddlString.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertFromMarkdownCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertTo-Html.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CustomSerialization.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/ExpressionColumnInfo.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/common/WriteFormatDataCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-wide/Format-Wide.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-file/Out-File.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-string/Out-String.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHostCmdlet.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetMember.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetVerbCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Group-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MarkdownOptionCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Measure-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/New-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/NewAliasCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/NewTemporaryFileCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/PSBreakpointAccessorCommandBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ReadConsoleCmdlet.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/RegisterObjectEventCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/RemoveAliasCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/SetAliasCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ShowMarkdownCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/UnblockFile.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/UtilityCommon.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Var.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/BasicHtmlWebResponseObject.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/ContentHelper.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WriteAliasCommandBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WriteConsoleCmdlet.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WriteProgressCmdlet.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/MshHostTraceListener.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/TraceCommandBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/TraceExpressionCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/TraceListenerCommandBase.cs
Labels: CL-CodeCleanup

#14042 Enable IDE0082: ConvertTypeOfToNameOf
  .globalconfig
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/System.Management.Automation/engine/Attributes.cs
  src/System.Management.Automation/engine/CmdletInfo.cs
  src/System.Management.Automation/engine/CommandMetadata.cs
  src/System.Management.Automation/engine/CompiledCommandParameter.cs
  src/System.Management.Automation/engine/MshObjectTypeDescriptor.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/hostifaces/InternalHostUserInterface.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspace.cs
  test/xUnit/csharp/test_AstDefaultVisit.cs
Labels: CL-CodeCleanup

#14041 Enable IDE0041: UseIsNullCheck
  .globalconfig
  src/System.Management.Automation/engine/MshMemberInfo.cs
  src/System.Management.Automation/engine/PSVersionInfo.cs
Labels: CL-CodeCleanup

#14107 Revert "Update hyperlink for `DefaultPromptFunctionText` (#13176)"
  src/System.Management.Automation/engine/InitialSessionState.cs
  test/powershell/engine/Help/assets/HelpURI/V2Cmdlets.csv
Labels: CL-NotInBuild

#13963 Add StyleCop.Analyzers package
  .globalconfig
  Analyzers.props
  PowerShell.Common.props
  test/Test.Common.props
Labels: CL-CodeCleanup

#14104 Update `README` and `metadata.json` for 7.2.0-preview.1 release
  README.md
  tools/metadata.json
Labels: CL-BuildPackaging

#14135 Revert "Change Nullable usage"
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
Labels: CL-NotInBuild

#14134 Revert "Fix nullable usage on authenticode"
  src/System.Management.Automation/security/Authenticode.cs
Labels: CL-NotInBuild

#14129 Fix a typo in the `Get-ChangeLog` function
  tools/releaseTools.psm1
Labels: CL-BuildPackaging

#14092 Fix whitespace issues
  src/System.Management.Automation/engine/ParameterSetInfo.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
  src/System.Management.Automation/namespaces/RegistryProvider.cs
  src/System.Management.Automation/security/SecurityManager.cs
Labels: CL-CodeCleanup

#14113 Expanding where alias to Where-Object in Reset-PWSHSystemPath.ps1.
  tools/windows/Reset-PWSHSystemPath.ps1
Labels: CL-CodeCleanup

#14130 Enable SA1007: Operator keyword should be followed by space
  .globalconfig
Labels: CL-CodeCleanup

#14097 Enable CA1000: Do not declare static members on generic types
  .globalconfig
Labels: CL-CodeCleanup

#14117 Enable CA1065: Do not raise exceptions in unexpected locations
  .globalconfig
  src/System.Management.Automation/engine/Attributes.cs
  src/System.Management.Automation/engine/MshMemberInfo.cs
Labels: CL-CodeCleanup

#13548 Enable IDE0031: Null check can be simplified
  .globalconfig
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimIndicationWatcher.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/CimJobException.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/ExtrinsicMethodInvocationJob.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetComputerInfoCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/OrderObjectBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/ContentHelper.Common.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData.cs
  src/System.Management.Automation/engine/ArgumentTypeConverterAttribute.cs
  src/System.Management.Automation/engine/CmdletParameterBinderController.cs
  src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs
  src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs
  src/System.Management.Automation/engine/CommandProcessor.cs
  src/System.Management.Automation/engine/EventManager.cs
  src/System.Management.Automation/engine/ExternalScriptInfo.cs
  src/System.Management.Automation/engine/Modules/RemoteDiscoveryHelper.cs
  src/System.Management.Automation/engine/ParameterBinderBase.cs
  src/System.Management.Automation/engine/PseudoParameterBinder.cs
  src/System.Management.Automation/engine/SessionStateScope.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/hostifaces/Connection.cs
  src/System.Management.Automation/engine/hostifaces/History.cs
  src/System.Management.Automation/engine/interpreter/InstructionList.cs
  src/System.Management.Automation/engine/interpreter/LightCompiler.cs
  src/System.Management.Automation/engine/lang/parserutils.cs
  src/System.Management.Automation/engine/lang/scriptblock.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/parser/SemanticChecks.cs
  src/System.Management.Automation/engine/parser/TypeResolver.cs
  src/System.Management.Automation/engine/parser/ast.cs
  src/System.Management.Automation/engine/remoting/client/ClientRemotePowerShell.cs
  src/System.Management.Automation/engine/remoting/client/RemotingProtocol2.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspace.cs
  src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs
  src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
  src/System.Management.Automation/engine/remoting/server/ServerRemoteHost.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  src/System.Management.Automation/engine/runtime/Operations/ClassOps.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/help/UpdateHelpCommand.cs
  src/System.Management.Automation/utils/ExecutionExceptions.cs
Labels: CL-CodeCleanup, Review - Needed

#14137 Enable SA1516: Elements should be separated by blank line
  .globalconfig
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetComputerInfoCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-hex/Format-Hex.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Tee-Object.cs
  src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/ComInterfaces.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/AssemblyInfo.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/UnsafeNativeMethods.cs
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatMsgCtxManager.cs
  src/System.Management.Automation/engine/Attributes.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CommandProcessorBase.cs
  src/System.Management.Automation/engine/CoreAdapter.cs
  src/System.Management.Automation/engine/EnumExpressionEvaluator.cs
  src/System.Management.Automation/engine/ExecutionContext.cs
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/Modules/ScriptAnalysis.cs
  src/System.Management.Automation/engine/MshObject.cs
  src/System.Management.Automation/engine/MshObjectTypeDescriptor.cs
  src/System.Management.Automation/engine/PSConfiguration.cs
  src/System.Management.Automation/engine/Subsystem/SubsystemInfo.cs
  src/System.Management.Automation/engine/debugger/Breakpoint.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/hostifaces/Connection.cs
  src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs
  src/System.Management.Automation/engine/hostifaces/PowerShellProcessInstance.cs
  src/System.Management.Automation/engine/hostifaces/RunspacePool.cs
  src/System.Management.Automation/engine/interpreter/InstructionFactory.cs
  src/System.Management.Automation/engine/lang/scriptblock.cs
  src/System.Management.Automation/engine/parser/ConstantValues.cs
  src/System.Management.Automation/engine/parser/SymbolResolver.cs
  src/System.Management.Automation/engine/parser/VariableAnalysis.cs
  src/System.Management.Automation/engine/parser/ast.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
  src/System.Management.Automation/engine/remoting/client/RemotingProtocol2.cs
  src/System.Management.Automation/engine/remoting/client/clientremotesessionprotocolstatemachine.cs
  src/System.Management.Automation/engine/remoting/common/fragmentor.cs
  src/System.Management.Automation/engine/remoting/common/psstreamobject.cs
  src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPluginTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManTransportManager.cs
  src/System.Management.Automation/engine/remoting/server/ServerRemotingProtocol2.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
  src/System.Management.Automation/engine/remoting/server/ServerSteppablePipelineSubscriber.cs
  src/System.Management.Automation/engine/remoting/server/serverremotesessionstatemachine.cs
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
  src/System.Management.Automation/engine/runtime/MutableTuple.cs
  src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs
  src/System.Management.Automation/help/HelpSystem.cs
  src/System.Management.Automation/namespaces/RegistryWrapper.cs
  src/System.Management.Automation/utils/HostInterfacesExceptions.cs
  test/xUnit/csharp/test_CommandLineParser.cs
Labels: CL-CodeCleanup

#14136 Enable SA1507: Code should not contain multiple blank lines in a row
  .globalconfig
  src/System.Management.Automation/engine/TypeTable_Types_Ps1Xml.cs
  src/powershell/Program.cs
  test/tools/WebListener/Controllers/DosController.cs
Labels: CL-CodeCleanup

#14132 Enable SA1131: Use readable conditions
  .globalconfig
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/SessionBasedWrapper.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/ExtrinsicMethodInvocationJob.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/TimeZoneCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Compare-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebResponseObject.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/StreamHelper.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
  src/System.Management.Automation/cimSupport/cmdletization/MethodInvocationInfo.cs
  src/System.Management.Automation/cimSupport/cmdletization/ScriptWriter.cs
  src/System.Management.Automation/cimSupport/cmdletization/cim/WildcardPatternToCimQueryParser.cs
  src/System.Management.Automation/cimSupport/other/ciminstancetypeadapter.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CommandMetadata.cs
  src/System.Management.Automation/engine/CoreAdapter.cs
  src/System.Management.Automation/engine/ErrorPackage.cs
  src/System.Management.Automation/engine/ExecutionContext.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/Modules/RemoteDiscoveryHelper.cs
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/PSConfiguration.cs
  src/System.Management.Automation/engine/TypeMetadata.cs
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/hostifaces/AsyncResult.cs
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
  src/System.Management.Automation/engine/remoting/client/ThrottlingJob.cs
  src/System.Management.Automation/engine/remoting/commands/newrunspacecommand.cs
  src/System.Management.Automation/engine/remoting/fanin/BaseTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManNativeAPI.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPlugin.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPluginFacade.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPluginShellSession.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPluginTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManTransportManager.cs
  src/System.Management.Automation/engine/remoting/server/OutOfProcServerMediator.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/help/CabinetNativeApi.cs
  src/System.Management.Automation/security/nativeMethods.cs
  src/System.Management.Automation/utils/CommandDiscoveryExceptions.cs
  src/System.Management.Automation/utils/ObjectStream.cs
  src/System.Management.Automation/utils/SessionStateExceptions.cs
Labels: CL-CodeCleanup

#14131 Enable SA1517: Code should not contain blank lines at start of file
  .globalconfig
Labels: CL-CodeCleanup

#14027 Fix IDE0090: Simplify new expression part 1
  src/Microsoft.PowerShell.Commands.Diagnostics/CommonUtils.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/CounterSet.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/GetCounterCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/GetEventCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/NewWinEventCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/PdhHelper.cs
Labels: CL-CodeCleanup

#14199 Remove useless comments
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
Labels: CL-CodeCleanup

#14145 Update markdown test packages with security fixes
  test/common/markdown/package.json
  test/common/markdown/yarn.lock
Labels: CL-Test

#14207 Code performance fixes follow-up
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Subsystem/SubsystemManager.cs
  src/System.Management.Automation/engine/parser/AstVisitor.cs
  src/System.Management.Automation/utils/EncodingUtils.cs
Labels: CL-CodeCleanup

#13964 Enable SA1106: Code should not contain empty statements
  .globalconfig
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimSessionOptionCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/PdhHelper.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Get-PSBreakpoint.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/UnsafeNativeMethods.cs
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/Microsoft.WSMan.Management/Interop.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/XmlLoaderBase.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayResourceManagerCache.cs
  src/System.Management.Automation/engine/ComInterop/ComEventDesc.cs
  src/System.Management.Automation/engine/ExecutionContext.cs
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/engine/MinishellParameterBinderController.cs
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/Pipe.cs
  src/System.Management.Automation/engine/SerializationStrings.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/hostifaces/Connection.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
  src/System.Management.Automation/engine/regex.cs
  src/System.Management.Automation/engine/remoting/client/ClientRemotePowerShell.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
  src/System.Management.Automation/engine/remoting/fanin/BaseTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManNativeAPI.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/help/CabinetNativeApi.cs
  src/System.Management.Automation/logging/MshLog.cs
  src/System.Management.Automation/namespaces/FileSystemContentStream.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/security/MshSignature.cs
  src/System.Management.Automation/security/SecuritySupport.cs
  src/System.Management.Automation/security/nativeMethods.cs
  src/System.Management.Automation/utils/PlatformInvokes.cs
Labels: CL-CodeCleanup

#14201 Fix IDE0090: Simplify new expression part 3
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimAsyncOperation.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimCommandBase.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetAssociatedInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetCimClass.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimInvokeCimMethod.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimNewCimInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimRemoveCimInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimResultObserver.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionOperations.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSetCimInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteError.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteProgress.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CmdletOperation.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimAssociatedInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimClassCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/InvokeCimMethodCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimSessionOptionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RegisterCimIndicationCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RemoveCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RemoveCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/SetCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/Utils.cs
Labels: CL-CodeCleanup

#14197 Enable SA1002: Semicolons should be spaced correctly
  .globalconfig
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/Microsoft.WSMan.Management/WsManHelper.cs
  src/System.Management.Automation/engine/hostifaces/History.cs
  src/System.Management.Automation/engine/interpreter/LightDelegateCreator.cs
  src/System.Management.Automation/engine/remoting/client/RemoteRunspacePoolInternal.cs
  src/System.Management.Automation/engine/remoting/server/serverremotesession.cs
  test/tools/WebListener/Program.cs
Labels: CL-CodeCleanup

#14194 Wrap and name GetListOfFilesFromData arguments
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
Labels: CL-CodeCleanup

#14193 Wrap and name LoadBinaryModule arguments
  src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
Labels: CL-CodeCleanup

#14089 Enable CA2216: Disposable types should declare finalizer
  .globalconfig
Labels: CL-CodeCleanup

#14142 Fix SA1642 for Microsoft.PowerShell.Commands.Utility
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConsoleColorCmdlet.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CustomSerialization.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/OutGridViewCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/OutWindowProxy.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-list/Format-List.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-object/Format-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-table/Format-Table.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-wide/Format-Wide.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-file/Out-File.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-printer/Out-Printer.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-printer/PrinterLineOutput.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-string/Out-String.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetMember.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Measure-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ObjectCommandComparer.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/OrderObjectBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ReadConsoleCmdlet.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Select-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ShowCommand/ShowCommandCommandInfo.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ShowCommand/ShowCommandModuleInfo.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ShowCommand/ShowCommandParameterInfo.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ShowCommand/ShowCommandParameterSetInfo.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ShowCommand/ShowCommandParameterType.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/BasicHtmlWebResponseObject.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebResponseObject.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/InvokeWebRequestCommand.CoreClr.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/FormObject.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/StreamHelper.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/WebRequestSession.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Write.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/MshHostTraceListener.cs
Labels: CL-CodeCleanup

#14052 Enable SA1006: Preprocessor keywords should not be preceded by space
  .globalconfig
  src/Microsoft.WSMan.Management/WSManInstance.cs
Labels: CL-CodeCleanup

#14051 Enable SA1212: Property accessors should follow order
  .globalconfig
  src/System.Management.Automation/engine/remoting/common/throttlemanager.cs
Labels: CL-General

#13940 Enable CA1012: Abstract types should not have public constructors
  .globalconfig
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimAsyncOperation.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimBaseAction.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimResultObserver.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/interpreter/ControlFlowInstructions.cs
  src/System.Management.Automation/utils/ObjectReader.cs
Labels: CL-General

#14128 Avoid creating instances of the generated delegate helper class every time `ReplaceOperatorImpl` is called
  src/System.Management.Automation/engine/lang/parserutils.cs
Labels: CL-Performance

#14223 Fix various xml documentation issues
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Measure-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/System.Management.Automation/engine/hostifaces/History.cs
Labels: CL-CodeCleanup

#14218 Fix SA1122: Use string.Empty for empty strings
  .globalconfig
  src/Microsoft.PowerShell.Commands.Management/commands/management/ComputerUnix.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/System.Management.Automation/engine/CommandCompletion/ExtensibleCompletion.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/EncodeAndDecode.cs
  src/powershell/Program.cs
Labels: CL-CodeCleanup

#14230 Mark private members as static part 7
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/Microsoft.WSMan.Management/CurrentConfigurations.cs
Labels: CL-CodeCleanup

#14210 Move Linux to Esrp signing
  tools/releaseBuild/azureDevOps/templates/insert-nuget-config-azfeed.yml
  tools/releaseBuild/azureDevOps/templates/linux.yml
Labels: BackPort-7.0.x-Consider, BackPort-7.1.x-Consider

#14246 Remove incorrectly implemented finalizer
  src/System.Management.Automation/utils/CryptoUtils.cs
Labels: CL-CodeCleanup

#14074 Enable CA1816: Dispose methods should call SuppressFinalize
  .globalconfig
  src/Microsoft.PowerShell.Commands.Management/commands/management/ComputerUnix.cs
  test/xUnit/csharp/test_FileSystemProvider.cs
  test/xUnit/csharp/test_PSConfiguration.cs
Labels: CL-CodeCleanup

#14073 Enable CA2211: Non-constant fields should not be visible
  .globalconfig
  src/System.Management.Automation/engine/remoting/fanin/PSSessionConfigurationData.cs
Labels: CL-CodeCleanup

#14220 Use `see` keyword in documentation
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/SessionBasedWrapper.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimQuery.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimWrapper.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/BasicHtmlWebResponseObject.Common.cs
  src/System.Management.Automation/FormatAndOutput/common/Utilities/Mshexpression.cs
  src/System.Management.Automation/cimSupport/cmdletization/MethodInvocationInfo.cs
  src/System.Management.Automation/cimSupport/cmdletization/MethodParameter.cs
  src/System.Management.Automation/cimSupport/cmdletization/ObjectModelWrapper.cs
  src/System.Management.Automation/cimSupport/cmdletization/QueryBuilder.cs
  src/System.Management.Automation/engine/CommandProcessor.cs
  src/System.Management.Automation/engine/CommandProcessorBase.cs
  src/System.Management.Automation/engine/FunctionInfo.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/MshCmdlet.cs
  src/System.Management.Automation/engine/MshMemberInfo.cs
  src/System.Management.Automation/engine/ScriptCommandProcessor.cs
  src/System.Management.Automation/engine/ThirdPartyAdapter.cs
  src/System.Management.Automation/engine/lang/scriptblock.cs
  src/System.Management.Automation/engine/parser/ast.cs
  src/System.Management.Automation/engine/remoting/client/ThrottlingJob.cs
  src/System.Management.Automation/engine/remoting/commands/NewPSSessionOptionCommand.cs
  src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/EncodeAndDecode.cs
  src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/utils/PathUtils.cs
Labels: CL-CodeCleanup

#14224 Mark private members as static part 1
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetAssociatedInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetCimClass.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimInvokeCimMethod.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimNewCimInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionOperations.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
Labels: CL-CodeCleanup

#14225 Mark private members as static part 2
  src/Microsoft.PowerShell.Commands.Diagnostics/GetEventCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/PdhHelper.cs
Labels: CL-CodeCleanup

#14226 Mark private members as static part 3
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/SessionBasedWrapper.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ClearRecycleBinCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetComputerInfoCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs
Labels: CL-CodeCleanup

#14227 Mark private members as static part 4
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertFrom-SddlString.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertTo-Html.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CustomSerialization.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/DebugRunspaceCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/TableView.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Get-PSBreakpoint.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Join-String.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Measure-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/UnblockFile.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Update-TypeData.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/BasicHtmlWebResponseObject.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebResponseObject.Common.cs
Labels: CL-CodeCleanup

#14228 Mark private members as static part 5
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostRawUserInterface.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/Executor.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/PendingProgress.cs
Labels: CL-CodeCleanup

#14229 Mark private members as static part 6
  src/Microsoft.PowerShell.Security/security/AclCommands.cs
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
Labels: CL-CodeCleanup

#14233 Mark private members as static part 8
  src/System.Management.Automation/engine/remoting/client/ClientMethodExecutor.cs
  src/System.Management.Automation/engine/remoting/client/ClientRemotePowerShell.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
  src/System.Management.Automation/engine/remoting/client/JobManager.cs
  src/System.Management.Automation/engine/remoting/client/RunspaceRef.cs
  src/System.Management.Automation/engine/remoting/client/clientremotesessionprotocolstatemachine.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspaceinfo.cs
  src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs
  src/System.Management.Automation/engine/remoting/commands/DebugJob.cs
  src/System.Management.Automation/engine/remoting/commands/DisconnectPSSession.cs
  src/System.Management.Automation/engine/remoting/commands/EnterPSHostProcessCommand.cs
  src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs
  src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs
  src/System.Management.Automation/engine/remoting/commands/PushRunspaceCommand.cs
  src/System.Management.Automation/engine/remoting/commands/ReceivePSSession.cs
  src/System.Management.Automation/engine/remoting/commands/RemoveJob.cs
  src/System.Management.Automation/engine/remoting/common/Indexer.cs
  src/System.Management.Automation/engine/remoting/common/RemoteSessionNamedPipe.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/RemoteHost.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/RemotingDataObject.cs
  src/System.Management.Automation/engine/remoting/fanin/BaseTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPlugin.cs
  src/System.Management.Automation/engine/remoting/server/serverremotesessionstatemachine.cs
Labels: CL-CodeCleanup

#14243 Fix IDE0032: UseAutoProperty part 1
  src/Microsoft.WSMan.Runtime/WSManSessionOption.cs
Labels: CL-CodeCleanup

#14244 Fix IDE0032: UseAutoProperty part 2
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimBaseAction.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimCommandBase.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetCimClass.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimIndicationWatcher.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimInvokeCimMethod.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimPromptUser.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimRegisterCimIndication.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimResultObserver.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionOperations.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSetCimInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteError.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteMessage.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteProgress.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteResultObject.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimAssociatedInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimClassCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/InvokeCimMethodCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimSessionOptionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RegisterCimIndicationCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RemoveCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/SetCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/Utils.cs
Labels: CL-CodeCleanup

#14248 Remove unnecessary finalizers
  src/Microsoft.PowerShell.Commands.Management/commands/management/ContentCommandBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/OutGridViewCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ShowCommand/ShowCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Tee-Object.cs
  src/System.Management.Automation/engine/CommandProcessorBase.cs
  src/System.Management.Automation/engine/EventManager.cs
  src/System.Management.Automation/engine/lang/scriptblock.cs
  src/System.Management.Automation/engine/pipeline.cs
Labels: CL-CodeCleanup

#13689 Fixing Formatting in Reset-PWSHSystemPath.ps1
  tools/windows/Reset-PWSHSystemPath.ps1
Labels: CL-Tools

#13396 Enable IDE0074: Use coalesce compound assignment
  .globalconfig
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/SessionBasedWrapper.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimWrapper.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/engine/Attributes.cs
  src/System.Management.Automation/engine/CmdletInfo.cs
  src/System.Management.Automation/engine/CmdletParameterBinderController.cs
  src/System.Management.Automation/engine/CommandBase.cs
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/engine/CommandInfo.cs
  src/System.Management.Automation/engine/EngineIntrinsics.cs
  src/System.Management.Automation/engine/ErrorPackage.cs
  src/System.Management.Automation/engine/ExecutionContext.cs
  src/System.Management.Automation/engine/ExternalScriptInfo.cs
  src/System.Management.Automation/engine/FunctionInfo.cs
  src/System.Management.Automation/engine/InformationRecord.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/InvocationInfo.cs
  src/System.Management.Automation/engine/Modules/PSModuleInfo.cs
  src/System.Management.Automation/engine/MshCmdlet.cs
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  src/System.Management.Automation/engine/ParameterBinderBase.cs
  src/System.Management.Automation/engine/PathInterfaces.cs
  src/System.Management.Automation/engine/ReflectionParameterBinder.cs
  src/System.Management.Automation/engine/ScriptInfo.cs
  src/System.Management.Automation/engine/SessionState.cs
  src/System.Management.Automation/engine/SessionStatePublic.cs
  src/System.Management.Automation/engine/SessionStateScope.cs
  src/System.Management.Automation/engine/ShellVariable.cs
  src/System.Management.Automation/engine/hostifaces/ConnectionBase.cs
  src/System.Management.Automation/engine/hostifaces/FieldDescription.cs
  src/System.Management.Automation/engine/interpreter/AddInstruction.cs
  src/System.Management.Automation/engine/interpreter/ControlFlowInstructions.cs
  src/System.Management.Automation/engine/interpreter/DivInstruction.cs
  src/System.Management.Automation/engine/interpreter/EqualInstruction.cs
  src/System.Management.Automation/engine/interpreter/GreaterThanInstruction.cs
  src/System.Management.Automation/engine/interpreter/InstructionFactory.cs
  src/System.Management.Automation/engine/interpreter/InstructionList.cs
  src/System.Management.Automation/engine/interpreter/InterpretedFrame.cs
  src/System.Management.Automation/engine/interpreter/LessThanInstruction.cs
  src/System.Management.Automation/engine/interpreter/MulInstruction.cs
  src/System.Management.Automation/engine/interpreter/NotEqualInstruction.cs
  src/System.Management.Automation/engine/interpreter/SubInstruction.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
  src/System.Management.Automation/engine/remoting/client/JobSourceAdapter.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspace.cs
  src/System.Management.Automation/engine/remoting/commands/DisconnectPSSession.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/logging/MshLog.cs
  src/System.Management.Automation/utils/ExecutionExceptions.cs
  src/System.Management.Automation/utils/ParameterBinderExceptions.cs
  src/System.Management.Automation/utils/StructuredTraceSource.cs
Labels: CL-CodeCleanup, Review - Needed, size/XL

#14231 Use consistent spacing in xml documentation tags
  src/Microsoft.PowerShell.Commands.Diagnostics/CoreCLR/Stubs.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/SessionBasedWrapper.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Join-String.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataManager.cs
  src/System.Management.Automation/cimSupport/other/ciminstancetypeadapter.cs
  src/System.Management.Automation/engine/SessionStateContainer.cs
  src/System.Management.Automation/engine/SessionStateScope.cs
  src/System.Management.Automation/engine/SessionStateVariableAPIs.cs
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  src/System.Management.Automation/engine/regex.cs
  src/System.Management.Automation/engine/remoting/client/ThrottlingJob.cs
  src/System.Management.Automation/engine/remoting/server/serverremotesession.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/namespaces/ContainerProviderBase.cs
  src/System.Management.Automation/namespaces/CoreCommandContext.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/namespaces/LocationGlobber.cs
  src/System.Management.Automation/namespaces/RegistrySecurity.cs
  src/System.Management.Automation/utils/tracing/EtwActivityReverter.cs
  src/System.Management.Automation/utils/tracing/EtwEventCorrelator.cs
Labels: CL-CodeCleanup

#14255 Fix IDE0090: Simplify new expression part 4.1
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/HeaderInfo.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/OutGridViewCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/TableView.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/common/WriteFormatDataCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-hex/Format-Hex.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-object/Format-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-wide/Format-Wide.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-file/Out-File.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-printer/Out-Printer.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-printer/PrinterLineOutput.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-string/Out-String.cs
Labels: CL-CodeCleanup

#14249 Use xml documentation child blocks correctly
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/SetCimInstanceCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertToJsonCommand.cs
Labels: CL-CodeCleanup

#14258 Fix IDE0090: Simplify new expression part 4.4
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddMember.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Compare-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConsoleColorCmdlet.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertFrom-SddlString.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertFrom-StringData.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertFromMarkdownCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertTo-Html.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Csv.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CustomSerialization.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/DebugRunspaceCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ExportAliasCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Get-PSBreakpoint.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetAliasCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetDateCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetEventCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetEventSubscriberCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetMember.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommand.cs
Labels: CL-CodeCleanup

#14236 Enable SA1643: Destructor summary documentation
  .globalconfig
  src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/PropVariant.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/System.Management.Automation/engine/EventManager.cs
  src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs
  src/System.Management.Automation/engine/remoting/fanin/BaseTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManNativeAPI.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPluginFacade.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPluginShellSession.cs
  src/System.Management.Automation/help/CabinetNativeApi.cs
Labels: CL-CodeCleanup

#14200 Fix IDE0090: Simplify new expression part 2
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/CimJobException.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/TerminatingErrorTracker.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimChildJobBase.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimCmdletInvocationContext.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimConverter.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimOperationOptionsHelper.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimQuery.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimWrapper.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/clientSideQuery.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/AddContentCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/CIMHelper.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ClearPropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ClearRecycleBinCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Clipboard.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ContentCommandBase.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetComputerInfoCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetContentCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Hotfix.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ParsePathCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/SetClipboardCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/SetContentCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/TimeZoneCommands.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/WriteContentCommandBase.cs
Labels: CL-CodeCleanup

#14256 Fix IDE0090: Simplify new expression part 4.2
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/BasicHtmlWebResponseObject.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/ContentHelper.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertFromJsonCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertToJsonCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/PSUserAgent.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/StreamHelper.cs
Labels: CL-CodeCleanup

#14257 Fix IDE0090: Simplify new expression part 4.3
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/MshHostTraceListener.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/TraceCommandBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/TraceExpressionCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/TraceListenerCommandBase.cs
Labels: CL-CodeCleanup

#14259 Fix IDE0090: Simplify new expression part 4.5
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRunspaceCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetVerbCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Group-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Import-LocalizedData.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImportAliasCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Join-String.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MarkdownOptionCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Measure-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/New-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/NewAliasCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/NewTemporaryFileCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ObjectCommandComparer.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/OrderObjectBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/PSBreakpointUpdaterCommandBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ReadConsoleCmdlet.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/RegisterPSEventCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/RemoveAliasCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/RemoveEventCommand.cs
Labels: CL-CodeCleanup

#14260 Fix IDE0090: Simplify new expression part 4.6
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Select-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Send-MailMessage.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Set-PSBreakpoint.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/SetAliasCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/SetDateCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ShowCommand/ShowCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ShowMarkdownCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Sort-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/StartSleepCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/TestJsonCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/TimeExpressionCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/UnblockFile.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/UnregisterEventCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Update-Data.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Update-List.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Update-TypeData.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/UtilityCommon.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Var.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WaitEventCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Write.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WriteConsoleCmdlet.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WriteProgressCmdlet.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/XmlCommands.cs
Labels: CL-CodeCleanup

#14265 Use AsSpan/AsMemory slice constructor
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/UpdatesNotification.cs
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/regex.cs
  src/System.Management.Automation/engine/runtime/Operations/ArrayOps.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-CodeCleanup

#14239 Fix SA1642 for Microsoft.Management.Infrastructure.CimCmdlets
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimAsyncOperation.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimBaseAction.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimCommandBase.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetAssociatedInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetCimClass.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimIndicationWatcher.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimInvokeCimMethod.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimNewCimInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimPromptUser.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimRegisterCimIndication.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimRemoveCimInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimResultObserver.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionOperations.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSetCimInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteError.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteMessage.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteProgress.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteResultObject.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CmdletOperation.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimAssociatedInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimClassCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/InvokeCimMethodCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimSessionOptionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RemoveCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RemoveCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/SetCimInstanceCommand.cs
Labels: CL-CodeCleanup

#14234 Mark private members as static part 9
  src/System.Management.Automation/engine/Attributes.cs
  src/System.Management.Automation/engine/CmdletParameterBinderController.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/engine/CommandSearcher.cs
  src/System.Management.Automation/engine/EnumExpressionEvaluator.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/ManagementObjectAdapter.cs
  src/System.Management.Automation/engine/Modules/GetModuleCommand.cs
  src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Modules/NewModuleManifestCommand.cs
  src/System.Management.Automation/engine/Modules/PSModuleInfo.cs
  src/System.Management.Automation/engine/Modules/ScriptAnalysis.cs
  src/System.Management.Automation/engine/Modules/TestModuleManifestCommand.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/PSClassSearcher.cs
  src/System.Management.Automation/engine/PSConfiguration.cs
  src/System.Management.Automation/engine/Pipe.cs
  src/System.Management.Automation/engine/SessionState.cs
  src/System.Management.Automation/engine/SessionStateContainer.cs
  src/System.Management.Automation/engine/SessionStateFunctionAPIs.cs
  src/System.Management.Automation/engine/SessionStateNavigation.cs
  src/System.Management.Automation/engine/SessionStateVariableAPIs.cs
  src/System.Management.Automation/engine/TypeMetadata.cs
  src/System.Management.Automation/engine/TypeTable.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/hostifaces/Command.cs
  src/System.Management.Automation/engine/hostifaces/History.cs
  src/System.Management.Automation/engine/hostifaces/InternalHostUserInterface.cs
  src/System.Management.Automation/engine/hostifaces/LocalConnection.cs
  src/System.Management.Automation/engine/hostifaces/PSDataCollection.cs
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
  src/System.Management.Automation/engine/interpreter/InstructionList.cs
  src/System.Management.Automation/engine/interpreter/LightCompiler.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/parser/PSType.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/parser/SafeValues.cs
  src/System.Management.Automation/engine/parser/SemanticChecks.cs
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  src/System.Management.Automation/engine/pipeline.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  src/System.Management.Automation/engine/serialization.cs
Labels: CL-CodeCleanup

#14235 Mark private members as static part 10
  src/System.Management.Automation/CoreCLR/CorePsAssemblyLoadContext.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/XmlLoaderBase.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayResourceManagerCache.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataQuery.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader.cs
  src/System.Management.Automation/FormatAndOutput/common/Utilities/Mshexpression.cs
  src/System.Management.Automation/cimSupport/cmdletization/ScriptWriter.cs
  src/System.Management.Automation/cimSupport/other/ciminstancetypeadapter.cs
  src/System.Management.Automation/help/CommandHelpProvider.cs
  src/System.Management.Automation/help/HelpFileHelpProvider.cs
  src/System.Management.Automation/help/MUIFileSearcher.cs
  src/System.Management.Automation/help/MamlNode.cs
  src/System.Management.Automation/help/SaveHelpCommand.cs
  src/System.Management.Automation/help/UpdatableHelpSystem.cs
  src/System.Management.Automation/help/UpdateHelpCommand.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/namespaces/LocationGlobber.cs
  src/System.Management.Automation/namespaces/RegistryProvider.cs
  src/System.Management.Automation/security/SecurityManager.cs
  src/System.Management.Automation/utils/ObjectReader.cs
  src/System.Management.Automation/utils/PowerShellETWTracer.cs
Labels: CL-CodeCleanup

#14261 Fix RCS1188: Remove redundant auto-property initialization part 1
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimCommandBase.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
Labels: CL-CodeCleanup

#13973 Enable SA1000: Keywords should be spaced correctly
  .globalconfig
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/UnblockFile.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressPane.cs
  src/System.Management.Automation/engine/TypeMetadata.cs
  test/tools/TestExe/TestExe.cs
  test/tools/WebListener/Controllers/ResumeController.cs
Labels: CL-CodeCleanup, Review - Needed
