Repository PowerShell/PowerShell, pull requests merged in 2020-10, with the labels that each got.

#13750 Fix blocking wait when starting file associated with a Windows application
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1
Labels: CL-General

#13738 Add `Get-ExperimentalFeature` `OutputType` attribute
  src/System.Management.Automation/engine/ExperimentalFeature/GetExperimentalFeatureCommand.cs
Labels: CL-General

#13732 Change default fallback encoding for GetEncoding in Start-Transcript
  src/System.Management.Automation/engine/Utils.cs
Labels: Breaking-Change, Committee-Reviewed

#13765 Rename 'Get-Subsystem' to 'Get-PSSubsystem'
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/Subsystem/Commands/GetPSSubsystemCommand.cs
  test/powershell/engine/Help/HelpSystem.Tests.ps1
Labels: BackPort-7.1.x-Consider, CL-Engine

#13777 Update PSReadLine version to `2.1.0-rc1`
  assets/files.wxs
  src/Modules/PSGalleryModules.csproj
  test/powershell/Modules/PSReadLine/PSReadLine.Tests.ps1
Labels: BackPort-7.1.x-Approved

#13779 Add missing PSToken entries
  src/System.Management.Automation/engine/lang/interface/PSToken.cs
Labels: BackPort-7.1.x-Consider

#13794 Bump `Microsoft.PowerShell.Native` to `7.1.0-rc.2`
  src/System.Management.Automation/System.Management.Automation.csproj
Labels: BackPort-7.1.x-Approved

#13793 fix: change Nullable usage (#13791)
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
Labels: CL-CodeCleanup, Hacktoberfest-Accepted

#12183 Add Modules from the PowerShell/Modules Repo to the tracked modules list
  src/System.Management.Automation/utils/Telemetry.cs
Labels: BackPort-7.1.x-Consider, CL-General

#13814 Remove unnecessary using
  src/System.Management.Automation/namespaces/PathInfo.cs
Labels: CL-CodeCleanup, Hacktoberfest-Accepted

#13811 Minor fix keyword typo in csharp comment.
  docs/cmdlet-example/visual-studio-simple-example.md
Labels: CL-CodeCleanup, Hacktoberfest-Accepted

#13861 Remove unnecessary using in security folder
  src/System.Management.Automation/security/CatalogHelper.cs
  src/System.Management.Automation/security/MshSignature.cs
  src/System.Management.Automation/security/nativeMethods.cs
  src/System.Management.Automation/security/wldpNativeMethods.cs
Labels: CL-CodeCleanup

#13835 Add global AnalyzerConfig with default configuration
  .globalconfig
  src/Microsoft.Management.UI.Internal/.globalconfig
Labels: CL-Tools

#13872 Enable CA1050: Declare types in namespaces
  .globalconfig
  test/xUnit/Asserts/PriorityAttribute.cs
  test/xUnit/Asserts/PriorityOrderer.cs
  test/xUnit/csharp/test_PSConfiguration.cs
Labels: CL-CodeCleanup

#12942 Fix NRE in Test-Json
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/TestJsonCommand.cs
Labels: CL-General, Review - Needed

#13500 Use span-based string.Concat instead of string.Substring
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/runtime/Operations/ArrayOps.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
Labels: CL-CodeCleanup

#13881 Enable IDE0036: OrderModifiers
  .globalconfig
Labels: CL-CodeCleanup

#13911 Enable IDE1005: InvokeDelegateWithConditionalAccess
  .globalconfig
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/SessionBasedWrapper.cs
  src/System.Management.Automation/engine/EventManager.cs
  src/System.Management.Automation/engine/hostifaces/AsyncResult.cs
  src/System.Management.Automation/engine/hostifaces/PSDataCollection.cs
  src/System.Management.Automation/engine/hostifaces/RunspacePool.cs
  src/System.Management.Automation/engine/hostifaces/RunspacePoolInternal.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/remoting/client/Job2.cs
  src/System.Management.Automation/engine/remoting/client/ThrottlingJob.cs
  src/System.Management.Automation/engine/remoting/client/remotingprotocolimplementation.cs
  src/System.Management.Automation/engine/remoting/commands/WaitJob.cs
  src/System.Management.Automation/engine/remoting/common/fragmentor.cs
  src/System.Management.Automation/engine/remoting/server/WSManChannelEvents.cs
  src/System.Management.Automation/utils/ExtensionMethods.cs
Labels: CL-CodeCleanup

#13896 Enable IDE0048: AddRequiredParentheses
  .globalconfig
Labels: CL-CodeCleanup

#13890 Fix IDE0044: MakeFieldReadonly part 7
  src/Microsoft.PowerShell.MarkdownRender/VT100EscapeSequences.cs
Labels: CL-CodeCleanup

#13886 Fix IDE0044: MakeFieldReadonly part 3
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/QueryJobBase.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetComputerInfoCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/SetClipboardCommand.cs
Labels: CL-CodeCleanup

#13889 Fix IDE0044: MakeFieldReadonly part 6
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/EventDescriptor.cs
Labels: CL-CodeCleanup

#13892 Fix IDE0044: MakeFieldReadonly part 9
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/Microsoft.WSMan.Management/CurrentConfigurations.cs
  src/Microsoft.WSMan.Management/InvokeWSManAction.cs
  src/Microsoft.WSMan.Management/WSManInstance.cs
  src/Microsoft.WSMan.Management/WsManHelper.cs
Labels: CL-CodeCleanup

#13888 Fix IDE0044: MakeFieldReadonly part 5
  src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/PropVariant.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostRawUserInterface.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostTranscript.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleTextWriter.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/Executor.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/PendingProgress.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressPane.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/Serialization.cs
Labels: CL-CodeCleanup

#13885 Fix IDE0044: MakeFieldReadonly part 2
  src/Microsoft.PowerShell.Commands.Diagnostics/CounterSample.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/CounterSet.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/GetCounterCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/GetEventCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/NewWinEventCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/PdhHelper.cs
Labels: CL-CodeCleanup

#13878 Enable CA1834: Consider using 'StringBuilder.Append(char)' when applicable
  .globalconfig
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimCommandBase.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/GetEventCommand.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/QueryJob.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Hotfix.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertTo-Html.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetDateCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Group-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfacePrompt.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/EventProviderTraceListener.cs
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/Microsoft.WSMan.Management/WsManHelper.cs
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs
  src/System.Management.Automation/FormatAndOutput/common/Utilities/MshParameter.cs
  src/System.Management.Automation/engine/COM/ComAdapter.cs
  src/System.Management.Automation/engine/COM/ComProperty.cs
  src/System.Management.Automation/engine/COM/ComUtil.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CommandInfo.cs
  src/System.Management.Automation/engine/CommandMetadata.cs
  src/System.Management.Automation/engine/CoreAdapter.cs
  src/System.Management.Automation/engine/ManagementObjectAdapter.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Modules/ModuleSpecification.cs
  src/System.Management.Automation/engine/Modules/NewModuleManifestCommand.cs
  src/System.Management.Automation/engine/MshMemberInfo.cs
  src/System.Management.Automation/engine/MshObject.cs
  src/System.Management.Automation/engine/NativeCommandParameterBinder.cs
  src/System.Management.Automation/engine/PSVersionInfo.cs
  src/System.Management.Automation/engine/ParameterSetInfo.cs
  src/System.Management.Automation/engine/ProxyCommand.cs
  src/System.Management.Automation/engine/SessionStateProviderAPIs.cs
  src/System.Management.Automation/engine/parser/SemanticChecks.cs
  src/System.Management.Automation/engine/parser/ast.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
  src/System.Management.Automation/engine/remoting/client/Job2.cs
  src/System.Management.Automation/engine/remoting/commands/NewPSSessionConfigurationFile.cs
  src/System.Management.Automation/engine/remoting/common/psstreamobject.cs
  src/System.Management.Automation/help/DefaultCommandHelpObjectBuilder.cs
  src/System.Management.Automation/namespaces/RegistryProvider.cs
  src/System.Management.Automation/singleshell/config/MshConsoleLoadException.cs
  src/System.Management.Automation/utils/StructuredTraceSource.cs
Labels: CL-CodeCleanup

#13877 Enable CA1836: Prefer IsEmpty over Count when available
  .globalconfig
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Update-TypeData.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataManager.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/TypeTable.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/utils/FormatAndTypeDataHelper.cs
Labels: CL-CodeCleanup

#13893 Fix IDE0044: MakeFieldReadonly part 10
  test/xUnit/csharp/test_CommandLineParser.cs
  test/xUnit/csharp/test_FileSystemProvider.cs
  test/xUnit/csharp/test_PSConfiguration.cs
  test/xUnit/csharp/test_Runspace.cs
Labels: CL-CodeCleanup

#13803 Use Environment.CurrentManagedThreadId
  src/Microsoft.Management.Infrastructure.CimCmdlets/Utils.cs
  src/System.Management.Automation/engine/InformationRecord.cs
  src/System.Management.Automation/engine/hostifaces/Connection.cs
  src/System.Management.Automation/engine/hostifaces/PSTask.cs
  src/System.Management.Automation/engine/interpreter/Utilities.cs
  src/System.Management.Automation/utils/tracing/SysLogProvider.cs
Labels: CL-CodeCleanup, Hacktoberfest-Accepted

#13804 Fix nullable usage on authenticode (#13791)
  src/System.Management.Automation/security/Authenticode.cs
Labels: CL-CodeCleanup, Hacktoberfest-Accepted, Review - Needed, WG-Security
