Repository PowerShell/PowerShell, pull requests merged in 2021-03, with the labels that each got.

#14893 Add suppress for NuGet multi-feed warning
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/releasePipeline.yml
  tools/releaseBuild/azureDevOps/templates/checkAzureContainer.yml
  tools/releaseBuild/azureDevOps/templates/compliance.yml
  tools/releaseBuild/azureDevOps/templates/json.yml
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/mac-file-signing.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-build.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/mac.yml
  tools/releaseBuild/azureDevOps/templates/nuget.yml
  tools/releaseBuild/azureDevOps/templates/testartifacts.yml
  tools/releaseBuild/azureDevOps/templates/windows-component-governance.yml
  tools/releaseBuild/azureDevOps/templates/windows-hosted-build.yml
Labels: BackPort-7.0.x-Consider, BackPort-7.1.x-Consider, CL-BuildPackaging

#14555 #4750 Fix Get-Date -UFormat %G and %g behavior
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetDateCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Date.Tests.ps1
Labels: Area-Cmdlets-Utility, Breaking-Change, CL-BreakingChange, CL-General, Review - Needed, WG-Engine

#14111 Remove the 32,767 character limit on the environment block for `Start-Process`
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
Labels: BackPort-7.1.x-Approved, CL-General

#14940 Update metadata and script to enable consuming .NET daily builds
  DotnetRuntimeMetadata.json
  tools/UpdateDotnetRuntime.ps1
Labels: CL-BuildPackaging

#14970 Declare which variable group is used for checking the blob in the release build
  tools/releaseBuild/azureDevOps/templates/checkAzureContainer.yml
Labels: BackPort-7.0.x-Consider, BackPort-7.1.x-Consider

#14912 Update `Concise` ErrorView to not show line information for errors from script module functions
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  test/powershell/engine/Formatting/ErrorView.Tests.ps1
Labels: CL-General

#14908 Move misplaced test file to tests directory
  test/powershell/Modules/Microsoft.PowerShell.Core/ImportProvider.Tests.ps1
Labels: CL-Test

#14504 Fix PromptForCredential() to add `targetName` as domain
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfaceSecurity.cs
  src/System.Management.Automation/engine/Utils.cs
  test/powershell/Host/HostUtilities.Tests.ps1
Labels: BackPort-7.0.x-Approved, BackPort-7.1.x-Approved, CL-General

#14971 Disable running markdown link verification in release build CI
  .vsts-ci/misc-analysis.yml
Labels: BackPort-7.0.x-Approved, BackPort-7.1.x-Approved, CL-BuildPackaging

#14913 Fix `Move-Item` for FileSystemProvider to use copy-delete instead of move for DFS paths
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
Labels: CL-General

#14975 Fix the variable name in the condition
  .vsts-ci/misc-analysis.yml
Labels: BackPort-7.0.x-Approved, BackPort-7.1.x-Approved, CL-BuildPackaging

#14413 Re-enable VT mode on Windows after running command in ConsoleHost
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
Labels: Backport-7.2.x-Consider, CL-General

#14927 Add UseOSCIndicator setting to enable progress indicator in terminal
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfaceProgress.cs
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  src/System.Management.Automation/FormatAndOutput/common/PSStyle.cs
Labels: CL-General

#14976 Build self-contained minimal size package for Guest Config team
  build.psm1
  global.json
  tools/packaging/packaging.psm1
  tools/releaseBuild/Images/GenericLinuxFiles/PowerShellPackage.ps1
  tools/releaseBuild/Images/microsoft_powershell_windowsservercore/PowerShellPackage.ps1
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/upload.yml
  tools/releaseBuild/azureDevOps/templates/windows-hosted-build.yml
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
  tools/releaseBuild/build.json
Labels: CL-BuildPackaging

#15007 Update .NET to version `6.0.100-preview.2.21155.3`
  assets/wix/files.wxs
  global.json
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
  tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  tools/packaging/projects/reference/System.Management.Automation/System.Management.Automation.csproj
Labels: CL-BuildPackaging

#14937 Fix broken links for dotnet CLI
  docs/building/linux.md
  docs/building/windows-core.md
Labels: Review - Needed

#15046 Update `README` and `metadata.json`
  README.md
  tools/metadata.json
Labels: CL-Docs

#15035 Move bypass execution policy check after AppLocker Deny check
  src/System.Management.Automation/security/SecurityManager.cs
Labels: CL-Engine, OS-Windows, WG-Security

#15053 Refactor `MultipleServiceCommandBase.AllServices`
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
Labels: CL-CodeCleanup

#15074 Allow patching of preview releases
  PowerShell.Common.props
  build.psm1
  tools/ci.psm1
  tools/packaging/packaging.psm1
  tools/releaseBuild/Images/GenericLinuxFiles/PowerShellPackage.ps1
  tools/releaseBuild/Images/microsoft_powershell_windowsservercore/PowerShellPackage.ps1
  tools/releaseBuild/azureDevOps/templates/upload.yml
  tools/releaseBuild/macOS/PowerShellPackageVsts.ps1
  tools/releaseBuild/vstsbuild.ps1
  tools/releaseTools.psm1
Labels: CL-BuildPackaging

#15097 Update WiX to 3.11.2
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
Labels: CL-BuildPackaging

#15077 Fallback to `CopyAndDelete()` when `MoveTo()` fails due to an IOException
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
Labels: Backport-7.2.x-Consider, CL-General

#12605 Adding IArgumentCompleterFactory for parameterized ArgumentCompleters
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CommandCompletion/ExtensibleCompletion.cs
  test/powershell/Language/Parser/ExtensibleCompletion.Tests.ps1
Labels: Backport-7.2.x-Consider, CL-General, Committee-Reviewed
