Repository PowerShell/PowerShell, pull requests merged in 2021-09, with the labels that each got.

#16025 Add .stylecop to filetypexml and format it
  CHANGELOG/6.0.md
  CHANGELOG/6.1.md
  CHANGELOG/6.2.md
  CHANGELOG/7.0.md
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/compliance.yml
  tools/terms/FileTypeSet.xml
  tools/terms/TermsExclusion.xml
Labels: BackPort-7.0.x-Consider, BackPort-7.1.x-Consider

#16038 Fix typo in build.psm1
  build.psm1
Labels: CL-Tools

#14369 Improve CommandInvocationIntrinsics API documentation and style
  src/System.Management.Automation/engine/MshCmdlet.cs
Labels: Review - Needed, CL-CodeCleanup

#16068 Fix ConvertTo-SecureString with key regression due to .NET breaking change
  src/System.Management.Automation/security/SecureStringHelper.cs
  test/powershell/Modules/Microsoft.PowerShell.Security/SecureString.Tests.ps1
Labels: CL-General

#14397 Add `isOutputRedirected` parameter to `GetFormatStyleString()` method
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/System.Management.Automation/engine/Utils.cs
  test/powershell/engine/Formatting/OutputRendering.Tests.ps1
Labels: Backport-7.2.x-Consider

#16073 Set locale correctly on Linux CI
  .vsts-ci/linux-daily.yml
  .vsts-ci/templates/nix-test.yml
  tools/ci.psm1
Labels: CL-BuildPackaging

#16075 Move `GetOuputString()` and `GetFormatStyleString()` to PSHostUserInterface as public API
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/System.Management.Automation/FormatAndOutput/common/ILineOutput.cs
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs
Labels: CL-General, Backport-7.2.x-Consider

#16088 Update minimum required OS version for macOS
  tools/packaging/packaging.psm1
Labels: Backport-7.2.x-Consider

#16066 Update .NET to `6.0.100-rc.1.21458.32`
  DotnetRuntimeMetadata.json
  global.json
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
Labels: CL-BuildPackaging

#16083 Add benchmark to test compiler performance
  test/perf/benchmarks/Engine.Compiler.cs
  test/perf/benchmarks/Program.cs
  test/perf/benchmarks/assets/compiler.test.ps1
  test/perf/benchmarks/powershell-perf.csproj
  test/perf/dotnet-tools/BenchmarkDotNet.Extensions/BenchmarkDotNet.Extensions.csproj
  test/perf/dotnet-tools/ResultsComparer/Program.cs
  tools/UpdateDotnetRuntime.ps1
Labels: CL-Test

#16044 Remove support for AppExeCLinks to retrieve target
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: Documentation Needed, CL-General

#15751 Update Windows Core Build Documentation To Reflect .NET 6
  docs/building/windows-core.md
Labels: Review - Needed, CL-Docs

#16092 Use 'PlainText' when writing to a host that doesn't support VT
  src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs
Labels: CL-General, Backport-7.2.x-Consider

#16102 Update more docs for `net6.0` TFM
  docs/building/linux.md
  docs/building/macos.md
Labels: CL-Docs

#16119 Remove Joey from Committee and WG membership
  docs/community/governance.md
  docs/community/working-group-definitions.md
Labels: CL-Docs

#16138 Update `Microsoft.CodeAnalysis.CSharp` version
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
Labels: CL-BuildPackaging, Backport-7.2.x-Consider

#16137 Change path for Component Governance for build to the path we actually build
  tools/releaseBuild/azureDevOps/templates/windows-hosted-build.yml
Labels: CL-BuildPackaging, Backport-7.2.x-Consider

#16147 Add sha256 hashes to release
  tools/releaseBuild/azureDevOps/templates/release-CreateGitHubDraft.yml
Labels: Backport-7.2-Approved

#16105 Remove Windows PowerShell issue link
  .github/ISSUE_TEMPLATE/config.yml
Labels: CL-Docs
