Repository PowerShell/PowerShell, pull requests merged in 2021-10, with the labels that each got.

#16178 Fix Microsoft update spelling issue.
  assets/wix/Product.wxs
Labels: Backport-7.2.x-Consider

#16169 Move vPack build to 1ES Pool
  tools/releaseBuild/azureDevOps/templates/vpackReleaseJob.yml
Labels: BackPort-7.0.x-Consider, BackPort-7.1.x-Consider, Backport-7.2.x-Consider

#16165 Change `Target` from a `CodeProperty` to be an `AliasProperty` that points to `FileSystemInfo.LinkTarget`
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/TypeTable_Types_Ps1Xml.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
Labels: Backport-7.2.x-Consider

#16332 Fix issues in release build
  tools/packaging/packaging.psm1
  tools/releaseBuild/azureDevOps/templates/compliance.yml
  tools/releaseBuild/azureDevOps/templates/nuget.yml
  tools/releaseBuild/azureDevOps/templates/windows-hosted-build.yml
Labels: CL-BuildPackaging, Backport-7.2.x-Consider, Extra Small

#16326 Refactor `cgmanifest` generator to include all components
  .github/workflows/GHWorkflowHelper/GHWorkflowHelper.psm1
  .github/workflows/daily.yml
  .github/workflows/update-cgmanifest.yml
  cgmanifest.json
  prquantifier.yaml
  tools/findMissingNotices.ps1
  tools/packaging/packaging.psm1
Labels: MustHave, Extra Large

#16310 Don't throw exception when trying to resolve a possible link path
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1
Labels: CL-General, Backport-7.2.x-Consider, Extra Small

#16340 Use notice task to generate license assuming `cgmanifest` contains all components
  tools/releaseBuild/azureDevOps/compliance.yml
  tools/releaseBuild/azureDevOps/templates/compliance/generateNotice.yml
Labels: Extra Small
