Repository PowerShell/PowerShell, pull requests merged in 2021-07, with the labels that each got.

#15683 Add @jborean93 to Remoting Working Group
  docs/community/working-group-definitions.md
  src/Microsoft.PowerShell.ConsoleHost/consolehost.proto
Labels: CL-Docs

#15711 Update issue templates to link to new docs
  .github/ISSUE_TEMPLATE/Bug_Report.yaml
  .github/ISSUE_TEMPLATE/Microsoft_Update_Issue.yaml
  .github/SUPPORT.md
Labels: CL-Docs

#15675 Make classes sealed
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/TerminatingErrorTracker.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimOperationOptionsHelper.cs
  src/System.Management.Automation/CoreCLR/CorePsAssemblyLoadContext.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatXMLWriter.cs
  src/System.Management.Automation/engine/CommandInfo.cs
  src/System.Management.Automation/engine/Modules/AnalysisCache.cs
  src/System.Management.Automation/engine/MshSnapinQualifiedName.cs
  src/System.Management.Automation/engine/interpreter/PowerShellInstructions.cs
  src/System.Management.Automation/engine/parser/SafeValues.cs
  src/System.Management.Automation/engine/parser/SemanticChecks.cs
  src/System.Management.Automation/engine/parser/SymbolResolver.cs
  src/System.Management.Automation/engine/parser/VariableAnalysis.cs
  src/System.Management.Automation/engine/remoting/client/ClientMethodExecutor.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/RemoteDebuggingCapability.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/RemoteSessionCapability.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/RemotingDataObject.cs
  src/System.Management.Automation/engine/remoting/server/ServerSteppablePipelineDriver.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs
  src/System.Management.Automation/help/AliasHelpInfo.cs
  src/System.Management.Automation/help/CommandHelpProvider.cs
  src/System.Management.Automation/help/HelpCommentsParser.cs
  src/System.Management.Automation/help/HelpFileHelpInfo.cs
  src/System.Management.Automation/help/MUIFileSearcher.cs
  src/System.Management.Automation/help/ProviderHelpInfo.cs
  src/System.Management.Automation/help/SyntaxHelpInfo.cs
  src/System.Management.Automation/utils/CryptoUtils.cs
  src/System.Management.Automation/utils/GraphicalHostReflectionWrapper.cs
Labels: CL-CodeCleanup

#15640 Add `SkipRoslynAnalyzers` parameter to `Start-PSBuild`
  build.psm1
Labels: CL-Tools

#15728 Disable IDE0130
  .globalconfig
Labels: CL-CodeCleanup

#13880 Enable IDE0044: MakeFieldReadonly
  .globalconfig
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/GlobalSuppressions.cs
  src/System.Management.Automation/cimSupport/cmdletization/EnumWriter.cs
  src/System.Management.Automation/cimSupport/cmdletization/ScriptWriter.cs
  src/System.Management.Automation/engine/InternalCommands.cs
  src/System.Management.Automation/engine/NativeCommandParameterBinder.cs
  src/System.Management.Automation/engine/interpreter/InstructionList.cs
  src/System.Management.Automation/engine/remoting/common/RemoteSessionHyperVSocket.cs
  src/System.Management.Automation/logging/MshLog.cs
  src/System.Management.Automation/security/CatalogHelper.cs
  src/System.Management.Automation/security/SecurityManager.cs
  src/System.Management.Automation/security/SecuritySupport.cs
  src/System.Management.Automation/security/nativeMethods.cs
  src/System.Management.Automation/security/wldpNativeMethods.cs
  src/System.Management.Automation/singleshell/config/MshConsoleLoadException.cs
  src/System.Management.Automation/singleshell/config/MshSnapinInfo.cs
  src/System.Management.Automation/singleshell/config/MshSnapinLoadException.cs
  src/System.Management.Automation/utils/tracing/PSEtwLogProvider.cs
  src/System.Management.Automation/utils/tracing/TracingGen.cs
  test/tools/WebListener/Controllers/MultipartController.cs
  test/tools/WebListener/Controllers/ResumeController.cs
  test/xUnit/csharp/test_Prediction.cs
Labels: CL-CodeCleanup

#15704 Fix `HyperVSocketEndPoint.ServiceId` setter
  src/System.Management.Automation/engine/remoting/common/RemoteSessionHyperVSocket.cs
Labels: CL-General

#15736 Fix computation of SHA512 checksum
  tools/packaging/packaging.psm1
  tools/releaseBuild/azureDevOps/templates/nuget.yml
Labels: CL-BuildPackaging

#15686 Use `List<T>.RemoveAll` in `System.Management.Automation.ModuleIntrinsics`
  src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs
Labels: CL-CodeCleanup

#15737 Add to bug report template getting details from `Get-Error`
  .github/ISSUE_TEMPLATE/Bug_Report.yaml
Labels: CL-Docs

#15738 Fix CA1846 and CA1845 for using `AsSpan` instead of `Substring`
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/NativeCommandParameterBinder.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs
  src/System.Management.Automation/help/HelpCommentsParser.cs
Labels: CL-CodeCleanup

#15665 Don't serialize to json ETS properties for DateTime and string types
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertTo-Json.Tests.ps1
Labels: CL-General, Review - Needed

#14403 Add support to colorize FileInfo file names
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  src/System.Management.Automation/FormatAndOutput/common/PSStyle.cs
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-Item.Tests.ps1
Labels: Committee-Reviewed

#14289 Enable IDE0030: UseCoalesceExpressionForNullable
  .globalconfig
  src/System.Management.Automation/engine/Modules/NewModuleManifestCommand.cs
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
  src/System.Management.Automation/engine/remoting/commands/NewPSSessionOptionCommand.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
Labels: CL-CodeCleanup, Review - Needed

#14513 Implement a completion for View parameter of format cmdlets
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General

#15715 Enable IDE0070: UseSystemHashCode
  .globalconfig
Labels: CL-CodeCleanup, Review - Needed

#15727 Add mu opt out to MSI install
  assets/wix/Product.wxs
  test/packaging/windows/msi.tests.ps1
  test/tools/Modules/HelpersCommon/HelpersCommon.psm1
  tools/ci.psm1
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging

#15770 Enable IDE0029: UseCoalesceExpression
  .globalconfig
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetCimClass.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimNewCimInstance.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionOperations.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/Utils.cs
  src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
Labels: CL-CodeCleanup

#15784 Make mu opt-out/in check boxes work
  assets/wix/Product.wxs
Labels: CL-BuildPackaging

#15786 Highlight using error color the exception Message and underline in PositionMessage for `Get-Error`
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Error.Tests.ps1
Labels: CL-General

#15706 Add tests for ConvertFrom-Json
  test/powershell/Modules/Microsoft.PowerShell.Utility/Json.Tests.ps1
Labels: CL-Test

#15725 Seal private classes
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimConverter.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/clientSideQuery.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetComputerInfoCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetMember.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Measure-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/New-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Select-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/Executor.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/PendingProgress.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/UpdatesNotification.cs
  src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Sam.cs
  src/Microsoft.PowerShell.ScheduledJob/ScheduledJob.cs
  src/System.Management.Automation/FormatAndOutput/common/BaseOutputtingCommand.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayResourceManagerCache.cs
  src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs
  src/System.Management.Automation/FormatAndOutput/out-console/ConsoleLineOutput.cs
  src/System.Management.Automation/engine/CmdletParameterBinderController.cs
  src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CommandInfo.cs
  src/System.Management.Automation/engine/CommandParameter.cs
  src/System.Management.Automation/engine/CoreAdapter.cs
  src/System.Management.Automation/engine/GetCommandCommand.cs
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/engine/Modules/RemoteDiscoveryHelper.cs
  src/System.Management.Automation/engine/Modules/ScriptAnalysis.cs
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  src/System.Management.Automation/engine/PSVersionInfo.cs
  src/System.Management.Automation/engine/TypeTable.cs
  src/System.Management.Automation/engine/debugger/Breakpoint.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/hostifaces/ConnectionBase.cs
  src/System.Management.Automation/engine/hostifaces/pipelinebase.cs
  src/System.Management.Automation/engine/interpreter/LightCompiler.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/parser/PSType.cs
  src/System.Management.Automation/engine/parser/TypeResolver.cs
  src/System.Management.Automation/engine/parser/VariableAnalysis.cs
  src/System.Management.Automation/engine/regex.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
  src/System.Management.Automation/engine/remoting/client/ThrottlingJob.cs
  src/System.Management.Automation/engine/remoting/client/remotepipeline.cs
  src/System.Management.Automation/engine/remoting/commands/ConnectPSSession.cs
  src/System.Management.Automation/engine/remoting/commands/DisconnectPSSession.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManTransportManager.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  src/System.Management.Automation/engine/runtime/Operations/VariableOps.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/utils/tracing/EtwActivity.cs
  src/TypeCatalogGen/TypeCatalogGen.cs
  src/powershell/Program.cs
Labels: CL-CodeCleanup

#14406 Use $PSStyle.Formatting.FormatAccent for Format-List and $PSStyle.Formatting.TableHeader for Format-Table output
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  src/System.Management.Automation/FormatAndOutput/common/ListWriter.cs
  src/System.Management.Automation/FormatAndOutput/common/PSStyle.cs
  src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs
  src/System.Management.Automation/engine/Utils.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
  test/powershell/Language/Classes/Scripting.Classes.BasicParsing.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Custom.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-List.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Out-File.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Set-Variable.Tests.ps1
  test/powershell/engine/Formatting/BugFix.Tests.ps1
  test/powershell/engine/Formatting/ErrorView.Tests.ps1
  test/powershell/engine/Formatting/PSStyle.Tests.ps1
Labels: CL-General

#15741 Remove consolehost.proto file
  src/Microsoft.PowerShell.ConsoleHost/consolehost.proto
Labels: CL-CodeCleanup

#15776 Make warning about MU being required most of the time dynamic
  assets/wix/Product.wxs
Labels: CL-BuildPackaging

#15408 Add a Windows mode for native commands that allows some commands to use legacy argument passing
  src/System.Management.Automation/engine/CommandBase.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/NativeCommandParameterBinder.cs
  src/System.Management.Automation/engine/NativeCommandParameterBinderController.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
  test/powershell/Language/Scripting/NativeExecution/NativeCommandArguments.Tests.ps1
Labels: Committee-Reviewed

#15810 Prefer version parameter of `dotnet-install` when available
  build.psm1
Labels: CL-BuildPackaging

#15813 Add new package name for `osx-arm64`
  tools/releaseBuild/azureDevOps/templates/release-ValidatePackageNames.yml
Labels: CL-BuildPackaging

#13813 Add position 0 to Write-Error parameters
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Write.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Write-Error.Tests.ps1
Labels: CL-General, Hacktoberfest-Accepted

#11029 ConvertTo-Csv / Export-Csv - Serialize IDictionary objects with key/value pairs as properties
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertTo-Csv.Tests.ps1
Labels: CL-General

#12135 Encoding Parameter for Tee-Object
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Tee-Object.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Tee-Object.Tests.ps1
Labels: CL-General

#15815 EditorConfig: don't replace tabs with spaces in tsv files
  .editorconfig
Labels: CL-Tools

#13713 Add `-PassThru` parameter to `Set-Clipboard`
  src/Microsoft.PowerShell.Commands.Management/commands/management/SetClipboardCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Clipboard.Tests.ps1
Labels: CL-General, Committee-Reviewed, Waiting on Author

#15808 Enable `/rebase` to automatically rebase a PR
  .github/workflows/rebase.yml
Labels: CL-Tools

#15819 Update README and metadata files for release v7.2.0-preview.8
  DotnetRuntimeMetadata.json
  README.md
  tools/metadata.json
Labels: CL-Docs

#15778 Specify api_surface property for all code quality rules
  .globalconfig
Labels: CL-CodeCleanup

#15825 Add validation to `$PSStyle` to reject printable text as ANSI escape sequence
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  src/System.Management.Automation/FormatAndOutput/common/PSStyle.cs
  src/System.Management.Automation/resources/PSStyleStrings.resx
  test/powershell/engine/Formatting/PSStyle.Tests.ps1
Labels: CL-General

#15832 Avoid unnecessary `StringCollection` allocation
  src/System.Management.Automation/FormatAndOutput/common/BaseOutputtingCommand.cs
Labels: CL-CodeCleanup

#15775 Fix CA1052 for public API
  .globalconfig
  src/System.Management.Automation/engine/PSVersionInfo.cs
  src/System.Management.Automation/engine/serialization.cs
  test/powershell/engine/Basic/assets/standardtypes.csv
  test/tools/WebListener/Program.cs
Labels: Breaking-Change, CL-BreakingChange, CL-CodeCleanup, Committee-Reviewed

#14491 Enable IDE0049: PreferBuiltInOrFrameworkType
  .globalconfig
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimCommandBase.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimIndicationWatcher.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimRegisterCimIndication.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteMessage.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimWriteProgress.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimAssociatedInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimClassCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/InvokeCimMethodCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/NewCimSessionOptionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RegisterCimIndicationCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RemoveCimInstanceCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RemoveCimSessionCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/SetCimInstanceCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/CommonUtils.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/GetEventCommand.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/CimJobException.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimChildJobBase.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimQuery.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetComputerInfoCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Compare-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImportAliasCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Send-MailMessage.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/SetDateCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ShowCommand/ShowCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/UtilityCommon.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WaitEventCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WriteProgressCmdlet.cs
  src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/ComInterfaces.cs
  src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/PropertyKey.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfaceProgress.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/PendingProgress.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/EventProvider.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/Reader/NativeWrapper.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/UnsafeNativeMethods.cs
  src/Microsoft.PowerShell.Security/security/SecureStringCommands.cs
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/Microsoft.WSMan.Management/InvokeWSManAction.cs
  src/Microsoft.WSMan.Management/NewWSManSession.cs
  src/Microsoft.WSMan.Management/PingWSMan.cs
  src/Microsoft.WSMan.Management/WSManConnections.cs
  src/Microsoft.WSMan.Management/WSManInstance.cs
Labels: CL-CodeCleanup, Review - Needed

#15839 Partially revert changes to `src/Microsoft.Management.UI.Internal/`
  src/Microsoft.Management.UI.Internal/HelpWindow/HelpViewModel.cs
  src/Microsoft.Management.UI.Internal/HelpWindow/ParagraphBuilder.cs
  src/Microsoft.Management.UI.Internal/ManagementList/Common/DismissiblePopup.cs
  src/Microsoft.Management.UI.Internal/ManagementList/Common/ListOrganizerItem.cs
  src/Microsoft.Management.UI.Internal/ManagementList/Common/ReadOnlyObservableAsyncCollection.cs
  src/Microsoft.Management.UI.Internal/ManagementList/CommonControls/Resizer.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/DefaultFilterRuleCustomizationFactory.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterEvaluator.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/ValidatingValue.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterProviders/AddFilterRulePicker.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterProviders/InputFieldBackgroundTextConverter.cs
  src/Microsoft.Management.UI.Internal/ManagementList/ManagementList/Innerlist.cs
  src/Microsoft.Management.UI.Internal/ManagementList/ManagementList/PropertyValueComparer.cs
  src/Microsoft.Management.UI.Internal/ManagementList/ManagementList/PropertyValueGetter.cs
  src/Microsoft.Management.UI.Internal/ManagementList/ManagementList/managementlist.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/Controls/ParameterSetControl.xaml.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/ViewModel/AllModulesViewModel.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/ViewModel/ModuleViewModel.cs
  src/Microsoft.Management.UI.Internal/commandHelpers/OutGridView.cs
  src/Microsoft.Management.UI.Internal/commandHelpers/ShowCommandHelper.cs
Labels: CL-CodeCleanup

#15841 Harden logic when looking for syslog entries for failing test
  test/powershell/Host/Logging.Tests.ps1
Labels: CL-Test

#14271 Forwarding progress stream changes from Foreach-Object -Parallel runspaces
  src/System.Management.Automation/engine/hostifaces/PSTask.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Foreach-Object-Parallel.Tests.ps1
Labels: CL-General
