Repository PowerShell/PowerShell, pull requests merged in 2021-12, with the labels that each got.

#16228 Fix PSVersion parameter version checks and error messages for PowerShell core remoting
  src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs
  src/System.Management.Automation/engine/remoting/commands/StartJob.cs
  src/System.Management.Automation/engine/remoting/commands/remotingcommandutil.cs
  src/System.Management.Automation/resources/RemotingErrorIdStrings.resx
  test/powershell/Modules/Microsoft.PowerShell.Core/Job.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Core/PSSessionConfiguration.Tests.ps1
Labels: Committee-Reviewed, CL-Engine, Small

#16536 Fix race condition between DisconnectAsync and Dispose
  src/System.Management.Automation/engine/remoting/client/RemotingProtocol2.cs
Labels: CL-General, Extra Small

#16535 Bring back `pwsh.exe` for framework dependent packages to support Start-Job
  assets/wix/files.wxs
  build.psm1
  tools/releaseBuild/azureDevOps/releasePipeline.yml
  tools/releaseBuild/azureDevOps/templates/release-ValidateFxdPackage.yml
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
Labels: Backport-7.2.x-Approved, Small

#16543 Set clean state before testing `UseMU` in the MSI
  .vsts-ci/windows/windows-packaging.yml
  test/packaging/windows/msi.tests.ps1
Labels: Backport-7.2.x-Consider, Extra Small

#16460 Remove declaration of experimental features in Utility module manifest as they are stable
  src/Modules/Unix/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/Modules/Windows/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
Labels: Backport-7.2.x-Approved, Extra Small

#16579 Add explicit job name for approval tasks in Snap stage
  tools/releaseBuild/azureDevOps/releasePipeline.yml
Labels: CL-BuildPackaging, Extra Small

#16598 Fix broken links in markdown
  docs/dev-process/coding-guidelines.md
Labels: CL-BuildPackaging, Extra Small

#16600 Update cgmanifest
  cgmanifest.json
Labels: CL-BuildPackaging, Extra Small

#16599 Disabled Yarn cache in markdown.yml
  .vsts-ci/misc-analysis/markdown.yml
Labels: CL-BuildPackaging, Extra Small

#16609 Update macOS build image and root folder for build
  tools/releaseBuild/azureDevOps/templates/cloneToOfficialPath.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-build.yml
  tools/releaseBuild/azureDevOps/templates/mac.yml
Labels: CL-BuildPackaging, Extra Small

#16611 Update the vmImage and PowerShell root directory for macOS builds
  tools/releaseBuild/azureDevOps/templates/cloneToOfficialPath.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-build.yml
  tools/releaseBuild/azureDevOps/templates/mac.yml
Labels: CL-BuildPackaging, Extra Small

#16586 Updated README.md and metadata.json for 7.2.1 release
  README.md
  tools/metadata.json
Labels: Small

#16616 Updating changelog for 7.2.1
  .spelling
  CHANGELOG/7.2.md
Labels: CL-Docs, Extra Small

#16629 Fix the DSC overview URL in a markdown file and some small cleanup changes
  build.psm1
  demos/DSC/readme.md
  src/Microsoft.PowerShell.ConsoleHost/host/msh/UpdatesNotification.cs
  src/System.Management.Automation/engine/parser/Parser.cs
Labels: CL-CodeCleanup, Extra Small

#16627 Updated README.md and metadata.json for v7.3.0-preview.1 release
  README.md
  tools/metadata.json
Labels: CL-Docs, Extra Small

#16640 Bring changes from 7.3.0-preview.1
  .spelling
  CHANGELOG/preview.md
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/System.Management.Automation/FormatAndOutput/common/PSStyle.cs
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Core/Enter-PSHostProcess.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Error.Tests.ps1
  test/powershell/engine/Formatting/OutputRendering.Tests.ps1
  test/powershell/engine/Formatting/PSStyle.Tests.ps1
  tools/releaseBuild/azureDevOps/templates/release-GlobalToolTest.yml
  tools/releaseBuild/azureDevOps/templates/release-SDKTests.yml
Labels: CL-BuildPackaging, Large

#16608 Fix parsing SemanticVersion build label from version string
  src/System.Management.Automation/engine/PSVersionInfo.cs
  test/powershell/engine/Basic/SemanticVersion.Tests.ps1
Labels: CL-General, Extra Small

#16641 Update SBOM generation
  .github/prquantifier.yaml
  .vsts-ci/linux.yml
  .vsts-ci/mac.yml
  .vsts-ci/misc-analysis/mdSpell.yml
  .vsts-ci/windows.yml
  .vsts-ci/windows/templates/windows-packaging.yml
  tools/cgmanifest.json
  tools/findMissingNotices.ps1
  tools/releaseBuild/azureDevOps/templates/SetVersionVariables.yml
  tools/releaseBuild/azureDevOps/templates/compliance.yml
  tools/releaseBuild/azureDevOps/templates/compliance/compliance.yml
  tools/releaseBuild/azureDevOps/templates/compliance/generateNotice.yml
  tools/releaseBuild/azureDevOps/templates/json.yml
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/mac-file-signing.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-build.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/mac.yml
  tools/releaseBuild/azureDevOps/templates/nuget.yml
  tools/releaseBuild/azureDevOps/templates/windows-hosted-build.yml
  tools/releaseBuild/azureDevOps/templates/windows-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
Labels: BackPort-7.0.x-Consider, BackPort-7.1.x-Consider, Backport-7.2.x-Consider, Medium

#16580 Update Images used for release
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/releasePipeline.yml
  tools/releaseBuild/azureDevOps/templates/checkAzureContainer.yml
  tools/releaseBuild/azureDevOps/templates/compliance.yml
  tools/releaseBuild/azureDevOps/templates/compliance/compliance.yml
  tools/releaseBuild/azureDevOps/templates/compliance/generateNotice.yml
  tools/releaseBuild/azureDevOps/templates/json.yml
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/mac-file-signing.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/nuget.yml
  tools/releaseBuild/azureDevOps/templates/release-GlobalToolTest.yml
  tools/releaseBuild/azureDevOps/templates/release-MsixBundle.yml
  tools/releaseBuild/azureDevOps/templates/release-SDKTests.yml
  tools/releaseBuild/azureDevOps/templates/release-UpdateDepsJson.yml
  tools/releaseBuild/azureDevOps/templates/release-ValidateFxdPackage.yml
  tools/releaseBuild/azureDevOps/templates/testartifacts.yml
  tools/releaseBuild/azureDevOps/templates/vpackReleaseJob.yml
  tools/releaseBuild/azureDevOps/templates/windows-component-governance.yml
  tools/releaseBuild/azureDevOps/templates/windows-hosted-build.yml
  tools/releaseBuild/azureDevOps/templates/windows-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
  tools/releaseBuild/azureDevOps/vpackRelease.yml
Labels: Compliance, BackPort-7.0.x-Consider, BackPort-7.1.x-Consider, Backport-7.2.x-Consider, Small

#16570 Register NuGet source when generating `CGManifest`
  tools/cgmanifest.json
  tools/findMissingNotices.ps1
Labels: Review - Needed, Backport-7.2.x-Consider, Extra Small
