Repository PowerShell/PowerShell, pull requests merged in 2021-11, with the labels that each got.

#16337 Generate manifest with latest public version of the packages
  .github/workflows/daily.yml
  cgmanifest.json
  tools/findMissingNotices.ps1
Labels: Medium

#16342 Fix global tool and SDK tests in release pipeline
  tools/releaseBuild/azureDevOps/templates/release-GlobalToolTest.yml
  tools/releaseBuild/azureDevOps/templates/release-SDKTests.yml
Labels: Backport-7.2.x-Consider, Extra Small

#16351 Add an approval for releasing build-info json
  tools/releaseBuild/azureDevOps/releasePipeline.yml
Labels: BackPort-7.0.x-Consider, BackPort-7.1.x-Consider, Backport-7.2.x-Consider, Extra Small

#16335 Release build info json when it is preview
  tools/metadata.json
  tools/releaseBuild/azureDevOps/templates/release-BuildJson.yml
Labels: CL-BuildPackaging, BackPort-7.0.x-Consider, BackPort-7.1.x-Consider, Backport-7.2.x-Consider, Extra Small

#16352 Move PR Quantifier config to subfolder
  .github/prquantifier.yaml
Labels: No Changes

#14539 Tee-Object: add `-Encoding` parameter
  test/powershell/Modules/Microsoft.PowerShell.Utility/Tee-Object.Tests.ps1
Labels: Review - Needed, CL-General, Extra Small

#16193 Add support in BasicHtmlWebResponseObject for open-ended input tags
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/BasicHtmlWebResponseObject.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: CL-General

#15853 Add HttpVersion parameter to Invoke-WebRequest cmdlet
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/HttpVersionCompletionsAttribute.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/WebCmdletStrings.resx
  src/System.Management.Automation/engine/ArgumentToVersionTransformationAttribute.cs
  src/System.Management.Automation/engine/InternalCommands.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
  test/tools/WebListener/Controllers/GetController.cs
  test/tools/WebListener/Program.cs
  test/xUnit/csharp/test_ArgumentToVersionTransformationAttribute.cs
Labels: WG-Cmdlets, WG-Cmdlets-Utility, CL-General, Large

#16354 increment RC MSI build number by 100
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging, Extra Small

#16353 Add current folder to the beginning of the module import
  .github/workflows/daily.yml
Labels: Extra Small

#16371 Remove File.ResolveLinkTarget from IsWindowsApplication
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
Labels: CL-General, Extra Small

#16395 Update metadata.json and README.md for 7.2.0 release
  README.md
  tools/metadata.json
Labels: Small

#16398 Update CgManifest.json for 6.0.0 .NET packages
  cgmanifest.json
Labels: Small

#16399 Add checkout to build json stage to get `ci.psm1`
  tools/releaseBuild/azureDevOps/templates/release-BuildJson.yml
Labels: Extra Small

#16381 Update the usage of metadata.json for getting LTS information
  tools/releaseBuild/azureDevOps/templates/release-PublishPackageMsftCom.yml
Labels: Backport-7.2.x-Consider, Extra Small

#16402 vPack release should use buildInfoJson new to 7.2
  tools/releaseBuild/azureDevOps/vpackRelease.yml
Labels: Backport-7.2.x-Consider, Small

#16404 Add diagnostics used to take corrective action when releasing buildInfoJson
  tools/releaseBuild/azureDevOps/templates/release-BuildJson.yml
Labels: Backport-7.2.x-Consider, Extra Small

#16405 Update cgmanifest
  cgmanifest.json
Labels: Extra Small

#16401 Update change log for 7.2.0
  .spelling
  CHANGELOG/7.2.md
  CHANGELOG/preview.md
Labels: Backport-7.2.x-Consider, Extra Small

#16406 Update `metadata.json` in preparation on `7.3.0-preview.1` release
  src/System.Management.Automation/engine/PSVersionInfo.cs
  test/powershell/Host/PSVersionTable.Tests.ps1
  test/powershell/Language/Scripting/Requires.Tests.ps1
  tools/metadata.json
Labels: Extra Small

#16397 Make static CI a matrix
  .vsts-ci/misc-analysis.yml
  .vsts-ci/misc-analysis/generateMarkdownMatrix.yml
  .vsts-ci/misc-analysis/markdown.yml
  .vsts-ci/misc-analysis/mdSpell.yml
  test/common/markdown-link/markdown-link.tests.ps1
  test/common/markdown-lint/.gitignore
  test/common/markdown-lint/gulpfile.js
  test/common/markdown-lint/markdown.tests.ps1
  test/common/markdown-lint/package.json
  test/common/markdown-lint/yarn.lock
Labels: Large

#16417 Make 7.2.0 the latest LTS
  tools/metadata.json
Labels: Extra Small

#16407 Fix typo for "privacy" in MSI installer
  assets/wix/Product.wxs
Labels: Backport-7.2.x-Consider, Extra Small

#16379 Update README.md to specify gathered telemetry
  .spelling
  .vsts-ci/linux.yml
  .vsts-ci/mac.yml
  .vsts-ci/windows.yml
  README.md
Labels: Extra Small

#14550 Fix tab completion for attribute ScriptBlocks.
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Extra Small

#16419 Update release instructions with link to new build
  tools/releaseBuild/azureDevOps/releasePipeline.yml
  tools/releaseBuild/azureDevOps/templates/release/approvalJob.yml
Labels: CL-BuildPackaging, BackPort-7.0.x-Consider, BackPort-7.1.x-Consider, Backport-7.2.x-Consider, Small

#16435 try changing error action
  .github/workflows/daily.yml
Labels: Extra Small

#16436 Add exit 0
  .github/workflows/daily.yml
Labels: Extra Small

#16418 Remove pre-release .NET 6 build sources
  DotnetRuntimeMetadata.json
  nuget.config
Labels: Extra Small

#16433 Add import so we can use common GitHub workflow function.
  .github/workflows/daily.yml
Labels: CL-BuildPackaging, Extra Small

#16434 Make tpn generation use different containers for different branches
  tools/releaseBuild/azureDevOps/templates/compliance/generateNotice.yml
Labels: Extra Small

#16456 Update HelpInfoUri for 7.2 release
  src/Modules/Shared/Microsoft.PowerShell.Host/Microsoft.PowerShell.Host.psd1
  src/Modules/Unix/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.psd1
  src/Modules/Unix/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.psd1
  src/Modules/Unix/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/Modules/Windows/CimCmdlets/CimCmdlets.psd1
  src/Modules/Windows/Microsoft.PowerShell.Diagnostics/Microsoft.PowerShell.Diagnostics.psd1
  src/Modules/Windows/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.psd1
  src/Modules/Windows/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.psd1
  src/Modules/Windows/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.psd1
  src/Modules/Windows/Microsoft.WSMan.Management/Microsoft.WSMan.Management.psd1
  src/Modules/Windows/PSDiagnostics/PSDiagnostics.psd1
  src/System.Management.Automation/help/UpdatableHelpCommandBase.cs
Labels: CL-General, Backport-7.2.x-Consider, Extra Small

#16454 Fix typo in Job.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
Labels: CL-CodeCleanup, No Changes

#16471 Updated README.md to include PS 7.2 Changelog link
  CHANGELOG/README.md
Labels: Extra Small

#16489 Add `[ArgumentToPSVersionTransformationAttribute]` to list of patterns to remove for generated ref assembly
  tools/packaging/packaging.psm1
Labels: Extra Small

#16487 Corrects the Max path condition check while using ChildItem based commands
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1
Labels: CL-General, Extra Small

#16263 Use the same temporary home directory when 'HOME' env variable is not set
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/engine/hostifaces/LocalConnection.cs
  src/System.Management.Automation/security/SecurityManager.cs
  src/System.Management.Automation/utils/PsUtils.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
Labels: CL-Engine, Large

#16509 Fix NuGet package generation in release build
  tools/packaging/packaging.psm1
Labels: Extra Small

#16416 Use Convert-Path for unknown drive in Build.psm1
  build.psm1
Labels: Review - Needed, CL-Tools, Extra Small
