Repository PowerShell/PowerShell, pull requests merged in 2022-09, with the labels that each got.

#17997 Add XML reference documents to NuPkg files for SDK
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging, Extra Small, Backport-7.3.x-Consider

#18036 Add schema for cgmanifest.json
  tools/cgmanifest.json
  tools/findMissingNotices.ps1
Labels: Extra Small

#18043 Make experimental feature `PSCleanBlock` stable
  experimental-feature-linux.json
  experimental-feature-windows.json
  src/System.Management.Automation/engine/CommandMetadata.cs
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
Labels: Extra Small, Backport-7.3.x-Consider

#18045 Make experimental feature `PSExec` stable
  experimental-feature-linux.json
  experimental-feature-windows.json
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/Modules/SwitchProcessCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Core/Exec.Tests.ps1
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
Labels: Extra Small, Backport-7.3.x-Consider

#18046 Make experimental feature `PSRemotingSSHTransportErrorHandling` stable
  experimental-feature-linux.json
  experimental-feature-windows.json
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs
Labels: CL-General, Extra Small, Backport-7.3.x-Consider

#18058 Remove unused variables
  src/Microsoft.PowerShell.Security/security/CmsCommands.cs
Labels: CL-CodeCleanup, Extra Small

#18063 Fix typo in EventResource.resx
  src/System.Management.Automation/resources/EventResource.resx
Labels: Extra Small

#18060 Handle PSObject argument specially in method invocation logging
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
Labels: CL-General, Extra Small, Backport-7.3.x-Consider

#18041 Make experimental feature `PSAMSIMethodInvocationLogging` stable
  experimental-feature-linux.json
  experimental-feature-windows.json
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
Labels: CL-General, Extra Small, Backport-7.3.x-Consider

#18044 Make experimental feature `PSNativeCommandArgumentPassing` stable
  experimental-feature-linux.json
  experimental-feature-windows.json
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/NativeCommandParameterBinder.cs
  test/powershell/Language/Scripting/NativeExecution/NativeCommandArguments.Tests.ps1
Labels: CL-General, Small, Backport-7.3.x-Consider

#18042 Make experimental feature `PSAnsiRenderingFileInfo` stable
  experimental-feature-linux.json
  experimental-feature-windows.json
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-Item.Tests.ps1
Labels: Extra Small, Backport-7.3.x-Consider

#18030 Improve pseudo binding for dynamic parameters
  src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-Engine, Extra Small

#18040 Revert "Add `-StrictMode` to `Invoke-Command` to allow specifying strict mode when invoking command locally"
  experimental-feature-linux.json
  experimental-feature-windows.json
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Core/Invoke-Command.Tests.ps1
Labels: Small, Backport-7.3.x-Consider

#17982 Fixing CA2014 warnings, and removing suppressions
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
Labels: Small

#18083 Backport of Make experimental feature PSAMSIMethodInvocationLogging stable
  experimental-feature-linux.json
  experimental-feature-windows.json
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
Labels: Extra Small

#18086 Backport of 'Fix error formatting to use color defined in $PSStyle.Formatting'
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
Labels: CL-Engine, Medium

#18093 Add ConfigurationFile option to syntax frontmatter
  src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx
Labels: Extra Small, Backport-7.3.x-Consider

#18095 Filter out compiler generated types for `Add-Type -PassThru`
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs
Labels: Review - Committee, CL-BreakingChange, CL-General, Extra Small, Backport-7.3.x-Approved

#18091 Update `DotnetRuntimeMetadata.json` for .NET 7 RC1 build
  DotnetRuntimeMetadata.json
  assets/wix/files.wxs
  global.json
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  test/perf/dotnet-tools/BenchmarkDotNet.Extensions/BenchmarkDotNet.Extensions.csproj
  test/perf/dotnet-tools/ResultsComparer/ResultsComparer.csproj
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
Labels: Small, Backport-7.3.x-Approved

#18105 Re-enable building with Ready-to-Run
  PowerShell.Common.props
  test/powershell/Host/Startup.Tests.ps1
Labels: CL-BuildPackaging, Extra Small

#18106 Update `DotnetRuntimeMetadata.json` for .NET 7 RC1 build (#18091)
  DotnetRuntimeMetadata.json
  assets/wix/files.wxs
  global.json
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  test/perf/dotnet-tools/BenchmarkDotNet.Extensions/BenchmarkDotNet.Extensions.csproj
  test/perf/dotnet-tools/ResultsComparer/ResultsComparer.csproj
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
Labels: Small

#18080 Treat `[NullString]::Value` as the string type when resolving methods
  src/System.Management.Automation/engine/CoreAdapter.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  test/powershell/Language/Scripting/Scripting.Followup.Tests.ps1
Labels: CL-Engine, Small

#18084 Update `WriteConsole` to not use `stackalloc` for buffer with too large size
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs
Labels: CL-General, Extra Small

#14611 Invoke-WebRequest: Display downloaded bytes in human readable format and display total expected download size
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebResponseObject.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/InvokeWebRequestCommand.CoreClr.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/StreamHelper.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/WebCmdletStrings.resx
  src/System.Management.Automation/engine/Utils.cs
  test/xUnit/csharp/test_Utils.cs
Labels: WG-Interactive-Console, WG-Cmdlets, CL-General, Small

#18128 Update `metadata.json` and `README.md` for v7.3.0-preview.8 release
  README.md
  tools/metadata.json
Labels: Extra Small

#18136 Update the change log for v7.3.0-preview.8
  .spelling
  CHANGELOG/preview.md
Labels: Extra Small

#18137 Update MSI exit message
  assets/wix/Product.wxs
Labels: Backport-7.2.x-Consider, Extra Small

#18130 Complete the progress bar rendering in `Invoke-WebRequest` when downloading is complete or cancelled
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/StreamHelper.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/WebCmdletStrings.resx
Labels: CL-General, Extra Small

#18138 Make PowerShell class not affiliate with Runspace when declaring the `NoRunspaceAffinity` attribute
  src/System.Management.Automation/engine/parser/PSType.cs
  src/System.Management.Automation/engine/parser/TypeResolver.cs
  src/System.Management.Automation/engine/runtime/Operations/ClassOps.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  test/powershell/Language/Classes/Scripting.Classes.NoRunspaceAffinity.Tests.ps1
  test/powershell/Language/Parser/TypeAccelerator.Tests.ps1
Labels: CL-General, Extra Small

#18158 Make the link to minimal package blob public during release
  tools/releaseBuild/azureDevOps/templates/release-MakeContainerPublic.yml
Labels: Backport-7.2.x-Consider, Extra Small, Backport-7.3.x-Consider

#18144 Replace `UTF8Encoding(false)` with `Encoding.Default`
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
Labels: CL-CodeCleanup, Extra Small

#18176 Add a workaround in automatic rebase workflow to continue on error
  .github/workflows/rebase.yml
Labels: Extra Small

#18184 Fix the verbose message when using `dotnet-install.sh`
  build.psm1
Labels: CL-BuildPackaging, Extra Small

#17545 Fix Parent property on processes with complex name
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-Process.Tests.ps1
Labels: CL-General, Extra Small

#18183 Make a minor update to the `FileInfo` table formatting on Unix to make it more concise
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/FileSystem_format_ps1xml.cs
Labels: CL-General, Extra Small

#18188 Bump to .NET SDK 6.0.401
  .editorconfig
  assets/wix/files.wxs
  global.json
  src/System.Management.Automation/System.Management.Automation.csproj
  src/System.Management.Automation/singleshell/config/MshSnapinInfo.cs
  src/System.Management.Automation/utils/tracing/PSSysLogProvider.cs
  src/System.Management.Automation/utils/tracing/SysLogProvider.cs
  test/perf/dotnet-tools/Reporting/Reporting.csproj
  test/perf/dotnet-tools/ResultsComparer/ResultsComparer.csproj
  test/tools/WebListener/Controllers/RetryController.cs
  test/tools/WebListener/WebListener.csproj
  tools/cgmanifest.json
Labels: Extra Small

#18191 Move ApiScan to compliance build
  PowerShell.Common.props
  build.psm1
  tools/releaseBuild/azureDevOps/compliance.yml
  tools/releaseBuild/azureDevOps/templates/compliance.yml
  tools/releaseBuild/azureDevOps/templates/compliance/apiscan.yml
Labels: Medium

#18185 Remove the extra new line form List formatting
  src/System.Management.Automation/FormatAndOutput/common/BaseOutputtingCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-List.Tests.ps1
Labels: CL-General, Extra Small

#18168 Remove ApplicationType telemetry sends.
  src/System.Management.Automation/engine/pipeline.cs
  src/System.Management.Automation/utils/Telemetry.cs
Labels: BackPort-7.0.x-Approved, Backport-7.2.x-Approved, Extra Small, Backport-7.3.x-Approved
