Repository PowerShell/PowerShell, pull requests merged in 2022-02, with the labels that each got.

#16821 Update .NET SDK to 6.0.101 and fix Microsoft.PowerShell.GlobalTool.Shim.csproj
  assets/wix/files.wxs
  global.json
  src/Microsoft.PowerShell.GlobalTool.Shim/GlobalToolShim.cs
  tools/packaging/packaging.psm1
Labels: Extra Small

#16438 Add completion for loop labels after Break/Continue
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Small

#16825 Update `markdownlint` to the latest version
  test/common/markdown-lint/package.json
  test/common/markdown-lint/yarn.lock
Labels: CL-Test, Extra Small

#16833 Add experimental json update automation
  .github/workflows/exp-json.yml
Labels: Small

#16834 Remove WiX install
  tools/releaseBuild/azureDevOps/releasePipeline.yml
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
Labels: Extra Small

#16827 Fix the clean block for generated proxy function
  src/System.Management.Automation/engine/CommandMetadata.cs
  test/powershell/Language/Scripting/PipelineBehaviour.Tests.ps1
Labels: CL-Engine, Extra Small

#16822 Add a couple fixes to generic method invocation
  src/System.Management.Automation/engine/CoreAdapter.cs
  src/System.Management.Automation/engine/MshMemberInfo.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/resources/ExtendedTypeSystem.resx
  test/powershell/Language/Parser/MethodInvocation.Tests.ps1
Labels: CL-Engine, Large

#16837 Fix automation to update experimental json files in GitHub action
  .github/workflows/exp-json.yml
Labels: CL-Tools, Small

#16823 Ensure alpine and arm SKUs have powershell.config.json file with experimental features enabled
  build.psm1
Labels: Extra Small

#16840 Replace FindFirstFileExW with FindFirstFileW
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-General, Backport-7.2.x-Consider, Extra Small

#16831 Update to use `windows-latest` as the build agent image
  .vsts-ci/templates/ci-build.yml
  .vsts-ci/templates/credscan.yml
  .vsts-ci/templates/nanoserver.yml
  .vsts-ci/templates/verify-xunit.yml
  .vsts-ci/templates/windows-test.yml
  .vsts-ci/windows-daily.yml
  .vsts-ci/windows/templates/windows-packaging.yml
  test/powershell/Modules/Microsoft.PowerShell.Core/CompatiblePSEditions.Module.Tests.ps1
  test/powershell/Modules/Microsoft.WSMan.Management/CredSSP.Tests.ps1
Labels: CL-BuildPackaging, Extra Small

#16849 Add newly joined members to their respective Working Groups
  .spelling
  docs/community/working-group-definitions.md
Labels: CL-Docs, Extra Small

#16860 Refactor Global Tool packaging to include SBOM generation
  tools/packaging/packaging.psd1
  tools/packaging/packaging.psm1
  tools/releaseBuild/azureDevOps/templates/global-tool-pkg-sbom.yml
  tools/releaseBuild/azureDevOps/templates/nuget.yml
Labels: CL-BuildPackaging, Large

#16781 Prevent tab completion if the word to complete is a single dash
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Extra Small

#16867 Add warning messages when package precheck fails
  tools/packaging/packaging.psm1
Labels: Extra Small

#16856 Update projects and scripts to use .NET 7 preview 1 pre-release builds
  Analyzers.props
  DotnetRuntimeMetadata.json
  PowerShell.Common.props
  assets/wix/files.wxs
  build.psm1
  global.json
  nuget.config
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/Modules/PSGalleryModules.csproj
  src/ResGen/ResGen.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/TypeCatalogGen/TypeCatalogGen.csproj
  test/Test.Common.props
  test/perf/dotnet-tools/ResultsComparer/ResultsComparer.csproj
  test/powershell/Host/Startup.Tests.ps1
  test/powershell/Modules/PackageManagement/PackageManagement.Tests.ps1
  test/powershell/Modules/PowerShellGet/PowerShellGet.Tests.ps1
  test/powershell/engine/ExperimentalFeature/Get-ExperimentalFeature.Tests.ps1
  test/tools/OpenCover/OpenCover.psm1
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
  tools/UpdateDotnetRuntime.ps1
  tools/cgmanifest.json
  tools/findMissingNotices.ps1
  tools/packaging/packaging.psm1
  tools/packaging/packaging.strings.psd1
  tools/packaging/projects/nuget/package.csproj
  tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  tools/packaging/projects/reference/Microsoft.PowerShell.ConsoleHost/Microsoft.PowerShell.ConsoleHost.csproj
  tools/packaging/projects/reference/System.Management.Automation/System.Management.Automation.csproj
  tools/releaseBuild/azureDevOps/templates/release-SDKTests.yml
Labels: Medium

#16910 Bump PSReadLine from 2.1.0 to 2.2.2
  assets/wix/files.wxs
  src/Modules/PSGalleryModules.csproj
  test/powershell/Modules/PSReadLine/PSReadLine.Tests.ps1
Labels: CL-BuildPackaging, Extra Small

#16889 Refactor module assembly loading logic to allow the whole module to be loaded in a custom ALC
  build.psm1
  src/System.Management.Automation/engine/ExecutionContext.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs
  test/powershell/engine/Module/IsolatedModule.Tests.ps1
  test/powershell/engine/Module/TestModuleManifest.Tests.ps1
  test/tools/Modules/IsolatedModule/IsolatedModule.psd1
  test/tools/TestAlc/TestAlc.sln
  test/tools/TestAlc/init/Init.cs
  test/tools/TestAlc/init/Test.Isolated.Init.csproj
  test/tools/TestAlc/nested/NestedCommand.cs
  test/tools/TestAlc/nested/Test.Isolated.Nested.csproj
  test/tools/TestAlc/root/RootCommand.cs
  test/tools/TestAlc/root/Test.Isolated.Root.csproj
Labels: CL-Engine, Extra Large

#16911 Opt-in to build security monitoring
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/releasePipeline.yml
Labels: BackPort-7.0.x-Consider, BackPort-7.1.x-Consider, Backport-7.2.x-Consider, Extra Small
