Repository PowerShell/PowerShell, pull requests merged in 2022-04, with the labels that each got.

#17141 Allow multiple installations of dotnet.
  build.psm1
  tools/cgmanifest.json
Labels: Waiting on Author, BackPort-7.0.x-Consider, Backport-7.2.x-Consider, Extra Small

#17098 Correct Typo in `PathResolvedToMultiple` error text.
  src/System.Management.Automation/resources/SessionStateStrings.resx
Labels: CL-CodeCleanup, Extra Small

#16981 Do not include node names when sending telemetry.
  src/System.Management.Automation/utils/Telemetry.cs
Labels: BackPort-7.0.x-Approved, BackPort-7.1.x-Approved, Backport-7.2.x-Approved, Extra Small

#17154 Replace illegal in notices container name
  tools/releaseBuild/azureDevOps/templates/compliance/generateNotice.yml
Labels: BackPort-7.0.x-Consider, Extra Small

#17166 Update link to PowerShell remoting in depth video
  docs/learning-powershell/powershell-beginners-guide.md
Labels: Extra Small

#17159 Use new Windows signature APIs from Microsoft.Security.Extensions package
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
  src/System.Management.Automation/System.Management.Automation.csproj
  src/System.Management.Automation/security/Authenticode.cs
  src/System.Management.Automation/security/MshSignature.cs
  src/System.Management.Automation/security/SecuritySupport.cs
  src/System.Management.Automation/security/nativeMethods.cs
  test/powershell/engine/Security/FileSignature.Tests.ps1
  tools/cgmanifest.json
Labels: BackPort-7.0.x-Consider, Backport-7.2.x-Consider, Large

#17151 Make mariner packages Framework dependent
  build.psm1
  tools/packages.microsoft.com/mapping.json
  tools/packaging/packaging.psm1
Labels: Small

#16896 Use SHA256 as digest for RPM packages (FIPS compliance)
  tools/packaging/packaging.psm1
Labels: BackPort-7.0.x-Consider, Backport-7.2.x-Consider, Extra Small

#17167 Making `NameObscurerTelemetryInitializer` internal
  src/System.Management.Automation/utils/Telemetry.cs
Labels: Extra Small

#17170 Update rebase.yml to use latest version of the action
  .github/workflows/rebase.yml
Labels: Extra Small

#17171 Update wix to include security extensions package
  assets/wix/files.wxs
Labels: Extra Small

#17174 Make a variable assignment in a `ParenExpression` to return the variable value
  src/System.Management.Automation/engine/ShellVariable.cs
  src/System.Management.Automation/engine/runtime/Operations/VariableOps.cs
  test/powershell/Language/Scripting/Scripting.Followup.Tests.ps1
Labels: Extra Small

#17180 Update package fallback list for ubuntu (from those updated for ubuntu 22.04) (deb)
  tools/packaging/packaging.psm1
Labels: Extra Small

#17189 Fix Stable Unique sort not being stable
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Sort-Object.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Sort-Object.Tests.ps1
Labels: CL-General, Extra Small

#17158 Updated metadata.json and README.md for v7.2.3 and v7.0.10
  README.md
  tools/metadata.json
Labels: CL-BuildPackaging, Small

#17207 Updated change logs for v7.0.9 / v7.0.10 / v7.1.6 / v7.1.7 / v7.2.2 / v7.2.3
  .spelling
  CHANGELOG/7.0.md
  CHANGELOG/7.1.md
  CHANGELOG/7.2.md
Labels: CL-Docs, Medium

#17212 Add backport action
  .github/workflows/backport.yml
  tools/actions/backport/action.yml
  tools/actions/backport/index.js
Labels: Medium

#17218 Change logic for determining whether PSHOME is writable.
  test/tools/Modules/HelpersCommon/HelpersCommon.psm1
Labels: Extra Small

#17220 Fixed package names verification to support multi-digit versions
  tools/releaseBuild/azureDevOps/templates/release-ValidatePackageNames.yml
Labels: Extra Small

#17198 Fixing dotnet sdk version parsing in build.psm1
  build.psm1
Labels: Extra Small

#17230 Mark `Microsoft.Management.Infrastructure.Runtime.Win` as a developer dependency to hide in notice file
  tools/cgmanifest.json
Labels: Backport-7.2.x-Done, Extra Small
