Repository PowerShell/PowerShell, pull requests merged in 2022-03, with the labels that each got.

#16935 Adding PowerShellGet Compat module to allow list of telemetry modules
  src/System.Management.Automation/utils/Telemetry.cs
Labels: CL-General, Extra Small

#16946 Add fix of process objects for processes that have exited.
  src/System.Management.Automation/engine/remoting/commands/EnterPSHostProcessCommand.cs
  src/System.Management.Automation/resources/RemotingErrorIdStrings.resx
Labels: Small

#16944 Try to stabilize a few tests that fail intermittently
  test/powershell/Modules/Microsoft.PowerShell.Core/Enter-PSHostProcess.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Diagnostics/Get-WinEvent.Tests.ps1
Labels: Extra Small

#16498 Improve hashtable completion
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/BugFix.Tests.ps1
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Large

#16958 Roll back windows images used in testing to Windows Server 2019
  .vsts-ci/templates/windows-test.yml
  .vsts-ci/windows-daily.yml
Labels: CL-BuildPackaging, Extra Small

#16956 Allow the `PSGetMemberBinder` to handle ByRef property
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  test/powershell/Language/Scripting/Adapter.Tests.ps1
Labels: Extra Small

#16957 Allow a collection with `Automation.Null` elements to be piped to pipeline
  src/System.Management.Automation/engine/Pipe.cs
  test/powershell/Language/Scripting/PipelineBehaviour.Tests.ps1
Labels: Extra Small

#16949 Fix typo in CommandHelpProvider.cs
  src/System.Management.Automation/help/CommandHelpProvider.cs
Labels: No Changes

#17013 Update `AzureFileCopy` task and fix the syntax for specifying `pool`
  tools/releaseBuild/azureDevOps/templates/release-BuildJson.yml
  tools/releaseBuild/azureDevOps/templates/release-UpdateDepsJson.yml
  tools/releaseBuild/azureDevOps/vpackRelease.yml
Labels: CL-BuildPackaging, Extra Small

#16979 Update docs for the v7.2.2 release
  README.md
  tools/metadata.json
Labels: Small

#16930 Update .NET to 7.0.0-preview.2 build
  DotnetRuntimeMetadata.json
  assets/wix/files.wxs
  build.psm1
  global.json
  nuget.config
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  test/powershell/Host/Startup.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1
  test/powershell/Modules/PackageManagement/PackageManagement.Tests.ps1
  test/powershell/Modules/PowerShellGet/PowerShellGet.Tests.ps1
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
  test/xUnit/csharp/test_NativeInterop.cs
  tools/cgmanifest.json
  tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  tools/packaging/projects/reference/System.Management.Automation/System.Management.Automation.csproj
Labels: Review - Needed, Medium

#17014 Simplify enum generator for bnot operator test.
  test/powershell/Language/Parser/BNotOperator.Tests.ps1
Labels: Extra Small

#17007 Do not pull dotnet updates from internal feed.
  .github/workflows/daily.yml
Labels: Area-Maintainers-Build, Extra Small

#17003 Fix Untill typo in names of method
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/OutGridViewCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/OutWindowProxy.cs
  src/System.Management.Automation/engine/TypeTable.cs
Labels: Extra Small

#17030 Add a `-because` to the failing condition to aid in debugging.
  test/powershell/engine/Help/HelpSystem.Tests.ps1
Labels: Extra Small

#17027 Remove `EventLogLogProvider` and its related legacy code
  src/System.Management.Automation/System.Management.Automation.csproj
  src/System.Management.Automation/logging/MshLog.cs
  src/System.Management.Automation/logging/eventlog/EventLogLogProvider.cs
  src/System.Management.Automation/utils/PowerShellExecutionHelper.cs
Labels: CL-CodeCleanup, Large

#17029 Update `readme.md` and `metadata.json` for v7.3.0-preview.3 release
  README.md
  tools/metadata.json
Labels: Extra Small

#17045 Merge the v7.3.0-preview.3 release branch back to master
  .spelling
  CHANGELOG/preview.md
Labels: CL-Docs, Extra Small

#17011 Add Custom Remote Connections Feature
  build.psm1
  src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs
  src/System.Management.Automation/engine/hostifaces/Connection.cs
  src/System.Management.Automation/engine/hostifaces/ConnectionFactory.cs
  src/System.Management.Automation/engine/remoting/client/RemoteRunspacePoolInternal.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspace.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspaceinfo.cs
  src/System.Management.Automation/engine/remoting/commands/newrunspacecommand.cs
  src/System.Management.Automation/engine/remoting/common/RemoteSessionNamedPipe.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
  src/System.Management.Automation/engine/remoting/fanin/BaseTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManTransportManager.cs
  src/System.Management.Automation/engine/remoting/server/OutOfProcServerMediator.cs
  src/System.Management.Automation/resources/RemotingErrorIdStrings.resx
  src/System.Management.Automation/utils/CryptoUtils.cs
  test/powershell/engine/Api/BasicEngine.Tests.ps1
  test/powershell/engine/Remoting/CustomConnection.Tests.ps1
  test/tools/NamedPipeConnection/build.ps1
  test/tools/NamedPipeConnection/doBuild.ps1
  test/tools/NamedPipeConnection/nuget.config
  test/tools/NamedPipeConnection/src/Microsoft.PowerShell.NamedPipeConnection.psd1
  test/tools/NamedPipeConnection/src/code/Microsoft.PowerShell.NamedPipeConnection.csproj
  test/tools/NamedPipeConnection/src/code/NamedPipeConnection.cs
  test/tools/NamedPipeConnection/test/CustomConnection.Tests.ps1
Labels: Extra Large

#15257 Prioritize validateset completions over Enums for parameters.
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Small

#16663 Fix for Stop-Service failure with less privileged user when not setting SDDL.
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
Labels: Review - Needed, CL-General, Extra Small

#16962 Add OutputType attribute to various commands
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/TimeZoneCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertTo-Html.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/TestJsonCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Var.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertToJsonCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/InvokeWebRequestCommand.CoreClr.cs
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
  src/Microsoft.WSMan.Management/CredSSP.cs
  src/Microsoft.WSMan.Management/InvokeWSManAction.cs
  src/Microsoft.WSMan.Management/NewWSManSession.cs
  src/Microsoft.WSMan.Management/PingWSMan.cs
  src/Microsoft.WSMan.Management/Set-QuickConfig.cs
  src/Microsoft.WSMan.Management/WSManInstance.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/namespaces/RegistryProvider.cs
Labels: Extra Small

#16504 Improve member completion
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: WG-Interactive-IntelliSense, CL-General, Large

#16811 Update regex used to remove ANSI escape sequences to be more specific to decoration and hyperlinks
  src/System.Management.Automation/FormatAndOutput/common/PSStyle.cs
  src/System.Management.Automation/FormatAndOutput/common/StringDecorated.cs
  test/powershell/engine/Formatting/PSStyle.Tests.ps1
Labels: Review - Needed, WG-Security, Backport-7.2.x-Consider, Extra Small

#17056 Create checksum file for global tools
  tools/releaseBuild/azureDevOps/templates/nuget.yml
Labels: BackPort-7.0.x-Consider, BackPort-7.1.x-Consider, Backport-7.2.x-Consider, Extra Small

#17057 Add mariner 1.0 amd64 package
  tools/packaging/packaging.psm1
  tools/packaging/releaseTests/sbom.tests.ps1
  tools/releaseBuild/azureDevOps/releasePipeline.yml
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-build.yml
  tools/releaseBuild/azureDevOps/templates/release-ValidatePackageBOM.yml
  tools/releaseBuild/azureDevOps/templates/release-ValidatePackageNames.yml
Labels: Backport-7.2.x-Consider, Large

#17062 Re-enable PowerShellGet tests targeting PowerShell gallery
  test/powershell/Modules/PackageManagement/PackageManagement.Tests.ps1
  test/powershell/Modules/PowerShellGet/PowerShellGet.Tests.ps1
Labels: CL-Test

#16948 Ignore failure attempting to set console window title
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs
Labels: Review - Needed, Extra Small

#17086 Update dotnet-install script download link
  build.psm1
Labels: BackPort-7.0.x-Consider, BackPort-7.1.x-Consider, Backport-7.2.x-Consider, Extra Small
