Repository PowerShell/PowerShell, pull requests merged in 2022-06, with the labels that each got.

#17463 Fix formatting to act appropriately when the style of table header or list label is empty string
  src/System.Management.Automation/FormatAndOutput/common/ListWriter.cs
  src/System.Management.Automation/FormatAndOutput/common/PSStyle.cs
  src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs
  test/powershell/engine/Formatting/PSStyle.Tests.ps1
Labels: CL-Engine, Extra Small

#17472 Update dotnet-runtime version
  tools/packaging/packaging.psm1
Labels: Extra Small

#17471 Update Get-Error test to not depend on DNS APIs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Error.Tests.ps1
Labels: Extra Small

#17365 Fix native library loading for osx-arm64
  src/System.Management.Automation/CoreCLR/CorePsAssemblyLoadContext.cs
Labels: Review - Needed, CL-Engine, Backport-7.2.x-Consider, Extra Small

#17480 Fix some typos.
  build.psm1
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
  test/powershell/Language/Operators/PipelineChainOperator.Tests.ps1
  test/powershell/Language/Parser/Parser.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Copy-Item.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Wait-Event.Tests.ps1
  test/tools/Modules/PSSysLog/PSSysLog.psm1
  tools/UpdateDotnetRuntime.ps1
  tools/performance/JIT.Regions.xml
Labels: Extra Small

#17481 Fix some typos in src/.
  src/Microsoft.Management.UI.Internal/ManagementList/Common/KeyboardHelp.cs
  src/Microsoft.Management.UI.Internal/ManagementList/Common/ListOrganizerItem.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterProviders/FilterRuleTemplateSelector.cs
  src/Microsoft.Management.UI.Internal/commandHelpers/HelpWindowHelper.cs
  src/Microsoft.Management.UI.Internal/commandHelpers/ShowCommandHelper.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Eventlog.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetContentCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertFromJsonCommand.cs
  src/Microsoft.PowerShell.ScheduledJob/ScheduledJobStore.cs
  src/Microsoft.WSMan.Management/CurrentConfigurations.cs
  src/Schemas/PSMaml/Maml_HTML_Style.xsl
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/FormatTable.cs
  src/System.Management.Automation/FormatAndOutput/common/ListWriter.cs
  src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs
  src/System.Management.Automation/engine/ComInterop/ComRuntimeHelpers.cs
  src/System.Management.Automation/engine/ComInterop/VarEnumSelector.cs
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/engine/CommandSearcher.cs
  src/System.Management.Automation/engine/CoreAdapter.cs
  src/System.Management.Automation/engine/ExternalScriptInfo.cs
  src/System.Management.Automation/engine/Modules/PSModuleInfo.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/TransactedString.cs
  src/System.Management.Automation/engine/hostifaces/ConnectionBase.cs
  src/System.Management.Automation/engine/hostifaces/History.cs
  src/System.Management.Automation/engine/hostifaces/LocalConnection.cs
  src/System.Management.Automation/engine/hostifaces/NativeCultureResolver.cs
  src/System.Management.Automation/engine/hostifaces/PSDataCollection.cs
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
  src/System.Management.Automation/engine/hostifaces/RunspacePoolInternal.cs
  src/System.Management.Automation/engine/hostifaces/pipelinebase.cs
  src/System.Management.Automation/engine/interpreter/ControlFlowInstructions.cs
  src/System.Management.Automation/engine/lang/scriptblock.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
  src/System.Management.Automation/engine/remoting/client/Job2.cs
  src/System.Management.Automation/engine/remoting/client/clientremotesessionprotocolstatemachine.cs
  src/System.Management.Automation/engine/remoting/client/remotepipeline.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspace.cs
  src/System.Management.Automation/engine/remoting/commands/PushRunspaceCommand.cs
  src/System.Management.Automation/engine/remoting/commands/ReceivePSSession.cs
  src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
  src/System.Management.Automation/engine/remoting/server/ServerSteppablePipelineSubscriber.cs
  src/System.Management.Automation/engine/remoting/server/serverremotesession.cs
  src/System.Management.Automation/help/BaseCommandHelpInfo.cs
  src/System.Management.Automation/help/HelpUtils.cs
  src/System.Management.Automation/help/MamlCommandHelpInfo.cs
  src/System.Management.Automation/help/MamlNode.cs
  src/System.Management.Automation/help/PSClassHelpProvider.cs
  src/System.Management.Automation/help/ProviderHelpInfo.cs
  src/System.Management.Automation/namespaces/FileSystemContentStream.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/namespaces/FileSystemSecurity.cs
  src/System.Management.Automation/namespaces/LocationGlobber.cs
  src/System.Management.Automation/namespaces/TransactedRegistryKey.cs
  src/System.Management.Automation/utils/ClrFacade.cs
  src/System.Management.Automation/utils/tracing/SysLogProvider.cs
  src/powershell-native/Install-PowerShellRemoting.ps1
Labels: CL-CodeCleanup, Extra Small

#17376 Use AST extent for `PSScriptRoot` path completion
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Extra Small

#17447 Add local session configuration -ConfigurationFile cmd line parameter to pwsh
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleShell.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ManagedEntrance.cs
  src/Microsoft.PowerShell.ConsoleHost/resources/CommandLineParameterParserStrings.resx
  src/Microsoft.PowerShell.ConsoleHost/resources/ConsoleHostStrings.resx
  src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/remoting/commands/NewPSSessionConfigurationFile.cs
  src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
  src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPlugin.cs
  src/System.Management.Automation/engine/remoting/server/OutOfProcServerMediator.cs
  src/System.Management.Automation/engine/remoting/server/serverremotesession.cs
  src/System.Management.Automation/resources/ConsoleInfoErrorStrings.resx
  src/System.Management.Automation/resources/RemotingErrorIdStrings.resx
  test/SSHRemoting/SSHRemoting.Basic.Tests.ps1
  test/hosting/test_HostingBasic.cs
  test/powershell/engine/Basic/DefaultCommands.Tests.ps1
  test/tools/Modules/HelpersRemoting/HelpersRemoting.psm1
  test/tools/Modules/Microsoft.PowerShell.RemotingTools/Microsoft.PowerShell.RemotingTools.psm1
  test/xUnit/csharp/test_CommandLineParser.cs
Labels: Committee-Reviewed, Extra Large

#17078 Enable completions for blank between comma and something
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: Review - Needed, Small

#17486 Fix operator completion
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Small

#17442 Make `AnsiRegex` able to capture Hyperlink ansi sequences
  src/System.Management.Automation/FormatAndOutput/common/StringDecorated.cs
  test/powershell/engine/Formatting/PSStyle.Tests.ps1
Labels: Review - Needed, Extra Small

#17477 Add Amended switch to Get-CimClass cmdlet
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimGetCimClass.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/GetCimClassCommand.cs
  test/powershell/Modules/CimCmdlets/Get-CimClass.Tests.ps1
Labels: CL-General, Extra Small

#17489 Fix various completion issues inside the param block
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Extra Small

#17505 Rename mariner package to cm
  tools/packages.microsoft.com/mapping.json
  tools/packaging/packaging.psm1
  tools/packaging/releaseTests/sbom.tests.ps1
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/release-ValidatePackageNames.yml
Labels: Backport-7.2.x-Consider, Extra Small

#17515 Downgrade the `Microsoft.CodeAnalysis.NetAnalyzers` package to `7.0.0-preview1.22217.1`
  Analyzers.props
Labels: Extra Small

#16963 Improve type inference and completions
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  src/System.Management.Automation/engine/parser/ast.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Security/ConstrainedLanguageRestriction.Tests.ps1
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: Medium

#17532 Disable RPM SBOM test.
  tools/packaging/releaseTests/sbom.tests.ps1
Labels: Backport-7.2.x-Consider

#17526 Update `README.md` and `metadata.json` for upcoming releases
  README.md
  tools/metadata.json
Labels: Small

#13799 Show optional parameters as such when dislplaying method definition and overloads
  src/System.Management.Automation/engine/CoreAdapter.cs
  test/powershell/engine/Api/GetMethodInfoOverloadDefinition.Tests.ps1
Labels: Review - Needed, CL-General, Hacktoberfest-Accepted

#17595 Update to use PSReadLine v2.2.6
  src/Modules/PSGalleryModules.csproj
Labels: CL-BuildPackaging, Extra Small

#17600 Install .NET 3.1 as it is required by the vPack task
  tools/releaseBuild/azureDevOps/templates/vpackReleaseJob.yml
Labels: Extra Small
