Repository PowerShell/PowerShell, pull requests merged in 2022-07, with the labels that each got.

#17625 link check github action reports error as katacoda.com now returns 404.
  docs/git/basics.md
Labels: Extra Small

#17630 Update `DotnetMetadata.json` to start consuming .NET 7 Preview 6 builds
  DotnetRuntimeMetadata.json
Labels: Extra Small

#17620 Use discard where possible
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Update-TypeData.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostRawUserInterface.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/Executor.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/Serialization.cs
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/ExecutionContext.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs
  src/System.Management.Automation/engine/ScriptCommandProcessor.cs
  src/System.Management.Automation/engine/SessionStateContainer.cs
  src/System.Management.Automation/engine/SessionStateNavigation.cs
  src/System.Management.Automation/engine/SessionStateVariableAPIs.cs
  src/System.Management.Automation/engine/TypeTable.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/parser/VariableAnalysis.cs
  src/System.Management.Automation/engine/parser/ast.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  src/System.Management.Automation/utils/PsUtils.cs
Labels: CL-CodeCleanup, Medium

#17632 Set the compound assignment preference to false
  .editorconfig
Labels: CL-BuildPackaging, Extra Small

#17560 Set-AuthenticodeSignature hash default to SHA256
  src/Microsoft.PowerShell.Security/security/SignatureCommands.cs
Labels: Extra Small

#17621 Add Milliseconds Parameter to New-TimeSpan
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/NewTimeSpanCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/New-TimeSpan.Tests.ps1
Labels: CL-General, Extra Small

#17664 Remove potential ANSI escape sequences in strings before using in `Out-GridView`
  src/Microsoft.Management.UI.Internal/commandHelpers/OutGridView.cs
Labels: CL-General, Extra Small

#17405 Change `ConvertFrom-Json -AsHashtable` to use ordered hashtable
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs
  src/System.Management.Automation/engine/OrderedHashtable.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertFrom-Json.Tests.ps1
  test/powershell/engine/OrderedHashtable.Tests.ps1
Labels: WG-Cmdlets, CL-General, Medium

#17669 Fix comment in InternalCommands.cs
  src/System.Management.Automation/engine/InternalCommands.cs
Labels: CL-CodeCleanup, No Changes

#17671 Fix `Export-PSSession` to not throw error when a rooted path is specified for `-OutputModule`
  src/System.Management.Automation/resources/PathUtilsStrings.resx
  src/System.Management.Automation/utils/PathUtils.cs
Labels: CL-General, BackPort-7.0.x-Consider, Backport-7.2.x-Consider, Extra Small

#17675 Create test artifacts for windows arm64
  tools/releaseBuild/azureDevOps/templates/testartifacts.yml
Labels: Extra Small

#17678 Fix SDK tests for release build
  tools/releaseBuild/azureDevOps/templates/release-SDKTests.yml
Labels: Extra Small

#17650 Render decimal numbers in a table using current culture
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator_Table.cs
  src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-List.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1
Labels: Small

#17693 Avoid binding positional parameters when completing parameter in front of value
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: Extra Small

#17676 Updating `README` and `metadata.json` for next release
  README.md
  tools/metadata.json
Labels: Extra Small

#17661 Improve dynamic parameter tab completion
  src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Extra Small

#17705 Fix legacy `$ErrorView` types to use `$host.PrivateData` colors
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
Labels: CL-General, Extra Small

#17670 Remove `PSNativePSPathResolution` experimental feature
  experimental-feature-linux.json
  experimental-feature-windows.json
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/NativeCommandParameterBinder.cs
  test/powershell/Language/Scripting/NativeExecution/NativeCommandArguments.Tests.ps1
Labels: Large

#17535 Fix #16929 do not show profile load time msg with new pwsh parameter
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx
Labels: WG-Interactive-Console, CL-General, Extra Small

#17708 Do not always collapse space between parameter and value for native args
  src/System.Management.Automation/engine/NativeCommandParameterBinder.cs
  test/powershell/Language/Scripting/NativeExecution/NativeCommandArguments.Tests.ps1
Labels: Extra Small

#17484 Fix type completion for attribute tokens
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: Review - Needed, Extra Small

#16745 Fix parser exception in using statements with empty aliases
  src/System.Management.Automation/engine/parser/Parser.cs
  test/powershell/Language/Parser/Parsing.Tests.ps1
Labels: Review - Needed, CL-Engine, Extra Small

#17709 Bump `PackageManagement` from 1.4.7 to 1.4.8.1
  assets/wix/files.wxs
  src/Modules/PSGalleryModules.csproj
Labels: CL-BuildPackaging, Extra Small

#17572 Fix enum-ranges for ValidateRange in proxy commands
  src/System.Management.Automation/engine/TypeMetadata.cs
  test/powershell/engine/Basic/ProxyCommand.tests.ps1
Labels: CL-General, Extra Small

#17619 Add completion for index expressions for dictionaries
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Medium

#17714 Fix typo in ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
Labels: CL-CodeCleanup

#17715 Add find.exe to legacy native command arg passing behavior for Windows
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  test/powershell/Language/Scripting/NativeExecution/NativeCommandArguments.Tests.ps1
Labels: CL-General

#17704 Change `Get-ChildItem` to treat trailing slash in path as indicating a directory when used with `-Recurse`
  src/System.Management.Automation/engine/SessionStateContainer.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1
Labels: CL-General, Extra Small

#17738 Re-enable the test `TestLoadNativeInMemoryAssembly`
  test/xUnit/csharp/test_NativeInterop.cs
Labels: CL-Test

#17719 Use compound assignment in /Microsoft.Management
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimAsyncOperation.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimCommandBase.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
Labels: CL-CodeCleanup

#17721 Use null-coalescing assignment in /Microsoft.WSMan
  src/Microsoft.WSMan.Management/WSManConnections.cs
Labels: CL-CodeCleanup

#17725 Use null-coalescing assignment in /System.Management.Automation.utils
  src/System.Management.Automation/utils/CommandDiscoveryExceptions.cs
  src/System.Management.Automation/utils/ExecutionExceptions.cs
  src/System.Management.Automation/utils/MshArgumentException.cs
  src/System.Management.Automation/utils/MshArgumentNullException.cs
  src/System.Management.Automation/utils/MshArgumentOutOfRangeException.cs
  src/System.Management.Automation/utils/MshInvalidOperationException.cs
  src/System.Management.Automation/utils/MshNotImplementedException.cs
  src/System.Management.Automation/utils/MshNotSupportedException.cs
  src/System.Management.Automation/utils/MshObjectDisposedException.cs
  src/System.Management.Automation/utils/ObjectStream.cs
  src/System.Management.Automation/utils/ParameterBinderExceptions.cs
  src/System.Management.Automation/utils/RuntimeException.cs
  src/System.Management.Automation/utils/SessionStateExceptions.cs
Labels: CL-CodeCleanup

#17726 Use null-coalescing assignment in /parser and /debugger
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/parser/SafeValues.cs
  src/System.Management.Automation/engine/parser/TypeResolver.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
Labels: CL-CodeCleanup

#17724 Use null-coalescing assignment in /System.Management.Automation
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/FormatAndOutput/common/BaseOutputtingCommand.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_List.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Wide.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator_Complex.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator_Table.cs
  src/System.Management.Automation/FormatAndOutput/common/ListWriter.cs
  src/System.Management.Automation/FormatAndOutput/common/StringDecorated.cs
  src/System.Management.Automation/FormatAndOutput/common/Utilities/Mshexpression.cs
  src/System.Management.Automation/help/BaseCommandHelpInfo.cs
  src/System.Management.Automation/help/ProviderHelpInfo.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/namespaces/NavigationProviderBase.cs
  src/System.Management.Automation/namespaces/RegistryProvider.cs
  src/System.Management.Automation/security/SecureStringHelper.cs
  src/System.Management.Automation/security/wldpNativeMethods.cs
  src/System.Management.Automation/singleshell/config/MshSnapinInfo.cs
Labels: CL-CodeCleanup

#17723 Use null-coalescing assignment in Microsoft.PowerShell.ConsoleHost/Security
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/Executor.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/PendingProgress.cs
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
  src/Microsoft.PowerShell.Security/security/SignatureCommands.cs
Labels: CL-General

#17720 Use null-coalescing assignment in /engine
  src/System.Management.Automation/engine/CompiledCommandParameter.cs
  src/System.Management.Automation/engine/CoreAdapter.cs
  src/System.Management.Automation/engine/ErrorPackage.cs
  src/System.Management.Automation/engine/ExecutionContext.cs
  src/System.Management.Automation/engine/ExtendedTypeSystemException.cs
  src/System.Management.Automation/engine/GetCommandCommand.cs
  src/System.Management.Automation/engine/InformationRecord.cs
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  src/System.Management.Automation/engine/MshMemberInfo.cs
  src/System.Management.Automation/engine/MshObject.cs
  src/System.Management.Automation/engine/MshObjectTypeDescriptor.cs
  src/System.Management.Automation/engine/MshSecurityException.cs
  src/System.Management.Automation/engine/ParameterBinderBase.cs
  src/System.Management.Automation/engine/Pipe.cs
  src/System.Management.Automation/engine/SessionStateContainer.cs
  src/System.Management.Automation/engine/SessionStateLocationAPIs.cs
  src/System.Management.Automation/engine/SessionStateProviderAPIs.cs
  src/System.Management.Automation/engine/SessionStateScope.cs
  src/System.Management.Automation/engine/TypeTable.cs
  src/System.Management.Automation/engine/pipeline.cs
Labels: CL-CodeCleanup

#17741 Fix Test-Json not handling non-object types at root
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/TestJsonCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Test-Json.Tests.ps1
Labels: CL-General

#17752 Fix type infeerence for ICollection
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: CL-General

#17751 Prevent braces from being removed when completing variables
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General

#17749 Fix test performance by stopping ongoing progress-bar
  test/powershell/Language/Scripting/ActionPreference.Tests.ps1
Labels: CL-Test

#17728 Use null-coalescing assignment in /remoting and /hostifaces
  src/System.Management.Automation/engine/hostifaces/AsyncResult.cs
  src/System.Management.Automation/engine/hostifaces/LocalConnection.cs
  src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs
  src/System.Management.Automation/engine/hostifaces/PSDataCollection.cs
  src/System.Management.Automation/engine/hostifaces/PSTask.cs
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
  src/System.Management.Automation/engine/hostifaces/RunspacePoolInternal.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
  src/System.Management.Automation/engine/remoting/client/Job2.cs
  src/System.Management.Automation/engine/remoting/client/RunspaceRef.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspace.cs
  src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs
  src/System.Management.Automation/engine/remoting/commands/ReceiveJob.cs
  src/System.Management.Automation/engine/remoting/commands/getrunspacecommand.cs
  src/System.Management.Automation/engine/remoting/commands/newrunspacecommand.cs
  src/System.Management.Automation/engine/remoting/common/psstreamobject.cs
  src/System.Management.Automation/engine/remoting/fanin/BaseTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
  src/System.Management.Automation/engine/remoting/fanin/PSSessionConfigurationData.cs
  src/System.Management.Automation/engine/remoting/server/OutOfProcServerMediator.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
Labels: CL-CodeCleanup

#17716 Improve type inference for $_
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: CL-General

#15684 Remove pre-parse for array-based JSON
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertFrom-Json.Tests.ps1
Labels: CL-General, Extra Small

#15873 Fix FileSystemProvider to work with volume and pipe paths
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1
Labels: Waiting on Author, Extra Small

#17727 Use null-coalescing assignment in /interpreter and /runtime
  src/System.Management.Automation/engine/interpreter/BranchLabel.cs
  src/System.Management.Automation/engine/interpreter/ControlFlowInstructions.cs
  src/System.Management.Automation/engine/interpreter/InstructionFactory.cs
  src/System.Management.Automation/engine/interpreter/InstructionList.cs
  src/System.Management.Automation/engine/interpreter/LabelInfo.cs
  src/System.Management.Automation/engine/interpreter/LightCompiler.cs
  src/System.Management.Automation/engine/interpreter/LocalVariables.cs
  src/System.Management.Automation/engine/interpreter/LoopCompiler.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
  src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs
Labels: CL-CodeCleanup

#17722 Use null-coalescing assignment in /Microsoft.PowerShell.Commands
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimChildJobBase.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimWrapper.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetComputerInfoCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/MovePropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/WriteContentCommandBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertTo-Html.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/TableView.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetUnique.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Group-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Measure-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/OrderObjectBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/PSBreakpointCommandBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Update-List.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Var.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/BasicHtmlWebResponseObject.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebResponseObject.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/StreamHelper.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/WebRequestSession.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Write.cs
Labels: CL-CodeCleanup

#16355 Move psxml type definitions from SMA to Security module
  src/Modules/Windows/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.psd1
  src/Modules/Windows/Microsoft.PowerShell.Security/Security.types.ps1xml
  src/System.Management.Automation/engine/TypeTable_Types_Ps1Xml.cs
  test/powershell/Host/Startup.Tests.ps1
  test/powershell/engine/ETS/TypeTable.Tests.ps1
Labels: Breaking-Change, CL-Performance, Large

#17770 Suppress IDE0031 to take .NET 7 Preview 7
  .editorconfig
Labels: CL-CodeCleanup

#16415 Adding VBS feature names to Get-ComputerInfo
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetComputerInfoCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-ComputerInfo.Tests.ps1
Labels: CL-General, Extra Small

#17729 Use null-coalescing assignment in the rest of /engine
  src/System.Management.Automation/engine/CmdletInfo.cs
  src/System.Management.Automation/engine/CmdletParameterBinderController.cs
  src/System.Management.Automation/engine/ComInterop/ComEventsSink.Extended.cs
  src/System.Management.Automation/engine/ComInterop/ComInvokeBinder.cs
  src/System.Management.Automation/engine/ComInterop/ComTypeClassDesc.cs
  src/System.Management.Automation/engine/ComInterop/IDispatchComObject.cs
  src/System.Management.Automation/engine/ComInterop/InteropServices/ComEventsMethod.cs
  src/System.Management.Automation/engine/ComInterop/SplatCallSite.cs
  src/System.Management.Automation/engine/ComInterop/TypeUtils.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/engine/CommandParameter.cs
  src/System.Management.Automation/engine/CommandPathSearch.cs
  src/System.Management.Automation/engine/CommandProcessorBase.cs
  src/System.Management.Automation/engine/CommandSearcher.cs
  src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs
  src/System.Management.Automation/engine/Modules/NewModuleManifestCommand.cs
Labels: CL-CodeCleanup

#17779 Fix the definition of the `PDH_COUNTER_INFO` struct
  src/Microsoft.PowerShell.Commands.Diagnostics/PdhHelper.cs
Labels: CL-General

#17789 Use null propagation operator in /engine
  src/System.Management.Automation/engine/COM/ComTypeInfo.cs
  src/System.Management.Automation/engine/CmdletParameterBinderController.cs
  src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs
  src/System.Management.Automation/engine/CommandInfo.cs
  src/System.Management.Automation/engine/EventManager.cs
  src/System.Management.Automation/engine/ExecutionContext.cs
  src/System.Management.Automation/engine/InternalCommands.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/MshCmdlet.cs
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  src/System.Management.Automation/engine/NativeCommand.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/ParameterBinderBase.cs
  src/System.Management.Automation/engine/Pipe.cs
  src/System.Management.Automation/engine/SessionStateVariableAPIs.cs
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/hostifaces/AsyncResult.cs
  src/System.Management.Automation/engine/hostifaces/InternalHostUserInterface.cs
  src/System.Management.Automation/engine/hostifaces/LocalConnection.cs
  src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs
  src/System.Management.Automation/engine/hostifaces/PSCommand.cs
  src/System.Management.Automation/engine/hostifaces/PSDataCollection.cs
  src/System.Management.Automation/engine/hostifaces/PSTask.cs
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
  src/System.Management.Automation/engine/lang/scriptblock.cs
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/parser/PreOrderVisitor.cs
  src/System.Management.Automation/engine/parser/SymbolResolver.cs
  src/System.Management.Automation/engine/parser/TypeResolver.cs
  src/System.Management.Automation/engine/parser/VariableAnalysis.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
  src/System.Management.Automation/engine/pipeline.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
Labels: CL-CodeCleanup

#17784 Reenable compound assignment preference
  .editorconfig
  src/System.Management.Automation/singleshell/config/MshSnapinInfo.cs
  src/System.Management.Automation/utils/tracing/PSSysLogProvider.cs
  src/System.Management.Automation/utils/tracing/SysLogProvider.cs
  test/tools/WebListener/Controllers/RetryController.cs
Labels: CL-CodeCleanup
