Repository PowerShell/PowerShell, pull requests merged in 2022-12, with the labels that each got.

#18695 Switch `$PSNativeCommandUseErrorActionPreference` to `$true` when feature is enabled
  src/System.Management.Automation/engine/InitialSessionState.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Write-Error.Tests.ps1
Labels: Committee-Reviewed, Extra Small

#18693 Fix `SuspiciousContentChecker.Match` to detect a pre-defined string when the text starts with it
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
  test/powershell/engine/Api/SuspiciousContentChecker.Tests.ps1
Labels: CL-General, Extra Small, Backport-7.3.x-Consider

#18710 Fix Process CommandLine on Linux
  src/System.Management.Automation/engine/TypeTable_Types_Ps1Xml.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-Process.Tests.ps1
Labels: Extra Small

#18690 Replace DllImport with LibraryImport for WNetGetConnection
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/Interop/Windows/Errors.cs
  src/System.Management.Automation/engine/Interop/Windows/NetShareEnum.cs
  src/System.Management.Automation/engine/Interop/Windows/WNetGetConnection.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-CodeCleanup, Medium

#18722 Use File.OpenHandle() instead CreateFileW pinvoke
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
Labels: CL-CodeCleanup, Small

#18721 Replace `DllImport` with `LibraryImport` for WNetAddConnection2
  src/System.Management.Automation/engine/Interop/Windows/WNetAddConnection2.cs
  src/System.Management.Automation/engine/Interop/Windows/WNetCancelConnection2.cs
  src/System.Management.Automation/engine/Interop/Windows/WNetGetConnection.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-CodeCleanup, Medium

#18591 Add `testexe.exe -echocmdline` to output raw command line received by the process on Windows
  test/tools/TestExe/TestExe.cs
Labels: CL-Test, Extra Small

#18732 Remove one CreateFileW
  src/System.Management.Automation/utils/PlatformInvokes.cs
Labels: CL-CodeCleanup, Extra Small

#18605 Allow non-default encodings to be used in user's script/code
  src/System.Management.Automation/engine/AutomationEngine.cs
  src/System.Management.Automation/utils/ClrFacade.cs
  src/System.Management.Automation/utils/EncodingUtils.cs
  test/powershell/Host/Startup.Tests.ps1
  test/powershell/Language/Scripting/Scripting.Followup.Tests.ps1
Labels: CL-Engine, Extra Small

#18746 Add output types to Format commands
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-list/Format-List.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-object/Format-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-table/Format-Table.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-wide/Format-Wide.cs
Labels: CL-General, Extra Small

#18703 WebResponseObject.Common merge partials atomic commits
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebResponseObject.Common.cs
Labels: CL-CodeCleanup, Small

#18634 Fix `New-Item -ItemType Hardlink` to resolve target to absolute path and not allow link to itself
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/resources/FileSystemProviderStrings.resx
  test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
Labels: Review - Needed, Extra Small

#18780 Update readme and metadata form 7.3.1 and 7.2.8 release
  README.md
  tools/metadata.json
Labels: Small

#18736 InvokeRestMethodCommand.Common cleanup and merge partials
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
Labels: Review - Needed, CL-CodeCleanup, Medium

#18785 Cleanup webresponseobject.common
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebResponseObject.Common.cs
Labels: CL-CodeCleanup, Extra Small

#18717 WebCmdlets get Retry-After from headers if StatusCode is 429
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
Labels: Extra Small

#18727 Add Instrumentation to AmsiUtil and make the init variable readonly
  src/PowerShell.Core.Instrumentation/PowerShell.Core.Instrumentation.man
  src/System.Management.Automation/engine/remoting/common/PSETWTracer.cs
  src/System.Management.Automation/logging/LogProvider.cs
  src/System.Management.Automation/security/SecuritySupport.cs
  src/System.Management.Automation/utils/tracing/PSEtwLog.cs
  src/System.Management.Automation/utils/tracing/PSEtwLogProvider.cs
  src/System.Management.Automation/utils/tracing/PSSysLogProvider.cs
Labels: Backport-5.1-Consider, CL-Engine, Small, Backport-7.3.x-Consider

#18786 Bump .NET SDK to version 7.0.101
  DotnetRuntimeMetadata.json
  assets/wix/files.wxs
  global.json
  src/Microsoft.PowerShell.Commands.Diagnostics/Microsoft.PowerShell.Commands.Diagnostics.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  test/tools/WebListener/WebListener.csproj
Labels: Extra Small

#18795 Remove TabExpansion from PSv2 remote session configuration
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/EncodeAndDecode.cs
  src/System.Management.Automation/engine/remoting/server/serverremotesession.cs
Labels: Medium

#18751 Unify CreateFile pinvoke in SMA
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
  src/System.Management.Automation/engine/Interop/Windows/CreateFile.cs
  src/System.Management.Automation/engine/Interop/Windows/Errors.cs
  src/System.Management.Automation/engine/Interop/Windows/FindExecutable.cs
  src/System.Management.Automation/engine/Interop/Windows/FindFirstFile.cs
  src/System.Management.Automation/engine/remoting/common/RemoteSessionNamedPipe.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/utils/PathUtils.cs
Labels: CL-CodeCleanup, Large

#18596 Cleanup webrequestpscmdlet.common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
Labels: CL-CodeCleanup, Large

#18794 Use Pattern matching in ast.cs
  src/System.Management.Automation/engine/parser/ast.cs
Labels: CL-CodeCleanup, Small

#18799 Update the next release tag in `metadata.json` for next preview
  src/System.Management.Automation/engine/PSVersionInfo.cs
  test/powershell/Host/PSVersionTable.Tests.ps1
  test/powershell/Language/Scripting/Requires.Tests.ps1
  tools/metadata.json
Labels: Extra Small

#18806 Remove unnecessary reference to `System.Runtime.CompilerServices.Unsafe`
  src/System.Management.Automation/System.Management.Automation.csproj
Labels: Extra Small, Backport-7.3.x-Consider

#18805 Bump `Microsoft.PowerShell.Native` to the latest preview version `v7.4.0-preview.1`
  src/System.Management.Automation/System.Management.Automation.csproj
Labels: Extra Small

#18792 Replace ArgumentNullException(nameof()) -> ArgumentNullException.ThrowIfNull() 2
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimRegisterCimIndication.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/Utils.cs
  src/Microsoft.Management.UI.Internal/ManagementList/Common/WpfHelp.cs
  src/Microsoft.Management.UI.Internal/ManagementList/ManagementList/DefaultStringConverter.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/ViewModel/AllModulesViewModel.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/SessionBasedWrapper.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/EventProviderTraceListener.cs
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/System.Management.Automation/CoreCLR/CorePsAssemblyLoadContext.cs
  src/System.Management.Automation/engine/ComInterop/Helpers.cs
  src/System.Management.Automation/engine/DefaultCommandRuntime.cs
  src/System.Management.Automation/engine/GetCommandCommand.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/PSClassInfo.cs
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/lang/scriptblock.cs
  src/System.Management.Automation/engine/parser/SafeValues.cs
  src/System.Management.Automation/engine/remoting/commands/JobRepository.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/namespaces/TransactedRegistryKey.cs
  src/System.Management.Automation/utils/BackgroundDispatcher.cs
  src/System.Management.Automation/utils/ParserException.cs
  src/System.Management.Automation/utils/perfCounters/CounterSetRegistrarBase.cs
Labels: CL-General, Small

#18818 Fix reference assembly generation logic for Microsoft.PowerShell.Commands.Utility
  .vsts-ci/windows/templates/windows-packaging.yml
  tools/packaging/packaging.psm1
Labels: Extra Small

#16514 Add completion for Using keywords
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/resources/TabCompletionStrings.resx
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Small

#18758 Fix type inference for all scope vars
  src/System.Management.Automation/engine/SpecialVariables.cs
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: CL-General, Extra Small

#18831 Update `README.md` and `metadata.json` for `v7.4.0-preview.1` release
  README.md
  tools/metadata.json
Labels: Extra Small

#18835 Change log for v7.4.0-preview.1 release
  .spelling
  CHANGELOG/preview.md
Labels: Large

#18842 Add StatusCode to HttpResponseException
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
Labels: CL-General, Extra Small

#18870 Fix `Format-Table -RepeatHeader` for property derived tables
  src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator_Table.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1
Labels: CL-General, Extra Small
