Repository PowerShell/PowerShell, pull requests merged in 2022-05, with the labels that each got.

#17231 Fix for partial PowerShell module search paths, that can be resolved to CWD locations
  src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs
  src/System.Management.Automation/resources/PathUtilsStrings.resx
  src/System.Management.Automation/utils/PathUtils.cs
Labels: Extra Small

#17213 Fix 'ForEach' method so it can set property on a scalar object as expected
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  test/powershell/Language/Scripting/Scripting.Followup.Tests.ps1
Labels: Extra Small

#17234 Adding a conditional check to account for script blocks in PSObject when using ForEach-Object -Parallel
  src/System.Management.Automation/engine/InternalCommands.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Foreach-Object-Parallel.Tests.ps1
Labels: CL-General, Extra Small

#17179 Fix line breakpoints for `return` statements without a value
  src/System.Management.Automation/engine/parser/Compiler.cs
  test/powershell/Language/Scripting/Debugging/Debugging.Tests.ps1
Labels: Extra Small

#17258 Move `cgmanifest` generation to daily
  .github/workflows/daily.yml
  .github/workflows/update-cgmanifest.yml
Labels: BackPort-7.0.x-Consider, Backport-7.2.x-Consider, Medium

#17219 Fix Generate checksum file for packages build failure
  tools/releaseBuild/azureDevOps/templates/nuget.yml
Labels: Extra Small

#17263 Update timeout for daily
  .vsts-ci/linux-daily.yml
Labels: Extra Small

#17271 Update engine working group members
  docs/community/working-group-definitions.md
Labels: CL-Docs, Extra Small

#17272 Update to use `mcr.microsoft.com`
  test/docker/networktest/Dockerfile
Labels: Extra Small

#17277 Add rotation between the two mariner images
  .vsts-ci/linux.yml
Labels: Extra Small

#17279 Fix build id variable name when selecting container
  .vsts-ci/linux.yml
Labels: Extra Small

#17273 Put Secure supply chain analysis at correct place
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/insert-nuget-config-azfeed.yml
Labels: Extra Small

#17281 Switch to using GitHub action to verify PRs for broken markdown links
  .github/workflows/markdown-link/config.json
  .github/workflows/markdownLink.yml
  .vsts-ci/misc-analysis.yml
  README.md
Labels: Extra Small

#17291 Reduce unneeded verbose message from `build.psm1`
  build.psm1
Labels: CL-BuildPackaging, Extra Small

#17262 Fix list view to not leak VT decorations
  src/System.Management.Automation/FormatAndOutput/common/ListWriter.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-List.Tests.ps1
Labels: CL-Engine, Extra Small

#17299 Fix `build.psm1` to find the required .NET SDK version when a higher version is installed
  build.psm1
Labels: CL-BuildPackaging, Extra Small

#17294 Enable more tests to be run in a container.
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/SetDateCommand.cs
  src/System.Management.Automation/engine/Utils.cs
  test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Set-Date.Tests.ps1
  test/powershell/engine/Help/HelpSystem.OnlineHelp.Tests.ps1
  test/powershell/engine/Help/HelpSystem.Tests.ps1
Labels: CL-Test, BackPort-7.0.x-Consider, Backport-7.2.x-Consider, Small

#17317 Add mapping for ubuntu22.04 jammy
  tools/packages.microsoft.com/mapping.json
Labels: Extra Small

#17314 Add a finalize template which causes jobs with issues to fail
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/checkAzureContainer.yml
  tools/releaseBuild/azureDevOps/templates/compliance/compliance.yml
  tools/releaseBuild/azureDevOps/templates/json.yml
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/mac-file-signing.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-build.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/mac.yml
  tools/releaseBuild/azureDevOps/templates/step/finalize.yml
  tools/releaseBuild/azureDevOps/templates/testartifacts.yml
  tools/releaseBuild/azureDevOps/templates/windows-hosted-build.yml
  tools/releaseBuild/azureDevOps/templates/windows-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
Labels: BackPort-7.0.x-Consider, Backport-7.2.x-Consider, Extra Small

#17303 Disable release security analysis for SSH CI
  .vsts-ci/sshremoting-tests.yml
Labels: Extra Small

#17315 Start rotating through all images
  .vsts-ci/linux.yml
  build.psm1
  test/tools/Modules/HelpersCommon/HelpersCommon.psm1
  tools/ci.psm1
Labels: Small

#17325 Add fedora to the OS's that can't run WSMan
  test/tools/Modules/HelpersCommon/HelpersCommon.psm1
Labels: Extra Small

#17326 Make sure we execute tests on LTS package for older LTS releases
  tools/releaseBuild/azureDevOps/releaseBuild.yml
Labels: BackPort-7.0.x-Consider, Backport-7.2.x-Consider, Extra Small

#17338 Update Ubuntu 22 to be detected as not supported WSMan
  test/tools/Modules/HelpersCommon/HelpersCommon.psm1
Labels: Extra Small

#17336 Update DotnetRuntimeMetadata.json for .NET 7 Preview 4
  DotnetRuntimeMetadata.json
Labels: Extra Small

#16782 On Windows, reset cursor visibility back to previous state when rendering progress
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressPane.cs
Labels: Review - Needed, CL-General, Extra Small

#17341 Have rebase workflow Post a message when it starts
  .github/workflows/rebase.yml
Labels: CL-Tools, Extra Small

#17221 Disable broken macOS CI job, which is unused
  .vsts-ci/mac.yml
Labels: Waiting on Author, Extra Small

#17329 Fix the error message in Hashtable-to-object conversion
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/resources/ExtendedTypeSystem.resx
  test/powershell/Language/Scripting/HashtableToPSCustomObjectConversion.Tests.ps1
Labels: CL-Engine, Extra Small

#17316 Fix the word wrapping in formatting to handle escape sequences properly
  Settings.StyleCop
  src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs
  src/System.Management.Automation/FormatAndOutput/common/ILineOutput.cs
  src/System.Management.Automation/FormatAndOutput/common/ListWriter.cs
  src/System.Management.Automation/FormatAndOutput/common/StringDecorated.cs
  src/System.Management.Automation/utils/StringUtil.cs
  stylecop.json
  test/powershell/engine/Formatting/PSStyle.Tests.ps1
Labels: CL-Engine, Large

#17304 Telemetry changes
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs
  src/System.Management.Automation/engine/pipeline.cs
  src/System.Management.Automation/utils/Telemetry.cs
  test/powershell/engine/Basic/Telemetry.Tests.ps1
Labels: CL-Engine, Medium

#17357 Redo the change that was reverted by #15853
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/WebCmdletStrings.resx
Labels: Extra Small

#17351 Add Daily Link Check GitHub Workflow
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/markdown-link/config.json
  .github/workflows/markdownLinkDaily.yml
Labels: Extra Small

#17318 Update metadata.json and readme for 7.2.4 and 7.0.11 releases
  README.md
  tools/metadata.json
Labels: Small

#17364 Release changelogs
  CHANGELOG/7.0.md
  CHANGELOG/7.2.md
Labels: Extra Small

#17363 Make sure verbose message is not null
  tools/UpdateDotnetRuntime.ps1
Labels: Extra Small

#17366 Run on every PR and let the action skip
  .github/workflows/markdownLink.yml
  .spelling
Labels: Extra Small

#17356 Simplify `Get-WSManSupport` based on current .NET Distro Support
  test/tools/Modules/HelpersCommon/HelpersCommon.psm1
Labels: Extra Small

#17375 Update script to automatically take new preview pre-release builds
  DotnetRuntimeMetadata.json
  tools/UpdateDotnetRuntime.ps1
Labels: Extra Small

#17396 Fix typo in AsyncResult.cs
  src/System.Management.Automation/engine/hostifaces/AsyncResult.cs
Labels: CL-CodeCleanup, No Changes

#17378 Update readme and metadata for 7.3.0-preview.4 release
  README.md
  tools/metadata.json
Labels: Extra Small

#17412 Update change log for v7.3.0-preview.4 release
  CHANGELOG/preview.md
Labels: Medium

#17413 Fix mariner mappings
  tools/packages.microsoft.com/mapping.json
Labels: Extra Small

#17414 Fix spelling errors introduced in changelog
  .spelling
Labels: Extra Small

#17410 Update Documentation Issue Template URL
  .github/ISSUE_TEMPLATE/config.yml
Labels: Extra Small

#17411 Move to configuring the fabric bot via JSON
  .github/fabricbot.json
Labels: Extra Large

#17416 Add AppX capabilities in MSIX manifest so that PS7 can call the AppX APIs
  assets/AppxManifest.xml
Labels: Backport-7.2.x-Consider, Extra Small

#17387 Add reminder workflows
  .github/workflows/createReminders.yml
  .github/workflows/processReminders.yml
  .poshchan/settings.json
Labels: Small

#17420 Increase ref assembly count to 161
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs
Labels: Extra Small

#17415 Do not publish package for Mariner 1.0
  tools/packages.microsoft.com/mapping.json
Labels: Extra Small

#17424 Update TLS test based on current platform settings
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: Backport-7.2.x-Approved, Extra Large

#17417 Base work for adding mariner amd64 package
  tools/packaging/packaging.psm1
  tools/packaging/releaseTests/sbom.tests.ps1
  tools/releaseBuild/azureDevOps/releasePipeline.yml
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-build.yml
  tools/releaseBuild/azureDevOps/templates/release-ValidatePackageBOM.yml
  tools/releaseBuild/azureDevOps/templates/release-ValidatePackageNames.yml
Labels: Large, reminder

#17334 Start-PSPester: argument completer for -Path
  build.psm1
Labels: Review - Needed, CL-Tools, Extra Small

#17419 Write out OSC indicator only if the stdout is not redirected
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfaceProgress.cs
  test/powershell/engine/Formatting/PSStyle.Tests.ps1
Labels: CL-General, Extra Small

#17448 Update script to pin to .NET 7 preview 5 version
  DotnetRuntimeMetadata.json
  tools/UpdateDotnetRuntime.ps1
Labels: Extra Small

#16951 Add type inference support for generic methods with type parameters
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: CL-General, Extra Small

#17451 Publish preview versions of mariner to preview repo
  tools/packages.microsoft.com/mapping.json
Labels: Backport-7.2.x-Consider, Extra Small
