Repository PowerShell/PowerShell, pull requests merged in 2022-10, with the labels that each got.

#18194 Update to use ComputeCore.dll for PowerShell Direct
  src/System.Management.Automation/utils/PInvokeDllNames.cs
Labels: Extra Small, Backport-7.3.x-Consider

#17346 Add `CustomTableHeaderLabel` formatting to differentiate table header labels that are not property names
  experimental-feature-linux.json
  experimental-feature-windows.json
  src/System.Management.Automation/FormatAndOutput/common/BaseOutputtingCommand.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator_Table.cs
  src/System.Management.Automation/FormatAndOutput/common/FormattingObjects.cs
  src/System.Management.Automation/FormatAndOutput/common/PSStyle.cs
  src/System.Management.Automation/FormatAndOutput/common/TableWriter.cs
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1
  test/powershell/engine/Formatting/PSStyle.Tests.ps1
Labels: CL-General, Small

#17955 Fix decompression in web cmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/StreamHelper.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: CL-General, Extra Small

#18195 Improve startup time by triggering initialization of additional types on background thread.
  src/System.Management.Automation/engine/InitialSessionState.cs
Labels: CL-General, Extra Small

#18189 Remove XML files for min-size package
  build.psm1
  tools/packaging/packaging.psm1
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
Labels: CL-BuildPackaging, Backport-7.2.x-Consider, Extra Small, Backport-7.3.x-Consider

#18213 Remove unnecessary native dependencies from the package
  PowerShell.Common.props
  assets/wix/files.wxs
  build.psm1
Labels: Small, Backport-7.3.x-Consider

#18214 Add branch counter to compliance build
  tools/releaseBuild/azureDevOps/templates/compliance/apiscan.yml
Labels: Extra Small, Backport-7.3.x-Consider

#18226 Do not cleanup pwsh.deps.json for framework dependent packages
  build.psm1
Labels: Extra Small, Backport-7.3.x-Consider

#18210 Make the static constructor of `PSVersionInfo` run faster for stable PowerShell releases
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostRawUserInterface.cs
  src/Microsoft.PowerShell.ConsoleHost/resources/ConsoleHostRawUserInterfaceStrings.resx
  src/System.Management.Automation/engine/PSVersionInfo.cs
Labels: CL-Performance, Small

#18215 On Unix, only explicitly terminate the native process if not in background
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
Labels: Backport-7.2.x-Consider, Extra Small, Backport-7.3.x-Consider

#18232 Skip evaluating suggestions at startup
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
Labels: CL-Performance, Extra Small

#18244 Use `MemoryExtensions.IndexOfAny` in `SessionStateInternal`
  src/System.Management.Automation/engine/SessionStateDriveAPIs.cs
Labels: CL-CodeCleanup, Extra Small

#18231 Some more code cleanup related to the use of `PSVersionInfo`
  src/System.Management.Automation/AssemblyInfo.cs
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/InternalCommands.cs
  src/System.Management.Automation/engine/PSVersionInfo.cs
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/remoting/client/remoterunspace.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/RemoteDebuggingCapability.cs
  src/System.Management.Automation/engine/remoting/server/ServerRunspacePoolDriver.cs
  src/System.Management.Automation/resources/RemotingErrorIdStrings.resx
Labels: CL-CodeCleanup, Small

#18253 Remove ETW trace collection and uploading for CLR CAP
  .vsts-ci/windows-daily.yml
Labels: CL-BuildPackaging, Extra Small

#15603 Use Source Code Generator for PSVersionInfo class
  PowerShell.Common.props
  src/System.Management.Automation/SourceGenerators/PSVersionInfoGenerator/PSVersionInfoGenerator.cs
  src/System.Management.Automation/SourceGenerators/PSVersionInfoGenerator/PSVersionInfoGenerator.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  src/System.Management.Automation/engine/PSVersionInfo.cs
Labels: WG-Security, CL-Performance, Medium

#18269 Disable static analysis CI on 7.0
  .vsts-ci/misc-analysis.yml
Labels: Extra Small

#18268 Back-port to 7.0: Move `cgmanifest` generation to daily
  .github/workflows/daily.yml
  .github/workflows/update-cgmanifest.yml
Labels: Medium

#18266 Back-port to 7.0: Update list of PowerShell team members in release tools
  tools/releaseTools.psm1
Labels: Extra Large

#18261 Add `-FuzzyMinimumDistance` parameter to `Get-Command`
  src/System.Management.Automation/engine/GetCommandCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Command.Tests.ps1
Labels: CL-General, Extra Small

#18267 Back-port to 7.0: Fix `build.psm1` to not specify both version and quality for `dotnet-install`
  build.psm1
Labels: Extra Small

#18271 [release/v7.2.7] Update to use version 2.21.0 of Application Insights
  src/System.Management.Automation/System.Management.Automation.csproj
  src/System.Management.Automation/utils/Telemetry.cs
Labels: Extra Small

#18276 Create tasks to collect and publish hashes for build files.
  tools/releaseBuild/azureDevOps/templates/compliance/apiscan.yml
Labels: Extra Small

#18277 Recurse the file listing.
  tools/releaseBuild/azureDevOps/templates/compliance/apiscan.yml
Labels: Extra Small, Backport-7.3.x-Consider

#18287 [release/v7.2.7] Backport of "Fix error formatting to use color defined in `$PSStyle.Formatting`"
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
Labels: Extra Large

#18280 [release/v7.2.7] On Unix, only explicitly terminate the native process if not in background
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
Labels: Extra Small

#18282 [release/v7.2.7] Fix `build.psm1` to find the required .NET SDK version when a higher version is installed (#17299)
  build.psm1
Labels: Extra Small

#18272 Bump .NET SDK to 3.1.424
  global.json
  test/hosting/hosting.tests.csproj
  test/tools/WebListener/WebListener.csproj
  test/xUnit/xUnit.tests.csproj
Labels: Extra Small

#18263 Fix typo in RemoteRunspacePoolInternal.cs
  src/System.Management.Automation/engine/remoting/client/RemoteRunspacePoolInternal.cs
Labels: No Changes

#18250 Use shortpath instead of multiple quotes in `Get-Item` test relying on node
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-Item.Tests.ps1
Labels: Extra Small

#18259 [release/v.7.0.12] Update `Newtonsoft.Json` version for 7.0.12 release
  src/System.Management.Automation/System.Management.Automation.csproj
Labels: CL-BuildPackaging, Extra Small

#18299 Add a function to get the PR Back-port report
  tools/releaseTools.psm1
Labels: Small

#18301 Small cleanup CORECLR
  src/Microsoft.PowerShell.Commands.Diagnostics/CoreCLR/Stubs.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/Microsoft.PowerShell.Commands.Diagnostics.csproj
Labels: CL-CodeCleanup, Extra Small

#18318 Update the `cgmanifest.json` for `v7.0.12`
  tools/cgmanifest.json
Labels: Extra Small

#18319 Update cgmanifest for 7.2.7
  tools/cgmanifest.json
Labels: Extra Small

#18270 Make the fuzzy searching flexible by passing in the fuzzy matcher
  src/System.Management.Automation/engine/CommandPathSearch.cs
  src/System.Management.Automation/engine/CommandSearcher.cs
  src/System.Management.Automation/engine/GetCommandCommand.cs
  src/System.Management.Automation/engine/Modules/ModuleUtils.cs
  src/System.Management.Automation/utils/FuzzyMatch.cs
Labels: CL-General, Medium

#18304 Replace win7 runtime with win8 and remove APISets
  .vsts-ci/windows/templates/windows-packaging.yml
  assets/wix/files.wxs
  build.psm1
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/ResGen/ResGen.csproj
  src/TypeCatalogGen/TypeCatalogGen.csproj
  src/powershell-win-core/powershell-win-core.csproj
  test/hosting/hosting.tests.csproj
  test/packaging/windows/exe.tests.ps1
  test/packaging/windows/msi.tests.ps1
  test/powershell/engine/ExperimentalFeature/Get-ExperimentalFeature.Tests.ps1
  test/tools/OpenCover/OpenCover.psm1
  test/tools/TestExe/TestExe.csproj
  test/tools/TestService/TestService.csproj
  test/xUnit/xUnit.tests.csproj
  tools/ci.psm1
  tools/findMissingNotices.ps1
  tools/packaging/packaging.psm1
  tools/releaseBuild/Images/microsoft_powershell_windowsservercore/PowerShellPackage.ps1
  tools/releaseBuild/azureDevOps/templates/testartifacts.yml
  tools/releaseBuild/azureDevOps/templates/windows-hosted-build.yml
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
Labels: Breaking-Change, Extra Large, Backport-7.3.x-Consider

#18320 Remove the `ProcessorArchitecture` portion from the full name as it's obsolete
  src/System.Management.Automation/singleshell/config/MshSnapinInfo.cs
  test/xUnit/csharp/test_MshSnapinInfo.cs
Labels: CL-General, Extra Small

#18322 Revert "Replace win7 runtime with win8 and remove APISets (#18304)"
  .vsts-ci/windows/templates/windows-packaging.yml
  build.psm1
  src/ResGen/ResGen.csproj
  src/TypeCatalogGen/TypeCatalogGen.csproj
  src/powershell-win-core/powershell-win-core.csproj
  test/hosting/hosting.tests.csproj
  test/packaging/windows/exe.tests.ps1
  test/packaging/windows/msi.tests.ps1
  test/powershell/engine/ExperimentalFeature/Get-ExperimentalFeature.Tests.ps1
  test/tools/OpenCover/OpenCover.psm1
  test/tools/TestExe/TestExe.csproj
  test/tools/TestService/TestService.csproj
  test/xUnit/xUnit.tests.csproj
  tools/ci.psm1
  tools/findMissingNotices.ps1
  tools/packaging/packaging.psm1
  tools/releaseBuild/Images/microsoft_powershell_windowsservercore/PowerShellPackage.ps1
  tools/releaseBuild/azureDevOps/templates/testartifacts.yml
  tools/releaseBuild/azureDevOps/templates/windows-hosted-build.yml
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
Labels: Medium, Backport-7.3.x-Consider

#18286 Bump to .NET 7 to version 7.0.100-rc.2.22477.20
  DotnetRuntimeMetadata.json
  assets/wix/files.wxs
  global.json
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
Labels: Small

#18242 Use `MemoryExtensions.IndexOfAny` in `WildcardPattern`
  src/System.Management.Automation/engine/regex.cs
Labels: Review - Needed, CL-CodeCleanup, Extra Small

#18328 Bump to .NET 7 RC2 official version
  assets/wix/files.wxs
  global.json
Labels: Extra Small, Backport-7.3.x-Consider

#18245 Use `MemoryExtensions.IndexOfAny` in `PSv2CompletionCompleter``
  src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs
Labels: CL-CodeCleanup, Extra Small

#18243 Remove some static initializations in `StringManipulationHelper`
  src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs
Labels: CL-CodeCleanup, Extra Small

#18332 Update README and metadata from servicing releases
  README.md
  tools/metadata.json
Labels: Small

#18342 Update change logs for v7.2.7 and v7.0.13
  .spelling
  CHANGELOG/7.0.md
  CHANGELOG/7.2.md
Labels: Small

#18252 Replace command-error suggestion with new implementation based on subsystem plugin
  experimental-feature-linux.json
  experimental-feature-windows.json
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  src/System.Management.Automation/FormatAndOutput/common/PSStyle.cs
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/Subsystem/FeedbackSubsystem/FeedbackHub.cs
  src/System.Management.Automation/engine/Subsystem/FeedbackSubsystem/IFeedbackProvider.cs
  src/System.Management.Automation/engine/Subsystem/ISubsystem.cs
  src/System.Management.Automation/engine/Subsystem/PredictionSubsystem/CommandPrediction.cs
  src/System.Management.Automation/engine/Subsystem/PredictionSubsystem/ICommandPredictor.cs
  src/System.Management.Automation/engine/Subsystem/SubsystemInfo.cs
  src/System.Management.Automation/engine/Subsystem/SubsystemManager.cs
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/hostifaces/HostUtilities.cs
  src/System.Management.Automation/resources/SubsystemStrings.resx
  src/System.Management.Automation/resources/SuggestionStrings.resx
  test/xUnit/csharp/test_Feedback.cs
  test/xUnit/csharp/test_Subsystem.cs
Labels: CL-General, Extra Large

#18341 Implement `IDisposable` in `NamedPipeClient`
  test/tools/NamedPipeConnection/src/code/NamedPipeConnection.cs
Labels: Extra Small

#18334 Remove FusionAssemblyIdentity and GlobalAssemblyCache
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/parser/FusionAssemblyIdentity.cs
  src/System.Management.Automation/engine/parser/GlobalAssemblyCache.cs
  src/System.Management.Automation/engine/parser/Parser.cs
Labels: CL-CodeCleanup, Large

#18336 Line ending fix for Exception Message on ConvertFrom-StringData
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertFrom-StringData.cs
Labels: Hacktoberfest, CL-General, Hacktoberfest-Accepted, Extra Small

#18351 Fix type inference error for empty return statements
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: CL-General, Extra Small

#18288 Code Cleanup ContentHelper.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/ContentHelper.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
Labels: Review - Needed, CL-CodeCleanup, Extra Small

#18367 Remove unused strings from ConsoleInfoErrorStrings.resx
  src/System.Management.Automation/resources/ConsoleInfoErrorStrings.resx
Labels: CL-CodeCleanup, Small

#18308 Add parsing to make cd~ a valid command.
  src/System.Management.Automation/engine/InitialSessionState.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Set-Location.Tests.ps1
Labels: Hacktoberfest, Documentation Needed, CL-General, Hacktoberfest-Accepted, Extra Small

#18369 Remove unused console strings
  src/Microsoft.PowerShell.ConsoleHost/resources/ConsoleControlStrings.resx
  src/Microsoft.PowerShell.ConsoleHost/resources/ConsoleHostStrings.resx
Labels: CL-CodeCleanup, Extra Small

#18370 Remove unused strings from Utility module
  src/Microsoft.PowerShell.Commands.Utility/resources/AliasCommandStrings.resx
  src/Microsoft.PowerShell.Commands.Utility/resources/HostStrings.resx
  src/Microsoft.PowerShell.Commands.Utility/resources/ImmutableStrings.resx
  src/Microsoft.PowerShell.Commands.Utility/resources/ImplicitRemotingStrings.resx
  src/Microsoft.PowerShell.Commands.Utility/resources/NewObjectStrings.resx
  src/Microsoft.PowerShell.Commands.Utility/resources/TraceCommandStrings.resx
  src/Microsoft.PowerShell.Commands.Utility/resources/UpdateDataStrings.resx
  src/Microsoft.PowerShell.Commands.Utility/resources/WebCmdletStrings.resx
Labels: CL-CodeCleanup, Small

#18354 [release/v7.3.0-rc.1] Replace win7 runtime with win8 and remove APISets (#18304)
  .vsts-ci/windows/templates/windows-packaging.yml
  assets/wix/files.wxs
  build.psm1
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/ResGen/ResGen.csproj
  src/TypeCatalogGen/TypeCatalogGen.csproj
  src/powershell-win-core/powershell-win-core.csproj
  test/hosting/hosting.tests.csproj
  test/packaging/windows/exe.tests.ps1
  test/packaging/windows/msi.tests.ps1
  test/powershell/engine/ExperimentalFeature/Get-ExperimentalFeature.Tests.ps1
  test/tools/OpenCover/OpenCover.psm1
  test/tools/TestExe/TestExe.csproj
  test/tools/TestService/TestService.csproj
  test/xUnit/xUnit.tests.csproj
  tools/ci.psm1
  tools/findMissingNotices.ps1
  tools/packaging/packaging.psm1
  tools/releaseBuild/Images/microsoft_powershell_windowsservercore/PowerShellPackage.ps1
  tools/releaseBuild/azureDevOps/templates/testartifacts.yml
  tools/releaseBuild/azureDevOps/templates/windows-hosted-build.yml
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
Labels: CL-BuildPackaging, Extra Large

#18378 [release/v7.3.0-rc.1] Bump to .NET 7 to version `7.0.100-rc.2.22477.20` (#18286)
  DotnetRuntimeMetadata.json
  assets/wix/files.wxs
  global.json
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
Labels: Small

#18380 Increase timeout to make subsystem tests more reliable
  test/xUnit/csharp/test_Feedback.cs
  test/xUnit/csharp/test_Prediction.cs
Labels: Extra Small

#18377 [release/v7.3.0-rc.1] Bump to .NET 7 RC2 official version (#18328)
  assets/wix/files.wxs
  global.json
Labels: Medium

#18383 Remove unused strings from parser
  src/System.Management.Automation/resources/ParserStrings.resx
Labels: CL-CodeCleanup, Medium

#18374 Correct incorrect cmdlet name in script
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
Labels: CL-General, Backport-7.2.x-Consider, Extra Small, Backport-7.3.x-Consider

#18348 Avoid using regex when unnecessary in `ScriptWriter`
  src/System.Management.Automation/cimSupport/cmdletization/ScriptWriter.cs
Labels: Extra Small

#18388 Remove some unused strings in System.Management.Automation
  src/System.Management.Automation/resources/PowerShellStrings.resx
  src/System.Management.Automation/resources/RunspaceStrings.resx
  src/System.Management.Automation/resources/TypesXmlStrings.resx
Labels: CL-CodeCleanup, Small

#18393 Update `README.json` and `metadata.json` for `v7.3.0-rc.1`
  README.md
  tools/metadata.json
Labels: Extra Small

#18394 Remove unused strings from SessionStateStrings
  src/System.Management.Automation/resources/SessionStateStrings.resx
Labels: CL-CodeCleanup, Small

#18392 Allow two-digit revisions in vPack package validation pattern
  tools/releaseBuild/azureDevOps/templates/vpackReleaseJob.yml
Labels: BackPort-7.0.x-Consider, Backport-7.2.x-Consider, Extra Small, Backport-7.3.x-Consider

#18154 Remove static constants
  src/Microsoft.PowerShell.Security/security/SecureStringCommands.cs
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator_Complex.cs
  src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/engine/CommandSearcher.cs
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs
  src/System.Management.Automation/engine/MshSnapinQualifiedName.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/PSVersionInfo.cs
  src/System.Management.Automation/engine/ParameterSetInfo.cs
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
  src/System.Management.Automation/engine/remoting/common/psstreamobject.cs
  src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/help/BaseCommandHelpInfo.cs
  src/System.Management.Automation/help/DscResourceHelpProvider.cs
  src/System.Management.Automation/help/HelpFileHelpProvider.cs
  src/System.Management.Automation/help/MamlNode.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/namespaces/ProviderBase.cs
Labels: CL-Performance, Medium

#18403 Remove unused strings from FileSystem and Registry providers
  src/System.Management.Automation/resources/FileSystemProviderStrings.resx
  src/System.Management.Automation/resources/RegistryProviderStrings.resx
Labels: CL-CodeCleanup, Small

#18400 Change log for v7.3.0-rc.1
  .spelling
  CHANGELOG/preview.md
Labels: Extra Small

#18382 Skip output rendering tests on Windows Server 2012 R2
  test/powershell/engine/Formatting/OutputRendering.Tests.ps1
Labels: CL-Test, Extra Small

#18411 Replace some string.Join(string) calls with string.Join(char)
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/Modules/NewModuleManifestCommand.cs
  src/System.Management.Automation/engine/Modules/SwitchProcessCommand.cs
  src/System.Management.Automation/engine/parser/PSType.cs
  src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/logging/MshLog.cs
Labels: CL-CodeCleanup, Extra Small

#18412 Make use of StringSplitOptions.TrimEntries when possible
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertFrom-StringData.cs
  src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs
Labels: CL-CodeCleanup, Extra Small
