Repository PowerShell/PowerShell, pull requests merged in 2023-01, with the labels that each got.

#18619 Fix up all comments to be in the proper order with proper spacing.
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetComputerInfoCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/WMIHelper.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Get-PSBreakpoint.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ObjectCommandComparer.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/XmlCommands.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/PendingProgress.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressPane.cs
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/System.Management.Automation/CoreCLR/CorePsStub.cs
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/engine/CoreAdapter.cs
  src/System.Management.Automation/engine/EventManager.cs
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Modules/PSModuleInfo.cs
  src/System.Management.Automation/engine/MshObject.cs
  src/System.Management.Automation/engine/PSConfiguration.cs
  src/System.Management.Automation/engine/ProgressRecord.cs
  src/System.Management.Automation/engine/TransactedString.cs
  src/System.Management.Automation/engine/TransactionManager.cs
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/hostifaces/Connection.cs
  src/System.Management.Automation/engine/hostifaces/FieldDescription.cs
  src/System.Management.Automation/engine/hostifaces/History.cs
  src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs
  src/System.Management.Automation/engine/hostifaces/MshHostRawUserInterface.cs
  src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs
  src/System.Management.Automation/engine/hostifaces/RunspacePool.cs
  src/System.Management.Automation/engine/parser/ast.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
  src/System.Management.Automation/engine/remoting/client/RemoteRunspacePoolInternal.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/RemotingDataObject.cs
  src/System.Management.Automation/engine/remoting/common/throttlemanager.cs
  src/System.Management.Automation/engine/runtime/Operations/ClassOps.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  src/System.Management.Automation/help/HelpCommands.cs
  src/System.Management.Automation/help/HelpSystem.cs
  src/System.Management.Automation/help/UpdatableHelpCommandBase.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/namespaces/ProviderBase.cs
  src/System.Management.Automation/namespaces/TransactedRegistryKey.cs
  src/System.Management.Automation/namespaces/TransactedRegistrySecurity.cs
  src/System.Management.Automation/utils/CryptoUtils.cs
  src/System.Management.Automation/utils/Verbs.cs
Labels: Review - Needed, No Changes

#18882 Handle AMSI initialization failures
  src/System.Management.Automation/security/SecuritySupport.cs
Labels: Extra Small

#18650 [backport release/v7.3.2] Fix `Switch-Process` error to include the command that is not found
  src/System.Management.Automation/engine/Modules/SwitchProcessCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Core/Exec.Tests.ps1
Labels: Review - Needed, Extra Small, Backport-7.3.x-Consider

#18888 Enable creating composite subsystem implementation in modules
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  src/System.Management.Automation/engine/Subsystem/DscSubsystem/ICrossPlatformDsc.cs
  src/System.Management.Automation/engine/Subsystem/FeedbackSubsystem/IFeedbackProvider.cs
  src/System.Management.Automation/engine/Subsystem/ISubsystem.cs
  src/System.Management.Automation/engine/Subsystem/PredictionSubsystem/ICommandPredictor.cs
  src/System.Management.Automation/engine/Subsystem/SubsystemInfo.cs
  src/System.Management.Automation/engine/Subsystem/SubsystemManager.cs
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/resources/SubsystemStrings.resx
  test/xUnit/csharp/test_Subsystem.cs
Labels: CL-General, Medium

#18891 Add bootstrap after SBOM task to re-install .NET
  .vsts-ci/windows/templates/windows-packaging.yml
Labels: Extra Small

#18726 Add `-CommandWithArgs` parameter to pwsh
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/resources/CommandLineParameterParserStrings.resx
  src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
Labels: Review - Needed, CL-General, Medium

#18859 Update build to include WinForms/WPF in all Windows builds
  build.psm1
Labels: Review - Needed, Extra Small

#18861 Cleanup InvokeRestMethodCommand.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
Labels: CL-CodeCleanup, Extra Small

#18820 Requires.NotNull-->ArgumentNullException.ThrowIfNull
  src/System.Management.Automation/engine/Subsystem/PredictionSubsystem/CommandPrediction.cs
  src/System.Management.Automation/engine/Subsystem/PredictionSubsystem/ICommandPredictor.cs
  src/System.Management.Automation/engine/Subsystem/SubsystemManager.cs
Labels: CL-CodeCleanup, Extra Small

#18755 Prioritize the default parameter set when completing positional args
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: Review - Needed, Extra Small

#18893 Add WDAC events and system lockdown notification
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/remoting/common/PSETWTracer.cs
  src/System.Management.Automation/logging/LogProvider.cs
  src/System.Management.Automation/security/wldpNativeMethods.cs
  src/System.Management.Automation/utils/tracing/PSEtwLog.cs
  src/System.Management.Automation/utils/tracing/PSEtwLogProvider.cs
  src/System.Management.Automation/utils/tracing/PSSysLogProvider.cs
Labels: Backport-5.1-Consider, Small

#18904 Add checks for Win8.1, Server2012
  assets/wix/Product.wxs
Labels: CL-BuildPackaging, Extra Small

#18881 Fix regression in RemoveNulls
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
Labels: CL-CodeCleanup, Extra Small

#18905 Create test to check if WebCmdlets decompress brotli-encoded data
  .spelling
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
  test/tools/WebListener/BrotliFilter.cs
  test/tools/WebListener/Controllers/CompressionController.cs
  test/tools/WebListener/README.md
  test/tools/WebListener/Views/Home/Index.cshtml
Labels: CL-Test, Extra Small

#18855 Enable `Get-Help` pattern tests on Unix
  test/powershell/engine/Help/HelpSystem.Tests.ps1
Labels: CL-Test, Extra Small

#18918 [release/v7.3.2] Remove unnecessary reference to `System.Runtime.CompilerServices.Unsafe`
  src/System.Management.Automation/System.Management.Automation.csproj
Labels: Extra Small

#18829 Invoke-RestMethod -FollowRelLink fix links containing commas
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: CL-General, Extra Small

#18933 Fix typo in ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
Labels: CL-CodeCleanup, No Changes

#18846 Simplification of GetHttpMethod and httpMethod in WebCmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
Labels: CL-CodeCleanup, Small

#18546 Add AllowInsecureRedirect switch to Web cmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
Labels: CL-General, Extra Small

#18939 Add tests for Allowinsecureredirect parameter in Web cmdlets
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
  test/tools/WebListener/Controllers/RedirectController.cs
Labels: CL-Test, Small

#18895 Fix `Get-Error` to work with strict mode
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Error.Tests.ps1
Labels: CL-General, Extra Small

#18902 Fix bug with managing redirection and keepAuthorization in Web cmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: CL-General, Extra Small

#18878 Bump `BenchmarkDotNet` to `0.13.3`
  test/perf/dotnet-tools/BenchmarkDotNet.Extensions/BenchmarkDotNet.Extensions.csproj
  test/perf/dotnet-tools/ResultsComparer/ResultsComparer.csproj
Labels: Extra Small

#18947 HttpKnownHeaderNames update headers list
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/HttpKnownHeaderNames.cs
Labels: CL-General, Extra Small

#18946 Small cleanup common code of webcmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/BasicHtmlWebResponseObject.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/ContentHelper.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebProxy.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebResponseHelper.CoreClr.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebResponseObjectFactory.CoreClr.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/FormObjectCollection.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/PSUserAgent.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/WebCmdletElementCollection.cs
Labels: CL-CodeCleanup, Medium

#18950 Cleanup StreamHelper.cs, WebRequestPSCmdlet.Common.cs and InvokeRestMethodCommand.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/StreamHelper.cs
Labels: CL-CodeCleanup, Small

#18962 Allow system lock down test debug hook to work with new wldp API (fixes system lock down tests)
  src/System.Management.Automation/security/wldpNativeMethods.cs
Labels: CL-Test, Extra Small, Backport-7.3.x-Consider

#18988 Use interpolated strings 8
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfacePrompt.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfacePromptForChoice.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/XmlLoaderBase.cs
  src/System.Management.Automation/engine/MshMemberInfo.cs
  src/System.Management.Automation/engine/hostifaces/InternalHostUserInterface.cs
  src/System.Management.Automation/engine/parser/token.cs
  src/System.Management.Automation/engine/remoting/client/Job.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManTransportManager.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  src/System.Management.Automation/help/AliasHelpInfo.cs
  src/System.Management.Automation/help/BaseCommandHelpInfo.cs
  src/System.Management.Automation/help/CommandHelpProvider.cs
  src/System.Management.Automation/help/HelpCommands.cs
  src/System.Management.Automation/help/ProviderHelpProvider.cs
Labels: CL-Performance, Small

#18985 Use interpolated strings 7
  src/Microsoft.PowerShell.ScheduledJob/ScheduledJobStore.cs
  src/Microsoft.WSMan.Management/WsManHelper.cs
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/FormatTable.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataQuery.cs
  src/System.Management.Automation/cimSupport/cmdletization/ScriptWriter.cs
  src/System.Management.Automation/cimSupport/cmdletization/xml/CoreCLR/cmdlets-over-objects.xmlSerializer.autogen.cs
Labels: CL-Performance, Small

#18993 Use interpolated strings 9
  src/Microsoft.PowerShell.ScheduledJob/ScheduledJobStore.cs
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataQuery.cs
  src/System.Management.Automation/cimSupport/cmdletization/ScriptWriter.cs
Labels: CL-Performance, Extra Small

#18992 Use interpolated strings 10
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfacePrompt.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfacePromptForChoice.cs
  src/System.Management.Automation/engine/hostifaces/InternalHostUserInterface.cs
Labels: CL-Performance, Extra Small

#18983 Use interpolated strings 6
  src/System.Management.Automation/engine/CmdletParameterBinderController.cs
  src/System.Management.Automation/engine/ComInterop/ComTypeEnumDesc.cs
  src/System.Management.Automation/engine/ComInterop/ComTypeLibDesc.cs
  src/System.Management.Automation/engine/ComInterop/DispCallable.cs
  src/System.Management.Automation/engine/ComInterop/IDispatchComObject.cs
  src/System.Management.Automation/engine/ComInterop/Variant.Extended.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CommandMetadata.cs
  src/System.Management.Automation/engine/CoreAdapter.cs
  src/System.Management.Automation/engine/GetCommandCommand.cs
  src/System.Management.Automation/engine/InternalCommands.cs
  src/System.Management.Automation/engine/ManagementObjectAdapter.cs
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  src/System.Management.Automation/engine/ParameterBinderController.cs
  src/System.Management.Automation/engine/ParameterSetInfo.cs
  src/System.Management.Automation/engine/TypeTable.cs
  src/System.Management.Automation/engine/cmdlet.cs
Labels: CL-Performance, Medium

#18978 Use interpolated strings 2
  src/Microsoft.PowerShell.Commands.Diagnostics/GetCounterCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/GetEventCommand.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/ImportCounterCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetComputerInfoCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-hex/Format-Hex.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Group-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/UtilityCommon.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/ContentHelper.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebResponseHelper.CoreClr.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/PSUserAgent.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/XmlCommands.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostRawUserInterface.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfacePrompt.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterfacePromptForChoice.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/UpdatesNotification.cs
Labels: CL-Performance, Medium

#18997 Use interpolated strings 5c
  src/System.Management.Automation/engine/Modules/AnalysisCache.cs
  src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
Labels: CL-Performance, Extra Small

#18979 Use interpolated strings 3
  src/System.Management.Automation/help/DefaultCommandHelpObjectBuilder.cs
  src/System.Management.Automation/help/HelpCommands.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/namespaces/LocationGlobber.cs
  src/System.Management.Automation/namespaces/RegistryProvider.cs
  src/System.Management.Automation/security/wldpNativeMethods.cs
  src/System.Management.Automation/singleshell/config/MshSnapinInfo.cs
  src/System.Management.Automation/utils/perfCounters/PSPerfCountersMgr.cs
  src/System.Management.Automation/utils/tracing/PSEtwLog.cs
  src/System.Management.Automation/utils/tracing/SysLogProvider.cs
  test/Test.Common.props
  test/perf/benchmarks/Engine.Compiler.cs
  test/perf/dotnet-tools/BenchmarkDotNet.Extensions/CommandLineOptions.cs
Labels: CL-Performance, Small

#18996 Use interpolated strings 5b
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/hostifaces/HostUtilities.cs
  src/System.Management.Automation/engine/hostifaces/InternalHostUserInterface.cs
  src/System.Management.Automation/engine/hostifaces/MshHostRawUserInterface.cs
  src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs
  src/System.Management.Automation/engine/hostifaces/PSTask.cs
  src/System.Management.Automation/engine/interpreter/BranchLabel.cs
  src/System.Management.Automation/engine/interpreter/LabelInfo.cs
  src/System.Management.Automation/engine/interpreter/LightCompiler.cs
  src/System.Management.Automation/engine/interpreter/LocalVariables.cs
  src/System.Management.Automation/engine/interpreter/StackOperations.cs
Labels: CL-Performance, Extra Small

#18980 Use interpolated strings 4
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/parser/DebugViewWriter.cs
  src/System.Management.Automation/engine/parser/PSType.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/parser/Position.cs
  src/System.Management.Automation/engine/parser/SymbolResolver.cs
  src/System.Management.Automation/engine/parser/ast.cs
  src/System.Management.Automation/engine/parser/token.cs
  src/System.Management.Automation/engine/remoting/client/RemoteRunspacePoolInternal.cs
  src/System.Management.Automation/engine/remoting/commands/NewPSSessionConfigurationFile.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
  src/System.Management.Automation/engine/remoting/fanin/BaseTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManTransportManager.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  src/System.Management.Automation/engine/runtime/MutableTuple.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  src/System.Management.Automation/engine/runtime/ScriptBlockToPowerShell.cs
Labels: CL-Performance, Medium

#18977 Use interpolated strings 1
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionOperations.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/RegisterCimIndicationCommand.cs
  src/Microsoft.Management.Infrastructure.CimCmdlets/Utils.cs
  src/Microsoft.Management.UI.Internal/HelpWindow/HelpParagraphBuilder.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/ValidatingSelectorValue.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/ValidatingValueBase.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterProviders/SearchTextParser.cs
  src/Microsoft.Management.UI.Internal/ManagementList/ManagementList/Innerlist.cs
  src/Microsoft.Management.UI.Internal/ManagementList/ManagementList/ViewGroupToStringConverter.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/Controls/MultipleSelectionControl.xaml.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/Controls/ParameterSetControl.xaml.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/ViewModel/CommandViewModel.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/ViewModel/ParameterSetViewModel.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/ViewModel/ParameterViewModel.cs
  src/System.Management.Automation/SourceGenerators/PSVersionInfoGenerator/PSVersionInfoGenerator.csproj
Labels: CL-Performance, Small

#18748 WebCmdlets parse XML declaration to get encoding value, if present.
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/StreamHelper.cs
Labels: CL-General, Extra Small

#19003 Use interpolated strings 12
  src/System.Management.Automation/engine/Modules/NewModuleManifestCommand.cs
  src/System.Management.Automation/engine/remoting/commands/NewPSSessionConfigurationFile.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
Labels: CL-Performance, Extra Small

#19014 Update metadata and readme for next releases
  README.md
  tools/metadata.json
Labels: Small

#19021 Fix typo in dotnet-tools/README.md
  test/perf/dotnet-tools/README.md
Labels: CL-Docs, Extra Small

#18735 Add progress to `Copy-Item`
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ProgressNode.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/resources/FileSystemProviderStrings.resx
  test/xUnit/csharp/test_Prediction.cs
Labels: WG-Interactive-Console, WG-Cmdlets, Small

#19018 Revert some of the interpolated string changes
  src/Microsoft.Management.Infrastructure.CimCmdlets/Utils.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterProviders/SearchTextParser.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-hex/Format-Hex.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.WSMan.Management/CredSSP.cs
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader_Views.cs
  src/System.Management.Automation/engine/CommandMetadata.cs
  src/System.Management.Automation/engine/GetCommandCommand.cs
  src/System.Management.Automation/engine/ManagementObjectAdapter.cs
  src/System.Management.Automation/engine/ParameterSetInfo.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/hostifaces/HostUtilities.cs
  src/System.Management.Automation/engine/interpreter/BranchLabel.cs
  src/System.Management.Automation/engine/interpreter/LightCompiler.cs
  src/System.Management.Automation/engine/interpreter/LocalVariables.cs
  src/System.Management.Automation/engine/interpreter/StackOperations.cs
  src/System.Management.Automation/engine/parser/DebugViewWriter.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/parser/Position.cs
  src/System.Management.Automation/engine/parser/token.cs
  src/System.Management.Automation/engine/remoting/fanin/BaseTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/OutOfProcTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPluginShellSession.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManTransportManager.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  src/System.Management.Automation/help/CommandHelpProvider.cs
  src/System.Management.Automation/help/HelpCommentsParser.cs
  src/System.Management.Automation/help/ProviderHelpProvider.cs
  src/System.Management.Automation/singleshell/config/MshSnapinInfo.cs
  src/System.Management.Automation/utils/tracing/SysLogProvider.cs
  test/perf/benchmarks/Engine.Compiler.cs
  test/perf/dotnet-tools/BenchmarkDotNet.Extensions/CommandLineOptions.cs
Labels: CL-CodeCleanup, Large

#19029 Update additional interpolated string changes
  src/Microsoft.WSMan.Management/WsManHelper.cs
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataQuery.cs
  src/System.Management.Automation/cimSupport/cmdletization/xml/CoreCLR/cmdlets-over-objects.xmlSerializer.autogen.cs
Labels: CL-CodeCleanup

#19026 Change test so output does not include newline.
  test/powershell/engine/Api/PSCommand.Tests.ps1
Labels: Extra Small

#19038 Fix progress calculation divide by zero in Copy-Item
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
Labels: Extra Small

#19058 fix typos
  src/Microsoft.Management.UI.Internal/HelpWindow/HelpParagraphBuilder.cs
  src/Microsoft.Management.UI.Internal/HelpWindow/HelpViewModel.cs
  src/Microsoft.Management.UI.Internal/HelpWindow/ParagraphBuilder.cs
  src/Microsoft.Management.UI.Internal/HelpWindow/ParagraphSearcher.cs
  src/Microsoft.Management.UI.Internal/ManagementList/Common/DataRoutedEventArgs.cs
  src/Microsoft.Management.UI.Internal/ManagementList/Common/DismissiblePopup.Generated.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/Controls/ParameterSetControl.xaml.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/ViewModel/CommandViewModel.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/ViewModel/ParameterSetViewModel.cs
  src/Microsoft.Management.UI.Internal/commandHelpers/HelpWindowHelper.cs
  src/Microsoft.Management.UI.Internal/commandHelpers/ShowCommandHelper.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetComputerInfoCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-hex/Format-Hex.cs
  src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/StringUtil.cs
  src/System.Management.Automation/CoreCLR/CorePsAssemblyLoadContext.cs
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
  src/System.Management.Automation/FormatAndOutput/out-console/ConsoleLineOutput.cs
  src/System.Management.Automation/engine/ComInterop/ComInvokeBinder.cs
  src/System.Management.Automation/engine/ComInterop/ExcepInfo.cs
  src/System.Management.Automation/engine/ComInterop/VarEnumSelector.cs
  src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/engine/CommandProcessor.cs
  src/System.Management.Automation/engine/CoreAdapter.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs
  src/System.Management.Automation/engine/MshCmdlet.cs
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  src/System.Management.Automation/engine/Subsystem/SubsystemManager.cs
  src/System.Management.Automation/engine/TypeTable.cs
  src/System.Management.Automation/engine/debugger/debugger.cs
  src/System.Management.Automation/engine/hostifaces/History.cs
  src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs
  src/System.Management.Automation/engine/hostifaces/pipelinebase.cs
  src/System.Management.Automation/engine/parser/token.cs
  src/System.Management.Automation/engine/remoting/client/RemotingProtocol2.cs
  src/System.Management.Automation/engine/remoting/client/remotepipeline.cs
  src/System.Management.Automation/engine/remoting/client/remotingprotocolimplementation.cs
  src/System.Management.Automation/engine/remoting/commands/ConnectPSSession.cs
  src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs
  src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs
  src/System.Management.Automation/engine/remoting/commands/ReceivePSSession.cs
  src/System.Management.Automation/engine/remoting/commands/getrunspacecommand.cs
  src/System.Management.Automation/engine/remoting/commands/newrunspacecommand.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManNativeAPI.cs
  src/System.Management.Automation/engine/remoting/fanin/WSManPluginShellSession.cs
  src/System.Management.Automation/engine/remoting/server/ServerRemotingProtocol2.cs
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/help/CommandHelpProvider.cs
  src/System.Management.Automation/help/HelpCommands.cs
  src/System.Management.Automation/utils/PlatformInvokes.cs
  src/System.Management.Automation/utils/Verbs.cs
Labels: Extra Small

#18949 Adding missing guard for telemetry optout to avoid NRE when importing modules
  src/System.Management.Automation/utils/Telemetry.cs
Labels: CL-General, Extra Small

#19059 fix typo (resx and man files)
  src/PowerShell.Core.Instrumentation/PowerShell.Core.Instrumentation.man
  src/System.Management.Automation/resources/EventResource.resx
Labels: Extra Small

#19025 Add 7.2 and 7.3 change logs
  .spelling
  CHANGELOG/7.2.md
  CHANGELOG/7.3.md
Labels: Small, reminder

#18827 Add tool to trigger license information gathering for NuGet modules
  .spelling
  tools/clearlyDefined/ClearlyDefined.ps1
  tools/clearlyDefined/readme.md
  tools/clearlyDefined/src/ClearlyDefined/ClearlyDefined.psm1
Labels: Review - Needed, CL-Tools, Medium
