Repository PowerShell/PowerShell, pull requests merged in 2023-10, with the labels that each got.

#20369 Fix `Test-Connection` due to .NET 8 changes
  src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs
Labels: CL-General, Extra Small

#20397 Adding survey for closed issues
  .github/policies/resourceManagement.yml
Labels: CL-Docs, Extra Small

#20459 Fix alpine tar package name and do not crossgen alpine fxdependent package
  build.psm1
  tools/packaging/packaging.psm1
  tools/releaseBuild/Images/GenericLinuxFiles/PowerShellPackage.ps1
  tools/releaseBuild/azureDevOps/templates/nuget.yml
  tools/releaseBuild/azureDevOps/templates/release-ValidatePackageNames.yml
Labels: BackPort-7.4.x-Consider

#20462 Fix typos in comments/documentation and clarify
  src/Microsoft.PowerShell.ConsoleHost/host/msh/Executor.cs
Labels: CL-Docs

#20332 Update `README.md` and `metadata.json` for 7.2.15 and 7.3.8 releases
  README.md
  tools/metadata.json
Labels: Review - Needed, Small

#20366 Fix unixmode to handle setuid/sticky when not executable
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/UnixStat.Tests.ps1
Labels: Small, PowerShell-Docs not needed, BackPort-7.4.x-Consider

#20476 Add HelpUri to Remove-Service
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
Labels: WG-Interactive-HelpSystem, CL-General, PowerShell-Docs not needed

#20473 Add 7.3 changelog URL to Readme
  CHANGELOG/README.md
Labels: CL-Docs

#20485 Update version of Microsoft.PowerShell.PSResourceGet to 1.0.0
  src/Modules/PSGalleryModules.csproj
Labels: BackPort-7.4.x-Consider

#20499 Suppress error output from `Set-Location` tests
  test/powershell/Modules/Microsoft.PowerShell.Management/Set-Location.Tests.ps1
Labels: CL-Test

#20470 Increase pacakages.microsoft.com timeout
  tools/releaseBuild/azureDevOps/releasePipeline.yml
Labels: CL-BuildPackaging, Backport-7.2.x-Consider, Backport-7.3.x-Consider, BackPort-7.4.x-Consider

#20478 Only register App Path for release package
  assets/wix/Product.wxs
Labels: CL-BuildPackaging, BackPort-7.4.x-Consider

#20460 Add error if invalid `-ExecutionPolicy` is passed to `pwsh`
  src/Microsoft.PowerShell.ConsoleHost/host/msh/CommandLineParameterParser.cs
  src/Microsoft.PowerShell.ConsoleHost/resources/CommandLineParameterParserStrings.resx
  test/powershell/Host/ConsoleHost.Tests.ps1
  test/xUnit/csharp/test_CommandLineParser.cs
Labels: CL-General, PowerShell-Docs not needed

#20428 Change New-FileCatalog -CatalogVersion default to 2
  src/Microsoft.PowerShell.Security/security/CatalogCommands.cs
  test/powershell/Modules/Microsoft.PowerShell.Security/FileCatalog.Tests.ps1
Labels: Breaking-Change, CL-BreakingChange, CL-General, Extra Small, PowerShell-Docs needed

#20371 Add telemetry to check for specific tags when importing a module
  src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs
  src/System.Management.Automation/utils/Telemetry.cs
Labels: Extra Small, PowerShell-Docs needed

#20419 Fix UNC path completion regression
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Extra Small, PowerShell-Docs not needed, BackPort-7.4.x-Consider

#20504 typo fixed in Update ADOPTERS.md
  ADOPTERS.md
Labels: CL-Docs

#20510 Bump to .NET 8 RC2
  DotnetRuntimeMetadata.json
  global.json
  src/Microsoft.PowerShell.Commands.Diagnostics/Microsoft.PowerShell.Commands.Diagnostics.csproj
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  test/perf/dotnet-tools/BenchmarkDotNet.Extensions/BenchmarkDotNet.Extensions.csproj
  test/perf/dotnet-tools/ResultsComparer/ResultsComparer.csproj
  test/tools/NamedPipeConnection/src/code/Microsoft.PowerShell.NamedPipeConnection.csproj
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
Labels: CL-BuildPackaging

#20509 Correct grammatical errors in README.md
  README.md
Labels: CL-Docs

#20520 Fix typo in Update ADOPTERS.md
  ADOPTERS.md
Labels: CL-Docs

#20517 Fix `Copy-Item` progress to only show completed when all files are copied
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: BackPort-7.4.x-Consider

#20243 Block any preview vPack release
  tools/releaseBuild/azureDevOps/vpackRelease.yml
Labels: Review - Needed, Extra Small, PowerShell-Docs not needed, BackPort-7.4.x-Consider

#20519 Add SBOM for release pipeline
  tools/releaseBuild/azureDevOps/releasePipeline.yml
  tools/releaseBuild/azureDevOps/templates/release-CreateGitHubDraft.yml
  tools/releaseBuild/azureDevOps/templates/release-ValidatePackageNames.yml
  tools/releaseBuild/azureDevOps/templates/vpackReleaseJob.yml
Labels: Backport-7.2.x-Consider, Backport-7.3.x-Consider, BackPort-7.4.x-Approved

#20551 Fix package version for .NET nuget packages
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
Labels: BackPort-7.4.x-Approved

#20555 Update ADOPTERS.md
  ADOPTERS.md
Labels: CL-Docs, Extra Small

#20515 docs: fix link in docs/community/governance.md
  docs/community/governance.md
Labels: CL-Docs

#20554 Added `-Version` argument completer for `Set-StrictMode`
  src/System.Management.Automation/engine/InternalCommands.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Extra Small

#20566 [release/v7.2.16]Add mariner arm64 package build to release build
  tools/packaging/packaging.psm1
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/linux-authenticode-sign.yml
  tools/releaseBuild/azureDevOps/templates/linux-packaging.yml
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/release-ValidatePackageNames.yml
Labels: CL-BuildPackaging, Large

#20569 [release/v7.2.16]Increase pacakages.microsoft.com timeout
  tools/releaseBuild/azureDevOps/releasePipeline.yml
Labels: CL-BuildPackaging, Extra Small

#20570 [release/v7.2.16]Add SBOM for release pipeline
  tools/releaseBuild/azureDevOps/releasePipeline.yml
  tools/releaseBuild/azureDevOps/templates/release-CreateGitHubDraft.yml
Labels: CL-BuildPackaging

#20568 [release/v7.2.16]Use fxdependent-win-desktop runtime for compliance runs
  tools/releaseBuild/azureDevOps/templates/compliance/apiscan.yml
Labels: CL-BuildPackaging, Medium

#20553 Update README.md
  README.md
Labels: CL-Docs, Extra Small

#20571 [release/v7.3.9]Use fxdependent-win-desktop runtime for compliance runs
  tools/releaseBuild/azureDevOps/templates/compliance/apiscan.yml
Labels: CL-BuildPackaging, Extra Small

#20572 [release/v7.3.9]Increase pacakages.microsoft.com timeout
  tools/releaseBuild/azureDevOps/releasePipeline.yml
Labels: CL-BuildPackaging, Extra Small

#20573 [release/v7.3.9]Add SBOM for release pipeline
  tools/releaseBuild/azureDevOps/releasePipeline.yml
  tools/releaseBuild/azureDevOps/templates/release-CreateGitHubDraft.yml
Labels: CL-BuildPackaging

#20558 Update README and metadata.json for RC1 release
  README.md
  tools/metadata.json
Labels: CL-Docs, Extra Small

#20565 [release/v7.2.16]Remove HostArchitecture dynamic for osxpkg
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging, Extra Small

#20567 [release/v7.2.16]Add mariner arm64 to PMC release
  tools/packages.microsoft.com/mapping.json
Labels: CL-BuildPackaging, Extra Small

#20564 [release/v7.2.16]add runtime and packaging type info for mariner2 arm64
  build.psm1
  tools/ci.psm1
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging, Extra Small

#20582 Update README and metadata.json for servicing releases
  README.md
  tools/metadata.json
Labels: CL-Docs, Small

#20608 Fix `Group-Object` so output uses current culture
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Group-Object.cs
Labels: CL-General, Extra Small, BackPort-7.4.x-Consider

#20593 Block getting help from network locations in restricted remoting session
  src/Microsoft.Management.UI.Internal/commandHelpers/ShowCommandHelper.cs
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/help/HelpCommands.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/resources/HelpErrors.resx
  test/powershell/engine/Help/HelpSystem.OnlineHelp.Tests.ps1
  test/powershell/engine/Remoting/RemoteSession.Basic.Tests.ps1
  test/tools/Modules/HelpersCommon/HelpersCommon.psd1
  test/tools/Modules/HelpersCommon/HelpersCommon.psm1
Labels: MustHave, Medium, 7.4-Blocking, BackPort-7.4.x-Consider
