Repository PowerShell/PowerShell, pull requests merged in 2023-07, with the labels that each got.

#19829 Add even more debugging to try to determine why these test fail in release build.
  test/powershell/Modules/PackageManagement/PackageManagement.Tests.ps1
Labels: Release-Testing, Extra Small, PowerShell-Docs not needed

#19450 add runtime and packaging type info for mariner2 arm64
  build.psm1
  tools/ci.psm1
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging, Needs-Triage, Extra Small, PowerShell-Docs needed

#19899 Switch to GitHub Action for linting markdown
  .github/workflows/markdownLink.yml
  test/common/markdown-link/markdown-link.tests.ps1
  test/common/markdown-lint/.gitignore
  test/common/markdown-lint/gulpfile.js
  test/common/markdown-lint/markdown.tests.ps1
  test/common/markdown-lint/package.json
  test/common/markdown-lint/yarn.lock
Labels: Large

#19908 Checkout history for markdown lint check
  .github/workflows/markdownLink.yml
Labels: Extra Small

#19907 Change variable used to bypass nuget security scanning
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/insert-nuget-config-azfeed.yml
Labels: Backport-7.2.x-Consider, Extra Small, Backport-7.3.x-Consider

#19916 Fix completion crash
  src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs
  test/powershell/Host/TabCompletion/BugFix.Tests.ps1
Labels: Extra Small, PowerShell-Docs not needed

#19879 Remove unused string completion code
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
Labels: WG-Engine, CL-CodeCleanup, Small

#19750 Publish rpm package for rhel9
  tools/packages.microsoft.com/mapping.json
Labels: CL-BuildPackaging, Backport-7.2.x-Consider, Extra Small, Backport-7.3.x-Consider, PowerShell-Docs needed

#19871 Migrate user docs to Docs repo
  .spelling
  docs/DOCSMIGRATION.md
  docs/FAQ.md
  docs/learning-powershell/README.md
  docs/learning-powershell/create-powershell-scripts.md
  docs/learning-powershell/debugging-from-commandline.md
  docs/learning-powershell/powershell-beginners-guide.md
  docs/learning-powershell/working-with-powershell-objects.md
Labels: CL-Docs, Extra Large, CommunityDay-Small

#19831 Add completion for variables assigned by Data statement
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: Review - Needed, CL-Engine, Extra Small, PowerShell-Docs not needed

#19692 Apply IDE0019: InlineAsTypeCheck in Management.Automation folders
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/cimSupport/cmdletization/MethodInvocationInfo.cs
  src/System.Management.Automation/cimSupport/cmdletization/ObjectModelWrapper.cs
  src/System.Management.Automation/cimSupport/cmdletization/ScriptWriter.cs
  src/System.Management.Automation/cimSupport/other/ciminstancetypeadapter.cs
  src/System.Management.Automation/logging/LogProvider.cs
  src/System.Management.Automation/logging/MshLog.cs
  src/System.Management.Automation/security/SecurityManager.cs
  src/System.Management.Automation/security/SecuritySupport.cs
  src/System.Management.Automation/singleshell/config/MshSnapinInfo.cs
  src/System.Management.Automation/utils/CryptoUtils.cs
  src/System.Management.Automation/utils/ExecutionExceptions.cs
  src/System.Management.Automation/utils/ParameterBinderExceptions.cs
  src/System.Management.Automation/utils/PowerShellExecutionHelper.cs
  src/System.Management.Automation/utils/PsUtils.cs
  src/System.Management.Automation/utils/RuntimeException.cs
  src/System.Management.Automation/utils/SessionStateExceptions.cs
Labels: Review - Needed, CL-CodeCleanup, Medium, PowerShell-Docs not needed

#19694 Apply IDE0019: InlineAsTypeCheck in Management.Automation.FormatAndOutput
  src/System.Management.Automation/FormatAndOutput/common/BaseFormattingCommandParameters.cs
  src/System.Management.Automation/FormatAndOutput/common/BaseOutputtingCommand.cs
  src/System.Management.Automation/FormatAndOutput/common/ComplexWriter.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/XmlLoaderBase.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Complex.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_List.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Table.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Wide.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataQuery.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatMsgCtxManager.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator_Complex.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator_List.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator_Table.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatViewManager.cs
  src/System.Management.Automation/FormatAndOutput/common/FormatXMLWriter.cs
  src/System.Management.Automation/FormatAndOutput/common/FormattingObjectsDeserializer.cs
  src/System.Management.Automation/FormatAndOutput/common/OutputQueue.cs
  src/System.Management.Automation/FormatAndOutput/common/Utilities/MshObjectUtil.cs
  src/System.Management.Automation/FormatAndOutput/common/Utilities/Mshexpression.cs
  src/System.Management.Automation/FormatAndOutput/out-console/OutConsole.cs
Labels: Review - Needed, Large, PowerShell-Docs not needed

#19921 Fix completion regression for filesystem paths with custom PSDrives
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: Extra Small

#19932 Update the link for getting started in `README.md`
  README.md
Labels: Backport-7.2.x-Consider, Extra Small, Backport-7.3.x-Consider

#19931 Change System.Security.AccessControl preview version to stable version
  src/System.Management.Automation/System.Management.Automation.csproj
  tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  tools/packaging/projects/reference/System.Management.Automation/System.Management.Automation.csproj
Labels: Extra Small, Backport-7.3.x-Consider

#19935 [release/v7.2.13]Change variable used to bypass nuget security scanning
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/insert-nuget-config-azfeed.yml
Labels: Extra Small

#19933 [release/v7.2.13]Bump to 6.0.412 SDK
  DotnetRuntimeMetadata.json
  global.json
Labels: Extra Small

#19936 [release/v7.2.13]Increase the timeout when waiting for the event log
  test/powershell/engine/Basic/GroupPolicySettings.Tests.ps1
Labels: Extra Small

#19937 [release/v7.2.13]Increase timeout to make subsystem tests more reliable
  test/xUnit/csharp/test_Prediction.cs
Labels: Extra Small

#19926 Add Microsoft.Powershell.PSResourceGet for telemetry module list
  src/System.Management.Automation/utils/Telemetry.cs
Labels: Extra Small

#19947 [release/v7.3.6]Update the link for getting started in `README.md`
  README.md
Labels: Extra Small

#19953 [release/v7.3.6]Change variable used to bypass nuget security scanning
  tools/releaseBuild/azureDevOps/compliance.yml
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/insert-nuget-config-azfeed.yml
Labels: Extra Small

#19951 [release/v7.3.6]Add ProductCode in registry for MSI install
  assets/wix/Product.wxs
  test/packaging/windows/msi.tests.ps1
Labels: Extra Small

#19954 Change variable used to bypass nuget security scanning
  tools/releaseBuild/azureDevOps/compliance.yml
Labels: Extra Small

#19952 [release/v7.3.6]Remove the property disabling optimization
  PowerShell.Common.props
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
Labels: Extra Small

#19945 [release/v7.3.6] Bump .NET to 7.0.306
  DotnetRuntimeMetadata.json
  global.json
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  tools/cgmanifest.json
Labels: Extra Small

#19955 Don't publish notice on failure because it prevents retry
  tools/releaseBuild/azureDevOps/templates/compliance/generateNotice.yml
Labels: Backport-7.2.x-Consider, Extra Small, Backport-7.3.x-Consider

#19956 [release/7.2.13]Update Notice file
  ThirdPartyNotices.txt
  tools/releaseBuild/azureDevOps/compliance.yml
Labels: Extra Small

#19957 Fix ///-comments that violate the docs schema
  src/Microsoft.Management.UI.Internal/ManagementList/Common/ReadOnlyObservableAsyncCollection.cs
  src/Microsoft.Management.UI.Internal/ManagementList/Common/ScalableImage.cs
  src/Microsoft.Management.UI.Internal/ManagementList/ManagementList/Innerlist.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs
  src/System.Management.Automation/engine/Attributes.cs
  src/System.Management.Automation/engine/CommandInfo.cs
  src/System.Management.Automation/engine/ErrorPackage.cs
  src/System.Management.Automation/engine/ProgressRecord.cs
  src/System.Management.Automation/engine/cmdlet.cs
  src/System.Management.Automation/engine/hostifaces/ChoiceDescription.cs
  src/System.Management.Automation/engine/hostifaces/Connection.cs
  src/System.Management.Automation/engine/hostifaces/FieldDescription.cs
  src/System.Management.Automation/engine/hostifaces/MshHostRawUserInterface.cs
  src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs
  src/System.Management.Automation/engine/lang/interface/PSToken.cs
  src/System.Management.Automation/engine/parser/PreOrderVisitor.cs
  src/System.Management.Automation/engine/parser/ast.cs
  src/System.Management.Automation/engine/parser/token.cs
  src/System.Management.Automation/namespaces/ProviderDeclarationAttribute.cs
  src/System.Management.Automation/utils/StructuredTraceSource.cs
Labels: CL-Docs, Extra Small

#19964 Update `README.md` and `metadata.json` for release v7.2.13 and v7.3.6
  README.md
  tools/metadata.json
Labels: Small

#19967 Update variable used to bypass the blocking check for multiple NuGet feeds
  .vsts-ci/linux.yml
  .vsts-ci/mac.yml
  .vsts-ci/windows.yml
  .vsts-ci/windows/windows-packaging.yml
  tools/releaseBuild/azureDevOps/vpackRelease.yml
Labels: CL-BuildPackaging, MustHave, Backport-7.2.x-Consider, Extra Small, Backport-7.3.x-Consider

#19963 Update variable used to bypass the blocking check for multiple NuGet feeds for release pipeline
  tools/releaseBuild/azureDevOps/releasePipeline.yml
Labels: Extra Small

#19929 Hide extension tests errors
  test/powershell/Host/ConsoleHost.Tests.ps1
Labels: Extra Small

#19973 Remove spelling CI in favor of GitHub Action
  .github/CONTRIBUTING.md
  .github/workflows/markdownLink.yml
  .vsts-ci/misc-analysis.yml
  .vsts-ci/misc-analysis/markdown.yml
  .vsts-ci/misc-analysis/mdSpell.yml
Labels: CL-Test, Backport-7.2.x-Consider, Medium, Backport-7.3.x-Consider, PowerShell-Docs not needed

#19940 Fix deadlock when piping to shell associated file extension
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
Labels: Extra Small, PowerShell-Docs not needed

#19939 Check for pre-release packages
  tools/findMissingNotices.ps1
Labels: Extra Small, PowerShell-Docs not needed

#19972 Add Help proxy function for non-Windows platforms
  src/System.Management.Automation/engine/InitialSessionState.cs
Labels: Waiting on Author, Medium, PowerShell-Docs not needed

#19968 Merge 7.3.5, 7.3.6, 7.2.12 and 7.2.13 change logs
  CHANGELOG/7.2.md
  CHANGELOG/7.3.md
Labels: CL-Docs, Medium, PowerShell-Docs not needed

#19824 Computer cmdlets should fail with error when not run via sudo on Unix
  src/Microsoft.PowerShell.Commands.Management/commands/management/ComputerUnix.cs
  src/Microsoft.PowerShell.Commands.Management/resources/ComputerResources.resx
  src/Microsoft.PowerShell.ConsoleHost/resources/ConsoleHostStrings.resx
  test/powershell/Modules/Microsoft.PowerShell.Management/Restart-Computer.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Stop-Computer.Tests.ps1
Labels: CL-General, Small, PowerShell-Docs not needed

#19993 Update man page to match current help for pwsh
  assets/pwsh.1.ronn
Labels: CL-Docs, Medium

#19994 Change docs.microsoft.com to learn.microsoft.com
  .editorconfig
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_Report.yaml
  .github/ISSUE_TEMPLATE/Microsoft_Update_Issue.yaml
  .github/SUPPORT.md
  .globalconfig
  .spelling
  ADOPTERS.md
  README.md
  assets/MicrosoftUpdate/RegisterMicrosoftUpdate.ps1
  build.psm1
  demos/DSC/readme.md
  docs/building/linux.md
  docs/building/windows-core.md
  docs/cmdlet-example/command-line-simple-example.md
  docs/debugging/README.md
  docs/dev-process/coding-guidelines.md
  docs/host-powershell/README.md
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/TestJsonCommand.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/System.Management.Automation/cimSupport/cmdletization/xml/cmdlets-over-objects.xsd
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/utils/EncodingUtils.cs
  src/System.Management.Automation/utils/PSTelemetryWrapper.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/assets/localized.ps1
  test/tools/Modules/HelpersCommon/HelpersCommon.psm1
  test/tools/Modules/HttpListener/HttpListener.psm1
  test/xUnit/README.md
  tools/performance/GC.Regions.xml
  tools/performance/PowerShell.Regions.xml
  tools/performance/PowerShell.stacktags
Labels: Extra Large

#19996 Replace docs.microsoft.com URLs in code with FWLinks
  assets/wix/Product.wxs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Get-Error.cs
Labels: CL-Docs, Extra Small

#19946 Add mariner arm64 package build to release build
  tools/packaging/packaging.psm1
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/linux-authenticode-sign.yml
  tools/releaseBuild/azureDevOps/templates/linux-packaging.yml
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/release-ValidatePackageNames.yml
Labels: CL-BuildPackaging, Waiting on Author, Medium, PowerShell-Docs needed

#19683 Added `-CaseInsensitive` switch parameter to `Select-Object` & `Get-Unique` cmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetUnique.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Select-Object.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Unique.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Select-Object.Tests.ps1
Labels: WG-Cmdlets, Review - Needed, WG-Cmdlets-Utility, Extra Small, CommunityDay-Small, PowerShell-Docs needed, WG-Reviewed

#19755 Change how relative paths in `Resolve-Path` are handled when using the `RelativeBasePath` parameter
  src/Microsoft.PowerShell.Commands.Management/commands/management/ResolvePathCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Resolve-Path.Tests.ps1
Labels: WG-Engine, Needs-Triage, Medium, CommunityDay-Small, PowerShell-Docs needed

#20019 Delete rule that was supposed to round-robin assign a maintainer
  .github/policies/resourceManagement.yml
Labels: CL-BuildPackaging, Extra Small

#20020 Auto assign PR Maintainer
  .github/workflows/AssignPrs.yml
Labels: CL-BuildPackaging, Extra Small

#19343 WebCmdlet unix-sockets
  .spelling
  build.psm1
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/WebRequestSession.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
  test/tools/Modules/UnixSocket/README.md
  test/tools/Modules/UnixSocket/UnixSocket.psd1
  test/tools/Modules/UnixSocket/UnixSocket.psm1
  test/tools/UnixSocket/UnixSocket.cs
  test/tools/UnixSocket/UnixSocket.csproj
Labels: WG-Cmdlets, Documentation Needed in this repo, Needs-Triage, Medium, CommunityDay-Large, PowerShell-Docs needed

#20021 Give assignPRs workflow write permissions
  .github/workflows/AssignPrs.yml
Labels: Extra Small

#20028 Test fixes which fail during release testing.
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1
  test/powershell/engine/Remoting/RemoteSession.Basic.Tests.ps1
  test/powershell/engine/Security/FileSignature.Tests.ps1
Labels: Small

#20048 Fix typo in Logging.Tests.ps1
  test/powershell/Host/Logging.Tests.ps1
Labels: CL-CodeCleanup, Extra Small

#20052 Fix use of `ThrowIf` where the arguments were reversed
  src/Microsoft.Management.UI.Internal/HelpWindow/ParagraphBuilder.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimConverter.cs
  src/System.Management.Automation/engine/ProgressRecord.cs
Labels: Extra Small
