Repository PowerShell/PowerShell, pull requests merged in 2023-12, with the labels that each got.

#20839 Update LTS links in README.md fixes #20774
  README.md
Labels: Extra Small

#20850 Bump .NET SDK to 8.0.0 RTM build and move the current preview changelog to `7.4.md`
  CHANGELOG/7.4.md
  DotnetRuntimeMetadata.json
  global.json
  src/Microsoft.PowerShell.Commands.Diagnostics/Microsoft.PowerShell.Commands.Diagnostics.csproj
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
  tools/releaseBuild/azureDevOps/templates/nuget-pkg-sbom.yml
Labels: CL-BuildPackaging, Small

#20849 Remove RHEL7 publishing to packages.microsoft.com as it's no longer supported
  tools/packages.microsoft.com/mapping.json
Labels: Extra Small, BackPort-7.4.x-Consider

#20820 Add `LP` to `LiteralPath` aliases for functions still missing it
  src/Microsoft.PowerShell.Security/security/AclCommands.cs
  src/Microsoft.PowerShell.Security/security/CertificateCommands.cs
  src/Microsoft.PowerShell.Security/security/SignatureCommands.cs
Labels: Extra Small

#20838 Fix typo in InputFieldBackgroundTextConverter.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterProviders/InputFieldBackgroundTextConverter.cs
Labels: CL-CodeCleanup, No Changes

#20794 Sign the global tool shim exe.
  tools/releaseBuild/signing.xml
Labels: CL-BuildPackaging, Extra Small

#20689 Set the ollForwardOnNoCandidateFx in runtime.config to roll forward only on minor.patch versions
  src/Microsoft.PowerShell.GlobalTool.Shim/runtimeconfig.template.json
  src/powershell-unix/runtimeconfig.template.json
  src/powershell-win-core/runtimeconfig.template.json
Labels: Review - Needed, Backport-7.2.x-Consider, Extra Small, Backport-7.3.x-Consider, BackPort-7.4.x-Consider

#20671 Update apiscan.yml to have access to variable group
  tools/releaseBuild/azureDevOps/templates/compliance/apiscan.yml
Labels: Review - Needed, Backport-7.2.x-Consider, Extra Small, Backport-7.3.x-Consider, BackPort-7.4.x-Consider

#20749 Fix #20400, Start-Process with -NoNewWindow returns null ExitCode on Process object with -PassThru
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
Labels: CL-General, Extra Small, CommunityDay-Small, BackPort-7.4.x-Consider

#20863 [release/v7.4.1] Fix rendering of DisplayRoot for network PSDrive
  src/System.Management.Automation/engine/Interop/Windows/WNetGetConnection.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/New-PSDrive.Tests.ps1
Labels: CL-General, Extra Small

#20864 [release/v7.4.1] Remove RHEL7 publishing to packages.microsoft.com as it's no longer supported
  tools/packages.microsoft.com/mapping.json
Labels: CL-BuildPackaging, Extra Small

#20871 Update dependencies for v7.4.1
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/System.Management.Automation/SourceGenerators/PSVersionInfoGenerator/PSVersionInfoGenerator.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  test/xUnit/xUnit.tests.csproj
Labels: Extra Small

#20805 Bot refactoring for easier use and updating
  .github/policies/IssueManagement.CloseResolutions.yml
  .github/policies/IssueManagement.IssueFeedbackForm.yml
  .github/policies/IssueManagement.ResolveStale.yml
  .github/policies/PRManagement.yml
  .github/policies/resourceManagement.yml
Labels: CL-Docs, Extra Large

#20874 Update cgmanifest for v7.4.1
  tools/cgmanifest.json
Labels: Small

#20815 Fix completion crash for certain providers
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
Labels: CL-General, Extra Small

#20878 Make sure feedback link is clickable
  .github/policies/IssueManagement.IssueFeedbackForm.yml
Labels: Extra Small

#20899 Bump `xunit` to 2.6.3 and disable the `xUnit1031` warning
  test/xUnit/AssemblyInfo.cs
  test/xUnit/xUnit.tests.csproj
Labels: CL-BuildPackaging, Extra Small

#20913 Fix four issues for the WDAC logging feature
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  src/System.Management.Automation/engine/remoting/client/RunspaceRef.cs
  src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  src/System.Management.Automation/resources/ParserStrings.resx
  src/System.Management.Automation/resources/RemotingErrorIdStrings.resx
Labels: CL-General, Small, BackPort-7.4.x-Consider

#20919 Revert "Fix completion crash for certain providers"
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
Labels: CL-General, Extra Small

#20928 Fixing incorrect formatting string in CommandSearcher trace logging.
  src/System.Management.Automation/engine/CommandSearcher.cs
Labels: CL-General, Extra Small, PowerShell-Docs not needed

#20286 Add `-Verb` argument completer for `Get-Verb`/ `Get-Command` and refactor `Get-Verb`
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetVerbCommand.cs
  src/System.Management.Automation/engine/GetCommandCommand.cs
  src/System.Management.Automation/utils/Verbs.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: WG-Cmdlets, CL-General, Medium, PowerShell-Docs not needed, WG-Reviewed

#20451 Add `-Scope` argument completer for `*-Variable`, `*-Alias` & `*-PSDrive` commands
  src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ExportAliasCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetAliasCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImportAliasCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/RemoveAliasCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Var.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WriteAliasCommandBase.cs
  src/System.Management.Automation/engine/CommandCompletion/ScopeArgumentCompleter.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Extra Small, PowerShell-Docs not needed

#20415 Add `-Verb` argument completer for `Start-Process`
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: WG-Cmdlets, CL-General, Small, CommunityDay-Small, PowerShell-Docs not needed

#20942 Fix `-OlderThan`/`-NewerThan` parameters for `Test-Path` when using `PathType` and date range
  src/Microsoft.PowerShell.Commands.Management/commands/management/TestPathCommand.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Test-Path.Tests.ps1
Labels: WG-Cmdlets-Utility, CL-BreakingChange, CL-General, Small, PowerShell-Docs needed, WG-Reviewed

#20678 Added `-Module` completion for `Save-Help`/`Update-Help` commands
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Small, PowerShell-Docs not needed

#20939 Test-FileCatalog changes to use File.OpenRead to better handle when the file is executing or open Fix #20703
  src/System.Management.Automation/security/CatalogHelper.cs
  test/powershell/Modules/Microsoft.PowerShell.Security/FileCatalog.Tests.ps1
Labels: CL-General, Extra Small, PowerShell-Docs not needed
