Repository PowerShell/PowerShell, pull requests merged in 2023-02, with the labels that each got.

#19030 Small cleanup WebCmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/ContentHelper.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebResponseHelper.CoreClr.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebResponseObjectFactory.CoreClr.cs
Labels: CL-CodeCleanup, Small

#19044 Add ValidateNotNullOrEmpty to OutFile and InFile parameters of WebCmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: CL-General, Extra Small

#18964 Rework SetRequestContent in WebCmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
Labels: CL-CodeCleanup, Small

#19069 Mark 7.2.x releases as latest LTS but not latest stable
  tools/metadata.json
Labels: Extra Small

#19024 Fix for JEA session leaking functions
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/SessionStateScope.cs
Labels: CL-Engine, Medium

#19082 Fix `Start-Process -Credential -Wait` to work on Windows
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
Labels: CL-General, Extra Small

#19113 Update CodeQL build agent to use `ubuntu-latest`
  .github/workflows/codeql-analysis.yml
Labels: CL-BuildPackaging, Extra Small

#19114 [release/v7.2.10] Add test for framework dependent package in release pipeline
  build.psm1
  tools/releaseBuild/azureDevOps/releasePipeline.yml
  tools/releaseBuild/azureDevOps/templates/release-ValidateFxdPackage.yml
  tools/releaseBuild/azureDevOps/templates/release-ValidatePackageNames.yml
  tools/releaseBuild/azureDevOps/templates/signBuildFiles.yml
Labels: Small

#19109 Small changes in Webcmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
Labels: CL-CodeCleanup, Extra Small

#19108 Add `-NoHeader` parameter to `ConvertTo-Csv` and `Export-Csv` cmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertTo-Csv.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Export-Csv.Tests.ps1
Labels: CL-General, Extra Small

#19080 Fix error formatting to remove the unneeded leading newline for concise view
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
Labels: CL-General, Extra Small

#19095 Make exception errors in PowerShell able to associate with the right history entry
  src/System.Management.Automation/engine/AutomationEngine.cs
  src/System.Management.Automation/engine/lang/parserutils.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  src/System.Management.Automation/utils/ParserException.cs
  test/powershell/Language/Scripting/ErrorHistoryId.Tests.ps1
Labels: CL-Engine, Medium

#18837 Improve Invoke-WebRequest xml and json errors format
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: CL-General, Small

#19117 Dispose previous response in Webcmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
Labels: CL-General, Extra Small

#19123 Added minor readability and refactoring fixes to Process.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
Labels: CL-CodeCleanup, Extra Small

#19124 Cleanup WebCmdlets comments
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/BasicHtmlWebResponseObject.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebResponseObject.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/InvokeWebRequestCommand.CoreClr.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebProxy.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/FormObject.cs
Labels: CL-CodeCleanup, Extra Small

#19119 Allow cross compiling windows
  build.psm1
Labels: Extra Small

#19126 Merge partials in WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
Labels: CL-CodeCleanup, Extra Large

#19111 Fix redirection for -CustomMethod "POST" in WebCmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: CL-General, Extra Small

#19128 Small cleanup webcmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
Labels: CL-CodeCleanup, Small

#19136 Revert comment changes in WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
Labels: CL-CodeCleanup, No Changes

#18595 Webcmdlets display an error on https to http redirect
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/WebCmdletStrings.resx
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: CL-General, Extra Small

#18894 Add PreserveHttpMethodOnRedirect switch to Web cmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: WG-Cmdlets-Utility, CL-General, Small

#19129 Add verification of R2R at packaging
  build.psm1
  tools/packaging/packaging.psm1
Labels: Medium

#19153 Fix a typo in the `pwsh` help content
  src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx
Labels: CL-CodeCleanup, Extra Small

#19159 Add URL for all distributions
  tools/packages.microsoft.com/mapping.json
Labels: CL-BuildPackaging, BackPort-7.0.x-Consider, Backport-7.2.x-Consider, Small

#19177 Fix typo in InitialSessionState.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
Labels: No Changes

#19042 Add `-Path` and `-LiteralPath` parameters to `Test-Json` cmdlet
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/TestJsonCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Test-Json.Tests.ps1
Labels: WG-Cmdlets-Utility, CL-General, Medium

#19176 Fix some minor spelling mistakes
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionProxy.cs
  src/System.Management.Automation/engine/DefaultCommandRuntime.cs
  src/System.Management.Automation/engine/parser/tokenizer.cs
  src/System.Management.Automation/engine/remoting/common/remotingexceptions.cs
  test/powershell/engine/Basic/ValidateAttributes.Tests.ps1
Labels: Extra Small

#19179 Fix class member completion for classes with base types
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Extra Small

#19151 Revert a few changes to not use 'ArgumentNullException.ThrowIfNull'
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/lang/scriptblock.cs
  src/System.Management.Automation/engine/parser/SafeValues.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/utils/ParserException.cs
  src/System.Management.Automation/utils/perfCounters/CounterSetRegistrarBase.cs
Labels: CL-CodeCleanup, Extra Small

#19160 Simplify Windows Packaging CI Trigger YAML
  .vsts-ci/windows/windows-packaging.yml
Labels: Extra Small

#19133 Update the `FeedbackProvider` interface to return structured data
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  src/System.Management.Automation/FormatAndOutput/common/PSStyle.cs
  src/System.Management.Automation/engine/Subsystem/FeedbackSubsystem/FeedbackHub.cs
  src/System.Management.Automation/engine/Subsystem/FeedbackSubsystem/IFeedbackProvider.cs
  src/System.Management.Automation/engine/hostifaces/HostUtilities.cs
  src/System.Management.Automation/resources/SuggestionStrings.resx
  test/xUnit/csharp/test_Feedback.cs
  test/xUnit/csharp/test_Subsystem.cs
Labels: CL-Engine, Large

#19194 Update to .NET 8 preview 1 build
  Analyzers.props
  DotnetRuntimeMetadata.json
  PowerShell.Common.props
  assets/wix/files.wxs
  build.psm1
  global.json
  nuget.config
  src/Microsoft.Management.UI.Internal/Microsoft.PowerShell.GraphicalHost.csproj
  src/Microsoft.PowerShell.Commands.Diagnostics/Microsoft.PowerShell.Commands.Diagnostics.csproj
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/Modules/PSGalleryModules.csproj
  src/ResGen/ResGen.csproj
  src/System.Management.Automation/SourceGenerators/PSVersionInfoGenerator/PSVersionInfoGenerator.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  src/TypeCatalogGen/TypeCatalogGen.csproj
  src/powershell-win-core/powershell-win-core.csproj
  test/Test.Common.props
  test/perf/dotnet-tools/BenchmarkDotNet.Extensions/BenchmarkDotNet.Extensions.csproj
  test/perf/dotnet-tools/ResultsComparer/ResultsComparer.csproj
  test/powershell/engine/ExperimentalFeature/Get-ExperimentalFeature.Tests.ps1
  test/powershell/engine/Formatting/PSStyle.Tests.ps1
  test/tools/NamedPipeConnection/build.ps1
  test/tools/NamedPipeConnection/src/code/Microsoft.PowerShell.NamedPipeConnection.csproj
  test/tools/OpenCover/OpenCover.psm1
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/BrotliFilter.cs
  test/tools/WebListener/Controllers/AuthController.cs
  test/tools/WebListener/Controllers/LinkController.cs
  test/tools/WebListener/Controllers/RedirectController.cs
  test/tools/WebListener/DeflateFilter.cs
  test/tools/WebListener/GzipFilter.cs
  test/tools/WebListener/WebListener.csproj
  tools/findMissingNotices.ps1
  tools/packaging/packaging.psm1
  tools/packaging/packaging.strings.psd1
  tools/packaging/projects/nuget/package.csproj
  tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  tools/packaging/projects/reference/Microsoft.PowerShell.ConsoleHost/Microsoft.PowerShell.ConsoleHost.csproj
  tools/packaging/projects/reference/System.Management.Automation/System.Management.Automation.csproj
  tools/releaseBuild/azureDevOps/templates/release-SDKTests.yml
Labels: CL-BuildPackaging, Large

#19199 Split test artifact build into windows and non-windows
  tools/releaseBuild/azureDevOps/templates/testartifacts.yml
Labels: Small

#19178 Add property assignment completion for enums
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: Extra Small

#19201 Replace `Requires.Condition` with `ArgumentOutOfRangeException.ThrowIfNegativeOrZero`
  src/System.Management.Automation/engine/Subsystem/FeedbackSubsystem/FeedbackHub.cs
  src/System.Management.Automation/engine/Subsystem/PredictionSubsystem/CommandPrediction.cs
  src/System.Management.Automation/engine/Utils.cs
Labels: CL-CodeCleanup, Extra Small

#19197 Replace `Requires.NotNullOrEmpty(string)` with `ArgumentException.ThrowIfNullOrEmpty`
  src/System.Management.Automation/engine/Subsystem/FeedbackSubsystem/IFeedbackProvider.cs
  src/System.Management.Automation/engine/Subsystem/PredictionSubsystem/CommandPrediction.cs
  src/System.Management.Automation/engine/Subsystem/PredictionSubsystem/ICommandPredictor.cs
  src/System.Management.Automation/engine/Utils.cs
Labels: CL-CodeCleanup, Extra Small

#19214 Add pattern to replace for reference API generation
  tools/packaging/packaging.psm1
Labels: Extra Small

#19204 Update tools metadata and README
  README.md
  tools/metadata.json
Labels: Small

#19216 Replace BitConverter.ToString(bytes).Replace("-", "") with Convert.ToHexString(bytes)
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs
  src/System.Management.Automation/security/CatalogHelper.cs
  src/System.Management.Automation/utils/PsUtils.cs
  src/System.Management.Automation/utils/tracing/PSEtwLog.cs
  src/TypeCatalogGen/TypeCatalogGen.cs
Labels: CL-CodeCleanup, Extra Small

#19219 Pull in changelogs for 7.2.10 and 7.3.3
  .spelling
  CHANGELOG/7.2.md
  CHANGELOG/7.3.md
Labels: CL-Docs, Extra Small

#19213 Use ArgumentException.ThrowIfNullOrEmpty() in more places
  src/Microsoft.Management.UI.Internal/ManagementList/Common/WpfHelp.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/PropertyValueSelectorFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/ValidatingValueBase.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterProviders/FilterRulePanelItem.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/TraceExpressionCommand.cs
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/Microsoft.WSMan.Management/CurrentConfigurations.cs
  src/Microsoft.WSMan.Management/WsManHelper.cs
  src/System.Management.Automation/CoreCLR/CorePsAssemblyLoadContext.cs
  src/System.Management.Automation/cimSupport/cmdletization/ObjectModelWrapper.cs
  src/System.Management.Automation/engine/CommandInfo.cs
  src/System.Management.Automation/engine/Modules/ModuleSpecification.cs
  src/System.Management.Automation/engine/Modules/PSModuleInfo.cs
  src/System.Management.Automation/engine/PSClassInfo.cs
  src/System.Management.Automation/engine/remoting/commands/InvokeCommandCommand.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/utils/MshTraceSource.cs
  src/System.Management.Automation/utils/StructuredTraceSource.cs
  src/System.Management.Automation/utils/perfCounters/PSPerfCountersMgr.cs
  test/xUnit/csharp/test_FileSystemProvider.cs
Labels: CL-BreakingChange, CL-CodeCleanup, Small

#19229 WebRequestPSCmdlet.Common.cs remove { } and indentation
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
Labels: Medium

#19215 Use `ArgumentException.ThrowIfNullOrEmpty` part 1
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimQuery.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/CIMHelper.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/PingPathCommand.cs
Labels: CL-BreakingChange, CL-CodeCleanup, Extra Small

#19241 Small style changes
  src/Microsoft.Management.UI.Internal/ManagementList/Common/WpfHelp.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
Labels: CL-CodeCleanup, Extra Small
