Repository PowerShell/PowerShell, pull requests merged in 2023-06, with the labels that each got.

#19729 Disable SBOM signing for CI and add extra files for packaging tests
  .vsts-ci/windows/templates/windows-packaging.yml
Labels: CL-BuildPackaging, Extra Small

#19728 Update windows.json packaging BOM
  tools/packaging/boms/windows.json
Labels: CL-BuildPackaging, Extra Small

#19224 Fix parsing for array literals in index expressions in method calls
  src/System.Management.Automation/engine/parser/Parser.cs
  test/powershell/Language/Parser/Parsing.Tests.ps1
Labels: WG-Engine, CL-Engine, Extra Small, PowerShell-Docs not needed

#19746 Re-enable Get-ComputerInfo pending tests.
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-ComputerInfo.Tests.ps1
Labels: Extra Small

#19701 Remove the property disabling optimization
  PowerShell.Common.props
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
Labels: CL-General, Extra Small, Backport-7.3.x-Consider, PowerShell-Docs not needed

#19740 Fix Enum member completion for PS Enums
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-Engine, Extra Small

#19727 Add ParameterSetName for the Detailed parameter
  src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs
Labels: CL-General, Extra Small, PowerShell-Docs needed

#19761 Add retry on failure for all upload tasks in Azure Pipelines
  .vsts-ci/linux/templates/packaging.yml
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/compliance/apiscan.yml
  tools/releaseBuild/azureDevOps/templates/compliance/generateNotice.yml
  tools/releaseBuild/azureDevOps/templates/linux-packaging.yml
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-build.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/nuget.yml
  tools/releaseBuild/azureDevOps/templates/release-BuildJson.yml
  tools/releaseBuild/azureDevOps/templates/release-UpdateDepsJson.yml
  tools/releaseBuild/azureDevOps/templates/sign-build-file.yml
  tools/releaseBuild/azureDevOps/templates/signBuildFiles.yml
  tools/releaseBuild/azureDevOps/templates/upload-final-results.yml
  tools/releaseBuild/azureDevOps/templates/upload.yml
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
Labels: Extra Small

#19759 Update group to assign PRs
  .github/fabricbot.json
Labels: CL-BuildPackaging

#19758 Update working-group.md to add section about reporting working group members
  docs/community/working-group.md
Labels: CL-Docs, Extra Small

#19467 Add FileNameStar to MultipartFileContent in WebCmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: WG-Cmdlets, CL-General, Extra Small, PowerShell-Docs needed

#18691 Fix variable type inference precedence
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: WG-Engine, CL-Engine, Extra Small

#19788 Update JsonSchema.Net from 4.1.2 to 4.1.3
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  tools/packaging/boms/windows.json
Labels: Extra Small

#19770 Add some debugging to the transcript test for SilentlyContinue.
  test/powershell/Host/Logging.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Diagnostics/Get-Counter.Tests.ps1
  test/powershell/Modules/Microsoft.Powershell.Host/Start-Transcript.Tests.ps1
  test/powershell/Modules/PackageManagement/PackageManagement.Tests.ps1
  test/tools/Modules/PSSysLog/PSSysLog.psm1
Labels: CL-Test, Extra Small, PowerShell-Docs not needed

#18417 Make use of new Random.Shared property
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
  src/System.Management.Automation/help/UpdatableHelpCommandBase.cs
Labels: Review - Needed, CL-CodeCleanup, Needs-Triage, Extra Small

#19803 [release/v7.2.12] Always regenerate files wxs fragment
  .gitignore
  assets/wix/files.wxs
  assets/wix/patch-template.wxs
  tools/packaging/boms/linux.json
  tools/packaging/boms/mac.json
  tools/packaging/boms/windows.json
  tools/packaging/packaging.psd1
  tools/packaging/packaging.psm1
Labels: Extra Large

#19798 Update to .NET 6.0.410
  DotnetRuntimeMetadata.json
  global.json
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  test/hosting/hosting.tests.csproj
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
Labels: Extra Small

#19807 Update to .NET 7.0.304
  Analyzers.props
  docs/learning-powershell/README.md
  global.json
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  test/hosting/hosting.tests.csproj
  test/powershell/engine/Remoting/CustomConnection.Tests.ps1
  test/tools/NamedPipeConnection/src/code/Microsoft.PowerShell.NamedPipeConnection.csproj
  test/tools/TestAlc/init/Test.Isolated.Init.csproj
  test/tools/TestAlc/nested/Test.Isolated.Nested.csproj
  test/tools/TestAlc/root/Test.Isolated.Root.csproj
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
  tools/packaging/boms/windows.json
Labels: Large

#19597 Add reference to PSResourceGet
  src/Modules/PSGalleryModules.csproj
  test/powershell/Modules/Microsoft.PowerShell.PSResourceGet/Microsoft.PowerShell.PSResourceGet.Tests.ps1
  test/powershell/Modules/PowerShellGet/PowerShellGet.Tests.ps1
  tools/packaging/boms/linux.json
  tools/packaging/boms/mac.json
  tools/packaging/boms/windows.json
Labels: Medium, PowerShell-Docs needed

#19809 Update working-group-definitions.md
  docs/community/working-group-definitions.md
Labels: Extra Small

#19810 Update CONTRIBUTING.md to include Code of Conduct enforcement
  .github/CONTRIBUTING.md
Labels: Extra Small

#19814 Fix completion of foreach variable
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: Extra Small

#19805 Harden Import-CliXml test and improve the logic.
  test/powershell/Modules/Microsoft.PowerShell.Utility/XMLCommand.Tests.ps1
Labels: CL-Test, Extra Small

#19782 Rename file from PingPathCommand.cs to TestPathCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/TestPathCommand.cs
Labels: No Changes, PowerShell-Docs not needed

#19812 Add additional platform check for Windows before launching native app.
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1
Labels: WG-Interactive-Console, WG-Engine, CL-General, Extra Small

#19558 Invoke-WebRequest and Invoke-RestMethod: Rename TimeoutSec to ConnectionTimeoutSeconds (with alias) and add OperationTimeoutSeconds
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/BasicHtmlWebResponseObject.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebResponseObject.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/InvokeWebRequestCommand.CoreClr.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/StreamHelper.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/WebRequestSession.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
  test/tools/WebListener/Controllers/DelayController.cs
Labels: WG-Cmdlets, CL-BreakingChange, CL-General, Large, PowerShell-Docs needed

#18763 Fix TabExpansion2 variable leak when completing variables
  src/System.Management.Automation/engine/CommandCompletion/CommandCompletion.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: WG-Interactive-PSReadLine, WG-Interactive-Console, WG-Interactive-IntelliSense, Review - Needed, Needs-Triage, Extra Small

#18474 Do not require activity when creating a completed progress record
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WriteProgressCmdlet.cs
  src/System.Management.Automation/engine/ProgressRecord.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Write-Progress.Tests.ps1
Labels: WG-Cmdlets, Documentation Needed in this repo, Extra Small, PowerShell-Docs needed

#18706 Set default native arg passing to Legacy on Windows.
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  test/powershell/Language/Scripting/NativeExecution/NativeCommandArguments.Tests.ps1
Labels: Committee-Reviewed, CL-Engine, Extra Small, Backport-7.3.x-Consider, PowerShell-Docs needed

#19765 Make `Update-Help` throw proper error when current culture is not associated with a language
  src/System.Management.Automation/help/UpdateHelpCommand.cs
  src/System.Management.Automation/resources/HelpDisplayStrings.resx
  test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1
Labels: CL-General, Extra Small, PowerShell-Docs needed

#19715 Get-Content -Head and -Tail disallow negative values and cleanup
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetContentCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-Content.Tests.ps1
Labels: WG-Cmdlets, CL-General, Small, PowerShell-Docs needed

#19842 Fix native executables not redirecting to file (fixed)
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  test/powershell/engine/Basic/NativeCommandBytePiping.Tests.ps1
Labels: CL-Engine, Extra Small

#19851 Update message to use the actual parameter name
  src/System.Management.Automation/resources/SessionStateStrings.resx
Labels: CL-Docs, Extra Small

#19846 Fix typo in NativeCommandProcessor.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
Labels: CL-CodeCleanup, No Changes

#19863 Update metadata.json and README.md for upcoming releases
  README.md
  tools/metadata.json
Labels: Small

#19872 Update README.md and metadata.json for 7.4.0-preview.4 release
  README.md
  tools/metadata.json
Labels: CL-Docs, Extra Small

#19874 Update change log for v7.4.0-preview.4
  .spelling
  CHANGELOG/preview.md
Labels: Medium
