Repository PowerShell/PowerShell, pull requests merged in 2023-03, with the labels that each got.

#19240 Fix VtSubstring helper method to correctly check chars copied
  src/System.Management.Automation/utils/StringUtil.cs
Labels: Extra Small

#19243 Use C# 11 UTF-8 string literals
  src/System.Management.Automation/engine/remoting/common/RemoteSessionHyperVSocket.cs
Labels: CL-CodeCleanup, CL-General, Extra Small

#19251 Remove comment and simplify condition in WebCmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
Labels: CL-CodeCleanup, Extra Small

#19190 Preserve WebSession.MaximumRedirection from changes
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: CL-General, Small

#19239 Fix `ConciseView` to handle custom `ParserError` ErrorRecords
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  test/powershell/engine/Formatting/ErrorView.Tests.ps1
Labels: CL-Engine, Extra Small

#19252 Improve Verbose message if content length is unknown in WebCmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/WebCmdletStrings.resx
Labels: Extra Small

#19258 Use ArgumentNullException.ThrowIfNull part 2
  src/Microsoft.Management.UI.Internal/ManagementList/Common/ListOrganizer.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/PropertyValueSelectorFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterProviders/FilterRulePanel.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterProviders/FilterRuleToDisplayNameConverter.cs
  src/Microsoft.Management.UI.Internal/ManagementList/ManagementList/PropertyValueGetter.cs
  src/Microsoft.Management.UI.Internal/ManagementList/ManagementList/managementlist.cs
  src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/PropVariant.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/EventProviderTraceListener.cs
  src/System.Management.Automation/engine/hostifaces/HostUtilities.cs
  src/System.Management.Automation/engine/remoting/client/ThrottlingJob.cs
  src/System.Management.Automation/engine/runtime/MutableTuple.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/namespaces/TransactedRegistryKey.cs
  test/perf/dotnet-tools/ResultsComparer/Program.cs
Labels: CL-CodeCleanup, Extra Small

#19152 Adjust PUT method behavior to POST one for default content type in WebCmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: CL-General, Extra Small

#19261 Update and remove outdated docs to fix the URL link checks
  docs/cmdlet-example/visual-studio-simple-example.md
  docs/testing-guidelines/CodeCoverageAnalysis.md
Labels: CL-BuildPackaging, Small

#19262 Add '-Force' to Move-Item to fix the workflow
  .github/workflows/exp-json.yml
Labels: CL-BuildPackaging, Extra Small

#19264 Increase the timeout when waiting for the event log
  test/powershell/engine/Basic/GroupPolicySettings.Tests.ps1
Labels: CL-Test, Extra Small

#19265 Remove the 'Code Coverage Status' badge from the build status table
  README.md
Labels: CL-Docs, Extra Small

#19268 Increase the timeout for creating the `WebListener` in testing
  test/tools/Modules/WebListener/WebListener.psm1
Labels: Extra Small

#19266 Fix codefactor if part 1
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Eventlog.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/WebServiceProxy.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddMember.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/DebugRunspaceCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/EnableDisableRunspaceDebugCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/NewEventCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Select-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Update-TypeData.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/XmlCommands.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/Microsoft.PowerShell.CoreCLR.Eventing/DotNetCode/Eventing/EventProvider.cs
  src/Microsoft.PowerShell.ScheduledJob/ScheduledJob.cs
  src/Microsoft.WSMan.Management/ConfigProvider.cs
  src/System.Management.Automation/CoreCLR/CorePsPlatform.cs
  src/System.Management.Automation/cimSupport/cmdletization/ScriptWriter.cs
  src/System.Management.Automation/engine/Attributes.cs
  src/System.Management.Automation/engine/ExternalScriptInfo.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/InternalCommands.cs
  src/System.Management.Automation/engine/NativeCommandParameterBinder.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/ParameterBinderBase.cs
  src/powershell/Program.cs
Labels: CL-CodeCleanup, Large

#18667 Update supported distros in Readme
  README.md
Labels: Review - Needed, Extra Small

#19267 Fix codefactor if part 2
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataManager.cs
  src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs
  src/System.Management.Automation/engine/Modules/ScriptAnalysis.cs
  src/System.Management.Automation/engine/parser/Position.cs
  src/System.Management.Automation/engine/parser/SemanticChecks.cs
  src/System.Management.Automation/engine/parser/TypeResolver.cs
  src/System.Management.Automation/engine/remoting/commands/ResumeJob.cs
  src/System.Management.Automation/engine/remoting/commands/StopJob.cs
  src/System.Management.Automation/engine/remoting/commands/SuspendJob.cs
  src/System.Management.Automation/engine/remoting/common/psstreamobject.cs
  src/System.Management.Automation/engine/remoting/server/ServerPowerShellDriver.cs
  src/System.Management.Automation/engine/runtime/CompiledScriptBlock.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  src/System.Management.Automation/help/UpdatableHelpCommandBase.cs
  src/System.Management.Automation/help/UpdatableHelpSystem.cs
  src/System.Management.Automation/namespaces/LocationGlobber.cs
  src/System.Management.Automation/namespaces/TransactedRegistryKey.cs
  src/System.Management.Automation/security/SecurityManager.cs
  src/System.Management.Automation/utils/ClrFacade.cs
  src/System.Management.Automation/utils/PsUtils.cs
  src/System.Management.Automation/utils/RuntimeException.cs
  src/System.Management.Automation/utils/assert.cs
  src/TypeCatalogGen/TypeCatalogGen.cs
  test/tools/NamedPipeConnection/src/code/NamedPipeConnection.cs
Labels: CL-CodeCleanup, Medium

#19269 Fix codefactor if part 3
  src/System.Management.Automation/engine/COM/ComTypeInfo.cs
  src/System.Management.Automation/engine/ComInterop/ComInvokeBinder.cs
  src/System.Management.Automation/engine/PSVersionInfo.cs
  src/System.Management.Automation/engine/PseudoParameters.cs
  src/System.Management.Automation/engine/SessionState.cs
  src/System.Management.Automation/engine/SessionStateScope.cs
  src/System.Management.Automation/engine/parser/ConstantValues.cs
  src/System.Management.Automation/engine/remoting/client/ClientMethodExecutor.cs
  src/System.Management.Automation/engine/remoting/commands/DebugJob.cs
  src/System.Management.Automation/engine/remoting/commands/EnterPSHostProcessCommand.cs
  src/System.Management.Automation/engine/remoting/commands/GetJob.cs
  src/System.Management.Automation/engine/remoting/commands/PushRunspaceCommand.cs
  src/System.Management.Automation/engine/remoting/commands/ReceivePSSession.cs
  src/System.Management.Automation/engine/remoting/commands/RemoveJob.cs
  src/System.Management.Automation/engine/remoting/common/RemoteSessionHyperVSocket.cs
  src/System.Management.Automation/engine/remoting/common/WireDataFormat/RemoteSessionCapability.cs
  src/System.Management.Automation/engine/remoting/common/psstreamobject.cs
  src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
  src/System.Management.Automation/engine/remoting/fanin/PSSessionConfigurationData.cs
  src/System.Management.Automation/engine/serialization.cs
Labels: CL-CodeCleanup, Medium

#19096 Fix Start-Process -Wait with -Credential
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
  src/System.Management.Automation/engine/Interop/Windows/AssignProcessToJobObject.cs
  src/System.Management.Automation/engine/Interop/Windows/CloseHandle.cs
Labels: Review - Needed, Medium

#10725 MSI installer: Add checkbox and MSI property DISABLE_TELEMETRY to optionally disable telemetry.
  assets/wix/Product.wxs
  test/packaging/windows/msi.tests.ps1
Labels: CL-BuildPackaging, Extra Small

#19027 Add Statement property to $MyInvocation
  src/System.Management.Automation/engine/InvocationInfo.cs
  test/powershell/Language/Scripting/MyInvocation.Tests.ps1
Labels: CL-General, Extra Small

#19281 Fix using xml -Body in webcmdlets without an encoding
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: CL-General, Extra Small

#19249 Support HTTP persistent connections in Web Cmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebProxy.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/WebRequestSession.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/WebCmdletStrings.resx
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: CL-General, Large

#19270 Fix codefactor if part 4
  src/Microsoft.PowerShell.ScheduledJob/ScheduledJobWTS.cs
  src/System.Management.Automation/DscSupport/CimDSCParser.cs
  src/System.Management.Automation/cimSupport/cmdletization/xml/cmdlets-over-objects.xmlSerializer.autogen.cs
  src/System.Management.Automation/engine/ComInterop/ComInvokeBinder.cs
  src/System.Management.Automation/engine/ExecutionContext.cs
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/ExperimentalFeature/GetExperimentalFeatureCommand.cs
  src/System.Management.Automation/engine/SessionStateScope.cs
  src/System.Management.Automation/engine/hostifaces/Connection.cs
  src/System.Management.Automation/engine/hostifaces/ConnectionBase.cs
  src/System.Management.Automation/engine/hostifaces/HostUtilities.cs
  src/System.Management.Automation/engine/hostifaces/InternalHost.cs
  src/System.Management.Automation/engine/hostifaces/LocalConnection.cs
  src/System.Management.Automation/engine/hostifaces/MshHostUserInterface.cs
  src/System.Management.Automation/engine/hostifaces/PSDataCollection.cs
  src/System.Management.Automation/engine/hostifaces/PowerShellProcessInstance.cs
  src/System.Management.Automation/engine/interpreter/CallInstruction.cs
Labels: CL-CodeCleanup, Medium

#19283 Fix `PlainText` output to correctly remove Reset VT sequence w/o number
  src/System.Management.Automation/FormatAndOutput/common/StringDecorated.cs
  test/powershell/engine/Formatting/OutputRendering.Tests.ps1
Labels: Extra Small

#18762 Telemetry improvements for tracking experimental feature optout
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/utils/Telemetry.cs
Labels: Review - Needed, Extra Small

#19294 Add a mariner install script
  .vsts-ci/install-ps.yml
  tools/install-powershell.sh
  tools/installpsh-debian.sh
  tools/installpsh-mariner.sh
Labels: CL-Tools, Large

#19196 Always regenerate files wxs fragment
  .gitignore
  assets/wix/files.wxs
  assets/wix/patch-template.wxs
  tools/packaging/boms/linux.json
  tools/packaging/boms/mac.json
  tools/packaging/boms/windows.json
  tools/packaging/packaging.psd1
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging, Extra Large

#19302 Use reference assemblies generated by dotnet
  tools/packaging/packaging.psm1
  tools/releaseBuild/azureDevOps/templates/nuget-pkg-sbom.yml
  tools/releaseBuild/azureDevOps/templates/nuget.yml
Labels: Backport-7.2.x-Consider, Backport-7.3.x-Consider

#19276 Move workflows that create PRs to private repo
  .github/workflows/daily.yml
  .github/workflows/exp-json.yml
Labels: CL-BuildPackaging, Large

#18937 Add stage for symbols job in Release build
  tools/releaseBuild/azureDevOps/releasePipeline.yml
  tools/releaseBuild/azureDevOps/templates/release-PublishSymbols.yml
Labels: Review - Needed, Small

#19304 Fix mariner sudo detection
  .vsts-ci/install-ps.yml
  .vsts-ci/linux.yml
  tools/installpsh-mariner.sh
Labels: CL-BuildPackaging, Extra Small

#18871 Remove code which delete GUID from Progress, Verbose, Debug and Warning messages
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/System.Management.Automation/engine/hostifaces/HostUtilities.cs
Labels: CL-CodeCleanup, Extra Small

#19298 -Encoding add ANSI option
  src/System.Management.Automation/utils/EncodingUtils.cs
  test/powershell/Language/Parser/RedirectionOperator.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-Content.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Hex.Tests.ps1
Labels: CL-General, Extra Small

#19068 Test fixes for stabilizing tests
  build.psm1
  experimental-feature-linux.json
  experimental-feature-windows.json
  test/powershell/Host/HostUtilities.Tests.ps1
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
  test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Core/RemoteGetModule.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Core/RemoteImportModule.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Security/CertificateProvider.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Security/CmsMessage.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Security/certificateCommon.psm1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Implicit.Remoting.Tests.ps1
  test/powershell/engine/ExperimentalFeature/Get-ExperimentalFeature.Tests.ps1
  test/powershell/engine/Remoting/RemoteSession.Disconnect.Tests.ps1
  test/powershell/engine/Remoting/RunspacePool.Tests.ps1
  test/tools/Modules/HelpersCommon/HelpersCommon.psd1
  test/tools/Modules/HelpersCommon/HelpersCommon.psm1
  test/tools/NamedPipeConnection/src/code/Microsoft.PowerShell.NamedPipeConnection.csproj
Labels: Large

#18972 Improve type inference for Get-Random
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: Review - Needed, Extra Small

#19299 Small cleanup WebCmdlets
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/BasicHtmlWebResponseObject.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebResponseHelper.CoreClr.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/StreamHelper.cs
Labels: CL-CodeCleanup, Small

#18968 Update and enable test
  test/powershell/Language/Parser/AutomaticVariables.Tests.ps1
Labels: Review - Needed, Extra Small

#18682 Fix completion for PSCustomObject variable properties
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Extra Small

#19321 Restructure the package build to simplify signing and packaging stages
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/compliance/compliance.yml
  tools/releaseBuild/azureDevOps/templates/json.yml
  tools/releaseBuild/azureDevOps/templates/linux-packaging.yml
  tools/releaseBuild/azureDevOps/templates/mac-file-signing.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-build.yml
  tools/releaseBuild/azureDevOps/templates/nuget.yml
  tools/releaseBuild/azureDevOps/templates/sign-build-file.yml
  tools/releaseBuild/azureDevOps/templates/windows-hosted-build.yml
  tools/releaseBuild/azureDevOps/templates/windows-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
Labels: CL-BuildPackaging, Backport-7.2.x-Consider, Extra Large, Backport-7.3.x-Consider

#19319 Fix typo in typeDataXmlLoader.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader.cs
Labels: CL-CodeCleanup, No Changes

#19193 Infer external application output as strings
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: Extra Small

#19325 Fixing MSI checkbox
  assets/wix/Product.wxs
Labels: Extra Small

#19326 Update `README.md` and `metadata.json` for `v7.4.0-preview.2`
  README.md
  tools/metadata.json
Labels: Extra Small

#19171 Speed up Resolve-Path relative path resolution
  src/Microsoft.PowerShell.Commands.Management/commands/management/ResolvePathCommand.cs
Labels: CL-Performance, Extra Small

#19333 Merged PR 24784: Change log for v7.4.0-preview.2
  .spelling
  CHANGELOG/preview.md
Labels: CL-Docs, Large

#19338 Fix issues in release build and release pipeline
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/releasePipeline.yml
Labels: Backport-7.2.x-Consider, Extra Small, Backport-7.3.x-Consider

#19291 Add nullable annotations in WebRequestSession.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/WebRequestSession.cs
Labels: CL-CodeCleanup, Extra Small

#19361 Initialize Regex lazy in BasicHtmlWebResponseObject
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/BasicHtmlWebResponseObject.Common.cs
Labels: CL-CodeCleanup, Extra Small

#19353 Fix stage dependencies and typo in release build
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-signing.yml
Labels: Backport-7.2.x-Consider, Extra Small, Backport-7.3.x-Consider

#19007 Allow using a folder path in WebCmdlet's OutFile parameter
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/InvokeWebRequestCommand.CoreClr.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebResponseHelper.CoreClr.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/WebCmdletStrings.resx
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: CL-General, Extra Small

#19383 Remove FormObject.cs and FormObjectCollection.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/FormObject.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/FormObjectCollection.cs
Labels: CL-CodeCleanup, Extra Small

#19382 Exclude redundant parameter aliases from completion results
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/BugFix.Tests.ps1
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Extra Small

#19387 Revert "Remove FormObject.cs and FormObjectCollection.cs"
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/FormObject.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/FormObjectCollection.cs
Labels: CL-NotInBuild, Extra Small

#19358 Add RelativeBasePath parameter to Resolve-Path
  src/Microsoft.PowerShell.Commands.Management/commands/management/ResolvePathCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Resolve-Path.Tests.ps1
Labels: CL-General, Small

#19400 Fix type inference crash
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: Extra Small

#19380 Remove WebResponseObjectFactory.CoreClr.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/InvokeWebRequestCommand.CoreClr.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebResponseObjectFactory.CoreClr.cs
Labels: CL-CodeCleanup, Extra Small

#19374 Add `-Environment` parameter to `Start-Process`
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
Labels: Extra Small

#19412 Improve package management acceptance tests by not going to the gallery
  test/powershell/Modules/PackageManagement/PackageManagement.Tests.ps1
  test/powershell/Modules/PackageManagement/assets/PowerShell.TestPackage.3.2.1.nupkg
Labels: Small

#19413 Skip VT100 tests on Windows Server 2012R2 as console does not support it
  test/powershell/Language/Scripting/SuppressAnsiEscapeSequence.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Error.Tests.ps1
  test/powershell/engine/Formatting/OutputRendering.Tests.ps1
Labels: CL-Test, Backport-7.2.x-Consider, Extra Small, Backport-7.3.x-Consider
