Repository PowerShell/PowerShell, pull requests merged in 2023-09, with the labels that each got.

#20141 Start using new packages.microsoft.com cli
  tools/releaseBuild/azureDevOps/releasePipeline.yml
  tools/releaseBuild/azureDevOps/templates/release-PublishPackageMsftCom.yml
  tools/releaseBuild/azureDevOps/templates/release-ReleaseToNuGet.yml
Labels: MustHave, Backport-7.2.x-Consider, Small, Backport-7.3.x-Consider, BackPort-7.4.x-Consider

#20182 Continued improvement to tests for release automation
  test/powershell/Modules/Microsoft.PowerShell.Security/ConstrainedLanguageRestriction.Tests.ps1
  test/powershell/Modules/PowerShellGet/PowerShellGet.Tests.ps1
Labels: CL-Test, Extra Small

#20220 Enable vPack provenance data
  tools/releaseBuild/azureDevOps/templates/vpackReleaseJob.yml
Labels: Backport-7.2.x-Consider, Extra Small, Backport-7.3.x-Consider, BackPort-7.4.x-Consider

#20233 [release/v7.2.14]Add ProductCode in registry for MSI install
  assets/wix/Product.wxs
  test/packaging/windows/msi.tests.ps1
Labels: Extra Small

#20234 [release/v7.2.14]Publish rpm package for rhel9
  tools/packages.microsoft.com/mapping.json
Labels: Extra Small

#20237 [release/v7.2.14]Update variable used to bypass the blocking check for multiple NuGet feeds
  .vsts-ci/linux.yml
  .vsts-ci/mac.yml
  .vsts-ci/windows.yml
  .vsts-ci/windows/windows-packaging.yml
  tools/releaseBuild/azureDevOps/vpackRelease.yml
Labels: Extra Small

#20235 [release/v7.2.14]Update the link for getting started in `README.md`
  README.md
Labels: Extra Small

#20238 [release/v7.2.14]Make PR creation tool use web because it is more reliable
  tools/releaseTools.psm1
Labels: Extra Small

#20239 [release/v7.2.14]Remove spelling CI in favor of GitHub Action
  .github/CONTRIBUTING.md
  .github/workflows/markdownLink.yml
  .vsts-ci/misc-analysis.yml
  .vsts-ci/misc-analysis/mdSpell.yml
Labels: Medium

#20240 [release/v7.2.14]Update man page to match current help for pwsh
  assets/pwsh.1.ronn
Labels: Medium

#20241 [release/v7.2.14]Start using new packages.microsoft.com cli
  tools/releaseBuild/azureDevOps/releasePipeline.yml
  tools/releaseBuild/azureDevOps/templates/release-PublishPackageMsftCom.yml
  tools/releaseBuild/azureDevOps/templates/release-ReleaseToNuGet.yml
Labels: Small

#20242 [release/v7.2.14]Enable vPack provenance data
  tools/releaseBuild/azureDevOps/templates/vpackReleaseJob.yml
Labels: Extra Small

#20244 [release/v7.3.7]add runtime and packaging type info for mariner2 arm64
  build.psm1
  tools/ci.psm1
  tools/packaging/packaging.psm1
Labels: Extra Small

#20245 [release/v7.3.7]Publish rpm package for rhel9
  tools/packages.microsoft.com/mapping.json
Labels: Extra Small

#20246 [release/v7.3.7]Update variable used to bypass the blocking check for multiple NuGet feeds
  .vsts-ci/linux.yml
  .vsts-ci/mac.yml
  .vsts-ci/windows.yml
  .vsts-ci/windows/windows-packaging.yml
  tools/releaseBuild/azureDevOps/vpackRelease.yml
Labels: Extra Small

#20247 [release/v7.3.7]Make PR creation tool use web because it is more reliable
  tools/releaseTools.psm1
Labels: Extra Small

#20250 [release/v7.3.7]Add mariner arm64 package build to release build
  tools/packaging/packaging.psm1
  tools/releaseBuild/azureDevOps/releaseBuild.yml
  tools/releaseBuild/azureDevOps/templates/linux-authenticode-sign.yml
  tools/releaseBuild/azureDevOps/templates/linux-packaging.yml
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/release-ValidatePackageNames.yml
Labels: Medium

#20249 [release/v7.3.7]Update man page to match current help for pwsh
  assets/pwsh.1.ronn
Labels: Medium

#20251 [release/v7.3.7]Add mariner arm64 to PMC release
  tools/packages.microsoft.com/mapping.json
Labels: Extra Small

#20252 [release/v7.3.7]Start using new packages.microsoft.com cli
  tools/releaseBuild/azureDevOps/releasePipeline.yml
  tools/releaseBuild/azureDevOps/templates/release-PublishPackageMsftCom.yml
  tools/releaseBuild/azureDevOps/templates/release-ReleaseToNuGet.yml
Labels: Small

#20253 [release/v7.3.7]Enable vPack provenance data
  tools/releaseBuild/azureDevOps/templates/vpackReleaseJob.yml
Labels: Extra Small

#20248 [release/v7.3.7]Remove spelling CI in favor of GitHub Action
  .github/CONTRIBUTING.md
  .github/workflows/markdownLink.yml
  .vsts-ci/misc-analysis.yml
  .vsts-ci/misc-analysis/markdown.yml
  .vsts-ci/misc-analysis/mdSpell.yml
  CHANGELOG/7.3.md
  README.md
  docs/learning-powershell/README.md
  docs/learning-powershell/create-powershell-scripts.md
  docs/learning-powershell/debugging-from-commandline.md
  docs/learning-powershell/powershell-beginners-guide.md
  docs/learning-powershell/working-with-powershell-objects.md
Labels: CL-BuildPackaging, Extra Large

#20254 [release/v7.4.0-preview.6]Harden some problematic release tests.
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-ChildItem.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Security/ConstrainedLanguageModules.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Security/ConstrainedLanguageRestriction.Tests.ps1
  test/powershell/Modules/PackageManagement/PackageManagement.Tests.ps1
  test/powershell/engine/Module/ModulePath.Tests.ps1
Labels: CL-Test, Medium

#20255 [release/v7.4.0-preview.6]Skip the test on x86 as InstallDate is not visible on Wow64
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-ComputerInfo.Tests.ps1
Labels: CL-Test, Extra Small

#20256 [release/v7.4.0-preview.6]fix: typo donet -> dotnet
  build.psm1
  tools/releaseBuild/azureDevOps/templates/compliance/apiscan.yml
  tools/releaseBuild/azureDevOps/templates/linux-packaging.yml
  tools/releaseBuild/azureDevOps/templates/linux.yml
  tools/releaseBuild/azureDevOps/templates/mac-package-build.yml
  tools/releaseBuild/azureDevOps/templates/mac.yml
  tools/releaseBuild/azureDevOps/templates/nuget.yml
  tools/releaseBuild/azureDevOps/templates/release-GlobalToolTest.yml
  tools/releaseBuild/azureDevOps/templates/release-SDKTests.yml
  tools/releaseBuild/azureDevOps/templates/release-ValidateFxdPackage.yml
  tools/releaseBuild/azureDevOps/templates/testartifacts.yml
  tools/releaseBuild/azureDevOps/templates/windows-hosted-build.yml
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
Labels: CL-BuildPackaging, Small

#20257 [release/v7.4.0-preview.6]Add mariner arm64 to PMC release
  tools/packages.microsoft.com/mapping.json
Labels: CL-BuildPackaging, Extra Small

#20258 [release/v7.4.0-preview.6]Start using new packages.microsoft.com cli
  tools/releaseBuild/azureDevOps/releasePipeline.yml
  tools/releaseBuild/azureDevOps/templates/release-PublishPackageMsftCom.yml
  tools/releaseBuild/azureDevOps/templates/release-ReleaseToNuGet.yml
Labels: CL-BuildPackaging, Small

#20259 [release/v7.4.0-preview.6]Continued improvement to tests for release automation
  test/powershell/Modules/Microsoft.PowerShell.Security/ConstrainedLanguageRestriction.Tests.ps1
  test/powershell/Modules/PowerShellGet/PowerShellGet.Tests.ps1
Labels: CL-Test, Extra Small

#20260 [release/v7.4.0-preview.6]Enable vPack provenance data
  tools/releaseBuild/azureDevOps/templates/vpackReleaseJob.yml
Labels: CL-BuildPackaging, Extra Small

#20261 [release/v7.4.0-preview.6]Bump Microsoft.Management.Infrastructure from 3.0.0-preview.1 to 3.0.0-preview.2
  src/System.Management.Automation/System.Management.Automation.csproj
Labels: CL-BuildPackaging, Extra Small

#20262 [release/v7.4.0-preview.6]Bump Microsoft.Management.Infrastructure from 3.0.0-preview.1 to 3.0.0-preview.2 in /tools/packaging/projects/reference/System.Management.Automation
  tools/packaging/projects/reference/System.Management.Automation/System.Management.Automation.csproj
Labels: CL-BuildPackaging, Extra Small

#20144 Include Module Version in error messages when module is not found
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/engine/Modules/ModuleSpecification.cs
  src/System.Management.Automation/resources/Modules.resx
  test/powershell/Language/Scripting/Requires.Tests.ps1
Labels: CL-General, Small, CommunityDay-Small

#20268 Fixing PS 7.4 regression that is breaking DSCv3
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/resources/ParserStrings.resx
Labels: Waiting on Author, Extra Small

#20282 Prevent Export-CSV from flushing with every input
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
Labels: CL-General, Extra Small

#20276 Fix `Get-Service` non-terminating error message to include category
  src/Microsoft.PowerShell.Commands.Management/commands/management/Service.cs
Labels: CL-General, Extra Small

#20277 Update `README.md` and `metadata.json` for 7.2.14 and 7.3.7 releases
  README.md
  tools/metadata.json
Labels: CL-Docs, Small

#20213 Add mapping for mariner arm64 stable
  tools/packages.microsoft.com/mapping.json
Labels: Review - Needed, Extra Small, Backport-7.3.x-Consider

#20307 release build: Change the names of the PATs.
  tools/releaseBuild/azureDevOps/releasePipeline.yml
Labels: Backport-7.2.x-Consider, Backport-7.3.x-Consider, BackPort-7.4.x-Consider

#20312 [release/v7.2.15]call set-azdoprojectinfo and set-azdoauthtoken in the right order
  tools/releaseBuild/azureDevOps/releasePipeline.yml
Labels: Extra Small

#20311 [release/v7.3.8]call set-azdoprojectinfo and set-azdoauthtoken in the right order
  tools/releaseBuild/azureDevOps/releasePipeline.yml
Labels: Extra Small

#20308 [release/v7.3.8]Switch to GitHub Action for linting markdown
  .github/workflows/markdownLink.yml
  test/common/markdown-link/markdown-link.tests.ps1
  test/common/markdown-lint/.gitignore
  test/common/markdown-lint/gulpfile.js
  test/common/markdown-lint/markdown.tests.ps1
  test/common/markdown-lint/package.json
  test/common/markdown-lint/yarn.lock
Labels: Large

#20310 [release/v7.3.8]Add mapping for mariner arm64 stable
  tools/packages.microsoft.com/mapping.json
Labels: Extra Small

#20315 [release/v7.2.15] Release build: Change the names of the PATs.
  tools/releaseBuild/azureDevOps/releasePipeline.yml
Labels: CL-BuildPackaging

#20269 Update .NET SDK to version 8.0.100-rc.1.23455.8
  DotnetRuntimeMetadata.json
  build.psm1
  global.json
  src/Microsoft.PowerShell.Commands.Diagnostics/Microsoft.PowerShell.Commands.Diagnostics.csproj
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/ResGen/ResGen.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  src/System.Management.Automation/engine/parser/ast.cs
  src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs
  src/System.Management.Automation/engine/remoting/commands/ReceivePSSession.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/TypeCatalogGen/TypeCatalogGen.csproj
  test/hosting/hosting.tests.csproj
  test/perf/dotnet-tools/BenchmarkDotNet.Extensions/BenchmarkDotNet.Extensions.csproj
  test/perf/dotnet-tools/ResultsComparer/ResultsComparer.csproj
  test/tools/NamedPipeConnection/src/code/Microsoft.PowerShell.NamedPipeConnection.csproj
  test/tools/TestExe/TestExe.csproj
  test/tools/TestService/TestService.csproj
  test/tools/UnixSocket/UnixSocket.csproj
  test/tools/WebListener/WebListener.csproj
  test/xUnit/xUnit.tests.csproj
Labels: Review - Needed, CL-BuildPackaging, Medium

#20326 Use fxdependent-win-desktop runtime for compliance runs
  tools/releaseBuild/azureDevOps/templates/compliance/apiscan.yml
Labels: Backport-7.2.x-Consider, Extra Small, Backport-7.3.x-Consider, BackPort-7.4.x-Consider

#20300 Revert change to use `BinaryFormatter` for `Out-GridView`
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/ComparableValueFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/DoesNotEqualFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/EqualsFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/FilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/FilterRuleExtensions.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/IsBetweenFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/IsEmptyFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/IsGreaterThanFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/IsLessThanFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/IsNotEmptyFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/IsNotEmptyValidationRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/PropertiesTextContainsFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/PropertyValueSelectorFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/SelectorFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/SingleValueComparableValueFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextContainsFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextDoesNotContainFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextDoesNotEqualFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextEndsWithFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextEqualsFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextStartsWithFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/ValidatingSelectorValue.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/ValidatingValue.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/ValidatingValueBase.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/ValidationRules/DataErrorInfoValidationRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterProviders/FilterRuleToDisplayNameConverter.cs
  src/Microsoft.Management.UI.Internal/ManagementList/ManagementList/ManagementListStateDescriptor.cs
  src/powershell-win-core/powershell-win-core.csproj
Labels: Medium, 7.4-Blocking, BackPort-7.4.x-Consider

#20274 Update Microsoft.PowerShell.PSResourceGet to 0.9.0-rc1
  src/Modules/PSGalleryModules.csproj
Labels: Review - Needed, Extra Small, BackPort-7.4.x-Consider

#20285 Set experimental features to stable for 7.4 release
  src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator_Table.cs
  src/System.Management.Automation/engine/BytePipe.cs
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/pipeline.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  test/powershell/engine/Basic/NativeCommandBytePiping.Tests.ps1
  test/powershell/engine/Basic/NativeCommandErrorHandling.Tests.ps1
Labels: Medium, BackPort-7.4.x-Consider

#20333 Fix cordinated build
  build.psm1
  global.json
  src/Microsoft.PowerShell.Commands.Diagnostics/Microsoft.PowerShell.Commands.Diagnostics.csproj
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  src/powershell-win-core/powershell-win-core.csproj
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
  tools/findMissingNotices.ps1
  tools/packaging/packaging.psm1
  tools/releaseBuild/Images/GenericLinuxFiles/PowerShellPackage.ps1
Labels: Small, BackPort-7.4.x-Consider

#20349 [release/v7.4.0-preview.6] release build: Change the names of the PATs.
  tools/releaseBuild/azureDevOps/releasePipeline.yml
Labels: CL-BuildPackaging

#20346 [release/v7.4.0-preview.6] Remove the comment trigger from feedback provider
  src/System.Management.Automation/engine/Subsystem/FeedbackSubsystem/FeedbackHub.cs
  src/System.Management.Automation/engine/Subsystem/FeedbackSubsystem/IFeedbackProvider.cs
Labels: CL-General, Extra Small

#20350 [release/v7.4.0-preview.6] Bump Microsoft.CodeAnalysis.CSharp from 4.7.0-2.final to 4.7.0
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/System.Management.Automation/SourceGenerators/PSVersionInfoGenerator/PSVersionInfoGenerator.csproj
Labels: CL-BuildPackaging

#20352 [release/v7.4.0-preview.6] Bump actions/checkout from 3 to 4
  .github/workflows/codeql-analysis.yml
  .github/workflows/markdownLink.yml
  .github/workflows/markdownLinkDaily.yml
  .github/workflows/rebase.yml
Labels: CL-BuildPackaging, Extra Small

#20353 [release/v7.4.0-preview.6] Bump JsonSchema.Net from 5.1.3 to 5.2.1
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
Labels: CL-BuildPackaging, Extra Small

#20354 [release/v7.4.0-preview.6] Bump Markdig.Signed from 0.32.0 to 0.33.0
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
Labels: CL-BuildPackaging, Extra Small

#20355 [release/v7.4.0-preview.6] Bump Microsoft.NET.Test.Sdk from 17.7.1 to 17.7.2
  test/xUnit/xUnit.tests.csproj
Labels: CL-BuildPackaging, Extra Small

#20357 [release/v7.4.0-preview.6] Bump xunit.runner.visualstudio from 2.5.0 to 2.5.1
  test/xUnit/xUnit.tests.csproj
Labels: CL-BuildPackaging, Extra Small

#20080 Fix: Update AppxManifest.xml to show application name on DefaultTile for Windows 10 21H2/22H2 Start Menu
  assets/AppxManifest.xml
Labels: Review - Needed, CL-BuildPackaging, Extra Small, PowerShell-Docs not needed

#20359 [release/v7.4.0-preview.6] Use fxdependent-win-desktop runtime for compliance runs
  tools/releaseBuild/azureDevOps/templates/compliance/apiscan.yml
Labels: CL-BuildPackaging, Extra Small

#20358 [release/v7.4.0-preview.6] Update .NET SDK to version 8.0.100-rc.1.23455.8
  DotnetRuntimeMetadata.json
  build.psm1
  global.json
  src/Microsoft.PowerShell.Commands.Diagnostics/Microsoft.PowerShell.Commands.Diagnostics.csproj
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/ResGen/ResGen.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  src/System.Management.Automation/engine/parser/ast.cs
  src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs
  src/System.Management.Automation/engine/remoting/commands/ReceivePSSession.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/TypeCatalogGen/TypeCatalogGen.csproj
  test/hosting/hosting.tests.csproj
  test/perf/dotnet-tools/BenchmarkDotNet.Extensions/BenchmarkDotNet.Extensions.csproj
  test/perf/dotnet-tools/ResultsComparer/ResultsComparer.csproj
  test/tools/NamedPipeConnection/src/code/Microsoft.PowerShell.NamedPipeConnection.csproj
  test/tools/TestExe/TestExe.csproj
  test/tools/TestService/TestService.csproj
  test/tools/UnixSocket/UnixSocket.csproj
  test/tools/WebListener/WebListener.csproj
  test/xUnit/xUnit.tests.csproj
Labels: CL-BuildPackaging, Medium

#20360 [release/v7.4.0-preview.6] Revert change to use `BinaryFormatter` for `Out-GridView`
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/ComparableValueFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/DoesNotEqualFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/EqualsFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/FilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/FilterRuleExtensions.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/IsBetweenFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/IsEmptyFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/IsGreaterThanFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/IsLessThanFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/IsNotEmptyFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/IsNotEmptyValidationRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/PropertiesTextContainsFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/PropertyValueSelectorFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/SelectorFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/SingleValueComparableValueFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextContainsFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextDoesNotContainFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextDoesNotEqualFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextEndsWithFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextEqualsFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextStartsWithFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/ValidatingSelectorValue.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/ValidatingValue.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/ValidatingValueBase.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/ValidationRules/DataErrorInfoValidationRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterProviders/FilterRuleToDisplayNameConverter.cs
  src/Microsoft.Management.UI.Internal/ManagementList/ManagementList/ManagementListStateDescriptor.cs
  src/powershell-win-core/powershell-win-core.csproj
Labels: CL-General, Medium

#20361 [release/v7.4.0-preview.6] Update Microsoft.PowerShell.PSResourceGet to 0.9.0-rc1
  src/Modules/PSGalleryModules.csproj
Labels: CL-BuildPackaging, Extra Small

#20362 [release/v7.4.0-preview.6] Set experimental features to stable for 7.4 release
  src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator_Table.cs
  src/System.Management.Automation/engine/BytePipe.cs
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/pipeline.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  test/powershell/engine/Basic/NativeCommandBytePiping.Tests.ps1
  test/powershell/engine/Basic/NativeCommandErrorHandling.Tests.ps1
Labels: CL-General, Medium

#20364 [release/v7.4.0-preview.6] Bump XunitXml.TestLogger from 3.1.11 to 3.1.17
  test/xUnit/xUnit.tests.csproj
Labels: CL-BuildPackaging, Extra Small

#20363 [release/v7.4.0-preview.6] Update experimental-feature json files
  experimental-feature-linux.json
  experimental-feature-windows.json
Labels: CL-BuildPackaging, Extra Small

#20365 [release/v7.4.0-preview.6] Fix cordinated build
  build.psm1
  global.json
  src/Microsoft.PowerShell.Commands.Diagnostics/Microsoft.PowerShell.Commands.Diagnostics.csproj
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  src/powershell-win-core/powershell-win-core.csproj
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
  tools/findMissingNotices.ps1
  tools/packaging/packaging.psm1
  tools/releaseBuild/Images/GenericLinuxFiles/PowerShellPackage.ps1
Labels: CL-BuildPackaging, Small

#20368 [release/v7.4.0-preview.6] Bump Microsoft.CodeAnalysis.CSharp from 4.7.0 to 4.8.0-2.final
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/System.Management.Automation/SourceGenerators/PSVersionInfoGenerator/PSVersionInfoGenerator.csproj
Labels: Extra Small

#20370 Updates RIDs used to generate component Inventory
  tools/cgmanifest.json
  tools/findMissingNotices.ps1
Labels: Extra Small

#20372 [release/v7.4.0-preview.6] Updates RIDs used to generate component Inventory
  tools/cgmanifest.json
  tools/findMissingNotices.ps1
Labels: CL-BuildPackaging

#20329 Fix typo in FileCatalog.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Security/FileCatalog.Tests.ps1
Labels: CL-Test, Extra Small, PowerShell-Docs not needed

#20373 Remove `ref` folder before running compliance
  tools/releaseBuild/azureDevOps/templates/compliance/apiscan.yml
Labels: CL-BuildPackaging, Extra Small, BackPort-7.4.x-Consider

#20375 [release/v7.4.0-preview.6] Remove `ref` folder before running compliance
  tools/releaseBuild/azureDevOps/templates/compliance/apiscan.yml
Labels: CL-BuildPackaging

#20367 Fix implicit remoting proxy cmdlets to act on common parameters
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  test/powershell/Modules/Microsoft.PowerShell.Core/CompatiblePSEditions.Module.Tests.ps1
Labels: Extra Small, BackPort-7.4.x-Consider

#20386 Update `README.md` and `metadata.json` for v7.4.0-preview.6 release
  README.md
  tools/metadata.json
Labels: CL-Docs, Extra Small

#20389 Bring updates in the 7.4-preview.6 release branch to the master branch
  CHANGELOG/preview.md
  tools/releaseBuild/azureDevOps/templates/release-ValidatePackageNames.yml
Labels: CL-BuildPackaging, Extra Small

#20396 Revert "Fix: Update AppxManifest.xml to show application name on DefaultTile for Windows 10 21H2/22H2 Start Menu"
  assets/AppxManifest.xml
Labels: CL-BuildPackaging, Extra Small
