Repository PowerShell/PowerShell, pull requests merged in 2024-06, with the labels that each got.

#23871 Get-Help may report parameters with `ValueFromRemainingArguments` attribute as pipeline-able
  src/System.Management.Automation/help/DefaultCommandHelpObjectBuilder.cs
  test/powershell/engine/Help/HelpSystem.Tests.ps1
Labels: CL-General, PowerShell-Docs not needed

#23904 Fix error in the vPack release, debug script that blocked release
  .pipelines/PowerShell-vPack-Official.yml
Labels: CL-BuildPackaging, Backport-7.2.x-Consider, BackPort-7.4.x-Consider

#20381 Redirecting to a variable should be possible
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Var.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/VariableCommandStrings.resx
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs
  test/powershell/Language/Parser/RedirectionOperator.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Security/ConstrainedLanguageRestriction.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Set-Variable.Tests.ps1
Labels: Issue-Enhancement, WG-Engine, Review - Needed, Medium, PowerShell-Docs needed, WG-Reviewed, KeepOpen

#23910 [release/v7.4.3] Generate msi for win-arm64 installer
  assets/wix/Product.wxs
  assets/wix/bundle.wxs
  tools/ci.psm1
  tools/packaging/packaging.psm1
  tools/releaseBuild/Images/microsoft_powershell_windowsservercore/PowerShellPackage.ps1
  tools/releaseBuild/azureDevOps/templates/windows-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
Labels: CL-BuildPackaging

#23912 [release/v7.4.3] Fix argument passing in GlobalToolShim, fix #11747
  src/Microsoft.PowerShell.GlobalTool.Shim/GlobalToolShim.cs
Labels: CL-General

#23938 [release/v7.2.21] When generating `OutputType` don't cast to `Type[]`
  src/System.Management.Automation/engine/parser/Compiler.cs
Labels: CL-Engine

#23939 [release/v7.2.21] Fix exe signing with third party signing for WiX engine
  .pipelines/templates/linux.yml
  .pipelines/templates/mac.yml
  .pipelines/templates/obp-file-signing.yml
  .pipelines/templates/windows-hosted-build.yml
  .pipelines/templates/windows-package-build.yml
Labels: CL-BuildPackaging

#23940 [release/v7.2.21] Fix error in the vPack release, debug script that blocked release
  .pipelines/PowerShell-vPack-Official.yml
Labels: CL-BuildPackaging

#23941 Create `powershell.config.json` for `PowerShell.Windows.x64` global tool
  .pipelines/templates/windows-hosted-build.yml
Labels: CL-BuildPackaging, Backport-7.2.x-Approved, BackPort-7.4.x-Approved

#23973 Update `metadata.json` for PowerShell June releases
  tools/metadata.json
Labels: CL-BuildPackaging

#23817 Add `IgnoreComments` and `AllowTrailingCommas` options to `Test-Json` cmdlet
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/TestJsonCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Test-Json.Tests.ps1
Labels: WG-Cmdlets, Review - Needed, CL-General, PowerShell-Docs needed, WG-Reviewed
