Repository PowerShell/PowerShell, pull requests merged in 2024-08, with the labels that each got.

#24032 Fix Hyper-V Remoting when using remoting import
  src/System.Management.Automation/engine/remoting/commands/PSRemotingCmdlet.cs
  src/System.Management.Automation/engine/remoting/commands/PushRunspaceCommand.cs
  src/System.Management.Automation/engine/remoting/commands/newrunspacecommand.cs
  src/System.Management.Automation/resources/RemotingErrorIdStrings.resx
Labels: Review - Needed

#24104 chore: Refactor Nuget package source creation to use New-NugetPackageSource function
  .pipelines/templates/insert-nuget-config-azfeed.yml
  build.psm1
Labels: CL-BuildPackaging, Backport-7.2.x-Consider, BackPort-7.4.x-Consider

#24105 Minor cleanup on local variable names within a method
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebResponseHelper.CoreClr.cs
Labels: CL-CodeCleanup

#24109 Update docs sample nuget.config
  docs/host-powershell/sample/NuGet.config.md
Labels: Compliance, CL-Docs, Backport-7.2.x-Consider, BackPort-7.4.x-Consider

#24075 Change type of LineNumber to ulong in Select-String
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs
Labels: WG-Cmdlets-Utility, CL-General, WG-Reviewed

#24128 Add ability to capture MSBuild Binary logs when restore fails
  .pipelines/PowerShell-Coordinated_Packages-Official.yml
  build.psm1
Labels: CL-BuildPackaging

#24134 Fix Global tool config generation
  .pipelines/templates/windows-hosted-build.yml
Labels: CL-BuildPackaging, Backport-7.2.x-Consider, BackPort-7.4.x-Consider

#20670 Add support for back porting PRs from GitHub or the Private Azure Repos
  test/releaseTools/releaseTools.tests.ps1
  tools/releaseTools.psm1
Labels: Review - Needed, Large

#24152 [release/v7.4.5] Rewrite the mac syslog tests as they seem somewhat flaky
  test/powershell/Host/Logging.Tests.ps1
  test/tools/Modules/PSSysLog/PSSysLog.psm1
Labels: CL-Test

#24159 Update `cgmanifest.json` for v7.4.5
  tools/cgmanifest.json
Labels: CL-BuildPackaging

#24162 Bump PackageManagement to 1.4.8.1
  src/Modules/PSGalleryModules.csproj
Labels: CL-BuildPackaging

#24149 Fixes to Azure Public feed usage
  .pipelines/PowerShell-Coordinated_Packages-Official.yml
  .pipelines/PowerShell-Packages-Official.yml
  .pipelines/templates/checkAzureContainer.yml
  .pipelines/templates/insert-nuget-config-azfeed.yml
  .pipelines/templates/mac.yml
  .pipelines/templates/nupkg.yml
  .pipelines/templates/release-MakeBlobPublic.yml
  .pipelines/templates/release-validate-sdk.yml
  .pipelines/templates/testartifacts.yml
  .pipelines/templates/uploadToAzure.yml
  .vsts-ci/templates/ci-build.yml
  build.psm1
  nuget.config
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Modules/nuget.config
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
  tools/releaseBuild/azureDevOps/AzArtifactFeed/PSGalleryToAzArtifacts.yml
  tools/releaseBuild/azureDevOps/AzArtifactFeed/SyncGalleryToAzArtifacts.psm1
  tools/releaseBuild/azureDevOps/releasePipeline.yml
  tools/releaseBuild/azureDevOps/templates/compliance/apiscan.yml
  tools/releaseBuild/azureDevOps/templates/insert-nuget-config-azfeed.yml
  tools/releaseBuild/azureDevOps/templates/mac.yml
  tools/releaseBuild/azureDevOps/templates/nuget-pkg-sbom.yml
  tools/releaseBuild/azureDevOps/templates/release-PublishPackageMsftCom.yml
  tools/releaseBuild/azureDevOps/templates/release-SDKTests.yml
Labels: CL-BuildPackaging, Backport-7.2.x-Consider, BackPort-7.4.x-Consider

#24163 Update cgmanifest
  tools/cgmanifest.json
Labels: CL-BuildPackaging

#23855 Save man files in /usr/share/man instead of /usr/local/share/man
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging, CommunityDay-Small

#24175 Remove old code that downloads msix for win-arm64
  tools/install-powershell.ps1
Labels: CL-Tools

#24072 If SMA.dll location is not found, use host exe to determine `$PSHOME` location
  src/System.Management.Automation/engine/Utils.cs
Labels: WG-Engine, CL-General, WG-NeedsReview

#20981 Add `-Force` parameter to `Resolve-Path` and `Convert-Path` cmdlets to support wildcard hidden files
  src/Microsoft.PowerShell.Commands.Management/commands/management/ConvertPathCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ResolvePathCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Convert-Path.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Resolve-Path.Tests.ps1
Labels: WG-Cmdlets, CL-General, Medium, CommunityDay-Small, PowerShell-Docs needed, WG-Reviewed

#24013 Delay progress bar in Copy-Item and Remove-Item cmdlets
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-General

#23815 Replace PSVersion source generator with incremental one
  PowerShell.sln
  src/System.Management.Automation/SourceGenerators/PSVersionInfoGenerator/PSVersionInfoGenerator.cs
  src/System.Management.Automation/SourceGenerators/PSVersionInfoGenerator/PSVersionInfoGenerator.csproj
Labels: CL-BuildPackaging

#24158 Bring 7.2 changelogs back to master
  CHANGELOG/7.2.md
Labels: CL-Docs

#24183 Update changelog and `metadata.json` for v7.4.5 release
  CHANGELOG/7.4.md
  tools/metadata.json
Labels: CL-Docs

#21157 Fix `Get-FormatData` attempting to incorrectly cast a type
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/common/GetFormatDataCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/GetFormatDataStrings.resx
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Complex.cs
Labels: Review - Needed, CL-General, Medium

#24204 fixed CL lint error
  CHANGELOG/7.2.md
Labels: CL-Docs

#24182 Update changelog readme with 7.4
  CHANGELOG/README.md
Labels: CL-Docs

#20640 Add support to `Get-Error` to handle BoundParameters
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Get-Error.Tests.ps1
Labels: Review - Needed, Extra Small
