Repository PowerShell/PowerShell, pull requests merged in 2024-03, with the labels that each got.

#20211 Fix error formatting for pipeline enumeration exceptions
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
  test/powershell/engine/Formatting/ErrorView.Tests.ps1
Labels: CL-Engine, Small, PowerShell-Docs not needed

#21184 Fall back to type inference when hashtable key value cannot be retrieved from safe expression
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: Review - Needed, Extra Small

#21302 Get-Process: Remove admin for IncludeUserName
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Management/resources/ProcessResources.resx
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-Process.Tests.ps1
Labels: Extra Small

#21331 Fix PowerShell class to support deriving from an abstract class with abstract properties
  src/System.Management.Automation/engine/parser/PSType.cs
  test/powershell/Language/Classes/scripting.Classes.inheritance.tests.ps1
Labels: CL-Engine, Extra Small, BackPort-7.4.x-Consider

#21344 Fix a null reference exception when 'Runspace.DefaultRunspace' is null
  src/System.Management.Automation/security/wldpNativeMethods.cs
Labels: CL-General, Extra Small, BackPort-7.4.x-Consider

#20997 Fix empty file when redirecting both stdout and stderr
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  test/powershell/Language/Scripting/NativeExecution/NativeCommandProcessor.Tests.ps1
  test/tools/TestExe/TestExe.cs
Labels: CL-General, Extra Small, BackPort-7.4.x-Consider

#21350 Fix typo in ast.cs
  src/System.Management.Automation/engine/parser/ast.cs
Labels: CL-Docs, No Changes

#21361 Register the assembly/library resolvers at early stage
  src/System.Management.Automation/CoreCLR/CorePsAssemblyLoadContext.cs
  src/System.Management.Automation/engine/hostifaces/ConnectionBase.cs
  src/System.Management.Automation/utils/ClrFacade.cs
  test/powershell/engine/Basic/RegisterAssemblyResolverEarly.ps1
Labels: CL-Engine, Extra Small, BackPort-7.4.x-Consider

#21368 Revert the PR #17856 (Do not preserve temporary results when no need to do so)
  src/System.Management.Automation/engine/parser/Compiler.cs
  test/powershell/Language/Scripting/Scripting.Followup.Tests.ps1
Labels: CL-Engine, Extra Small, BackPort-7.4.x-Consider

#21352 add file description to `pwsh.exe`
  PowerShell.Common.props
Labels: Extra Small

#21333 Fix argument passing in GlobalToolShim, fix #11747
  src/Microsoft.PowerShell.GlobalTool.Shim/GlobalToolShim.cs
Labels: Review - Needed, Extra Small

#21337 Fix typo in a test
  test/powershell/engine/Remoting/CustomConnection.Tests.ps1
Labels: CL-Docs, Extra Small
