Repository PowerShell/PowerShell, pull requests merged in 2024-12, with the labels that each got.

#20943 Resolve symlink target relative to the symlink instead of the working directory (#15235)
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
Labels: Extra Small

#21009 Add error for Get-PSSession -ComputerName on Unix
  src/System.Management.Automation/engine/remoting/commands/getrunspacecommand.cs
  src/System.Management.Automation/engine/remoting/common/remotingexceptions.cs
  src/System.Management.Automation/resources/RemotingErrorIdStrings.resx
Labels: CL-General, Extra Small

#21373 Emit ProgressRecord in CLIXML minishell output
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
Labels: WG-Interactive-Console, Review - Needed, Extra Small, WG-Reviewed

#24632 Deploy Box Update
  .pipelines/PowerShell-Release-Official.yml
  .pipelines/templates/release-SetReleaseTagandContainerName.yml
  .pipelines/templates/release-SetTagAndTools.yml
  .pipelines/templates/release-githubtasks.yml
  .pipelines/templates/release-publish-nuget.yml
  .pipelines/templates/release-validate-packagenames.yml
  .pipelines/templates/uploadToAzure.yml
  .pipelines/templates/variable/release-shared.yml
Labels: CL-BuildPackaging

#24275 Update Cmdlets WG members
  docs/community/working-group-definitions.md
Labels: Review - Needed

#21164 Seal internal types in file `RemotingProtocol2.cs`
  src/System.Management.Automation/engine/remoting/client/RemotingProtocol2.cs
Labels: CL-CodeCleanup, Extra Small

#24705 Seal internal type `ClientRemoteSessionDSHandlerImpl`
  src/System.Management.Automation/engine/remoting/client/remotingprotocolimplementation.cs
Labels: CL-CodeCleanup

#21117 Add `-PropertyType` argument completer for `New-ItemProperty`
  src/Microsoft.PowerShell.Commands.Management/commands/management/NewPropertyCommand.cs
  src/System.Management.Automation/resources/TabCompletionStrings.resx
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Medium

#21115 Fix `Get-ItemProperty` to report non-terminating error for cast exception
  src/System.Management.Automation/namespaces/RegistryProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Registry.Tests.ps1
Labels: Review - Needed, CL-General, Extra Small, PowerShell-Docs not needed

#21218 Remove `SuppressFinalize` from `ClientRemoteSessionDSHandlerImpl`
  src/System.Management.Automation/engine/remoting/client/remotingprotocolimplementation.cs
Labels: CL-CodeCleanup, Extra Small

#20330 Add completion of modules by their shortname
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: WG-Interactive-IntelliSense, CL-General, Extra Small, PowerShell-Docs not needed, WG-Reviewed

#24714 Update `DnsNameList` for `X509Certificate2` to use `X509SubjectAlternativeNameExtension.EnumerateDnsNames` Method
  src/Microsoft.PowerShell.Security/security/CertificateProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Security/CertificateProvider.Tests.ps1
Labels: CL-General

#21137 Update Named and Statement block type inference to not consider AssignmentStatements and Increment/decrement operators as part of their output
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: Review - Needed, CL-General, Extra Small

#18955 Add ExcludeModule parameter to Get-Command
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/GetCommandCommand.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Core/Get-Command.Tests.ps1
Labels: WG-Cmdlets, Review - Needed, CL-General, Needs-Triage, Extra Small, PowerShell-Docs needed, WG-Reviewed
