Repository PowerShell/PowerShell, pull requests merged in 2024-07, with the labels that each got.

#23963 fix typo: `the the` -> `the`
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/WebRequestSession.cs
Labels: Review - Needed

#23945 Skip build steps that dont have exe packages
  .pipelines/templates/windows-package-build.yml
  tools/packaging/packaging.psm1
Labels: Review - Needed, CL-BuildPackaging

#23955 Peer review for code change to include Azure Linux installations[[install-powershell.sh doesn't work on azure-linux #23944]]
  tools/install-powershell.sh
Labels: Review - Needed

#23891 Enable `-NoRestart` to work with `Register-PSSessionConfiguration`
  src/System.Management.Automation/engine/remoting/commands/CustomShellCommands.cs
Labels: CL-General, PowerShell-Docs needed

#23952 WebCmdlets fix issue with -Body and no -ContentType
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: Review - Needed, CL-General, PowerShell-Docs not needed

#23869 Fix progress calculation on Remove-Item
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-General

#21387 Fix up .NET method invocation with Optional arg
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  test/powershell/engine/Basic/CLRBinding.Tests.ps1
Labels: Review - Needed, CL-General, CommunityDay-Small, WG-Reviewed

#24004 Fix `Move-Item` to error when moving into itself
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/resources/FileSystemProviderStrings.resx
  test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
Labels: CL-General

#21217 Remove explicit `IDE1005` suppressions
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/FilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/ValidatingSelectorValue.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/ValidatingValueBase.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterProviders/AddFilterRulePickerItem.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterProviders/FilterRulePanel.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterProviders/FilterRulePanelController.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterProviders/FilterRulePanelItem.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterProviders/SearchBox.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/ViewModel/CommandViewModel.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/ViewModel/ParameterSetViewModel.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/ViewModel/ParameterViewModel.cs
Labels: Review - Needed, Extra Small

#21096 Set-Acl: Do not fail on untranslatable SID
  src/System.Management.Automation/namespaces/FileSystemSecurity.cs
  test/powershell/Modules/Microsoft.PowerShell.Security/AclCmdlets.Tests.ps1
Labels: Review - Needed, Extra Small

#24041 Show file name in Invoke-WebRequest -OutFile -Verbose
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/InvokeWebRequestCommand.CoreClr.cs
Labels: CL-General

#24047 Add OutFile property in WebResponseObject
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebResponseObject.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/InvokeWebRequestCommand.CoreClr.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: Waiting on Author

#24065 RecommendedAction: Explicitly start and stop ANSI Error Color
  src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs
Labels: Issue-Bug, WG-Interactive-Console, CommunityDay-Small, WG-Reviewed

#24063 Enumerate over all signed zip packages
  .pipelines/templates/mac-package-build.yml
Labels: Review - Needed

#24034 Add script to update SDK for release branches
  build.psm1
Labels: Stale, Waiting on Author

#23951 Cleanup unused csproj
  tools/ci.psm1
  tools/packaging/packaging.psm1
  tools/packaging/projects/nuget/package.csproj
  tools/packaging/projects/nuget/powershell.nuspec
Labels: Review - Needed, CL-BuildPackaging, Backport-7.2.x-Consider, BackPort-7.4.x-Consider

#24098 Make Microsoft feeds the default
  .gitignore
  .pipelines/templates/insert-nuget-config-azfeed.yml
  .vsts-ci/windows/templates/windows-packaging.yml
  build.psm1
  docs/building/linux.md
  docs/building/macos.md
  docs/building/windows-core.md
  nuget.config
  src/Modules/nuget.config
  test/hosting/NuGet.Config
  test/perf/nuget.config
  test/tools/NamedPipeConnection/nuget.config
  tools/ci.psm1
Labels: CL-BuildPackaging, Backport-7.2.x-Consider, BackPort-7.4.x-Consider

#23857 devcontainers: mount workspace in /PowerShell
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/fedora30/Dockerfile
  .devcontainer/fedora30/devcontainer.json
Labels: Review - Needed
