Repository PowerShell/PowerShell, pull requests merged in 2024-09, with the labels that each got.

#24219 Add windows signing for pwsh.exe
  .pipelines/templates/obp-file-signing.yml
Labels: CL-BuildPackaging, Backport-7.2.x-Consider, BackPort-7.4.x-Consider

#24243 Use Managed Identity for APIScan authentication
  tools/releaseBuild/azureDevOps/templates/compliance/apiscan.yml
Labels: CL-BuildPackaging, Backport-7.2.x-Consider, BackPort-7.4.x-Consider

#24244 Put issues in specific path
  .config/tsaoptions.json
Labels: Backport-7.2.x-Consider, BackPort-7.4.x-Consider

#24236 Write type data found by `Get-TypeData` to the pipeline immediately instead of collecting it first
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Update-TypeData.cs
Labels: CL-General

#24148 Capture environment better
  .github/workflows/codeql-analysis.yml
  .pipelines/PowerShell-Coordinated_Packages-Official.yml
  .pipelines/PowerShell-vPack-Official.yml
  .pipelines/templates/SetVersionVariables.yml
  .pipelines/templates/linux-package-build.yml
  .pipelines/templates/mac-package-build.yml
  .pipelines/templates/nupkg.yml
  .pipelines/templates/obp-file-signing.yml
  .pipelines/templates/release-MakeBlobPublic.yml
  .pipelines/templates/release-githubtasks.yml
  .pipelines/templates/release-publish-nuget.yml
  .pipelines/templates/release-symbols.yml
  .pipelines/templates/release-upload-buildinfo.yml
  .pipelines/templates/release-validate-fxdpackages.yml
  .pipelines/templates/release-validate-globaltools.yml
  .pipelines/templates/release-validate-packagenames.yml
  .pipelines/templates/release-validate-sdk.yml
  .pipelines/templates/uploadToAzure.yml
  .pipelines/templates/windows-package-build.yml
  .vsts-ci/linux-daily.yml
  .vsts-ci/linux/templates/packaging.yml
  .vsts-ci/sshremoting-tests.yml
  .vsts-ci/templates/ci-build.yml
  .vsts-ci/templates/install-ps-phase.yml
  .vsts-ci/templates/test/nix-test-steps.yml
  .vsts-ci/templates/windows-test.yml
  .vsts-ci/windows-daily.yml
  .vsts-ci/windows/templates/windows-packaging.yml
  tools/releaseBuild/azureDevOps/templates/SetVersionVariables.yml
  tools/releaseBuild/azureDevOps/templates/compliance/apiscan.yml
  tools/releaseBuild/azureDevOps/templates/global-tool-pkg-sbom.yml
  tools/releaseBuild/azureDevOps/templates/release-ValidatePackageBOM.yml
  tools/releaseBuild/azureDevOps/templates/release-ValidatePackageNames.yml
  tools/releaseBuild/azureDevOps/templates/vpackReleaseJob.yml
Labels: Review - Needed, CL-BuildPackaging, Backport-7.2.x-Consider, BackPort-7.4.x-Consider

#24252 Create new pipeline for compliance
  .pipelines/apiscan-gen-notice.yml
  .pipelines/templates/compliance/apiscan.yml
  .pipelines/templates/compliance/generateNotice.yml
Labels: CL-BuildPackaging, BackPort-7.4.x-Consider

#24246 Make `PSCommandNotFoundSuggestion`, `PSCommandWithArgs`, and `PSModuleAutoLoadSkipOfflineFiles` stable
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/Modules/ModuleUtils.cs
  src/System.Management.Automation/engine/Subsystem/FeedbackSubsystem/IFeedbackProvider.cs
  src/System.Management.Automation/engine/hostifaces/HostUtilities.cs
Labels: CL-General, BackPort-7.5.x-Consider

#24248 chore: update ShowModuleControl.xaml.cs
  src/Microsoft.Management.UI.Internal/ShowCommand/Controls/ShowModuleControl.xaml.cs
Labels: CL-CodeCleanup

#24264 Update and add new NuGet package sources for different environments.
  build.psm1
  test/tools/Modules/nuget.config
Labels: CL-BuildPackaging, Backport-7.2.x-Consider, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#24265 Fix how processor arch is validated in `Import-Module`
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  test/powershell/Modules/Microsoft.PowerShell.Core/Import-Module.Tests.ps1
Labels: CL-General, BackPort-7.5.x-Consider

#24228 Handle global tool specially when prepending PSHome to PATH
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs
Labels: CL-General, MustHave, BackPort-7.5.x-Consider

#24263 Do not build the exe for Global tool shim project
  build.psm1
Labels: CL-BuildPackaging, MustHave, BackPort-7.5.x-Consider

#24270 Make some release tests run in a hosted pools
  .pipelines/PowerShell-Release-Official.yml
  .pipelines/templates/release-validate-sdk.yml
Labels: Backport-7.2.x-Consider, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#24273 Bump .NET 9 to `9.0.100-rc.1.24452.12`
  global.json
  src/Microsoft.PowerShell.Commands.Diagnostics/Microsoft.PowerShell.Commands.Diagnostics.csproj
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimConverter.cs
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.PowerShell.Security/security/CertificateCommands.cs
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/security/SecuritySupport.cs
  test/powershell/Host/Startup.Tests.ps1
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/Program.cs
  test/tools/WebListener/WebListener.csproj
Labels: MustHave, BackPort-7.5.x-Consider

#24247 Telemetry for feature use
  src/System.Management.Automation/CoreCLR/CorePsAssemblyLoadContext.cs
  src/System.Management.Automation/engine/Modules/ModuleUtils.cs
  src/System.Management.Automation/engine/Subsystem/FeedbackSubsystem/IFeedbackProvider.cs
  src/System.Management.Automation/engine/Subsystem/SubsystemInfo.cs
  src/System.Management.Automation/utils/Telemetry.cs
Labels: CL-General, BackPort-7.5.x-Consider

#24288 Remove the MD5 branch in the strong name signing token calculation
  src/TypeCatalogGen/TypeCatalogGen.cs
Labels: CL-BuildPackaging, BackPort-7.5.x-Consider

#20999 ConvertTo-Json: Treat large enums as numbers
  experimental-feature-linux.json
  experimental-feature-windows.json
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertTo-Json.PSSerializeJSONLongEnumAsNumber.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Json.Tests.ps1
  test/tools/TestMetadata.json
Labels: WG-Cmdlets, Breaking-Change, CL-BreakingChange, CL-General, Extra Small, WG-Reviewed

#24301 add updated libicu dependency for debian packages
  tools/packages.microsoft.com/mapping.json
  tools/packaging/packaging.psm1
Labels: BackPort-7.5.x-Consider

#24323 Update markdownLink.yml to not run on release branches
  .github/workflows/markdownLink.yml
Labels: CL-Tools

#24305 [release/v7.5] Enable create and submit in vPack build by default
  .pipelines/PowerShell-vPack-Official.yml
Labels: CL-BuildPackaging

#24306 [release/v7.5] Add windows signing for pwsh.exe
  .pipelines/templates/obp-file-signing.yml
Labels: CL-BuildPackaging

#24308 [release/v7.5] Use Managed Identity for APIScan authentication
  tools/releaseBuild/azureDevOps/templates/compliance/apiscan.yml
Labels: CL-BuildPackaging

#24309 [release/v7.5] Put issues in specific path
  .config/tsaoptions.json
Labels: CL-BuildPackaging

#24310 [release/v7.5] Make `PSCommandNotFoundSuggestion`, `PSCommandWithArgs`, and `PSModuleAutoLoadSkipOfflineFiles` stable
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/Modules/ModuleUtils.cs
  src/System.Management.Automation/engine/Subsystem/FeedbackSubsystem/IFeedbackProvider.cs
  src/System.Management.Automation/engine/hostifaces/HostUtilities.cs
Labels: CL-General

#24312 [release/v7.5] Create new pipeline for compliance
  .pipelines/apiscan-gen-notice.yml
  .pipelines/templates/compliance/apiscan.yml
  .pipelines/templates/compliance/generateNotice.yml
Labels: CL-BuildPackaging

#24313 [release/v7.5] Delete assets/AppImageThirdPartyNotices.txt
  assets/AppImageThirdPartyNotices.txt
Labels: CL-BuildPackaging

#24314 [release/v7.5] Delete demos directory
  demos/Apache/Apache/Apache.psm1
  demos/Apache/apache-demo.ps1
  demos/Apache/readme.md
  demos/Azure/Azure-Demo.ps1
  demos/Azure/Compute-Linux.json
  demos/Azure/README.md
  demos/DSC/dsc-demo.ps1
  demos/DSC/readme.md
  demos/Docker-PowerShell/Docker-PowerShell.ps1
  demos/README.md
  demos/SystemD/SystemD/SystemD.psm1
  demos/SystemD/journalctl-demo.ps1
  demos/SystemD/readme.md
  demos/WindowsPowerShellModules/README.md
  demos/crontab/CronTab/CronTab.ps1xml
  demos/crontab/CronTab/CronTab.psd1
  demos/crontab/CronTab/CronTab.psm1
  demos/crontab/README.md
  demos/crontab/crontab.ps1
  demos/dsc.ps1
  demos/powershellget/PowerShellGet.ps1
  demos/powershellget/README.md
  demos/python/README.md
  demos/python/class1.ps1
  demos/python/class1.py
  demos/python/demo_script.ps1
  demos/python/inline_python.ps1
  demos/rest/README.md
  demos/rest/rest.ps1
Labels: CL-Docs

#24317 [release/v7.5] Fix how processor arch is validated in `Import-Module`
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  test/powershell/Modules/Microsoft.PowerShell.Core/Import-Module.Tests.ps1
Labels: CL-Engine

#24318 [release/v7.5]Make some release tests run in a hosted pools
  .pipelines/PowerShell-Release-Official.yml
  .pipelines/templates/release-validate-sdk.yml
Labels: CL-BuildPackaging

#24320 [release/v7.5] Bump .NET 9 to `9.0.100-rc.1.24452.12`
  global.json
  src/Microsoft.PowerShell.Commands.Diagnostics/Microsoft.PowerShell.Commands.Diagnostics.csproj
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimConverter.cs
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.PowerShell.Security/security/CertificateCommands.cs
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/security/SecuritySupport.cs
  test/powershell/Host/Startup.Tests.ps1
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/Program.cs
  test/tools/WebListener/WebListener.csproj
Labels: CL-BuildPackaging

#24316 [release/v7.5] Update and add new NuGet package sources for different environments.
  build.psm1
  test/tools/Modules/nuget.config
Labels: CL-BuildPackaging

#24322 [release/v7.5] Add PMC mapping to Azurelinux repo
  tools/packages.microsoft.com/mapping.json
Labels: CL-BuildPackaging

#24324 [release/v7.5] add updated libicu dependency for debian packages
  tools/packages.microsoft.com/mapping.json
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging

#24304 [release/v7.5] ConvertTo-Json: Treat large enums as numbers
  experimental-feature-linux.json
  experimental-feature-windows.json
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertTo-Json.PSSerializeJSONLongEnumAsNumber.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Utility/Json.Tests.ps1
  test/tools/TestMetadata.json
Labels: CL-BreakingChange, CL-General

#24321 [release/v7.5] Remove the MD5 branch in the strong name signing token calculation
  src/TypeCatalogGen/TypeCatalogGen.cs
Labels: CL-General

#24331 [release/v7.5] Telemetry for feature use
  src/System.Management.Automation/CoreCLR/CorePsAssemblyLoadContext.cs
  src/System.Management.Automation/engine/Modules/ModuleUtils.cs
  src/System.Management.Automation/engine/Subsystem/FeedbackSubsystem/IFeedbackProvider.cs
  src/System.Management.Automation/engine/Subsystem/SubsystemInfo.cs
  src/System.Management.Automation/utils/Telemetry.cs
Labels: CL-General

#24300 Update Microsoft.PowerShell.PSResourceGet to 1.1.0-preview2
  src/Modules/PSGalleryModules.csproj
  test/powershell/Modules/Microsoft.PowerShell.PSResourceGet/Microsoft.PowerShell.PSResourceGet.Tests.ps1
Labels: BackPort-7.5.x-Approved

#24337 [release/v7.5] Update `Microsoft.PowerShell.PSResourceGet` to `1.1.0-preview2`
  src/Modules/PSGalleryModules.csproj
  test/powershell/Modules/Microsoft.PowerShell.PSResourceGet/Microsoft.PowerShell.PSResourceGet.Tests.ps1
Labels: CL-BuildPackaging

#24269 Copy to static site instead of making blob public
  .pipelines/templates/release-MakeBlobPublic.yml
  .pipelines/templates/release-upload-buildinfo.yml
  tools/install-powershell.ps1
Labels: BackPort-7.5.x-Approved

#24343 [release/v7.5] Copy to static site instead of making blob public
  .pipelines/templates/release-MakeBlobPublic.yml
  .pipelines/templates/release-upload-buildinfo.yml
  tools/install-powershell.ps1
Labels: CL-BuildPackaging

#24345 [release/v7.5] Fix cleanup in PSResourceGet test
  test/powershell/Modules/Microsoft.PowerShell.PSResourceGet/Microsoft.PowerShell.PSResourceGet.Tests.ps1
Labels: CL-Test
