Repository PowerShell/PowerShell, pull requests merged in 2024-05, with the labels that each got.

#21559 Create the Windows.x64 global tool with shim for signing
  .pipelines/templates/nupkg.yml
  .pipelines/templates/obp-file-signing.yml
  .pipelines/templates/windows-hosted-build.yml
  src/GlobalTools/PowerShell.Windows.x64/PowerShell.Windows.x64.csproj
  src/GlobalTools/PowerShell.Windows.x64/Powershell_64.png
  tools/packaging/packaging.psm1
  tools/packaging/packaging.strings.psd1
Labels: Backport-7.2.x-Consider, Backport-7.3.x-Consider, BackPort-7.4.x-Consider

#21605 When generating `OutputType` don't cast to `Type[]`
  src/System.Management.Automation/engine/parser/Compiler.cs
Labels: CL-Engine, Backport-7.2.x-Consider, BackPort-7.4.x-Consider

#21611 Use PSScriptRoot to find path to Wix module
  build.psm1
Labels: CL-BuildPackaging, Backport-7.2.x-Consider, Backport-7.3.x-Consider, BackPort-7.4.x-Consider

#20420 Remember installation options and used them to initialize options for the next installation
  assets/wix/Product.wxs
  test/packaging/windows/msi.tests.ps1
Labels: Breaking-Change, CL-BreakingChange, Large, PowerShell-Docs not needed

#21782 Bump to .NET 9 preview 3
  global.json
  src/Microsoft.PowerShell.Commands.Diagnostics/Microsoft.PowerShell.Commands.Diagnostics.csproj
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  test/powershell/Host/Startup.Tests.ps1
  test/powershell/Language/Parser/MethodInvocation.Tests.ps1
  tools/packaging/boms/windows.json
Labels: CL-BuildPackaging

#20778 Added progress bar for `Remove-Item` cmdlet
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/resources/FileSystemProviderStrings.resx
Labels: WG-Interactive-Console, Extra Small, WG-NeedsReview

#23796 Update PSResourceGet version to 1.0.5
  src/Modules/PSGalleryModules.csproj
Labels: CL-BuildPackaging

#23864 Merge the `v7.5.0-preview.3` release branch to GitHub master branch
  .pipelines/PowerShell-Coordinated_Packages-Official.yml
  .pipelines/PowerShell-Packages-Official.yml
  .pipelines/PowerShell-Release-Official.yml
  .pipelines/templates/SetVersionVariables.yml
  .pipelines/templates/checkAzureContainer.yml
  .pipelines/templates/linux-package-build.yml
  .pipelines/templates/linux.yml
  .pipelines/templates/mac.yml
  .pipelines/templates/release-MakeBlobPublic.yml
  .pipelines/templates/release-create-msix.yml
  .pipelines/templates/release-githubtasks.yml
  .pipelines/templates/release-publish-nuget.yml
  .pipelines/templates/release-publish-pmc.yml
  .pipelines/templates/release-symbols.yml
  .pipelines/templates/release-upload-buildinfo.yml
  .pipelines/templates/release-validate-packagenames.yml
  .pipelines/templates/testartifacts.yml
  .pipelines/templates/windows-hosted-build.yml
  CHANGELOG/preview.md
  src/GlobalTools/PowerShell.Windows.x64/PowerShell.Windows.x64.csproj
Labels: CL-BuildPackaging

#23865 Add checkout to fix TSA config paths
  .pipelines/templates/release-symbols.yml
  .pipelines/templates/release-upload-buildinfo.yml
Labels: CL-BuildPackaging

#23870 update wix install in ci.psm1
  tools/ci.psm1
Labels: CL-BuildPackaging

#23878 Fix exe signing with third party signing for WiX engine
  .pipelines/templates/linux.yml
  .pipelines/templates/mac.yml
  .pipelines/templates/obp-file-signing.yml
  .pipelines/templates/windows-hosted-build.yml
  .pipelines/templates/windows-package-build.yml
Labels: CL-BuildPackaging, Backport-7.2.x-Consider, BackPort-7.4.x-Consider
