Repository PowerShell/PowerShell, pull requests merged in 2024-02, with the labels that each got.

#21162 Validate the value for `using namespace` during semantic checks to prevent declaring invalid namespaces
  src/System.Management.Automation/engine/parser/SemanticChecks.cs
  src/System.Management.Automation/resources/ParserStrings.resx
  test/powershell/Language/Parser/UsingNamespace.Tests.ps1
Labels: CL-Engine, Extra Small

#21169 Fix for #21161 - using assembly not working on non-Windows platforms.
  src/System.Management.Automation/engine/parser/Compiler.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  test/powershell/Language/Parser/UsingAssembly.Tests.ps1
Labels: WG-Language

#21126 Add DirectoryInfo to OutputType for New-Item
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: Review - Needed, Extra Small

#21098 Update changelog for v7.4.1
  CHANGELOG/7.4.md
Labels: Review - Needed, CL-Docs, Extra Small

#21091 Update WG members
  docs/community/working-group-definitions.md
Labels: Extra Small

#21173 Fix incorrect examples in XML docs in `PowerShell.cs`
  src/System.Management.Automation/engine/hostifaces/PowerShell.cs
Labels: CL-Docs, No Changes

#20516 Generate msi for win-arm64 installer
  assets/wix/Product.wxs
  assets/wix/bundle.wxs
  tools/ci.psm1
  tools/packaging/packaging.psm1
  tools/releaseBuild/Images/microsoft_powershell_windowsservercore/PowerShellPackage.ps1
  tools/releaseBuild/azureDevOps/templates/windows-package-signing.yml
  tools/releaseBuild/azureDevOps/templates/windows-packaging.yml
Labels: Small

#21174 Rewrite the mac syslog tests as they seem somewhat flaky.
  test/powershell/Host/Logging.Tests.ps1
  test/tools/Modules/PSSysLog/PSSysLog.psm1
Labels: CL-Test, Small

#21190 Update versions of PSResourceGet
  src/Modules/PSGalleryModules.csproj
Labels: Extra Small

#20402 Add tilde expansion for windows native executables
  src/System.Management.Automation/engine/ExperimentalFeature/ExperimentalFeature.cs
  src/System.Management.Automation/engine/NativeCommandParameterBinder.cs
  test/powershell/Language/Scripting/NativeExecution/NativeWindowsTildeExpansion.Tests.ps1
  test/tools/TestMetadata.json
Labels: Review - Needed, Small, CommunityDay-Small, PowerShell-Docs not needed

#21189 Remove PSScheduledJob source code
  src/Microsoft.PowerShell.ScheduledJob/AssemblyInfo.cs
  src/Microsoft.PowerShell.ScheduledJob/ScheduledJob.cs
  src/Microsoft.PowerShell.ScheduledJob/ScheduledJobDefinition.cs
  src/Microsoft.PowerShell.ScheduledJob/ScheduledJobOptions.cs
  src/Microsoft.PowerShell.ScheduledJob/ScheduledJobSourceAdapter.cs
  src/Microsoft.PowerShell.ScheduledJob/ScheduledJobStore.cs
  src/Microsoft.PowerShell.ScheduledJob/ScheduledJobTrigger.cs
  src/Microsoft.PowerShell.ScheduledJob/ScheduledJobWTS.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/AddJobTrigger.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/DisableJobDefinition.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/DisableJobDefinitionBase.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/DisableJobTrigger.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/EnableDisableCmdletBase.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/EnableJobDefinition.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/EnableJobTrigger.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/GetJobDefinition.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/GetJobTrigger.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/GetScheduledJobOption.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/NewJobTrigger.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/NewScheduledJobOption.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/RegisterJobDefinition.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/RemoveJobTrigger.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/SchedJobCmdletBase.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/ScheduledJobOptionCmdletBase.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/SetJobDefinition.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/SetJobTrigger.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/SetScheduledJobOption.cs
  src/Microsoft.PowerShell.ScheduledJob/commands/UnregisterJobDefinition.cs
  src/Microsoft.PowerShell.ScheduledJob/resources/ScheduledJobErrorStrings.resx
Labels: Extra Large

#21179 Fix typo in CoreAdapter.cs
  src/System.Management.Automation/engine/CoreAdapter.cs
Labels: No Changes

#20925 ConvertFrom-Json: Add -DateKind parameter
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertFromJsonCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonDateKind.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertFrom-Json.Tests.ps1
Labels: CL-General, Medium, PowerShell-Docs needed

#21229 Bump to .NET 9 Preview 1
  PowerShell.Common.props
  build.psm1
  global.json
  nuget.config
  src/Microsoft.PowerShell.Commands.Diagnostics/Microsoft.PowerShell.Commands.Diagnostics.csproj
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/Modules/PSGalleryModules.csproj
  src/ResGen/ResGen.csproj
  src/System.Management.Automation/SourceGenerators/PSVersionInfoGenerator/PSVersionInfoGenerator.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  src/TypeCatalogGen/TypeCatalogGen.csproj
  test/Test.Common.props
  test/powershell/engine/Basic/StandardLibraryTypes.Tests.ps1
  test/tools/NamedPipeConnection/build.ps1
  test/tools/NamedPipeConnection/src/code/Microsoft.PowerShell.NamedPipeConnection.csproj
  test/tools/OpenCover/OpenCover.psm1
  tools/findMissingNotices.ps1
  tools/packaging/boms/windows.json
  tools/packaging/packaging.psm1
  tools/packaging/packaging.strings.psd1
  tools/packaging/projects/nuget/package.csproj
  tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  tools/packaging/projects/reference/Microsoft.PowerShell.ConsoleHost/Microsoft.PowerShell.ConsoleHost.csproj
  tools/packaging/projects/reference/System.Management.Automation/System.Management.Automation.csproj
  tools/releaseBuild/azureDevOps/templates/nuget-pkg-sbom.yml
  tools/releaseBuild/azureDevOps/templates/release-SDKTests.yml
Labels: Medium

#21238 Remove surrogateFile setting of APIScan
  tools/releaseBuild/azureDevOps/templates/compliance/apiscan.yml
Labels: Extra Small

#21239 Add dotenv install as latest version does not work with current Ruby version
  build.psm1
Labels: CL-BuildPackaging, Extra Small

#21259 Add `dotnet-runtime-9.0` as a dependency for the Mariner package
  tools/packaging/packaging.psm1
Labels: Extra Small

#21264 Update `metadata.json` and `README.md`
  README.md
  tools/metadata.json
Labels: Extra Small

#21265 Skip test on Windows Server 2012 R2 for no-nl
  test/powershell/Language/Scripting/I18n/I18n.Tests.ps1
Labels: CL-Test, Extra Small

#21156 Fix `Format-Table` where header label is empty
  src/System.Management.Automation/FormatAndOutput/common/FormatViewGenerator_Table.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Format-Table.Tests.ps1
Labels: Review - Needed, Extra Small, BackPort-7.4.x-Consider

#21049 Revert "Adjust PUT method behavior to POST one for default content type in WebCmdlets"
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1
Labels: WG-Cmdlets, Review - Needed, Extra Small, WG-Reviewed, BackPort-7.4.x-Consider

#21000 ConvertTo-Json: Serialize BigInteger as a number
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/JsonObject.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertTo-Json.Tests.ps1
Labels: Breaking-Change, WG-Cmdlets-Utility, CL-BreakingChange, CL-General, Extra Small, WG-Reviewed

#21246 Remove `JetBrains.Annotations` attributes
  ThirdPartyNotices.txt
  src/System.Management.Automation/utils/assert.cs
Labels: Review - Needed, Extra Small

#21244 Suppress MacOS package manager output
  build.psm1
Labels: CL-BuildPackaging, Extra Small

#21165 Enable CA1868: Unnecessary call to 'Contains' for sets
  .globalconfig
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimSessionOperations.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertFrom-SddlString.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Update-TypeData.cs
  src/System.Management.Automation/FormatAndOutput/common/DisplayDatabase/typeDataQuery.cs
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/engine/InitialSessionState.cs
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  src/System.Management.Automation/engine/parser/PSType.cs
  src/System.Management.Automation/engine/parser/SemanticChecks.cs
  src/System.Management.Automation/engine/remoting/client/RemotingProtocol2.cs
  src/System.Management.Automation/help/CommandHelpProvider.cs
  src/System.Management.Automation/help/HelpFileHelpProvider.cs
  src/System.Management.Automation/security/CatalogHelper.cs
Labels: Review - Needed, CL-CodeCleanup, Small
