Repository PowerShell/PowerShell, pull requests merged in 2024-11, with the labels that each got.

#24542 [release/v7.4] Add a way to use only NuGet feed sources
  build.psm1
  nuget.config
  src/Modules/nuget.config
  test/tools/Modules/nuget.config
  tools/findMissingNotices.ps1
Labels: CL-BuildPackaging

#24543 [release/v7.4] Fix seed max value for Container Linux CI
  tools/ci.psm1
Labels: CL-BuildPackaging

#24545 [release/v7.4] Fix backport mistake in #24429
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  test/tools/TestService/TestService.csproj
Labels: CL-BuildPackaging

#24555 Support PSObject wrapped values in ArgumentToEncodingTransformationAttribute
  src/System.Management.Automation/utils/EncodingUtils.cs
  test/powershell/engine/Basic/Encoding.Tests.ps1
Labels: CL-General

#24588 [release/v7.5] Update machine pool for copy blob and upload buildinfo stage
  .pipelines/PowerShell-Release-Official.yml
  .pipelines/templates/release-MakeBlobPublic.yml
  .pipelines/templates/release-upload-buildinfo.yml
Labels: CL-BuildPackaging

#24596 Update nuget publish to use Deploy Box
  .pipelines/templates/release-publish-nuget.yml
Labels: BackPort-7.5.x-Approved

#24617 Set `LangVersion` compiler option to `13.0`
  src/System.Management.Automation/SourceGenerators/PSVersionInfoGenerator/PSVersionInfoGenerator.csproj
  test/perf/dotnet-tools/ResultsComparer/ResultsComparer.csproj
  test/tools/NamedPipeConnection/src/code/Microsoft.PowerShell.NamedPipeConnection.csproj
  tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  tools/packaging/projects/reference/Microsoft.PowerShell.ConsoleHost/Microsoft.PowerShell.ConsoleHost.csproj
  tools/packaging/projects/reference/System.Management.Automation/System.Management.Automation.csproj
Labels: CL-BuildPackaging

#24600 Fix up buffer management getting network roots
  src/System.Management.Automation/engine/Interop/Windows/WNetGetConnection.cs
  src/System.Management.Automation/engine/Utils.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Get-PSDrive.Tests.ps1
Labels: CL-General

#24619 Set LangVersion compiler option to 13.0
  PowerShell.Common.props
Labels: CL-BuildPackaging
