Repository PowerShell/PowerShell, pull requests merged in 2025-03, with the labels that each got.

#25112 Fix tooltip for variable expansion and include description
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General

#25061 Set standard handles explicitly when starting a process with `-NoNewWindow`
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Start-Process.Tests.ps1
Labels: CL-General, BackPort-7.5.x-Consider

#25051 Make some `SystemPolicy` APIs visible but non-op on Unix so that they can be included in `PowerShellStandard.Library`
  src/System.Management.Automation/CoreCLR/CorePsStub.cs
Labels: CL-General

#21113 Don't complete duplicate command names
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Small

#25126 Add `dotnet_style_prefer_collection_expression` to `.editorconfig`
  .editorconfig
  build.psm1
Labels: CL-NotInBuild

#25122 Fix completion that relies on pseudobinding in script blocks
  src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs
  src/System.Management.Automation/engine/Modules/ScriptAnalysis.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General

#25129 Improve the completion for attribute arguments
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General

#17687 Fix parameter completion when script requirements fail
  src/System.Management.Automation/engine/CommandCompletion/PseudoParameterBinder.cs
  src/System.Management.Automation/engine/CommandDiscovery.cs
  src/System.Management.Automation/engine/ExecutionContext.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: WG-Interactive-IntelliSense, CL-General, Extra Small

#25137 Return `Array.Empty` instead of collection `[]`
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
Labels: CL-CodeCleanup

#25133 Check GH token availability for Get-Changelog
  tools/releaseTools.psm1
Labels: CL-Tools, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25143 Add `dotnet_diagnostic.CA1859.severity = suggestion` to editorconfig
  .editorconfig
  build.psm1
Labels: CL-NotInBuild

#25138 Move common completion methods to CompletionHelpers class
  src/Microsoft.PowerShell.Commands.Management/commands/management/NewPropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionHelpers.cs
  src/System.Management.Automation/engine/CommandCompletion/ScopeArgumentCompleter.cs
  src/System.Management.Automation/engine/ExperimentalFeature/EnableDisableExperimentalFeatureCommand.cs
  src/System.Management.Automation/engine/GetCommandCommand.cs
  src/System.Management.Automation/engine/InternalCommands.cs
  src/System.Management.Automation/engine/Modules/GetModuleCommand.cs
  src/System.Management.Automation/utils/Verbs.cs
Labels: CL-CodeCleanup

#25139 Make the use of Oxford commas consistent
  src/Microsoft.PowerShell.ConsoleHost/resources/ManagedEntranceStrings.resx
Labels: CL-CodeCleanup

#25145 Add GitHub Actions workflow to verify PR labels
  .github/workflows/labels.yml
Labels: CL-BuildPackaging

#25118 Remove Az module installs and AzureRM uninstalls in pipeline
  .pipelines/PowerShell-Packages-Official.yml
  .pipelines/PowerShell-Release-Official-Azure.yml
  .pipelines/PowerShell-Release-Official.yml
  .pipelines/templates/checkAzureContainer.yml
  .pipelines/templates/compliance/apiscan.yml
  .pipelines/templates/compliance/generateNotice.yml
  .pipelines/templates/release-MakeBlobPublic.yml
  .pipelines/templates/release-create-msix.yml
  .pipelines/templates/release-upload-buildinfo.yml
  .pipelines/templates/release-validate-packagenames.yml
  .pipelines/templates/uploadToAzure.yml
Labels: CL-BuildPackaging, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25102 Skip additional packages when generating component manifest
  tools/findMissingNotices.ps1
Labels: Review - Needed, CL-BuildPackaging, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25158 [release/v7.4]Add GitHub Actions workflow to verify PR labels
  .github/workflows/labels.yml
Labels: CL-BuildPackaging

#25157 [release/v7.4]Remove Az module installs and AzureRM uninstalls in pipeline
  .pipelines/PowerShell-Packages-Official.yml
  .pipelines/PowerShell-Release-Official-Azure.yml
  .pipelines/PowerShell-Release-Official.yml
  .pipelines/templates/checkAzureContainer.yml
  .pipelines/templates/compliance/apiscan.yml
  .pipelines/templates/compliance/generateNotice.yml
  .pipelines/templates/release-MakeBlobPublic.yml
  .pipelines/templates/release-create-msix.yml
  .pipelines/templates/release-upload-buildinfo.yml
  .pipelines/templates/release-validate-packagenames.yml
  .pipelines/templates/uploadToAzure.yml
Labels: CL-BuildPackaging

#25156 [release/v7.4]Check GH token availability for Get-Changelog
  tools/releaseTools.psm1
Labels: CL-Tools

#25160 [release/v7.4]Skip additional packages when generating component manifest
  tools/findMissingNotices.ps1
Labels: CL-BuildPackaging

#19830 Improve variable type inference
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: WG-Interactive-IntelliSense, CL-General, Extra Large, PowerShell-Docs not needed

#25169 Add 7.4.9 changelog
  CHANGELOG/7.4.md
Labels: CL-Docs

#25171 [release/v7.4]Add 7.4.9 changelog
  CHANGELOG/7.4.md
Labels: CL-Docs

#25181 Add XUnit test for `HandleDoubleAndSingleQuote` in CompletionHelpers class
  test/xUnit/csharp/test_CompletionHelpers.cs
Labels: CL-Test

#25179 Refactor CompletionHelpers `HandleDoubleAndSingleQuote` to have less nesting logic
  src/System.Management.Automation/engine/CommandCompletion/CompletionHelpers.cs
Labels: CL-General

#25177 Remove the old fuzzy suggestion and fix the local script file name suggestion
  src/System.Management.Automation/engine/Subsystem/FeedbackSubsystem/IFeedbackProvider.cs
  src/System.Management.Automation/engine/hostifaces/HostUtilities.cs
  src/System.Management.Automation/resources/SuggestionStrings.resx
  src/System.Management.Automation/utils/Telemetry.cs
  test/xUnit/csharp/test_Feedback.cs
Labels: CL-General, BackPort-7.5.x-Consider

#25191 Update package pipeline windows image version
  .pipelines/PowerShell-Packages-Official.yml
  .pipelines/templates/checkAzureContainer.yml
Labels: CL-BuildPackaging, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#24985 Fix `TypeName.GetReflectionType()` to work when the `TypeName` instance represents a generic type definition within a `GenericTypeName`
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/engine/parser/ast.cs
  test/powershell/Language/Parser/Parsing.Tests.ps1
Labels: CL-General

#25178 Remove CompletionHelpers `escape` parameter from `CompletionRequiresQuotes`
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionHelpers.cs
Labels: CL-CodeCleanup

#24677 Convert `-ChildPath` parameter to `string[]` for `Join-Path` cmdlet
  src/Microsoft.PowerShell.Commands.Management/commands/management/CombinePathCommand.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/Join-Path.Tests.ps1
Labels: CL-BreakingChange, CL-General, PowerShell-Docs needed

#21143 Improve assignment type inference
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: CL-General, Extra Small

#25172 Fix type inference of parameters in classic functions
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: CL-General

#25022 Move .NET method invocation logging to after the needed type conversion is done for method arguments
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
Labels: CL-General, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25154 Bump .NET to 10 preview.1
  PowerShell.Common.props
  build.psm1
  global.json
  src/GlobalTools/PowerShell.Windows.x64/PowerShell.Windows.x64.csproj
  src/Microsoft.PowerShell.Commands.Diagnostics/Microsoft.PowerShell.Commands.Diagnostics.csproj
  src/Microsoft.PowerShell.Commands.Management/Microsoft.PowerShell.Commands.Management.csproj
  src/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
  src/Microsoft.WSMan.Management/Microsoft.WSMan.Management.csproj
  src/Modules/PSGalleryModules.csproj
  src/ResGen/ResGen.csproj
  src/System.Management.Automation/SourceGenerators/PSVersionInfoGenerator/PSVersionInfoGenerator.csproj
  src/System.Management.Automation/System.Management.Automation.csproj
  src/TypeCatalogGen/TypeCatalogGen.csproj
  test/Test.Common.props
  test/tools/NamedPipeConnection/build.ps1
  test/tools/NamedPipeConnection/src/code/Microsoft.PowerShell.NamedPipeConnection.csproj
  test/tools/OpenCover/OpenCover.psm1
  test/tools/TestService/TestService.csproj
  test/tools/WebListener/WebListener.csproj
  tools/findMissingNotices.ps1
  tools/packaging/boms/windows.json
  tools/packaging/packaging.psm1
  tools/packaging/packaging.strings.psd1
  tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility/Microsoft.PowerShell.Commands.Utility.csproj
  tools/packaging/projects/reference/Microsoft.PowerShell.ConsoleHost/Microsoft.PowerShell.ConsoleHost.csproj
  tools/packaging/projects/reference/System.Management.Automation/System.Management.Automation.csproj
Labels: CL-BuildPackaging

#25180 Add `QuoteCompletionText` method to CompletionHelpers class
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionHelpers.cs
  test/xUnit/csharp/test_CompletionHelpers.cs
Labels: CL-CodeCleanup

#25197 Update GitHub Actions to work in private GitHub repo
  .github/workflows/AssignPrs.yml
  .github/workflows/backport.yml
  .github/workflows/createReminders.yml
  .github/workflows/labels.yml
  .github/workflows/linux-ci.yml
  .github/workflows/macos-ci.yml
  .github/workflows/markdownLink.yml
  .github/workflows/processReminders.yml
  .github/workflows/scorecards.yml
  .github/workflows/windows-ci.yml
Labels: CL-BuildPackaging

#25213 Remove dependabot updates that don't work
  .github/dependabot.yml
Labels: CL-BuildPackaging

#25219 Add `NoWarn NU1605` to System.ServiceModel.*
  src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj
Labels: CL-BuildPackaging

#25192 [release/v7.4]Update package pipeline windows image version
  .pipelines/PowerShell-Packages-Official.yml
  .pipelines/templates/checkAzureContainer.yml
Labels: CL-BuildPackaging

#25159 [release/v7.5]Add GitHub Actions workflow to verify PR labels
  .github/workflows/labels.yml
Labels: Review - Needed, CL-BuildPackaging

#25226 Remove obsolete template from Windows Packaging CI
  .vsts-ci/windows/templates/windows-packaging.yml
Labels: CL-BuildPackaging, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#24912 Fallback to AppLocker after `WldpCanExecuteFile`
  src/System.Management.Automation/security/wldpNativeMethods.cs
Labels: Review - Needed, CL-Engine, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#24620 Add PipelineStopToken to PSCmdlet
  src/System.Management.Automation/engine/CommandBase.cs
  src/System.Management.Automation/engine/cmdlet.cs
  src/System.Management.Automation/engine/pipeline.cs
  test/powershell/Language/Scripting/PipelineStoppedToken.Tests.ps1
Labels: WG-Engine, Review - Needed, CommunityDay-Small, WG-Reviewed

#25211 Fix `WildcardPattern.Escape` to escape lone backticks correctly
  src/System.Management.Automation/engine/regex.cs
  test/powershell/Language/Operators/ComparisonOperator.Tests.ps1
  test/xUnit/csharp/test_WildcardPattern.cs
Labels: CL-BreakingChange, CL-General

#17864 Add tooltips for hashtable key completions
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/resources/TabCompletionStrings.resx
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Large

#25206 Fix infinite loop in variable type inference
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: CL-General

#25223 Refactor and add comments to `CompletionRequiresQuotes` to clarify implementation
  src/System.Management.Automation/engine/CommandCompletion/CompletionHelpers.cs
Labels: CL-CodeCleanup

#25224 Exclude outvariable assignments within the same CommandAst when inferring variables
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: CL-General

#25247 Switch to ubuntu-lastest for CI
  .github/workflows/linux-ci.yml
Labels: CL-BuildPackaging
