Repository PowerShell/PowerShell, pull requests merged in 2025-08, with the labels that each got.

#25819 Fix updatable help test for new content
  test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1
  test/powershell/engine/Help/assets/Microsoft.PowerShell.Utility_1da87e53-152b-403e-98dc-74d7b4d63d59_en-US_helpcontent.cab
  test/powershell/engine/Help/assets/Microsoft.PowerShell.Utility_1da87e53-152b-403e-98dc-74d7b4d63d59_en-US_helpcontent.zip
Labels: CL-Test

#21188 Fix `Write-Host` to respect OutputRendering = PlainText
  src/System.Management.Automation/engine/hostifaces/InternalHostUserInterface.cs
Labels: CL-General, Extra Small

#25780 Fix up SSHConnectionInfo ssh PATH checks
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
Labels: CL-Engine

#25867 Change the macos runner image to macos 15 large
  .github/workflows/macos-ci.yml
Labels: CL-BuildPackaging

#25864 Suppress false positive PSScriptAnalyzer warnings in tests and build scripts
  test/powershell/Modules/Microsoft.PowerShell.LocalAccounts/Pester.Command.Cmdlets.LocalAccounts.LocalUser.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Security/CmsMessage.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Security/GetCredential.Tests.ps1
  test/powershell/Modules/Microsoft.PowerShell.Security/TestData/CatalogTestData/UserConfigProv/DSCResources/UserConfigProviderModVersion1/UserConfigProviderModVersion1.psm1
  test/powershell/Modules/Microsoft.PowerShell.Security/TestData/CatalogTestData/UserConfigProv/DSCResources/UserConfigProviderModVersion2/UserConfigProviderModVersion2.psm1
  test/powershell/Modules/Microsoft.PowerShell.Security/TestData/CatalogTestData/UserConfigProv/DSCResources/UserConfigProviderModVersion3/UserConfigProviderModVersion3.psm1
  test/powershell/Modules/Microsoft.PowerShell.Security/certificateCommon.psm1
  test/powershell/Modules/Microsoft.PowerShell.Utility/ConvertTo-SecureString.Tests.ps1
  test/powershell/Modules/Microsoft.WSMan.Management/ConfigProvider.Tests.ps1
  test/powershell/engine/Api/Serialization.Tests.ps1
  test/powershell/engine/Remoting/PSSession.Tests.ps1
  test/powershell/engine/Remoting/RemoteSession.Basic.Tests.ps1
  test/tools/Modules/WebListener/WebListener.psm1
  tools/WindowsCI.psm1
  tools/ci.psm1
Labels: CL-Test

#25847 Update PATH envrionment variable for package manager executable on Windows
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/Utils.cs
  test/powershell/Language/Scripting/NativeExecution/NativeCommandPathUpdate.Tests.ps1
  test/tools/TestExe/TestExe.cs
Labels: CL-General

#25849 Seal internal types in `Microsoft.PowerShell.Commands.Management`
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/CreateInstanceJob.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/DeleteInstanceJob.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/EnumerateAssociatedInstancesJob.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/InstanceMethodInvocationJob.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/ModifyInstanceJob.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/QueryJob.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/StaticMethodInvocationJob.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimCmdletDefinitionContext.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimCmdletInvocationContext.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimConverter.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimJobContext.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/cimQuery.cs
  src/Microsoft.PowerShell.Commands.Management/cimSupport/cmdletization/cim/clientSideQuery.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/ContentCommandBase.cs
Labels: CL-CodeCleanup

#25892 Seal internal types in `Microsoft.PowerShell.Commands.Utility`
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ConvertTo-Html.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Csv.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CustomSerialization.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/ExpressionColumnInfo.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/HeaderInfo.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/OriginalColumnInfo.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/OutGridViewCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/OutWindowProxy.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/ScalarTypeColumnInfo.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/OutGridView/TableView.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetRandomCommandBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/JsonSchemaReferenceResolutionException.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ObjectCommandComparer.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/OrderObjectBase.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Select-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ShowCommand/ShowCommandProxy.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/InvokeRestMethodCommand.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebProxy.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/StreamHelper.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/XmlCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/MshHostTraceListener.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/trace/TraceExpressionCommand.cs
Labels: CL-CodeCleanup

#25885 Remove AsyncSDL from Pipelines Toggle Official/NonOfficial Runs
  .pipelines/MSIXBundle-vPack-Official.yml
  .pipelines/PowerShell-Coordinated_Packages-Official.yml
  .pipelines/PowerShell-Packages-Official.yml
  .pipelines/PowerShell-Release-Official-Azure.yml
  .pipelines/PowerShell-Release-Official.yml
  .pipelines/PowerShell-vPack-Official.yml
Labels: CL-BuildPackaging, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#24391 Fix stderr output of console host to respect NO_COLOR
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  test/powershell/Host/ConsoleHost.Tests.ps1
Labels: Review - Needed, CL-Engine

#25910 Change the default feedback provider timeout from 300ms to 1000ms
  src/System.Management.Automation/engine/Subsystem/FeedbackSubsystem/FeedbackHub.cs
Labels: CL-General

#25926 Remove redundant `System.Runtime.Versioning` attributes
  src/System.Management.Automation/namespaces/TransactedRegistry.cs
  src/System.Management.Automation/namespaces/TransactedRegistryKey.cs
  src/System.Management.Automation/namespaces/Win32Native.cs
Labels: CL-CodeCleanup

#25230 Support registering a cover-all completer for native commands
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CommandCompletion/ExtensibleCompletion.cs
  src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs
  src/System.Management.Automation/engine/lang/scriptblock.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: WG-Interactive-Console, CL-General, WG-Reviewed

#25934 Remove obsolete `CA1026` rule suppression
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/utils/perfCounters/CounterSetRegistrarBase.cs
  src/System.Management.Automation/utils/perfCounters/PSPerfCountersMgr.cs
Labels: CL-CodeCleanup
