Repository PowerShell/PowerShell, pull requests merged in 2025-09, with the labels that each got.

#25948 Remove obsolete `CA1701` rule suppression
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
Labels: CL-CodeCleanup

#25957 Remove obsolete `CA2240` rule suppression
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/utils/MetadataExceptions.cs
Labels: CL-CodeCleanup

#25962 Fix typo in CHANGELOG for script filename suggestion
  CHANGELOG/7.5.md
Labels: CL-Docs

#25946 Replace `DOTNET_SKIP_FIRST_TIME_EXPERIENCE` with `DOTNET_NOLOGO`
  .github/workflows/linux-ci.yml
  .github/workflows/macos-ci.yml
  .github/workflows/windows-ci.yml
  .pipelines/templates/linux.yml
  .pipelines/templates/release-symbols.yml
  .pipelines/templates/release-upload-buildinfo.yml
  .pipelines/templates/release-validate-fxdpackages.yml
  .pipelines/templates/release-validate-sdk.yml
  .pipelines/templates/uploadToAzure.yml
  .pipelines/templates/variable/release-shared.yml
  .pipelines/templates/windows-hosted-build.yml
  .vsts-ci/linux-daily.yml
  .vsts-ci/linux-internal.yml
  .vsts-ci/linux.yml
  .vsts-ci/mac.yml
  .vsts-ci/psresourceget-acr.yml
  .vsts-ci/sshremoting-tests.yml
  .vsts-ci/windows-arm64.yml
  .vsts-ci/windows-daily.yml
  .vsts-ci/windows.yml
  .vsts-ci/windows/windows-packaging.yml
Labels: CL-BuildPackaging

#25968 Ensure `.cs` files end with exactly one newline
  src/Microsoft.PowerShell.Commands.Diagnostics/CounterFileInfo.cs
  src/Microsoft.PowerShell.Commands.Diagnostics/ImportCounterCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/CommitTransactionCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Eventlog.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetTransactionCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/GetWMIObjectCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/RollbackTransactionCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/StartTransactionCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/UseTransactionCommand.cs
  src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/AddLocalGroupMemberCommand.cs
  src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/DisableLocalUserCommand.cs
  src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/EnableLocalUserCommand.cs
  src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/GetLocalGroupCommand.cs
  src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/GetLocalGroupMemberCommand.cs
  src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/GetLocalUserCommand.cs
  src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/NewLocalGroupCommand.cs
  src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/NewLocalUserCommand.cs
  src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/RemoveLocalGroupCommand.cs
  src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/RemoveLocalGroupMemberCommand.cs
  src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/RemoveLocalUserCommand.cs
  src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/RenameLocalGroupCommand.cs
  src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/RenameLocalUserCommand.cs
  src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/SetLocalGroupCommand.cs
  src/Microsoft.PowerShell.LocalAccounts/LocalAccounts/Commands/SetLocalUserCommand.cs
  src/System.Management.Automation/cimSupport/cmdletization/xml/cmdlets-over-objects.objectModel.autogen.cs
  src/System.Management.Automation/cimSupport/cmdletization/xml/cmdlets-over-objects.xmlSerializer.autogen.cs
  src/System.Management.Automation/engine/SessionStateDriveAPIs.cs
  src/System.Management.Automation/engine/SessionStateItem.cs
  src/System.Management.Automation/engine/SessionStateNavigation.cs
  src/System.Management.Automation/engine/SessionStateProperty.cs
  src/System.Management.Automation/engine/TransactedString.cs
  src/System.Management.Automation/engine/TransactionManager.cs
  src/System.Management.Automation/engine/hostifaces/RunspaceInvoke.cs
  src/System.Management.Automation/namespaces/ProviderBase.cs
  src/System.Management.Automation/security/CredentialParameter.cs
  src/TypeCatalogGen/TypeCatalogGen.cs
  test/perf/dotnet-tools/BenchmarkDotNet.Extensions/Extensions.cs
  test/perf/dotnet-tools/BenchmarkDotNet.Extensions/MandatoryCategoryValidator.cs
  test/perf/dotnet-tools/BenchmarkDotNet.Extensions/PartitionFilter.cs
  test/perf/dotnet-tools/BenchmarkDotNet.Extensions/TooManyTestCasesValidator.cs
  test/perf/dotnet-tools/BenchmarkDotNet.Extensions/ValuesGenerator.cs
  test/perf/dotnet-tools/Reporting/Counter.cs
  test/perf/dotnet-tools/Reporting/Os.cs
  test/perf/dotnet-tools/ResultsComparer/CommandLineOptions.cs
  test/perf/dotnet-tools/ResultsComparer/DataTransferContracts.cs
Labels: CL-CodeCleanup

#25943 Add Codeql Suppressions
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/System.Management.Automation/engine/NativeCommandProcessor.cs
  src/System.Management.Automation/engine/remoting/common/RunspaceConnectionInfo.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
Labels: CL-Tools, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25915 Add build to vPack Pipeline
  .pipelines/PowerShell-vPack-Official.yml
  .pipelines/templates/obp-file-signing.yml
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging, BackPort-7.4.x-Approved, BackPort-7.5.x-Approved

#25987 [release/v7.4] Update container images to use mcr.microsoft.com for Linux and Azure Linux
  .pipelines/PowerShell-Coordinated_Packages-Official.yml
  .pipelines/PowerShell-Packages-Official.yml
  .pipelines/PowerShell-Release-Official-Azure.yml
  .pipelines/PowerShell-Release-Official.yml
  .pipelines/apiscan-gen-notice.yml
  .pipelines/templates/linux.yml
  .pipelines/templates/mac.yml
  .pipelines/templates/windows-hosted-build.yml
  build.psm1
Labels: CL-BuildPackaging

#26000 Add LinuxHost Network configuration to PowerShell Packages pipeline
  .pipelines/PowerShell-Packages-Official.yml
Labels: CL-BuildPackaging, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#26001 Update third-party library versions to 8.0.19 for ObjectPool, Windows Compatibility, and System.Drawing.Common
  ThirdPartyNotices.txt
Labels: CL-Docs

#26006 Remove unnecessary `CS0618` suppressions from Variant APIs
  src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/PropVariant.cs
  src/System.Management.Automation/engine/COM/ComInvoker.cs
  src/System.Management.Automation/engine/COM/ComUtil.cs
Labels: CL-CodeCleanup

#26025 Update Ev2 Shell Extension Image to AzureLinux 3 for PMC Release
  .pipelines/EV2Specs/ServiceGroupRoot/ServiceModel.json
Labels: Compliance, CL-BuildPackaging, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25866 fix(apt-package): add libicu76 dependency to support Debian 13
  tools/packaging/packaging.psm1
Labels: Review - Needed, CL-BuildPackaging

#26016 Fix the APIScan pipeline
  .pipelines/apiscan-gen-notice.yml
  .pipelines/templates/compliance/apiscan.yml
Labels: CL-BuildPackaging

#26034 Ensure that the workflows are triggered on `.globalconfig` and other files at the root of the repo
  .github/workflows/linux-ci.yml
  .github/workflows/macos-ci.yml
  .github/workflows/windows-ci.yml
Labels: Review - Needed, CL-BuildPackaging

#25813 Enable CA2021: Do not call Enumerable.Cast<T> or Enumerable.OfType<T> with incompatible types
  .globalconfig
Labels: CL-CodeCleanup

#25725 Automate Store Publishing
  .pipelines/PowerShell-Release-Official.yml
  .pipelines/store/PDP/PDP-Media/en-US/Error.png
  .pipelines/store/PDP/PDP-Media/en-US/Experimental_Features.png
  .pipelines/store/PDP/PDP-Media/en-US/Feedback_Provider.png
  .pipelines/store/PDP/PDP-Media/en-US/Predictor_Inline.png
  .pipelines/store/PDP/PDP-Media/en-US/Predictor_ListView.png
  .pipelines/store/PDP/PDP-Media/en-US/Prompt.png
  .pipelines/store/PDP/PDP-Media/en-US/Stable_Release.png
  .pipelines/store/PDP/PDP-Media/en-US/pwshLogo.png
  .pipelines/store/PDP/PDP/en-US/PDP.xml
  .pipelines/store/SBConfig.json
  .pipelines/templates/channelSelection.yml
  .pipelines/templates/package-create-msix.yml
  .pipelines/templates/release-MSIX-Publish.yml
  .pipelines/templates/release-SetTagAndChangelog.yml
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging, BackPort-7.4.x-Approved, BackPort-7.5.x-Approved

#26086 Allow opt-out of the named-pipe listener using an environment variable
  src/System.Management.Automation/engine/Utils.cs
  src/System.Management.Automation/engine/remoting/common/RemoteSessionNamedPipe.cs
  src/System.Management.Automation/resources/RemotingErrorIdStrings.resx
  src/System.Management.Automation/utils/Telemetry.cs
Labels: CL-Engine
