Repository PowerShell/PowerShell, pull requests merged in 2025-02, with the labels that each got.

#24839 Add quote handling in Verb, StrictModeVersion, Scope & PropertyType Argument Completers with single helper method
  src/Microsoft.PowerShell.Commands.Management/commands/management/NewPropertyCommand.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Process.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/CommandCompletion/ScopeArgumentCompleter.cs
  src/System.Management.Automation/engine/InternalCommands.cs
  src/System.Management.Automation/utils/Verbs.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General

#24907 Replace char[] array in CompletionRequiresQuotes with cached SearchValues<char>
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
Labels: CL-CodeCleanup

#24905 Add UseDotnet task for installing dotnet
  .github/actions/test/linux-packaging/action.yml
  .github/actions/test/windows/action.yml
  .github/workflows/linux-ci.yml
  .github/workflows/macos-ci.yml
  .pipelines/templates/compliance/apiscan.yml
  .pipelines/templates/linux-package-build.yml
  .pipelines/templates/linux.yml
  .pipelines/templates/mac-package-build.yml
  .pipelines/templates/mac.yml
  .pipelines/templates/nupkg.yml
  .pipelines/templates/release-validate-fxdpackages.yml
  .pipelines/templates/release-validate-globaltools.yml
  .pipelines/templates/release-validate-sdk.yml
  .pipelines/templates/testartifacts.yml
  .pipelines/templates/windows-hosted-build.yml
  .pipelines/templates/windows-package-build.yml
  .vsts-ci/linux/templates/packaging.yml
  .vsts-ci/mac.yml
  .vsts-ci/psresourceget-acr.yml
  .vsts-ci/templates/ci-build.yml
  .vsts-ci/templates/nix-test.yml
  .vsts-ci/templates/test/nix-container-test.yml
  .vsts-ci/templates/windows-test.yml
  .vsts-ci/windows-daily.yml
  .vsts-ci/windows/templates/windows-packaging.yml
  build.psm1
  tools/ci.psm1
  tools/packaging/packaging.psm1
  tools/releaseBuild/azureDevOps/templates/linux-packaging.yml
  tools/releaseBuild/azureDevOps/templates/linux.yml
Labels: CL-BuildPackaging

#24929 Fix GitHub Action filter overmatching
  .github/action-filters.yml
  .github/workflows/linux-ci.yml
  .github/workflows/macos-ci.yml
  .github/workflows/windows-ci.yml
Labels: CL-BuildPackaging, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#24926 Use Environment.ProcessId in SpecialVariables.PID
  src/System.Management.Automation/engine/SessionState.cs
Labels: CL-CodeCleanup

#24941 Fix formatting of docs in ///-comments for Clean()
  src/System.Management.Automation/engine/lang/scriptblock.cs
Labels: CL-CodeCleanup

#24960 [release/v7.4]Fix release branch filters
  .github/workflows/linux-ci.yml
  .github/workflows/macos-ci.yml
Labels: CL-BuildPackaging

#24959 [release/v7.5]Fix release branch filters
  .github/workflows/linux-ci.yml
  .github/workflows/macos-ci.yml
  .github/workflows/windows-ci.yml
Labels: CL-BuildPackaging

#24958 [release/v7.5]Fix GitHub Action filter overmatching
  .github/action-filters.yml
  .github/workflows/linux-ci.yml
  .github/workflows/macos-ci.yml
  .github/workflows/windows-ci.yml
Labels: CL-BuildPackaging

#24957 [release/v7.4]Fix GitHub Action filter overmatching
  .github/action-filters.yml
  .github/workflows/linux-ci.yml
  .github/workflows/macos-ci.yml
  .github/workflows/windows-ci.yml
Labels: CL-BuildPackaging

#24940 Remove redundant `Attribute` suffix
  src/Microsoft.Management.Infrastructure.CimCmdlets/CimIndicationWatcher.cs
  src/Microsoft.PowerShell.Commands.Management/commands/management/Navigation.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddMember.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/CsvCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-hex/Format-Hex.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-object/Format-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/format-wide/Format-Wide.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-file/Out-File.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/FormatAndOutput/out-string/Out-String.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetDateCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/ImplicitRemotingCommands.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/MatchString.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Select-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Send-MailMessage.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/StartSleepCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Tee-Object.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Update-TypeData.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WaitEventCommand.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/XmlCommands.cs
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
  src/Microsoft.WSMan.Management/Interop.cs
  src/Microsoft.WSMan.Management/WSManInstance.cs
  src/System.Management.Automation/FormatAndOutput/out-console/OutConsole.cs
  src/System.Management.Automation/cimSupport/cmdletization/xml/CoreCLR/cmdlets-over-objects.objectModel.autogen.cs
  src/System.Management.Automation/engine/Attributes.cs
  src/System.Management.Automation/engine/CommonCommandParameters.cs
  src/System.Management.Automation/engine/DataStoreAdapter.cs
  src/System.Management.Automation/engine/MshMemberInfo.cs
  src/System.Management.Automation/engine/ProgressRecord.cs
  src/System.Management.Automation/engine/SessionState.cs
  src/System.Management.Automation/engine/hostifaces/History.cs
  src/System.Management.Automation/engine/remoting/client/ClientRemotePowerShell.cs
  src/System.Management.Automation/engine/remoting/client/RemotingErrorRecord.cs
  src/System.Management.Automation/engine/remoting/client/clientremotesession.cs
  src/System.Management.Automation/engine/remoting/client/clientremotesessionprotocolstatemachine.cs
  src/System.Management.Automation/engine/remoting/client/remotingprotocolimplementation.cs
  src/System.Management.Automation/engine/remoting/commands/WaitJob.cs
  src/System.Management.Automation/engine/remoting/common/RemoteSessionHyperVSocket.cs
  src/System.Management.Automation/engine/remoting/common/fragmentor.cs
  src/System.Management.Automation/engine/remoting/fanin/BaseTransportManager.cs
  src/System.Management.Automation/engine/remoting/fanin/InitialSessionStateProvider.cs
  src/System.Management.Automation/engine/remoting/fanin/PriorityCollection.cs
  src/System.Management.Automation/engine/remoting/server/serverremotesession.cs
  src/System.Management.Automation/engine/remoting/server/serverremotesessionstatemachine.cs
  src/System.Management.Automation/engine/serialization.cs
  src/System.Management.Automation/help/CabinetNativeApi.cs
  src/System.Management.Automation/help/HelpCommands.cs
  src/System.Management.Automation/help/SaveHelpCommand.cs
  src/System.Management.Automation/namespaces/CoreCommandContext.cs
  src/System.Management.Automation/namespaces/FileSystemContentStream.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  src/System.Management.Automation/namespaces/LocationGlobber.cs
  src/System.Management.Automation/namespaces/ProviderBase.cs
  src/System.Management.Automation/namespaces/SessionStateProviderBase.cs
  src/System.Management.Automation/namespaces/Win32Native.cs
  src/System.Management.Automation/security/SecuritySupport.cs
  src/System.Management.Automation/security/Win32Native/WinTrust.cs
  src/System.Management.Automation/security/nativeMethods.cs
Labels: CL-CodeCleanup

#24963 Fix `Start-Transcript` error when `$Transcript` is a `PSObject` wrapped string
  src/Microsoft.PowerShell.ConsoleHost/host/msh/StartTranscriptCmdlet.cs
  test/powershell/Modules/Microsoft.Powershell.Host/Start-Transcript.Tests.ps1
Labels: CL-General

#24936 Fix `New-Item -Force` to error on invalid directory name
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/New-Item.Tests.ps1
Labels: CL-General

#24621 Set `LangVersion` compiler option to `13.0` in Test.Common.props
  test/Test.Common.props
  test/tools/WebListener/Controllers/GetController.cs
  test/tools/WebListener/Controllers/MultipartController.cs
  test/tools/WebListener/Controllers/ResponseHeadersController.cs
Labels: CL-BuildPackaging

#24971 Add completion single/double quote support for `-PSEdition` parameter
  src/System.Management.Automation/engine/Modules/GetModuleCommand.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General

#24720 Fix `RunspacePool`, `RunspacePoolInternal` and `RemoteRunspacePoolInternal` `IDisposable` implementation
  src/System.Management.Automation/engine/hostifaces/RunspacePool.cs
  src/System.Management.Automation/engine/hostifaces/RunspacePoolInternal.cs
  src/System.Management.Automation/engine/remoting/client/RemoteRunspacePoolInternal.cs
Labels: CL-CodeCleanup

#24949 Stringify ErrorRecord with empty exception message to empty string
  src/System.Management.Automation/engine/ErrorPackage.cs
  test/powershell/Modules/Microsoft.PowerShell.Utility/Implicit.Remoting.Tests.ps1
  test/xUnit/csharp/test_Utils.cs
Labels: CL-General

#24192 Remove trailing space from event source name
  src/System.Management.Automation/help/HelpCommands.cs
Labels: WG-Engine, CL-General, WG-NeedsReview

#24883 Adding In-PR as label to not close issues
  .github/policies/IssueManagement.ResolveStale.yml
Labels: CL-NotInBuild

#24987 Give the pipeline runs meaningful names
  .pipelines/PowerShell-Coordinated_Packages-Official.yml
  .pipelines/PowerShell-Packages-Official.yml
  .pipelines/PowerShell-Release-Official-Azure.yml
  .pipelines/PowerShell-Release-Official.yml
  .pipelines/PowerShell-vPack-Official.yml
Labels: BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#24989 Update CODEOWNERS
  .github/CODEOWNERS
Labels: CL-Tools, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#24965 Fix PSMethodInvocationConstraints.GetHashCode method
  src/System.Management.Automation/engine/MshMemberInfo.cs
Labels: CL-General, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25006 Update Third Party Notices
  ThirdPartyNotices.txt
Labels: CL-Docs

#25014 Add experimental feature completion single/double quote support for `-Name` parameter
  src/System.Management.Automation/engine/ExperimentalFeature/EnableDisableExperimentalFeatureCommand.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General

#25031 Use types from both sides of the pipeline chain for the type inference
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: CL-General

#24910 Filter out the nested modules of `PSReadLine` from module name tab completion
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
Labels: CL-General

#24909 Never load a module targeting the PSReadLine module's `SessionState`
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
Labels: CL-General

#25049 [release/v7.6.0-preview.3]Fix the expected path of .NET after using UseDotnet 2 task to install
  .pipelines/templates/release-validate-sdk.yml
Labels: CL-BuildPackaging

#25030 Improve the type inference for binary expressions
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  src/System.Management.Automation/engine/parser/ast.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: CL-General

#25001 Add 7.6.0-preview.3 changelog
  CHANGELOG/preview.md
Labels: CL-Docs

#25012 Update metadata.json
  tools/metadata.json
Labels: Review - Needed

#24852 Allow DSC parsing through OS architecture translation layers
  src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs
  src/System.Management.Automation/engine/parser/Parser.cs
  src/System.Management.Automation/utils/PsUtils.cs
Labels: Review - Needed, CL-General

#24757 Fix issue with incomplete results when completing paths with wildcards in non-filesystem providers
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/BugFix.Tests.ps1
Labels: CL-General

#19440 Fix share completion with provider and spaces
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: WG-Engine, Extra Small, PowerShell-Docs not needed, WG-Reviewed

#20340 Enable completion of scoped variables without specifying scope
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: WG-Interactive-Console, CL-General, Small, PowerShell-Docs not needed, WG-Reviewed

#24755 Fix completion of provider paths when a path returns itself instead of its children
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General

#25076 Fix completion of variables assigned inside Do loops
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General

#25093 Update Component Manifest
  tools/cgmanifest.json
Labels: CL-BuildPackaging

#25094 Make Component Manifest Updater use neutral target in addition to RID target
  tools/findMissingNotices.ps1
Labels: BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#20017 Use script filepath when completing relative paths for using statements
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Extra Small, PowerShell-Docs needed

#24194 Use Get-Help approach to find 'about_*.help.txt' files with correct locale for completions
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
Labels: CL-General

#21134 Update variable/property assignment completion so it can fallback to type inference
  src/System.Management.Automation/engine/CommandCompletion/CompletionAnalysis.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General, Medium

#20409 Allow empty prefix string in 'Import-Module -Prefix' to override default prefix in manifest
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  test/powershell/Modules/Microsoft.PowerShell.Core/Import-Module.Tests.ps1
Labels: WG-Engine, CL-General, Extra Small, PowerShell-Docs not needed, WG-Reviewed

#25106 Add back-port workflow using dotnet/arcade
  .github/workflows/backport.yml
Labels: CL-BuildPackaging

#21131 Handle type inference for redirected commands
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: CL-General, Small

#25104 Add completion for variables assigned by command redirection
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General

#21127 Add type inference for functions without OutputType attribute and anonymous functions
  src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs
  test/powershell/engine/Api/TypeInference.Tests.ps1
Labels: CL-General, Extra Small
