Repository PowerShell/PowerShell, pull requests merged in 2025-05, with the labels that each got.

#25479 Improve debug logging of Web cmdlet request and response
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/Microsoft.PowerShell.Commands.Utility/resources/WebCmdletStrings.resx
Labels: CL-General

#25420 Fix the isolated module test that was disabled previously
  test/powershell/engine/Module/IsolatedModule.Tests.ps1
  test/tools/TestAlc/nested/NestedCommand.cs
  test/tools/TestAlc/nested/Test.Isolated.Nested.csproj
Labels: Review - Needed, CL-Test

#25511 Adding PS* aliases for Where|Foreach magic methods
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  test/powershell/engine/ETS/Adapter.Tests.ps1
Labels: CL-Engine

#25512 Move MSIXBundle to Packages and Release to GitHub
  .pipelines/PowerShell-Packages-Official.yml
  .pipelines/PowerShell-Release-Official.yml
  .pipelines/templates/package-create-msix.yml
  .pipelines/templates/uploadToAzure.yml
Labels: CL-BuildPackaging, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25524 Update Third Party Notices
  ThirdPartyNotices.txt
Labels: CL-Docs

#25520 Add 7.4.10 Changelog
  CHANGELOG/7.4.md
Labels: CL-Docs, BackPort-7.4.x-Consider

#25514 Add internal methods to check Preferences
  src/System.Management.Automation/engine/MshCommandRuntime.cs
  src/System.Management.Automation/engine/cmdlet.cs
Labels: CL-General

#25396 Add support for thousands separators in [bigint] casting
  src/System.Management.Automation/engine/LanguagePrimitives.cs
  test/powershell/engine/Api/LanguagePrimitive.Tests.ps1
Labels: CL-General

#25519 Add more tests for `PSForEach` and `PSWhere` methods
  test/powershell/engine/ETS/Adapter.Tests.ps1
Labels: CL-Test

#25538 Remove duplicate modules from completion results
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General

#25186 Treat -Target as literal in New-Item
  src/System.Management.Automation/engine/SessionStateContainer.cs
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
  test/powershell/engine/Basic/GroupPolicySettings.Tests.ps1
Labels: CL-General

#25245 Make inherited protected internal instance members accessible in class scope.
  src/System.Management.Automation/engine/CoreAdapter.cs
  src/System.Management.Automation/engine/runtime/Binding/Binders.cs
  test/powershell/Language/Classes/scripting.Classes.inheritance.tests.ps1
Labels: CL-General

#25497 Fix Out-GridView by replacing use of obsolete BinaryFormatter with custom implementation.
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/ComparableValueFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/DoesNotEqualFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/EqualsFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/FilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/FilterRuleExtensions.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/IsBetweenFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/IsEmptyFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/IsGreaterThanFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/IsLessThanFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/IsNotEmptyFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/IsNotEmptyValidationRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/PropertiesTextContainsFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/PropertyValueSelectorFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/SelectorFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/SingleValueComparableValueFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextContainsFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextDoesNotContainFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextDoesNotEqualFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextEndsWithFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextEqualsFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/FilterRules/TextStartsWithFilterRule.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/IDeepCloneable.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/ValidatingSelectorValue.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/ValidatingValue.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/ValidatingValueBase.cs
  src/Microsoft.Management.UI.Internal/ManagementList/FilterCore/ValidationRules/DataErrorInfoValidationRule.cs
Labels: CL-CodeCleanup

#24615 Use absolute path in `FileSystemProvider.CreateDirectory`
  src/System.Management.Automation/namespaces/FileSystemProvider.cs
  test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1
Labels: CL-General

#25532 Update links and contribution guide in documentation
  .github/CONTRIBUTING.md
  .github/Images/Codespaces.png
  README.md
  docs/building/windows-core.md
Labels: CL-Docs
