Repository PowerShell/PowerShell, pull requests merged in 2025-04, with the labels that each got.

#25243 Update change log for v7.6.0-preview.4
  CHANGELOG/preview.md
Labels: CL-Docs

#25267 Revert "Cleanup old release pipelines (#25201)"
  tools/releaseBuild/setReleaseTag.ps1
  tools/releaseBuild/setReleaseTag.sh
Labels: CL-BuildPackaging

#25269 Fix the net framework folder in nuget packages
  .pipelines/templates/nupkg.yml
  .pipelines/templates/windows-hosted-build.yml
Labels: CL-BuildPackaging

#25272 Remove call to NuGet
  .pipelines/templates/compliance/generateNotice.yml
Labels: CL-BuildPackaging, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25244 Delete .github/ISSUE_TEMPLATE/Distribution_Request.yaml
  .github/ISSUE_TEMPLATE/Distribution_Request.yaml
Labels: CL-Docs

#25235 [release/v7.5]Add setup dotnet action to the build composite action
  .github/actions/build/ci/action.yml
  .github/actions/test/nix/action.yml
Labels: CL-BuildPackaging

#25273 Update ThirdPartyNotices file
  ThirdPartyNotices.txt
Labels: CL-BuildPackaging

#25275 Make GitHub Workflows work in the internal mirror
  .github/actions/infrastructure/path-filters/action.yml
  .github/actions/test/nix/action.yml
  .github/actions/test/process-pester-results/action.yml
  .github/workflows/linux-ci.yml
  .github/workflows/macos-ci.yml
  .github/workflows/windows-ci.yml
  build.psm1
Labels: Compliance, CL-BuildPackaging, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25277 Disable SBOM generation on set variables job in release build
  .pipelines/PowerShell-Coordinated_Packages-Official.yml
Labels: CL-BuildPackaging

#25280 Downgrade the packages needed by SDK
  test/hosting/hosting.tests.csproj
Labels: CL-Test

#25229 [release/v7.4] Fallback to AppLocker after `WldpCanExecuteFile`
  src/System.Management.Automation/security/wldpNativeMethods.cs
Labels: Review - Needed, CL-Engine

#25237 [release/v7.5]Remove obsolete template from Windows Packaging CI
  .vsts-ci/windows/templates/windows-packaging.yml
Labels: Review - Needed, CL-BuildPackaging

#25279 Do not run labels workflow in the internal repo
  .github/workflows/labels.yml
Labels: CL-Tools, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25281 [release/v7.5] Add UseDotnet task for installing dotnet
  .github/actions/test/linux-packaging/action.yml
  .github/actions/test/windows/action.yml
  .github/workflows/linux-ci.yml
  .github/workflows/macos-ci.yml
  .pipelines/templates/compliance/apiscan.yml
  .pipelines/templates/linux-package-build.yml
  .pipelines/templates/linux.yml
  .pipelines/templates/mac-package-build.yml
  .pipelines/templates/mac.yml
  .pipelines/templates/nupkg.yml
  .pipelines/templates/release-validate-fxdpackages.yml
  .pipelines/templates/release-validate-globaltools.yml
  .pipelines/templates/release-validate-sdk.yml
  .pipelines/templates/testartifacts.yml
  .pipelines/templates/windows-hosted-build.yml
  .pipelines/templates/windows-package-build.yml
  .vsts-ci/linux/templates/packaging.yml
  .vsts-ci/mac.yml
  .vsts-ci/psresourceget-acr.yml
  .vsts-ci/templates/ci-build.yml
  .vsts-ci/templates/nix-test.yml
  .vsts-ci/templates/test/nix-container-test.yml
  .vsts-ci/templates/windows-test.yml
  .vsts-ci/windows-daily.yml
  .vsts-ci/windows/templates/windows-packaging.yml
  build.psm1
  tools/ci.psm1
  tools/packaging/packaging.psm1
Labels: CL-BuildPackaging

#25288 Update test result processing to use NUnitXml format and enhance logging for better clarity
  .github/actions/test/nix/action.yml
  .github/actions/test/process-pester-results/action.yml
  .github/actions/test/process-pester-results/process-pester-results.ps1
  .github/actions/test/windows/action.yml
  build.psm1
Labels: CL-BuildPackaging, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25295 Migrate MacOS Signing to OneBranch
  .pipelines/templates/mac-package-build.yml
Labels: Compliance, CL-BuildPackaging, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25346 Fix tab completion for env/function variables
  src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
Labels: CL-General

#25359 Add CodeQL suppressions for PowerShell intended behavior
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/AddType.cs
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs
  src/System.Management.Automation/engine/ExecutionContext.cs
Labels: CL-BuildPackaging

#25296 Add Windows Store Signing to MSIX bundle
  .pipelines/PowerShell-Release-Official.yml
  .pipelines/templates/release-create-msix.yml
Labels: CL-BuildPackaging, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25318 Combine GitHub and Nuget Release Stage
  .pipelines/PowerShell-Release-Official.yml
  .pipelines/templates/release-githubNuget.yml
  .pipelines/templates/release-publish-nuget.yml
Labels: CL-BuildPackaging, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25367 Enhance path filters action to set outputs for all changes when not a PR
  .github/actions/infrastructure/path-filters/action.yml
Labels: Compliance, CL-BuildPackaging

#25386 Update CODEOWNERS add Justin as a maintainer
  .github/CODEOWNERS
Labels: CL-Tools

#25385 Retry ClearlyDefined operations
  tools/clearlyDefined/src/ClearlyDefined/ClearlyDefined.psm1
Labels: CL-BuildPackaging

#25283 Add single/double quote support for `Join-String` Argument Completer
  src/Microsoft.PowerShell.Commands.Utility/commands/utility/Join-String.cs
  src/System.Management.Automation/engine/CommandCompletion/CompletionHelpers.cs
  src/System.Management.Automation/resources/TabCompletionStrings.resx
  test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1
  test/xUnit/csharp/test_CompletionHelpers.cs
Labels: CL-General

#25388 Update APIScan to use new symbols server
  .pipelines/apiscan-gen-notice.yml
  .pipelines/templates/compliance/apiscan.yml
  build.psm1
Labels: CL-BuildPackaging

#25398 Use GitHubReleaseTask
  .pipelines/PowerShell-Release-Official.yml
  .pipelines/templates/release-SetTagAndChangelog.yml
  .pipelines/templates/release-githubNuget.yml
Labels: CL-BuildPackaging, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25422 Updated Third Party Notices
  ThirdPartyNotices.txt
Labels: CL-Docs

#25423 Add PSScriptAnalyzer
  .pipelines/apiscan-gen-notice.yml
Labels: CL-BuildPackaging

#25382 Add 7.5.1 Change log
  CHANGELOG/7.5.md
Labels: CL-Docs, BackPort-7.5.x-Consider

#25434 Use new variables template for vPack
  .pipelines/PowerShell-vPack-Official.yml
Labels: CL-BuildPackaging, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25440 Fix the NREs when writing to console from multiple threads
  src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs
Labels: CL-General, WG-Reviewed, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25462 Revert "Allow empty prefix string in 'Import-Module -Prefix' to override default prefix in manifest (#20409)"
  src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs
  test/powershell/Modules/Microsoft.PowerShell.Core/Import-Module.Tests.ps1
Labels: CL-General

#25438 Update metadata.json
  tools/metadata.json
Labels: CL-BuildPackaging

#25468 Fix Conditional Parameter to Skip NuGet Publish
  .pipelines/PowerShell-Release-Official.yml
  .pipelines/templates/release-githubNuget.yml
Labels: CL-BuildPackaging, BackPort-7.4.x-Consider, BackPort-7.5.x-Consider

#25478 Fix Merge Errors from #25401 and Internal 33077
  .pipelines/templates/release-MakeBlobPublic.yml
  .pipelines/templates/release-githubNuget.yml
Labels: CL-BuildPackaging
